import React,{useState} from 'react';
import {router} from 'expo-router';
import {ActivityIndicator,FlatList,Pressable,RefreshControl,Switch,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Button,Empty,Field,Icon,Note,Row,Segments,T} from '../../components/ui';
import {useI18n,errorKey} from '../../lib/i18n';
import {useApp} from '../../state/AppState';
import {RouteSheet} from '../routes/RouteSheet';
import {friendRequest,unblockRequest,exactFriendHandle} from './presentationModel';
import {SocialHeader,SocialPending,SocialReadState} from './SocialSurface';
import type {BlockedPerson,FriendRow,FriendVerb,SocialRequest} from './types';
import {useSocialScreen} from './useSocialScreen';

type Confirm={kind:'friend';row:FriendRow;verb:'block'|'remove'}|{kind:'unblock';row:BlockedPerson}|{kind:'presence'}|{kind:'actions';row:FriendRow};
export default function FriendsScreen({embedded=false}:{embedded?:boolean}){
 const screen=useSocialScreen(),{social}=screen,{colors}=useApp(),{t}=useI18n(),insets=useSafeAreaInsets();
 const [tab,setTab]=useState('friends'),[query,setQuery]=useState(''),[handle,setHandle]=useState(''),[add,setAdd]=useState(false),[confirm,setConfirm]=useState<Confirm|null>(null);
 const [error,setError]=useState<string|null>(null),[operationId,setOperationId]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const failure=(value:unknown)=>{if(screen.current())setError(t(errorKey(value,'social')));};
 const send=async(build:()=>SocialRequest)=>{try{const result=await screen.run(async()=>{const request=build();setBusy(true);setError(null);return await screen.live.current.social.mutate(request);});if(result&&screen.current()){setOperationId(result);setAdd(false);setConfirm(null);}}catch(value){failure(value);}finally{if(screen.current())setBusy(false);}};
 const act=(row:FriendRow,verb:FriendVerb)=>send(()=>friendRequest(row,verb,screen.live.current.social.friends));
 const open=(value:Confirm)=>{try{screen.guard();setError(null);setConfirm(value);}catch(error){failure(error);}};
 const changeTab=(value:string)=>{if(screen.moving)return;setTab(value);setQuery('');if(value==='blocked')void social.loadMoreBlocked().catch(failure);};
 const togglePresence=async(enabled:boolean)=>{if(enabled){open({kind:'presence'});return;}try{screen.guard(false);setBusy(true);await screen.live.current.social.setPresence(false);}catch(value){failure(value);}finally{if(screen.current())setBusy(false);}};
 const confirmAction=async()=>{const value=confirm;if(!value)return;if(value.kind==='presence'){try{await screen.run(async()=>{setBusy(true);await screen.live.current.social.setPresence(true);});if(screen.current())setConfirm(null);}catch(error){failure(error);}finally{if(screen.current())setBusy(false);}}else if(value.kind==='unblock')await send(()=>unblockRequest(value.row,screen.live.current.social.blocked));else if(value.kind==='friend')await act(value.row,value.verb);};
 const list=tab==='blocked'?social.blocked:social.friends.filter(value=>tab==='friends'?value.state==='accepted':value.state==='pending');
 const needle=query.trim().toLocaleLowerCase(),rows=list.filter(value=>`${value.display_name} ${value.handle}`.toLocaleLowerCase().includes(needle));
 const page=social.pages[tab==='blocked'?'blocked':'friends'],more=tab==='blocked'?social.loadMoreBlocked:social.loadMoreFriends;
 const allowed=screen.enabled&&!busy;
 const emptyTitle=needle?'m5a.noMatch':tab==='friends'?'m5a.noFriends':tab==='requests'?'m5a.noRequests':'m5a.noBlocked';
 const emptyBody=needle?'m5a.noMatchBody':tab==='friends'?'m5a.noFriendsBody':tab==='requests'?'m5a.noRequestsBody':'m5a.noBlockedBody';
 const row=(item:FriendRow|BlockedPerson)=>{
  const blocked='block_token' in item,friend=blocked?null:item;
  const online=!blocked&&social.fresh&&social.presence.some(value=>value.user_id===item.user_id&&value.online);
  return <View style={{paddingVertical:18,borderBottomWidth:1,borderBottomColor:colors.line,gap:14}}><Row><View accessibilityElementsHidden style={{width:48,height:48,borderRadius:24,backgroundColor:colors.raised,alignItems:'center',justifyContent:'center'}}><T size={20} weight="semibold">{Array.from(item.display_name)[0]??'@'}</T></View><View style={{flex:1}}><T size={17} weight="semibold">{item.display_name}</T><T size={13} muted>@{item.handle}</T></View>{friend?.state==='accepted'?<Row style={{gap:6}}><View style={{width:6,height:6,borderRadius:3,backgroundColor:online?colors.good:colors.muted}}/><T size={12} muted>{t(online?'m5a.online':'m5a.offline')}</T></Row>:null}{friend&&<Pressable accessibilityRole="button" accessibilityLabel={t('m5a.moreActions',{name:item.display_name})} disabled={!allowed} onPress={()=>open({kind:'actions',row:friend})} style={{minWidth:44,minHeight:44,justifyContent:'center',alignItems:'center'}}><Icon name="ellipsis-horizontal"/></Pressable>}</Row>
   {blocked?<Button small secondary label={t('m5a.unblock')} disabled={!allowed} onPress={()=>open({kind:'unblock',row:item})}/>:friend?.state==='pending'?<><T muted size={13}>{t(friend.direction==='incoming'?'m5a.incoming':'m5a.outgoing')}</T><Row>{friend.direction==='incoming'?<><Button small label={t('m5a.accept')} disabled={!allowed} onPress={()=>act(friend,'accept')}/><Button small secondary label={t('m5a.decline')} disabled={!allowed} onPress={()=>act(friend,'decline')}/></>:<Button small secondary label={t('m5a.cancelRequest')} disabled={!allowed} onPress={()=>act(friend,'cancel')}/>}</Row></>:null}</View>;
 };
 return <View style={{flex:1,backgroundColor:colors.bg}}><FlatList data={rows} keyExtractor={item=>item.user_id} renderItem={({item})=>row(item)} scrollEnabled={!screen.moving} keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingHorizontal:24,paddingTop:embedded?8:insets.top+18,paddingBottom:124+insets.bottom}} refreshControl={<RefreshControl refreshing={social.loading} tintColor={colors.accent} enabled={!screen.moving} onRefresh={()=>{if(!screen.moving)void social.refresh().catch(failure);}}/>}
  ListHeaderComponent={<View style={{gap:18}}><SocialHeader title={t('m5a.friends')} body={t('m5a.friendsBody')} embedded={embedded} action={<Button small icon="add-outline" label={t('m5a.addFriend')} disabled={!allowed} onPress={()=>{try{screen.guard();setAdd(true);setError(null);}catch(value){failure(value);}}}/>}/><SocialReadState/>{screen.moving&&<Note>{t('m5a.moving')}</Note>}{screen.online===false&&<Note>{t('m5a.connectionHint')}</Note>}<SocialPending/>{operationId&&(social.latest?.operationId===operationId&&social.latest.status==='rejected'?<Note error>{t(errorKey(social.latest.error,'social'))}</Note>:<Note>{t(social.latest?.operationId===operationId&&social.latest.status==='applied'?'m5a.applied':'m5a.pendingQueued')}</Note>)}{(error||social.error)&&<Note error>{error??t(errorKey(social.error,'social'))}</Note>}
   <Button small secondary icon="qr-code-outline" label={t('m5b.friends')} disabled={screen.moving||!screen.active||!screen.focused} onPress={()=>{if(screen.moving||!screen.active||!screen.focused)return;router.push('/friend-links');}}/>
   <Row style={{justifyContent:'space-between',paddingVertical:10}}><View style={{flex:1}}><T weight="semibold">{t('m5a.presence')}</T><T muted size={12}>{t('m5a.presenceShort')}</T></View><Switch accessibilityLabel={t('m5a.presence')} value={social.optedIn} disabled={busy||screen.moving||!social.ready||!screen.active||!screen.focused} trackColor={{false:colors.line,true:colors.accent}} onValueChange={value=>void togglePresence(value)}/></Row>
   <Segments value={tab} items={[{value:'friends',label:t('m5a.friends')},{value:'requests',label:t('m5a.requestTab')},{value:'blocked',label:t('m5a.blockedTab')}]} onChange={changeTab}/><Field label={t('m5a.searchLoaded')} value={query} onChangeText={value=>{if(!screen.moving)setQuery(value);}} editable={!screen.moving} autoCapitalize="none"/><T muted size={11}>{t('m5a.loadedStatus')}</T></View>}
  ListEmptyComponent={social.ready&&social.fresh&&!page.loading&&!page.error?<View style={{paddingTop:24}}><Empty icon="people-outline" title={t(emptyTitle)} body={t(emptyBody)}/></View>:null}
  ListFooterComponent={<View style={{gap:12,paddingTop:18}}>{page.loading&&<ActivityIndicator color={colors.accent}/>}{page.error&&<Note error>{t(errorKey(page.error,'social'))}</Note>}{(page.hasMore||page.error)&&<Button small secondary label={t(page.error?'m5a.refresh':'m5a.loadMore')} disabled={screen.moving||page.loading} onPress={()=>void (page.error&&tab!=='blocked'?social.refresh():more()).catch(failure)}/>}</View>}/>
  <RouteSheet visible={add&&!screen.moving&&screen.focused&&screen.active} title={t('m5a.addFriend')} onClose={()=>setAdd(false)}>{add&&<><Field label={t('m5a.exactHandle')} value={handle} onChangeText={setHandle} autoCapitalize="none" autoCorrect={false} maxLength={25}/><T muted>{t('m5a.handleHint')}</T>{error&&<Note error>{error}</Note>}<Button label={t('m5a.requestFriend')} disabled={!allowed} busy={busy} onPress={()=>void send(()=>({schema_version:1,action:'request_friend',handle:exactFriendHandle(handle)}))}/></>}</RouteSheet>
  <RouteSheet visible={!!confirm&&!screen.moving&&screen.focused&&screen.active} title={confirm?.kind==='presence'?t('m5a.presence'):confirm?t('m5a.moreActions',{name:confirm.row.display_name}):''} onClose={()=>setConfirm(null)}>{confirm?.kind==='actions'?<><Button secondary label={t('m5a.block')} disabled={!allowed} onPress={()=>open({kind:'friend',row:confirm.row,verb:'block'})}/>{confirm.row.state==='accepted'&&<Button secondary label={t('m5a.removeFriend')} disabled={!allowed} onPress={()=>open({kind:'friend',row:confirm.row,verb:'remove'})}/>}</>:confirm?<><T>{t(confirm.kind==='presence'?'m5a.presenceBody':confirm.kind==='unblock'?'m5a.unblockBody':confirm.verb==='block'?'m5a.blockBody':'m5a.removeBody')}</T>{error&&<Note error>{error}</Note>}<Button label={t(confirm.kind==='presence'?'m5a.presenceEnable':'m5a.confirm')} disabled={!allowed} busy={busy} onPress={()=>void confirmAction()}/></>:null}</RouteSheet>
 </View>;
}
