import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {freezeSocialOperation,isSocialInstant,validateBlockedPage,validateInvitationPage,validateSocialMutation,validateSocialOperation,validateSocialPage} from './model';
import type {BlockedCursor,BlockedPage,InvitationCursor,InvitationPage,SocialCursor,SocialMutationResponse,SocialOperation,SocialPage,SocialReceipt} from './types';
export type {BlockedCursor,BlockedPage,BlockedPerson,FriendRow,InvitationCursor,InvitationPage,InvitationRow,SocialCursor,SocialPage,SocialReceipt,SocialOperation,SocialMutationResponse} from './types';
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
const exact=(value:unknown,fields:readonly string[]):value is Record<string,unknown>=>!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===fields.length&&fields.every(key=>Object.hasOwn(value,key));
const id=(value:unknown):value is string=>typeof value==='string'&&uuid.test(value);
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function stableError(failure:{code?:string;message?:string}){if(failure.code==='PGRST301'||failure.code==='PGRST302'||failure.message==='Authentication required')return Error('SOCIAL_AUTH_REQUIRED');if(failure.message==='ACCOUNT_DELETION_PENDING')return Error('ACCOUNT_DELETION_PENDING');return Error('SOCIAL_UNAVAILABLE');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>):Promise<unknown>=>{current(scope,session);let response;try{response=await client.rpc(name,args);}catch{current(scope,session);throw Error('SOCIAL_UNAVAILABLE');}current(scope,session);if(response.error)throw stableError(response.error);return response.data;};}
function limitValid(limit:number){if(!Number.isInteger(limit)||limit<1||limit>30)throw Error('SOCIAL_INVALID');}
export async function getSocialSnapshot(scope:AuthScope,session:Session,limit=30,cursor:SocialCursor|null=null):Promise<SocialPage>{limitValid(limit);if(cursor!==null&&(!exact(cursor,['updated_at','user_id'])||!isSocialInstant(cursor.updated_at)||!id(cursor.user_id)))throw Error('SOCIAL_INVALID');const rpc=transport(scope,session);return validateSocialPage(await rpc('rs_social_snapshot',{p_limit:limit,p_before:cursor?.updated_at??null,p_before_user:cursor?.user_id??null}),scope.userId!);}
export async function getBlockedPeople(scope:AuthScope,session:Session,limit=30,cursor:BlockedCursor|null=null):Promise<BlockedPage>{limitValid(limit);if(cursor!==null&&(!exact(cursor,['user_id'])||!id(cursor.user_id)))throw Error('SOCIAL_INVALID');const rpc=transport(scope,session);return validateBlockedPage(await rpc('rs_blocked_people',{p_limit:limit,p_before_user:cursor?.user_id??null}),scope.userId!);}
export async function getInvitationInbox(scope:AuthScope,session:Session,limit=30,cursor:InvitationCursor|null=null):Promise<InvitationPage>{limitValid(limit);if(cursor!==null&&(!exact(cursor,['created_at','id'])||!isSocialInstant(cursor.created_at)||!id(cursor.id)))throw Error('SOCIAL_INVALID');const rpc=transport(scope,session);return validateInvitationPage(await rpc('rs_invitation_inbox',{p_limit:limit,p_before:cursor?.created_at??null,p_before_id:cursor?.id??null}),scope.userId!);}
/** No hidden retry/status lookup here: the durable coordinator owns response loss. */
export async function sendSocialMutation(scope:AuthScope,session:Session,value:SocialOperation):Promise<SocialMutationResponse>{const operation=freezeSocialOperation(value),rpc=transport(scope,session);return validateSocialMutation(await rpc('rs_social_mutate',{p_operation:operation.operationId,p_request:operation.request}),scope.userId!,operation);}
export async function getSocialOperation(scope:AuthScope,session:Session,operationId:string):Promise<SocialReceipt|null>{if(!id(operationId))throw Error('SOCIAL_INVALID');const rpc=transport(scope,session);return validateSocialOperation(await rpc('rs_social_operation',{p_operation:operationId}),scope.userId!,operationId);}
export async function heartbeatSocial(scope:AuthScope,session:Session):Promise<string>{const rpc=transport(scope,session),expiry=await rpc('rs_heartbeat',{});if(!isSocialInstant(expiry))throw Error('SOCIAL_INVALID_RESPONSE');return expiry;}
