import {test} from 'node:test';import assert from 'node:assert/strict';import jpeg from 'jpeg-js';import {encode} from 'blurhash';import {createHash} from 'node:crypto';
import {decode} from '../functions/_shared/vendor/jpeg-js-0.4.4-strict.mjs';
import {createCommunityCommitHandler,createCommunityURLHandler,readCommunityObject,readCommunityMediaRequest} from '../functions/_shared/community-media-handler.mjs';
import {createCommunityCleanupHandler} from '../functions/_shared/community-cleanup-handler.mjs';
const owner='00000000-0000-4000-8000-000000000071',postId='00000000-0000-4000-8000-000000000111',mediaId='00000000-0000-4000-8000-000000000112',token='00000000-0000-4000-8000-000000000113',path=`${owner}/${postId}/${mediaId}.jpg`,project='https://local-test.supabase.co',signed=`${project}/storage/v1/object/sign/ride-post-media/${path}?token=opaque-test-token`;
const response=(_req,body,status=200)=>Response.json(body,{status}),req=body=>new Request('https://local.test/functions/v1/test',{method:'POST',body:JSON.stringify(body??{postId,mediaId})}),digest=async bytes=>createHash('sha256').update(bytes).digest('hex');
function fixture(){const pixels=new Uint8Array(20*20*4).fill(255),bytes=new Uint8Array(jpeg.encode({data:pixels,width:20,height:20},75).data),declared={mime:'image/jpeg',sha256:createHash('sha256').update(bytes).digest('hex'),byte_count:bytes.length,width:20,height:20,blurhash:null},events=[];let committed=null;
 const admin={rpc:async(name,args)=>{events.push([name,args]);if(name==='rs_claim_community_media')return{data:committed?{state:'committed',post_id:postId,media_id:mediaId,descriptor:committed}:{state:'reserved',post_id:postId,media_id:mediaId,bucket:'ride-post-media',path,declared,token}};if(name==='rs_finish_community_media'){committed=args.p_descriptor;return{data:{post_id:postId,media_id:mediaId,descriptor:committed}};}return{data:null};},storage:{from:bucket=>({createSignedUrl:async(p,ttl)=>{events.push(['sign',{bucket,path:p,ttl}]);return{data:{signedUrl:signed}};}})}};
 const ports={authenticate:async()=>({userId:owner,admin}),preflight:()=>null,response,projectUrl:()=>project,decode,encodeBlurhash:encode,digest,fetcher:async(url,options)=>{events.push(['fetch',{url,redirect:options.redirect}]);return new Response(bytes,{headers:{'content-length':String(bytes.length)}});},uuid:()=>token};return{ports,bytes,declared,events,admin};
}
test('actual entropy commit binds actor/post/asset, derived descriptor and exact canonical response; committed retry has no download',async()=>{
 const f=fixture(),handler=createCommunityCommitHandler(f.ports),result=await handler(req());assert.equal(result.status,200);const value=await result.json();assert.equal(value.descriptor.sha256,f.declared.sha256);assert.equal(typeof value.descriptor.blurhash,'string');assert.equal(f.events.filter(x=>x[0]==='fetch').length,1);assert.equal(f.events.find(x=>x[0]==='rs_finish_community_media')[1].p_owner,owner);assert.deepEqual(await(await handler(req())).json(),value);assert.equal(f.events.filter(x=>x[0]==='fetch').length,1);
});
test('foreign paths and unsigned origins never reach fetch; malformed actual bytes release exact reservation as invalid',async()=>{
 const foreign=fixture();foreign.admin.rpc=async()=>({data:{state:'reserved',post_id:postId,media_id:mediaId,bucket:'ride-post-media',path:`${mediaId}/${path}`,declared:foreign.declared,token}});assert.equal((await createCommunityCommitHandler(foreign.ports)(req())).status,503);assert.equal(foreign.events.length,0);
 const corrupt=fixture();corrupt.ports.fetcher=async()=>new Response(new Uint8Array(corrupt.bytes.length));const result=await createCommunityCommitHandler(corrupt.ports)(req());assert.equal((await result.json()).error.code,'COMMUNITY_MEDIA_INVALID');assert.equal(corrupt.events.at(-1)[0],'rs_release_community_media');assert.equal(corrupt.events.at(-1)[1].p_invalid,true);
 const badURL=fixture();badURL.admin.storage.from=()=>({createSignedUrl:async()=>({data:{signedUrl:'https://foreign.test/secret'}})});assert.equal((await createCommunityCommitHandler(badURL.ports)(req())).status,503);assert.equal(badURL.events.some(x=>x[0]==='fetch'),false);
});
test('bounded requests/streams reject foreign keys, invalid UTF-8, missing/extra bytes independently of Content-Length',async()=>{
 await assert.rejects(readCommunityMediaRequest(req({postId,mediaId,path})));await assert.rejects(readCommunityMediaRequest(new Request('https://local.test',{method:'POST',body:new Uint8Array([255])})));await assert.rejects(readCommunityMediaRequest(new Request('https://local.test',{method:'POST',body:'x'.repeat(4097)})));
 await assert.rejects(readCommunityObject(signed,10,async()=>new Response(new Uint8Array(11))));await assert.rejects(readCommunityObject(signed,10,async()=>new Response(new Uint8Array(9))));await assert.rejects(readCommunityObject(signed,10,async()=>new Response(new Uint8Array(10),{headers:{'content-length':'99999'}})));
});
test('signed media rechecks current caller parent after signing; blocks or raw DB failures cannot return URL/error text',async()=>{
 const f=fixture(),asset={post_id:postId,media_id:mediaId,bucket:'ride-post-media',path,sha256:f.declared.sha256};let read=0;f.ports.authenticate=async()=>({userId:owner,admin:f.admin,userClient:{rpc:async()=>({data:++read===1?asset:{error:{code:'COMMUNITY_UNAVAILABLE'}}})}});const denied=await createCommunityURLHandler(f.ports)(req());assert.equal((await denied.json()).error.code,'COMMUNITY_UNAVAILABLE');
 f.ports.authenticate=async()=>({userId:owner,admin:f.admin,userClient:{rpc:async()=>({error:{code:'XX999',message:'private raw SQL and GPS'}})}});const unavailable=await createCommunityURLHandler(f.ports)(req());assert.equal(JSON.stringify(await unavailable.json()).includes('private raw'),false);
});
test('anonymous commit fails before request/storage work and returns fixed nested auth error',async()=>{const f=fixture();f.ports.authenticate=async()=>{throw Object.assign(Error('opaque'),{code:'AUTH_REQUIRED'});};const out=await createCommunityCommitHandler(f.ports)(req());assert.equal(out.status,401);assert.deepEqual(await out.json(),{error:{code:'COMMUNITY_AUTH_REQUIRED'}});assert.equal(f.events.length,0);});
test('cleanup is service-authenticated and binary removal must succeed before exact lease ACK',async()=>{
 const events=[],admin={rpc:async(name,args)=>{events.push([name,args]);return name==='rs_claim_community_media_cleanup'?{data:[{bucket:'ride-post-media',path,token}]}:{data:null};},storage:{from:()=>({remove:async()=>{events.push(['remove']);return{error:{message:'Storage unavailable'}};}})}};
 class HttpError extends Error{constructor(status,code){super(code);this.status=status;this.code=code;}}const handler=createCommunityCleanupHandler({authorize:async()=>admin,response,HttpError,failure:(_req,e)=>Response.json({error:e.code},{status:e.status??503})}),out=await handler(req({}));assert.equal(out.status,503);assert.equal(events.some(x=>x[0]==='rs_ack_community_media_cleanup'),false);assert.equal(events.at(-1)[0],'rs_release_community_media_cleanup');
});
