import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {stripTypeScriptTypes} from 'node:module';import {runInNewContext} from 'node:vm';
import {RouteProviderError,readRouteServiceRequest,normalizeRouteProviderResult,routeProviderDistance,routeProviderFailureReason,routeProviderURL} from '../functions/_shared/route-provider.ts';
const owner='00000000-0000-4000-8000-000000000041',lease='40000000-0000-4000-8000-000000000041';
const input={operation:'route',stops:[{latitude:13.7,longitude:100.5},{latitude:13.71,longitude:100.5}],profile:'scooter',consent:true};
const upstream={type:'FeatureCollection',properties:{apiKey:'NEVER_RETURN'},features:[{type:'Feature',geometry:{type:'MultiLineString',coordinates:[[[100.5,13.7],[100.5,13.71]]]},properties:{distance:1200,distance_units:'Meters',time:180,legs:[]}}]};
const req=(body=input)=>new Request('https://configured.test/route-service',{method:'POST',body:JSON.stringify(body)});
test('request parser demands explicit consent, exact operation fields, bounded pins/query and valid UTF-8',async()=>{assert.deepEqual(await readRouteServiceRequest(req()),input);for(const body of [{...input,consent:false},{...input,ownerId:owner},{...input,url:'https://elsewhere'},{...input,stops:[input.stops[0]]},{...input,profile:'bicycle'},{operation:'search',query:'ab',language:'th',consent:true}])await assert.rejects(readRouteServiceRequest(req(body)),/INVALID_REQUEST/);assert.equal((await readRouteServiceRequest(req({operation:'search',query:'  กรุงเทพมหานคร   ',language:'th',consent:true}))).query,'กรุงเทพมหานคร');await assert.rejects(readRouteServiceRequest(new Request('https://x',{method:'POST',body:new Uint8Array([255])})),/INVALID_REQUEST/);await assert.rejects(readRouteServiceRequest(new Request('https://x',{method:'POST',body:'x'.repeat(16385)})),/REQUEST_TOO_LARGE/);});
test('provider URLs are fixed, requests have metric coordinates in correct order and no paid extras',()=>{const url=new URL(routeProviderURL(input,'test-only-key'));assert.equal(url.origin,'https://api.geoapify.com');assert.equal(url.pathname,'/v1/routing');assert.equal(url.searchParams.get('waypoints'),'13.7,100.5|13.71,100.5');assert.equal(url.searchParams.get('mode'),'scooter');assert.equal(url.searchParams.get('units'),'metric');for(const key of ['details','avoid','optimize_stops','elevation'])assert.equal(url.searchParams.has(key),false);});
test('normalizer preserves disconnected GeoJSON legs, coordinate order and drops request/key properties',()=>{const result=normalizeRouteProviderResult(input,upstream,new Date('2026-10-01T03:00:00Z'));assert.deepEqual(result.segments,[[{latitude:13.7,longitude:100.5},{latitude:13.71,longitude:100.5}]]);assert.equal(result.distanceMeters,1200);assert.equal(result.durationSeconds,180);assert.equal(JSON.stringify(result).includes('NEVER_RETURN'),false);for(const body of [{...upstream,features:[]},{...upstream,features:[{...upstream.features[0],properties:{distance:1200,distance_units:'Miles',time:180}}]},{...upstream,features:[{...upstream.features[0],geometry:{type:'LineString',coordinates:[[100.5,13.7],[100.5,13.71]]}}]}])assert.throws(()=>normalizeRouteProviderResult(input,body,new Date()),/NO_ROUTE|PROVIDER_UNAVAILABLE/);});
class HttpError extends Error{constructor(status,code){super(code);this.status=status;this.code=code;}}
const response=(_req,body,status=200)=>Response.json(body,{status}),failure=(req,e)=>response(req,{error:e instanceof HttpError?e.code:'SERVICE_UNAVAILABLE'},e.status??503);
async function handlerFor(context){const source=await readFile(new URL('../functions/route-service/index.ts',import.meta.url),'utf8');let handler;runInNewContext(stripTypeScriptTypes(source.replace(/^import .*;\r?\n/gm,''),{mode:'strip'}),{Deno:{serve:fn=>handler=fn,env:{get:key=>key==='GEOAPIFY_API_KEY'?'test-only-key':undefined}},HttpError,RouteProviderError,readRouteServiceRequest,normalizeRouteProviderResult,routeProviderDistance,routeProviderFailureReason,routeProviderURL,preflight:()=>null,response,failure,AbortController,setTimeout,clearTimeout,TextDecoder,Uint8Array,Date,Error,...context});return handler;}
function boundary(options={}){const calls=[];return{calls,authenticate:async()=>({userId:owner,admin:{rpc:async(name,args)=>{calls.push(name);assert.equal(args.p_owner,owner);if(name==='rs_route_service_claim'){assert.deepEqual(Object.keys(args),['p_owner','p_request']);return options.claim??{data:{state:'claimed',lease,requestHash:'a'.repeat(64)},error:null};}assert.equal(args.p_lease,lease);if(name==='rs_route_service_reconcile'){assert.deepEqual(Object.keys(args),['p_owner','p_lease','p_distance_m']);assert.equal(args.p_distance_m,options.distance??1200);return options.rpcErrors?.[name]?{data:null,error:options.rpcErrors[name]}:{data:null,error:null};}assert.equal(name,'rs_route_service_finish');assert.deepEqual(Object.keys(args),['p_owner','p_lease','p_result']);return options.rpcErrors?.[name]?{data:null,error:options.rpcErrors[name]}:{data:{...args.p_result,routeToken:lease,requestHash:'a'.repeat(64)},error:null};}}}),fetch:async(url,init)=>{calls.push('fetch');assert.equal(new URL(url).searchParams.get('apiKey'),'test-only-key');assert.equal(init.redirect,'error');return options.provider??Response.json(upstream);}};}
test('canonical Edge reserves quota before egress, normalizes response, commits owner result and does not return key',async()=>{const b=boundary(),res=await(await handlerFor(b))(req());assert.equal(res.status,200);const result=await res.json();assert.equal(result.cached,false);assert.equal(result.routeToken,lease);assert.equal(JSON.stringify(result).includes('test-only-key'),false);assert.deepEqual(b.calls,['rs_route_service_claim','fetch','rs_route_service_reconcile','rs_route_service_finish']);});
test('private cache hits skip provider egress and quota rejection never starts network work',async()=>{const hit=boundary({claim:{data:{state:'cached',result:{items:[],attribution:'Powered by Geoapify'}},error:null}}),res=await(await handlerFor(hit))(req({operation:'search',query:'Bangkok',language:'en',consent:true}));assert.equal((await res.json()).cached,true);assert.deepEqual(hit.calls,['rs_route_service_claim']);const limited=boundary({claim:{data:null,error:{message:'QUOTA_EXCEEDED'}}});const denied=await(await handlerFor(limited))(req());assert.equal(denied.status,429);assert.deepEqual(await denied.json(),{error:'QUOTA_EXCEEDED'});assert.deepEqual(limited.calls,['rs_route_service_claim']);});
test('provider errors and oversized streams expose stable errors without committing untrusted bodies',async()=>{for(const provider of [new Response('private key-bearing URL',{status:503}),new Response('x'.repeat(1048577),{status:200})]){const b=boundary({provider}),res=await(await handlerFor(b))(req());assert.equal(res.status,503);assert.deepEqual(await res.json(),{error:'PROVIDER_UNAVAILABLE'});assert.deepEqual(b.calls,['rs_route_service_claim','fetch']);}});
test('too-long provider work is reconciled before rejection, never cached or disguised as an input error',async()=>{const long=structuredClone(upstream);long.features[0].properties.distance=1600000;const b=boundary({provider:Response.json(long),distance:1600000}),res=await(await handlerFor(b))(req());assert.equal(res.status,400);assert.deepEqual(await res.json(),{error:'ROUTE_DISTANCE_LIMIT'});assert.deepEqual(b.calls,['rs_route_service_claim','fetch','rs_route_service_reconcile']);});
test('normalization reasons are deterministic whitelist codes, never provider values or error text',()=>{
 const cases=[['geometry_type',b=>b.features[0].geometry.type='secret-shaped-type'],['distance_units_other',b=>b.features[0].properties.distance_units='secret-unit'],['duration',b=>delete b.features[0].properties.time],['coordinate_dimensions',b=>b.features[0].geometry.coordinates[0][0].push(999)],['coordinate_bounds',b=>b.features[0].geometry.coordinates[0][0][1]=91],['part_size',b=>b.features[0].geometry.coordinates[0]=[]]];
 for(const [reason,change]of cases){const body=structuredClone(upstream);change(body);assert.throws(()=>normalizeRouteProviderResult(input,body,new Date()),error=>{assert.equal(routeProviderFailureReason(error),reason);assert.equal(error.message,'PROVIDER_UNAVAILABLE');return true;});}
 assert.equal(routeProviderFailureReason(new RouteProviderError(503,'PROVIDER_UNAVAILABLE','secret-unit')),null);assert.equal(routeProviderFailureReason(Error('secret-url')),null);
});
test('distance unit diagnostics reject abbreviated, imperial, absent and unknown values without inventing metres',()=>{
 for(const [unit,reason]of [['m','distance_units_m'],['Miles','distance_units_imperial'],['miles','distance_units_imperial'],['secret-bearing-unknown','distance_units_other'],[null,'distance_units_other'],[undefined,'distance_units_absent']]){
  const body=structuredClone(upstream);if(unit===undefined)delete body.features[0].properties.distance_units;else body.features[0].properties.distance_units=unit;
  assert.equal(routeProviderDistance(body),null);assert.throws(()=>normalizeRouteProviderResult(input,body,new Date()),error=>routeProviderFailureReason(error)===reason);
 }
});
test('documented and empirically observed metre case spellings normalize and reconcile the same metric work',async()=>{
 const lower=structuredClone(upstream);lower.features[0].properties.distance_units='meters';
 const time=new Date('2026-10-01T06:54:56Z');assert.deepEqual(normalizeRouteProviderResult(input,lower,time),normalizeRouteProviderResult(input,upstream,time));assert.equal(routeProviderDistance(lower),1200);
 const b=boundary({provider:Response.json(lower)}),res=await(await handlerFor(b))(req());assert.equal(res.status,200);assert.equal((await res.json()).distanceMeters,1200);assert.deepEqual(b.calls,['rs_route_service_claim','fetch','rs_route_service_reconcile','rs_route_service_finish']);
});
test('SQL reconcile/finish failures never swap a call ID for the lease, cache a failure or log private SQL text',async()=>{
 for(const [rpc,stage]of [['rs_route_service_reconcile','reconcile'],['rs_route_service_finish','finish']]){
  const logs=[],b=boundary({rpcErrors:{[rpc]:{code:'22023',message:'SECRET SQL request coordinates key-bearing URL'}}});
  const res=await(await handlerFor({...b,console:{warn:(...args)=>logs.push(args)}}))(req());assert.equal(res.status,503);assert.deepEqual(await res.json(),{error:'PROVIDER_UNAVAILABLE'});
  assert.equal(logs.length,1);assert.equal(logs[0][1].stage,stage);assert.equal(logs[0][1].databaseCode,'22023');assert.equal(logs[0][1].normalizationReason,null);assert.equal(JSON.stringify(logs).includes('SECRET'),false);assert.equal(b.calls.at(-1),rpc);
 }
 const logs=[],body=structuredClone(upstream);body.features[0].geometry.coordinates[0][0].push(42);
 const res=await(await handlerFor({...boundary({provider:Response.json(body)}),console:{warn:(...args)=>logs.push(args)}}))(req());assert.equal(res.status,503);assert.equal(logs[0][1].normalizationReason,'coordinate_dimensions');assert.equal(logs[0][1].upstreamStatus,200);assert.deepEqual(Object.keys(logs[0][1]),['stage','upstreamStatus','databaseCode','normalizationReason']);
});
