// Actual SQL outputs through the maintained TypeScript decoders, no DTO stubs.
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {PGlite} from '@electric-sql/pglite';
import {liveModule} from '../../ExpoRideSpeed/tests/helpers/live.mjs';
import {initialize,ports,profiles,friends,room,join,approve,start,grant,sample,request,hash,A,B,C,id} from './live-fixture.mjs';
const model=liveModule('model');let db,p;const R=id(7000);before(async()=>{db=new PGlite();await initialize(db);p=ports(db);await profiles(p);await p.admin('update ride_private.live_policy set live_enabled=true');await friends(p,A,B);await friends(p,A,C);});after(async()=>{await db?.close()});
const checkReceipt=(receipt,owner)=>model.validateLiveReceipt(receipt,owner,{operationId:receipt.operation_id,request:receipt.request});
test('actual SQL link/create/proof/request/revoke envelopes pass owner/exact-operation client decoders',async()=>{const token='E'.repeat(43),ack=await p.mutate(A,id(7001),request('friend_link_create',{link_id:id(7002),token_hash:hash('friend-link',token),ttl_seconds:3600}));checkReceipt(ack,A);model.validateFriendLinks(await p.value(A,'select public.rs_friend_links() as value'),A);const resolved=model.validateFriendLinkResolution(await p.value(C,'select public.rs_resolve_friend_link($1,$2) as value',[id(7002),token]),C,id(7002));checkReceipt(await p.mutate(C,id(7003),request('friend_link_request',{proof_id:resolved.preview.proof_id,issuer_id:A})),C);checkReceipt(await p.mutate(A,id(7004),request('friend_link_revoke',{link_id:id(7002),expected_revision:1})),A);});
test('actual SQL host/applicant/accepted list and hidden-consent shapes match the frozen client wire',async()=>{checkReceipt(await room(p,A,R,id(7005)),A);model.validateConvoySnapshot(await p.snapshot(A,R),A,R);model.validateConvoyList(await p.value(A,'select public.rs_list_convoys() as value'),A);model.validateConvoyCodeResolution(await p.value(B,'select public.rs_resolve_convoy_code($1) as value',['ABCD1234']),B);checkReceipt(await join(p,B,R,'ABCD1234',id(7006)),B);model.validateConvoySnapshot(await p.snapshot(B,R),B,R);checkReceipt(await approve(p,A,B,R,id(7007)),A);model.validateConvoySnapshot(await p.snapshot(B,R),B,R);checkReceipt(await start(p,A,R,id(7008)),A);});
test('actual SQL initial none revision-zero revoke remains a valid idempotent client receipt',async()=>{const view=await p.snapshot(A,R),ack=await p.mutate(A,id(7009),request('location_revoke',{convoy_id:R,expected_member_generation:view.self_generation,expected_consent_revision:0,expected_lease_id:null}));assert.equal(ack.result.revision,0);checkReceipt(ack,A);});
test('actual SQL grant/publish/peer/heartbeat and exact revoke pass maintained client validators',async()=>{const ack=await grant(p,B,R,id(7010));checkReceipt(ack,B);const body=model.freezeLiveSample(await sample(p,B,R)),reply=await p.value(B,'select public.rs_publish_live_position($1::jsonb) as value',[JSON.stringify(body)]);model.validateLivePublishAck(reply,B,body);const host=model.validateConvoySnapshot(await p.snapshot(A,R),A,R);model.validateConvoyPositions(await p.value(A,'select public.rs_convoy_positions($1,$2) as value',[R,host.topic_generation]),A,host);model.validateConvoyHeartbeat(await p.value(A,'select public.rs_convoy_heartbeat($1,$2) as value',[R,host.self_generation]),A,host);const view=await p.snapshot(B,R);checkReceipt(await p.mutate(B,id(7011),request('location_revoke',{convoy_id:R,expected_member_generation:view.self_generation,expected_consent_revision:view.self_consent.revision,expected_lease_id:view.self_consent.lease_id})),B);});
test('actual SQL departed member rejoin masks applicant consent metadata and later approval restores canonical revision',async()=>{let view=await p.snapshot(B,R);checkReceipt(await p.mutate(B,id(7020),request('convoy_member',{convoy_id:R,other_id:B,verb:'leave',expected_room_revision:view.revision,expected_member_generation:view.self_generation,expected_member_state:'accepted'})),B);assert.equal(await p.snapshot(B,R),null);checkReceipt(await join(p,B,R,'ABCD1234',id(7021)),B);view=model.validateConvoySnapshot(await p.snapshot(B,R),B,R);assert.equal(view.self_consent.revision,0);checkReceipt(await approve(p,A,B,R,id(7022)),A);assert.ok(model.validateConvoySnapshot(await p.snapshot(B,R),B,R).self_consent.revision>0);});
test('actual SQL cancellation proof is request-bound and typed cancellation remains distinct from a receipt',async()=>{const view=await p.snapshot(A,R),req=request('location_grant',{convoy_id:R,expected_room_revision:view.revision,expected_member_generation:view.self_generation,expected_consent_revision:view.self_consent.revision,capture_id:id(7030),duration_seconds:900,precision:'precise'}),operation={operationId:id(7031),request:req};const proof=await p.value(A,'select public.rs_cancel_live_grant($1,$2::jsonb) as value',[operation.operationId,JSON.stringify(req)]);assert.equal(proof.state,'cancelled');model.validateLiveGrantCancellation(proof,A,operation);const rejected=await p.mutate(A,operation.operationId,req);assert.deepEqual(model.validateLiveMutation(rejected,A,operation),{error:{code:'LIVE_OPERATION_CANCELLED'}});});
test('actual SQL terminal host/member views contain no topic/code/location and decode without raw endpoints',async()=>{const view=await p.snapshot(A,R);checkReceipt(await p.mutate(A,id(7040),request('convoy_end',{convoy_id:R,expected_room_revision:view.revision,verb:'end'})),A);for(const owner of[A,B]){const final=model.validateConvoySnapshot(await p.snapshot(owner,R),owner,R);assert.equal(final.topic,null);assert.equal(final.self_code,null);assert.equal(final.self_consent.precision,'none');assert.equal(final.members.length,owner===A?1:2);assert.equal(JSON.stringify(final).includes('Secret home'),false);}});
