// Mandatory local rollout proof when the authorized portable PostgreSQL exists.
// It accepts only the disposable loopback17.11 runtime, never a remote URL/key.
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Client} from 'pg';
import {initialize,ports,profiles,friends,A,B,C,D,E,F,request} from './live-fixture.mjs';
import {approvedRaceCourse,createRace,acceptRace,reserveRaceAttempt,stageRaceAttempt,probeRaceAttempt,armRaceAttempt,bindRaceEvidence,nextRaceId} from './race-fixture.mjs';
let settings;try{settings=JSON.parse(await readFile(new URL('../../build/local-postgres/readiness.json',import.meta.url),'utf8'));}catch{}
const available=!!settings,connections=[];let admin,db,p,dbname;
async function connect(database,name='race-test'){const c=new Client({host:'127.0.0.1',port:settings.port,user:'ride_test_admin',database,application_name:name,ssl:false,connectionTimeoutMillis:5000});await c.connect();c.exec=sql=>c.query(sql);await c.query("set timezone='UTC';set lock_timeout='3s';set statement_timeout='6s'");connections.push(c);return c;}
async function actor(owner,name){const c=await connect(dbname,name);await c.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await c.query('set role authenticated');return c;}
const value=async(c,sql,args=[])=>(await c.query(sql,args)).rows[0].value;
const settle=promise=>promise.then(value=>({value}),error=>({error}));
async function waitBlocked(c){for(let n=0;n<100;n++){const row=(await db.query('select wait_event from pg_stat_activity where pid=$1',[c.processID])).rows[0];if(row?.wait_event==='advisory')return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('RPC did not reach the common advisory fence');}
async function clean(){await db.query(`truncate ride_private.race_course_approvals,ride_private.race_operations,ride_private.race_activation_cancellations,ride_private.race_admission,ride_private.race_poll_slots,ride_private.race_evidence_cleanup cascade;delete from public.rs_blocks;delete from public.rs_friendships;delete from ride_private.daily_quotas;delete from storage.objects where bucket_id='ride-race-evidence';update ride_private.race_policy set enabled=true;`);}
async function armInput(){await clean();const f=await createRace(p),a=await reserveRaceAttempt(p,f),stage=await stageRaceAttempt(p,f,a),clock=await probeRaceAttempt(p,f,a);return{f,a,operation:nextRaceId(),body:request('attempt_arm',{attempt_id:a.attemptId,expected_revision:1,stage_proof_id:stage.proof.proof_id,capture_id:a.captureId,clock_probe_ids:clock.probes.map(x=>x.probe_id)})};}
before(async()=>{if(!available)return;assert.equal(settings.host,'127.0.0.1');assert.equal(settings.user,'ride_test_admin');assert.equal(settings.version,'17.11');assert.ok(Number.isInteger(settings.port)&&settings.port>1024&&settings.port<65536);admin=await connect('postgres','race-bootstrap');dbname=`ride_race_m5c_${process.pid}_${Date.now()}`;assert.match(dbname,/^ride_race_m5c_[0-9]+_[0-9]+$/);await admin.query(`create database ${dbname}`);db=await connect(dbname,'race-controller');await db.query("do $$begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin;end if;if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin;end if;if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls;end if;end$$");await initialize(db,{roles:false});p=ports(db);await profiles(p);});
after(async()=>{if(!available)return;for(const c of connections.filter(x=>x!==admin))await c.end();if(dbname)await admin.query(`drop database ${dbname}`);await admin.end();});
test('realPG exact activation cancellation fences a delayed arm without applying future authority',{skip:!available},async()=>{
 const f=await armInput(),cancel=await actor(A,'race-cancel-first'),send=await actor(A,'race-arm-delayed');await cancel.query('begin');
 const proof=await value(cancel,'select public.rs_cancel_race_activation($1,$2::jsonb) value',[f.operation,JSON.stringify(f.body)]);assert.equal(proof.kind,'cancelled');
 const pending=settle(value(send,'select public.rs_race_mutate($1,$2::jsonb) value',[f.operation,JSON.stringify(f.body)]));await waitBlocked(send);await cancel.query('commit');const out=await pending;assert.equal(out.error,undefined);assert.deepEqual(out.value,{error:{code:'RACE_OPERATION_CANCELLED'}});
 assert.equal((await db.query('select state from ride_private.race_attempts where id=$1',[f.a.attemptId])).rows[0].state,'reserved');
});
test('realPG applied arm wins concurrent cancellation only as the original immutable recoverable receipt',{skip:!available},async()=>{
 const f=await armInput(),send=await actor(A,'race-arm-first'),cancel=await actor(A,'race-cancel-after');await send.query('begin');const receipt=await value(send,'select public.rs_race_mutate($1,$2::jsonb) value',[f.operation,JSON.stringify(f.body)]);assert.equal(receipt.result.attempt.state,'armed');
 const pending=settle(value(cancel,'select public.rs_cancel_race_activation($1,$2::jsonb) value',[f.operation,JSON.stringify(f.body)]));await waitBlocked(cancel);await send.query('commit');const out=await pending;assert.equal(out.error,undefined);assert.deepEqual(out.value,receipt);
});
test('realPG route edit enters global fence before route rows and cannot deadlock another owner preparing to arm',{skip:!available},async()=>{
 await clean();const f=await createRace(p);await acceptRace(p,f);const a=await reserveRaceAttempt(p,f,B),stage=await stageRaceAttempt(p,f,a),clock=await probeRaceAttempt(p,f,a),writer=await actor(A,'race-route-writer'),sender=await actor(B,'race-arm-peer');
 await writer.query('begin');await writer.query('select public.rs_save_route_v2($1,$2,1,$3::jsonb)',[nextRaceId(),f.routeId,JSON.stringify({...f.document,title:'Changed after approval'})]);
 const body=request('attempt_arm',{attempt_id:a.attemptId,expected_revision:1,stage_proof_id:stage.proof.proof_id,capture_id:a.captureId,clock_probe_ids:clock.probes.map(x=>x.probe_id)}),pending=settle(value(sender,'select public.rs_race_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(body)]));await waitBlocked(sender);await writer.query('commit');const out=await pending;assert.equal(out.error,undefined);assert.equal(out.value.error.code,'RACE_APPROVAL_UNAVAILABLE');assert.equal((await db.query('select state from ride_private.race_attempts where id=$1',[a.attemptId])).rows[0].state,'dnf');
});
test('realPG two creators contend for the final live pilot slot without over-admission',{skip:!available},async()=>{
 await clean();await createRace(p,{mode:'live'});const prepared=[];for(const[owner,peer]of[[C,D],[E,F]]){const c=await approvedRaceCourse(p,owner);await friends(p,owner,peer);prepared.push({owner,body:request('race_create',{race_id:nextRaceId(),mode:'live',approval_id:c.approvalId,route_id:c.routeId,route_revision:1,reviewed_projection_hash:c.projection.geometryHash,starts_at:c.startsAt,ends_at:c.endsAt,friends:[{user_id:peer,friendship_generation:10}],acknowledgement_version:1,evidence_consent_version:1})});}
 const actors=await Promise.all(prepared.map((x,i)=>actor(x.owner,`race-capacity-${i}`))),results=await Promise.all(prepared.map((x,i)=>value(actors[i],'select public.rs_race_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(x.body)])));
 assert.equal(results.filter(x=>!x.error).length,1);assert.equal(results.find(x=>x.error).error.code,'RACE_CAPACITY');assert.equal((await db.query("select count(*)::int n from ride_private.races where mode='live' and state='lobby'")).rows[0].n,2);
});
test('realPG a committed block clears verifier authority before a waiting opposite-owner finalization',{skip:!available},async()=>{
 await clean();const f=await createRace(p);await acceptRace(p,f);const a=await reserveRaceAttempt(p,f,B),armed=await armRaceAttempt(p,f,a),bound=await bindRaceEvidence(p,a,armed),reservation=bound.receipt.result.reservation;
 await db.query("insert into storage.objects(bucket_id,name,owner_id,metadata) values('ride-race-evidence',$1,$2,'{\"size\":50000,\"mimetype\":\"application/json\"}')",[reservation.path,B]);await p.value(B,'select public.rs_race_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(request('evidence_queue',{attempt_id:a.attemptId,expected_revision:bound.receipt.result.attempt.revision,sha256:reservation.sha256}))]);
 const claim=(await p.service('select public.rs_claim_race_attempt($1,$2) value',[a.attemptId,B])).rows[0].value,blocker=await actor(A,'race-block-first'),worker=await connect(dbname,'race-finalize-waiter');await blocker.query('begin');await value(blocker,'select public.rs_social_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(request('friend_action',{other_id:B,verb:'block',expected_generation:10}))]);
 const pending=settle(worker.query('select public.rs_finalize_race_attempt($1,$2,$3::jsonb)',[a.attemptId,claim.token,'{}']));await waitBlocked(worker);await blocker.query('commit');const out=await pending;assert.match(out.error?.message??'',/RACE_ELIGIBILITY_OR_LEASE_CHANGED/);assert.equal((await db.query('select count(*)::int n from ride_private.race_results')).rows[0].n,0);
});
test('realPG janitor and deletion preserve account-global order and quarantine without a foreign account fence',{skip:!available},async()=>{
 await clean();const f=await createRace(p,{owner:E,peer:F}),janitor=await connect(dbname,'race-janitor'),deletion=await connect(dbname,'race-deletion');await janitor.query('begin');await janitor.query('select public.rs_race_cleanup()');const pending=settle(value(deletion,'select public.rs_begin_account_deletion($1,$2) value',[E,nextRaceId()]));await waitBlocked(deletion);await janitor.query('commit');const out=await pending;assert.equal(out.error,undefined);assert.equal(out.value.state,'storage_pending');assert.equal((await db.query('select state from ride_private.races where id=$1',[f.raceId])).rows[0].state,'cancelled');
});
test('realPG two evidence reservations contend for final256MiB capacity without over-admission',{skip:!available},async()=>{
 await clean();const f=await createRace(p);await acceptRace(p,f);const attempts=[];
 for(const owner of[A,B]){const a=await reserveRaceAttempt(p,f,owner),armed=await armRaceAttempt(p,f,a);attempts.push({owner,body:request('evidence_bind',{attempt_id:a.attemptId,expected_revision:armed.receipt.result.attempt.revision,capture_id:a.captureId,first_sequence:1,last_sequence:80,sample_count:80,byte_length:50000,sha256:'a'.repeat(64)})});}
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('ride-race-evidence','disposable-capacity-fixture',$1::jsonb)",[JSON.stringify({size:268435456-50000})]);
 const first=await actor(A,'race-byte-capacity-first'),second=await actor(B,'race-byte-capacity-next');await first.query('begin');const accepted=await value(first,'select public.rs_race_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(attempts[0].body)]);assert.ok(accepted.result.reservation);
 const pending=settle(value(second,'select public.rs_race_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(attempts[1].body)]));await waitBlocked(second);await first.query('commit');const denied=await pending;assert.equal(denied.error,undefined);assert.equal(denied.value.error.code,'RACE_CAPACITY');assert.equal(Number((await db.query('select ride_private.race_reserved_evidence_bytes() n')).rows[0].n),268435456);
});
