// Execute the operator SQL against real migration009. The Cron facade verifies
// our setup/retention statements, not a managed scheduler or extension install.
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
import {initialize} from './live-fixture.mjs';
let db;const file=name=>readFile(new URL(`../ops/${name}.sql`,import.meta.url),'utf8');
before(async()=>{db=new PGlite();await initialize(db);});after(async()=>{await db?.close();});
const facade=`create schema cron;
create table cron.job(jobid bigserial primary key,jobname text not null,username text not null default current_user,database text not null default current_database(),schedule text not null,command text not null,active boolean not null default true,unique(jobname,username));
create table cron.job_run_details(runid bigserial primary key,jobid bigint not null references cron.job(jobid),status text,start_time timestamptz,end_time timestamptz);
create function cron.schedule(job_name text,schedule text,command text) returns bigint language plpgsql as $$declare job_id bigint;begin insert into cron.job(jobname,schedule,command) values($1,$2,$3) on conflict(jobname,username) do update set schedule=excluded.schedule,command=excluded.command returning jobid into job_id;return job_id;end$$;
create function cron.alter_job(job_id bigint,schedule text default null,command text default null,database text default null,username text default null,active boolean default null) returns void language sql as $$update cron.job j set schedule=coalesce($2,j.schedule),command=coalesce($3,j.command),database=coalesce($4,j.database),username=coalesce($5,j.username),active=coalesce($6,j.active) where j.jobid=$1$$;`;
test('operator readiness returns only catalog/aggregates and safely identifies absent Cron without enabling races',async()=>{
 const row=(await db.query(await file('m5c-race-readiness'))).rows[0].race_readiness;
 assert.equal(row.policy.enabled,false);assert.equal(row.private_tables.length,13);for(const item of row.private_tables){assert.equal(item.rls,true);assert.equal(item.anon_select,false);assert.equal(item.authenticated_select,false);assert.equal(item.authenticated_write,false);}assert.equal(row.functions.length,23);assert.equal(row.predecessor_helpers.count,6);assert.equal(row.predecessor_helpers.browser_or_service_execute,false);assert.equal(row.cron.named_schedule_present,false);assert.equal(row.retained_counts.stage_rows,0);
 const cleanup=row.functions.find(f=>f.signature==='rs_race_cleanup()');assert.equal(cleanup.authenticated_execute,false);assert.equal(cleanup.service_execute,true);
 await assert.rejects(db.exec(await file('m5c-race-cron')),/RACE_CRON_EXTENSION_REQUIRED/);await db.exec('rollback');assert.equal((await db.query('select enabled from ride_private.race_policy')).rows[0].enabled,false);await db.exec(facade);
});
test('named setup is repeatable, repairs its inactive own job and never changes an unrelated job',async()=>{
 await db.query("select cron.schedule('unrelated-job','0 0 * * *','select 42')");const unrelated=(await db.query("select * from cron.job where jobname='unrelated-job'")).rows[0];const setup=await file('m5c-race-cron');await db.exec(setup);const first=(await db.query("select * from cron.job where jobname='ride-race-state-cleanup-v1'")).rows[0];assert.equal(first.schedule,'* * * * *');assert.equal(first.active,true);assert.ok(first.command.includes("j.username=current_user"));assert.ok(first.command.includes('limit 1000'));
 await db.query("update cron.job set active=false,command='select 99',schedule='0 1 * * *' where jobid=$1",[first.jobid]);await db.exec(setup);const next=(await db.query("select * from cron.job where jobname='ride-race-state-cleanup-v1'")).rows[0];assert.deepEqual(next,first);assert.deepEqual((await db.query("select * from cron.job where jobname='unrelated-job'")).rows[0],unrelated);assert.equal((await db.query('select enabled from ride_private.race_policy')).rows[0].enabled,false);
 await db.query("insert into cron.job_run_details(jobid,status,start_time,end_time) values($1,'succeeded',now()-interval '8 days',now()-interval '8 days'),($1,'succeeded',now(),now()),($2,'succeeded',now()-interval '8 days',now()-interval '8 days')",[first.jobid,unrelated.jobid]);await db.exec('begin');await db.exec(first.command);await db.exec('commit');assert.equal((await db.query('select count(*)::int n from cron.job_run_details where jobid=$1',[first.jobid])).rows[0].n,1);assert.equal((await db.query('select count(*)::int n from cron.job_run_details where jobid=$1',[unrelated.jobid])).rows[0].n,1);
});
test('same named foreign operator job is refused atomically rather than modified or silently duplicated',async()=>{
 await db.query("insert into cron.job(jobname,username,schedule,command) values('ride-race-state-cleanup-v1','different_operator','0 0 * * *','select 10')");const before=(await db.query('select * from cron.job order by jobid')).rows;await assert.rejects(db.exec(await file('m5c-race-cron')),/RACE_CRON_OWNER_OR_DATABASE_MISMATCH/);await db.exec('rollback');assert.deepEqual((await db.query('select * from cron.job order by jobid')).rows,before);
});
