// Disposable PostgreSQL17.11 loopback only; no cloud URLs or credentials.
import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {Client} from 'pg';
import {initialize,ports,profiles,friends,A,B,C,D,request} from './live-fixture.mjs';import {nextRaceId} from './race-fixture.mjs';
let settings;try{settings=JSON.parse(await readFile(new URL('../../build/local-postgres/readiness.json',import.meta.url),'utf8'));}catch{}const available=!!settings,connections=[];let admin,db,p,dbname;
const descriptor={mime:'image/jpeg',sha256:'a'.repeat(64),byte_count:500,width:20,height:20,blurhash:null};
async function connect(database,name){const c=new Client({host:'127.0.0.1',port:settings.port,user:'ride_test_admin',database,application_name:name,ssl:false,connectionTimeoutMillis:5000});await c.connect();c.exec=sql=>c.query(sql);await c.query("set timezone='UTC';set lock_timeout='3s';set statement_timeout='6s'");connections.push(c);return c;}
async function actor(owner,name){const c=await connect(dbname,name);await c.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);await c.query('set role authenticated');return c;}
const value=async(c,sql,args=[])=>(await c.query(sql,args)).rows[0].value,settle=promise=>promise.then(value=>({value}),error=>({error}));
async function waitBlocked(c){for(let n=0;n<100;n++){if((await db.query('select wait_event from pg_stat_activity where pid=$1',[c.processID])).rows[0]?.wait_event==='advisory')return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Community RPC did not reach its advisory fence');}
before(async()=>{if(!available)return;assert.equal(settings.host,'127.0.0.1');assert.equal(settings.user,'ride_test_admin');assert.equal(settings.version,'17.11');admin=await connect('postgres','community-bootstrap');dbname=`ride_community_m7_${process.pid}_${Date.now()}`;assert.match(dbname,/^ride_community_m7_[0-9]+_[0-9]+$/);await admin.query(`create database ${dbname}`);db=await connect(dbname,'community-controller');await db.query("do $$begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin;end if;if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin;end if;if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls;end if;end$$");await initialize(db,{roles:false});p=ports(db);await profiles(p);});
after(async()=>{if(!available)return;for(const c of connections.filter(x=>x!==admin))await c.end();if(dbname)await admin.query(`drop database ${dbname}`);await admin.end();});
async function draft(owner){const id=nextRaceId();await p.value(owner,'select public.rs_community_reserve_post($1) value',[id]);return id;}
test('realPG mixed avatar/photo reservations contend for the final aggregate slot without owner lock inversion',{skip:!available},async()=>{
 const postId=await draft(B);await db.query("insert into storage.objects(bucket_id,name,metadata) values('ride-avatars','capacity-test',$1::jsonb)",[JSON.stringify({size:805306368-1048576})]);const first=await actor(A,'community-avatar-first'),second=await actor(B,'community-photo-waiter');await first.query('begin');const avatar=await value(first,"select public.rs_reserve_avatar($1,'image/jpeg') value",[nextRaceId()]);assert.ok(avatar.path);const pending=settle(value(second,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[postId,nextRaceId(),JSON.stringify(descriptor)]));await waitBlocked(second);await first.query('commit');const result=await pending;assert.equal(result.error,undefined);assert.equal(result.value.error.code,'COMMUNITY_CAPACITY');assert.equal(Number((await db.query('select ride_private.community_storage_bytes() n')).rows[0].n),805306368);await db.query("delete from storage.objects where name='capacity-test'");await db.query('delete from public.rs_avatar_uploads where path=$1',[avatar.path]);
});
test('realPG same asset UUID cannot bind another owner while the first reservation response is delayed',{skip:!available},async()=>{
 const one=await draft(A),two=await draft(B),mediaId=nextRaceId(),first=await actor(A,'community-media-owner'),second=await actor(B,'community-media-foreign');await first.query('begin');const reservation=await value(first,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[one,mediaId,JSON.stringify(descriptor)]);const pending=settle(value(second,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[two,mediaId,JSON.stringify(descriptor)]));await waitBlocked(second);await first.query('commit');assert.equal((await pending).value.error.code,'COMMUNITY_MEDIA_UNAVAILABLE');assert.deepEqual(await value(first,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[one,mediaId,JSON.stringify(descriptor)]),reservation);
});
test('realPG deletion quarantine wins over held photo verification finish and stale token cannot commit',{skip:!available},async()=>{
 const postId=await draft(C),mediaId=nextRaceId(),reserved=await p.value(C,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[postId,mediaId,JSON.stringify(descriptor)]);await db.query("insert into storage.objects(bucket_id,name,metadata) values('ride-post-media',$1,'{\"size\":500,\"mimetype\":\"image/jpeg\"}')",[reserved.path]);const token=nextRaceId();await p.service('select public.rs_claim_community_media($1,$2,$3,$4)',[C,postId,mediaId,token]);const deletion=await connect(dbname,'community-deletion-first'),worker=await connect(dbname,'community-worker-waiter');await worker.query('set role service_role');await deletion.query('begin');await deletion.query('select public.rs_begin_account_deletion($1,$2)',[C,nextRaceId()]);const pending=settle(worker.query('select public.rs_finish_community_media($1,$2,$3,$4,$5::jsonb)',[C,postId,mediaId,token,JSON.stringify({...descriptor,blurhash:'BDHLj}39|cuuRmjt'})]));await waitBlocked(worker);await deletion.query('commit');assert.match((await pending).error?.message??'',/ACCOUNT_DELETION_PENDING/);assert.equal((await db.query('select state from ride_private.community_media where media_id=$1',[mediaId])).rows[0].state,'reserved');
});
test('realPG opposite-owner block commits before waiting parent read and former public content cannot survive',{skip:!available},async()=>{
 const postId=await draft(D),doc={schema_version:1,caption:'Real disposable fixture',description:'',visibility:'public',ride:null,route:null,include_ride_route:false,media_ids:[]};await p.value(D,'select public.rs_community_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(request('publish',{post_id:postId,expected_revision:0,document:doc}))]);await friends(p,D,B);const blocker=await actor(D,'community-block-first'),reader=await actor(B,'community-reader-waiter');await blocker.query('begin');const ack=await value(blocker,'select public.rs_social_mutate($1,$2::jsonb) value',[nextRaceId(),JSON.stringify(request('friend_action',{other_id:B,verb:'block',expected_generation:10}))]);assert.equal(ack.error,undefined);const pending=settle(value(reader,'select public.rs_community_post($1) value',[postId]));await waitBlocked(reader);await blocker.query('commit');const result=await pending;assert.equal(result.error,undefined);assert.equal(result.value.error.code,'COMMUNITY_UNAVAILABLE');
});
