import {test,beforeEach,after} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFile,readdir} from 'node:fs/promises';
import {initialize,ports,profiles,friends,route,A,B,C,D,request,schema,owners} from './live-fixture.mjs';
import {nextRaceId} from './race-fixture.mjs';
import {communityModule} from '../../ExpoRideSpeed/tests/communityFixtures.mjs';
const model=communityModule('model');let db,p;
beforeEach(async()=>{await db?.close();db=new PGlite();await initialize(db);p=ports(db);await profiles(p);});after(async()=>{await db?.close();});
const document=(patch={})=>({schema_version:1,caption:'เส้นทางวันนี้',description:'',visibility:'friends',ride:null,route:null,include_ride_route:false,media_ids:[],...patch});
const reserve=(owner,id)=>p.value(owner,'select public.rs_community_reserve_post($1) value',[id]);
const mutate=(owner,operation,body)=>p.value(owner,'select public.rs_community_mutate($1,$2::jsonb) value',[operation,JSON.stringify(body)]);
const feed=(owner=A,mode='latest',cursor=null,limit=20)=>p.value(owner,'select public.rs_community_feed($1::jsonb,$2::jsonb,$3) value',[JSON.stringify({schema_version:1,mode}),cursor?JSON.stringify(cursor):null,limit]);
async function post(owner=A,patch={}){const id=nextRaceId();await reserve(owner,id);const body=request('publish',{post_id:id,expected_revision:0,document:document(patch)}),operation=nextRaceId(),ack=await mutate(owner,operation,body);assert.equal(ack.error,undefined);model.validateCommunityReceipt(ack,owner,{operationId:operation,request:body});return{id,ack};}
test('owned draft reservation and exact immutable publication replay preserve Thai codepoints and privacy',async()=>{
 const id=nextRaceId(),first=await reserve(A,id);model.validatePostReservation(first,A,id);assert.deepEqual(await reserve(A,id),first);assert.equal((await reserve(B,id)).error.code,'COMMUNITY_DRAFT_UNAVAILABLE');
 const body=request('publish',{post_id:id,expected_revision:0,document:document({caption:'ก'.repeat(150)})}),operation=nextRaceId(),ack=await mutate(A,operation,body);model.validateCommunityReceipt(ack,A,{operationId:operation,request:body});assert.deepEqual(await mutate(A,operation,body),ack);assert.equal((await mutate(A,operation,{...body,document:document()})).error.code,'COMMUNITY_OPERATION_CONFLICT');
 assert.equal((await feed(B)).items.length,0);await friends(p,A,B);const page=await feed(B);model.validateCommunityPage(page,B,{schema_version:1,mode:'latest'});assert.equal(page.items[0].caption,'ก'.repeat(150));assert.equal(page.items[0].legacy_claimed_speed_kmh,null);
});
test('new caption limits and exact discriminants reject before writes or admission',async()=>{
 const id=nextRaceId();await reserve(A,id);for(const body of[request('unsupported',{post_id:id,expected_revision:0}),request(null,{post_id:id,expected_revision:0}),request('delete_post',{post_id:id,expected_revision:0}),request('publish',{post_id:id,expected_revision:0,document:document({caption:'ก'.repeat(151)})}),request('publish',{post_id:id,expected_revision:0,document:document({caption:'\u0007'})})])assert.equal((await mutate(A,nextRaceId(),body)).error.code,'COMMUNITY_INVALID');
 assert.equal((await p.admin('select count(*)::int n from ride_private.community_operations')).rows[0].n,0);
});
test('desired likes, private saves and comments replay canonically and current blocks hide parent and children',async()=>{
 const {id}=await post(A,{visibility:'public'}),like=request('like',{post_id:id,expected_revision:1,liked:true}),operation=nextRaceId(),ack=await mutate(B,operation,like);model.validateCommunityReceipt(ack,B,{operationId:operation,request:like});assert.deepEqual(await mutate(B,operation,like),ack);
 await mutate(B,nextRaceId(),request('save',{post_id:id,expected_revision:1,saved:true}));const commentId=nextRaceId();await mutate(B,nextRaceId(),request('comment',{post_id:id,expected_revision:1,comment_id:commentId,body:'ขับขี่ปลอดภัยครับ'}));let detail=await p.value(B,'select public.rs_community_post($1) value',[id]);model.validateCommunityDetail(detail,B,id);assert.deepEqual(detail.post.engagement,{likes:1,comments:1,liked:true,saved:true});
 const comments=await p.value(C,'select public.rs_community_comments($1,null,30) value',[id]);model.validateCommunityComments(comments,C,id);assert.equal(comments.items[0].comment_id,commentId);
 await p.admin('insert into public.rs_blocks(blocker_id,blocked_id) values($1,$2)',[A,B]);assert.equal((await p.value(B,'select public.rs_community_post($1) value',[id])).error.code,'COMMUNITY_UNAVAILABLE');detail=await p.value(C,'select public.rs_community_post($1) value',[id]);assert.equal(detail.post.engagement.likes,0);assert.equal(detail.post.engagement.comments,0);assert.equal((await p.value(C,'select public.rs_community_comments($1,null,30) value',[id])).items.length,0);
});
test('audience and deletion are CAS-bound, old immutable receipt cannot revive a post',async()=>{
 const {id}=await post(A,{visibility:'public'}),body=request('audience',{post_id:id,expected_revision:1,visibility:'private'}),operation=nextRaceId(),ack=await mutate(A,operation,body);assert.equal(ack.result.content_revision,2);assert.equal((await mutate(A,nextRaceId(),{...body,visibility:'friends'})).error.code,'COMMUNITY_REVISION_CONFLICT');
 const deleted=await mutate(A,nextRaceId(),request('delete_post',{post_id:id,expected_revision:2}));assert.equal(deleted.result.state,'deleted');assert.deepEqual(await mutate(A,operation,body),ack);assert.equal((await p.value(A,'select public.rs_community_post($1) value',[id])).error.code,'COMMUNITY_UNAVAILABLE');assert.equal((await feed()).items.length,0);
});
const photoDescriptor={mime:'image/jpeg',sha256:'a'.repeat(64),byte_count:500,width:20,height:20,blurhash:null};
const reservePhoto=(owner,postId,mediaId,descriptor=photoDescriptor)=>p.value(owner,'select public.rs_community_reserve_media($1,$2,$3::jsonb) value',[postId,mediaId,JSON.stringify(descriptor)]);
async function committedPhoto(owner,postId,mediaId=nextRaceId()){
 const reservation=await reservePhoto(owner,postId,mediaId);await p.as(owner,"insert into storage.objects(bucket_id,name,owner_id,metadata) values('ride-post-media',$1,$2,$3::jsonb)",[reservation.path,owner,JSON.stringify({size:500,mimetype:'image/jpeg'})]);
 const token=nextRaceId(),claim=(await p.service('select public.rs_claim_community_media($1,$2,$3,$4) value',[owner,postId,mediaId,token])).rows[0].value,descriptor={...photoDescriptor,blurhash:'BDHLj}39|cuuRmjt'};assert.equal(claim.path,reservation.path);
 const ack=(await p.service('select public.rs_finish_community_media($1,$2,$3,$4,$5::jsonb) value',[owner,postId,mediaId,token,JSON.stringify(descriptor)])).rows[0].value;model.validateMediaCommit(ack,postId,mediaId,photoDescriptor);return{reservation,descriptor,mediaId};
}
test('24 draft candidates bind immutable owner/post/descriptor; committed retry survives expiry and uploads cannot bypass',async()=>{
 const postId=nextRaceId();await reserve(A,postId);const image=await committedPhoto(A,postId);model.validateMediaReservation(image.reservation,A,postId,image.mediaId);assert.equal((await reservePhoto(B,postId,image.mediaId)).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');assert.equal((await reservePhoto(A,postId,image.mediaId,{...photoDescriptor,width:21})).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');
 await p.admin('update ride_private.community_media set expires_at=clock_timestamp()-interval \'1 hour\' where media_id=$1',[image.mediaId]);const committed=await reservePhoto(A,postId,image.mediaId);assert.equal(committed.state,'committed');assert.equal((await p.service('select public.rs_claim_community_media($1,$2,$3,$4) value',[A,postId,image.mediaId,nextRaceId()])).rows[0].value.descriptor.blurhash,image.descriptor.blurhash);
 for(let n=0;n<23;n++)assert.equal((await reservePhoto(A,postId,nextRaceId())).state,'reserved');assert.equal((await reservePhoto(A,postId,nextRaceId())).error.code,'COMMUNITY_CAPACITY');
 await assert.rejects(p.as(B,"insert into storage.objects(bucket_id,name,metadata) values('ride-post-media',$1,'{}')",[`${B}/${postId}/${nextRaceId()}.jpg`]),e=>e.code==='42501');assert.equal((await p.as(B,"select * from storage.objects where bucket_id='ride-post-media'")).rows.length,0);
 for(const sql of['select public.rs_create_post($1)',"select public.rs_delete_post($1)","select public.rs_report_post($1,'spam','')"] )await assert.rejects(p.as(A,sql,[postId]),e=>e.code==='42501');await assert.rejects(p.as(A,"insert into storage.objects(bucket_id,name,metadata) values('ride-community',$1,'{}')",[`${A}/${postId}/${nextRaceId()}.jpg`]),e=>e.code==='42501');
});
test('pending media counts bucket maximum, committed bytes count once, wrong-size and unknown-size cannot reserve around cap',async()=>{
 const postId=nextRaceId(),media=nextRaceId();await reserve(A,postId);const photo=await reservePhoto(A,postId,media);assert.equal(Number((await p.admin("select ride_private.community_storage_bytes('ride-post-media') n")).rows[0].n),1048576);
 await p.as(A,"insert into storage.objects(bucket_id,name,metadata) values('ride-post-media',$1,'{\"size\":501,\"mimetype\":\"image/jpeg\"}')",[photo.path]);await assert.rejects(p.service('select public.rs_claim_community_media($1,$2,$3,$4)',[A,postId,media,nextRaceId()]),/COMMUNITY_MEDIA_UNAVAILABLE/);
 await p.admin("update storage.objects set metadata='{\"size\":500,\"mimetype\":\"image/jpeg\"}' where name=$1",[photo.path]);const token=nextRaceId();await p.service('select public.rs_claim_community_media($1,$2,$3,$4)',[A,postId,media,token]);await p.service('select public.rs_finish_community_media($1,$2,$3,$4,$5::jsonb)',[A,postId,media,token,JSON.stringify({...photoDescriptor,blurhash:'BDHLj}39|cuuRmjt'})]);assert.equal(Number((await p.admin("select ride_private.community_storage_bytes('ride-post-media') n")).rows[0].n),500);
 await p.admin("insert into storage.objects(bucket_id,name,metadata) values('ride-avatars','orphan-unknown','{}')");assert.equal((await reservePhoto(A,postId,nextRaceId())).error.code,'COMMUNITY_CAPACITY');assert.equal((await reservePhoto(A,postId,media)).state,'committed');await assert.rejects(p.as(A,"select public.rs_reserve_avatar($1,'image/jpeg')",[nextRaceId()]),/AVATAR_UNAVAILABLE/);await assert.rejects(p.as(A,"select public.rs_reserve_vehicle_photo($1,'vehicle1','image/jpeg')",[nextRaceId()]),/GARAGE_PHOTO_UNAVAILABLE/);
});
test('attachment review freezes only current own sanitized route, no private pins; source revision drift rejects publish',async()=>{
 const routeId=nextRaceId();await route(p,A,routeId);const binding={route_id:routeId,route_revision:1},review=await p.value(A,'select public.rs_community_attachment_review(null::jsonb,$1::jsonb,false) value',[JSON.stringify(binding)]);
 assert.equal(review.error,undefined);const actual=await p.value(A,"select public.rs_community_attachment_review('null'::jsonb,$1::jsonb,false) value",[JSON.stringify(binding)]);assert.deepEqual(actual.route,review.route);assert.equal(actual.route.source,'route');assert.equal(actual.route.privacyTrimMeters,200);assert.ok(actual.route.segments[0][0].latitude>13.7);assert.ok(!JSON.stringify(actual).includes('Secret home'));assert.equal((await p.value(B,"select public.rs_community_attachment_review('null'::jsonb,$1::jsonb,false) value",[JSON.stringify(binding)])).error.code,'COMMUNITY_SOURCE_CHANGED');
 await p.admin('update public.rs_routes set revision=2 where id=$1',[routeId]);const postId=nextRaceId();await reserve(A,postId);assert.equal((await mutate(A,nextRaceId(),request('publish',{post_id:postId,expected_revision:0,document:document({route:binding})}))).error.code,'COMMUNITY_SOURCE_CHANGED');
});
test('Top this Bangkok week excludes self and old likes, preserves exact keysets and rejects changed visibility',async()=>{
 const first=await post(A,{visibility:'public'}),second=await post(B,{visibility:'public'});await mutate(A,nextRaceId(),request('like',{post_id:first.id,expected_revision:1,liked:true}));await mutate(C,nextRaceId(),request('like',{post_id:first.id,expected_revision:1,liked:true}));await mutate(D,nextRaceId(),request('like',{post_id:second.id,expected_revision:1,liked:true}));await p.admin("update ride_private.community_likes set created_at=clock_timestamp()-interval '10 days' where user_id=$1",[D]);
 const page=await feed(C,'top_week',null,1);model.validateCommunityPage(page,C,{schema_version:1,mode:'top_week'});assert.equal(page.items[0].post_id,first.id);assert.equal(page.items[0].week_score,1);assert.ok(page.next_cursor);const next=await feed(C,'top_week',page.next_cursor,1);model.validateCommunityPage(next,C,{schema_version:1,mode:'top_week'},page.next_cursor);assert.equal(next.items[0].post_id,second.id);
 await mutate(A,nextRaceId(),request('audience',{post_id:first.id,expected_revision:1,visibility:'private'}));assert.equal((await feed(C,'top_week',page.next_cursor,1)).error.code,'COMMUNITY_CHANGED');
});
test('six committed photos publish in exact manifest order, signer metadata has current-parent ACL and no raw feed paths',async()=>{
 const postId=nextRaceId();await reserve(A,postId);const images=[];for(let n=0;n<6;n++)images.push(await committedPhoto(A,postId));const mediaIds=images.map(x=>x.mediaId).reverse(),body=request('publish',{post_id:postId,expected_revision:0,document:document({visibility:'friends',media_ids:mediaIds})});assert.equal((await mutate(A,nextRaceId(),body)).error,undefined);await friends(p,A,B);
 const detail=await p.value(B,'select public.rs_community_post($1) value',[postId]);model.validateCommunityDetail(detail,B,postId);assert.deepEqual(detail.post.media.map(x=>x.media_id),mediaIds);assert.equal(JSON.stringify(detail).includes('ride-post-media'),false);assert.equal(JSON.stringify(detail).includes(`${A}/${postId}/`),false);
 const asset=await p.value(B,'select public.rs_community_media_for_view($1,$2) value',[postId,mediaIds[0]]);assert.equal(asset.path,`${A}/${postId}/${mediaIds[0]}.jpg`);await p.admin('insert into public.rs_blocks(blocker_id,blocked_id) values($1,$2)',[A,B]);assert.equal((await p.value(B,'select public.rs_community_media_for_view($1,$2) value',[postId,mediaIds[0]])).error.code,'COMMUNITY_UNAVAILABLE');
});
test('expiry is identity-first, concurrent invalid claims are fenced and known bad descriptors cannot commit',async()=>{
 const postId=nextRaceId(),mediaId=nextRaceId();await reserve(A,postId);for(const descriptor of[{...photoDescriptor,mime:null},{...photoDescriptor,sha256:null},{...photoDescriptor,byte_count:0},{...photoDescriptor,blurhash:'not-a-valid-hash'}])assert.equal((await reservePhoto(A,postId,nextRaceId(),descriptor)).error.code,'COMMUNITY_INVALID');const reserved=await reservePhoto(A,postId,mediaId);await p.admin('update ride_private.community_media set expires_at=clock_timestamp()-interval \'1 second\' where media_id=$1',[mediaId]);assert.equal((await reservePhoto(B,postId,mediaId)).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');assert.equal((await reservePhoto(A,postId,mediaId)).error.code,'COMMUNITY_MEDIA_EXPIRED');assert.equal((await reservePhoto(A,postId,mediaId,{...photoDescriptor,width:21})).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');
 const liveId=nextRaceId(),live=await reservePhoto(A,postId,liveId);await p.admin("insert into storage.objects(bucket_id,name,metadata) values('ride-post-media',$1,'{\"size\":500,\"mimetype\":\"image/jpeg\"}')",[live.path]);const token=nextRaceId();await p.service('select public.rs_claim_community_media($1,$2,$3,$4)',[A,postId,liveId,token]);await assert.rejects(p.service('select public.rs_claim_community_media($1,$2,$3,$4)',[A,postId,liveId,nextRaceId()]),/COMMUNITY_MEDIA_UNAVAILABLE/);await assert.rejects(p.service('select public.rs_finish_community_media($1,$2,$3,$4,$5::jsonb)',[A,postId,liveId,nextRaceId(),JSON.stringify({...photoDescriptor,blurhash:'BDHLj}39|cuuRmjt'})]),/COMMUNITY_MEDIA_UNAVAILABLE/);await assert.rejects(p.service('select public.rs_finish_community_media($1,$2,$3,$4,$5::jsonb)',[A,postId,liveId,token,JSON.stringify({...photoDescriptor,width:21,blurhash:'BDHLj}39|cuuRmjt'})]),/COMMUNITY_MEDIA_INVALID/);assert.equal(reserved.state,'reserved');
});
test('cleanup and account deletion both require binary absence before metadata purge, preserve unrelated owner',async()=>{
 const postId=nextRaceId();await reserve(A,postId);const image=await committedPhoto(A,postId);await mutate(A,nextRaceId(),request('publish',{post_id:postId,expected_revision:0,document:document({media_ids:[image.mediaId],visibility:'public'})}));const other=await post(B,{visibility:'public'});await mutate(B,nextRaceId(),request('comment',{post_id:postId,expected_revision:1,comment_id:nextRaceId(),body:'จริง'}));const deletionId=nextRaceId(),job=(await p.service('select public.rs_begin_account_deletion($1,$2) value',[A,deletionId])).rows[0].value;
 assert.equal((await p.value(A,'select public.rs_community_post($1) value',[postId])).error.code,'ACCOUNT_DELETION_PENDING');const objects=(await p.service('select public.rs_account_deletion_objects($1,$2,$3) value',[A,deletionId,job.token])).rows[0].value;assert.ok(objects.some(x=>x.bucket==='ride-post-media'&&x.path===image.reservation.path));await assert.rejects(p.service('select public.rs_purge_account_data($1,$2,$3)',[A,deletionId,job.token]),/DELETION_ASSETS_REMAIN/);
 await p.admin("delete from storage.objects where bucket_id='ride-post-media' and name=$1",[image.reservation.path]);await p.service('select public.rs_purge_account_data($1,$2,$3)',[A,deletionId,job.token]);assert.equal((await p.admin('select count(*)::int n from ride_private.community_comments where post_id=$1',[postId])).rows[0].n,0);assert.equal((await p.value(B,'select public.rs_community_post($1) value',[other.id])).post.post_id,other.id);
 const draft=nextRaceId();await reserve(B,draft);const expired=await committedPhoto(B,draft);await p.admin('update ride_private.community_media set committed_at=clock_timestamp()-interval \'8 days\' where media_id=$1',[expired.mediaId]);const claim=(await p.service('select public.rs_claim_community_media_cleanup(20) value')).rows[0].value.find(x=>x.path===expired.reservation.path);assert.ok(claim);await assert.rejects(p.service('select public.rs_ack_community_media_cleanup($1,$2,$3)',[claim.bucket,claim.path,claim.token]),/COMMUNITY_MEDIA_UNAVAILABLE/);await p.admin('delete from storage.objects where bucket_id=$1 and name=$2',[claim.bucket,claim.path]);await p.service('select public.rs_ack_community_media_cleanup($1,$2,$3)',[claim.bucket,claim.path,claim.token]);assert.equal((await reservePhoto(B,draft,expired.mediaId)).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');assert.equal((await reservePhoto(C,draft,expired.mediaId)).error.code,'COMMUNITY_MEDIA_UNAVAILABLE');
});
test('legacy280-caption/claim/mixed-codec content remains honest, reports/moderation are trusted only',async()=>{
 const postId=nextRaceId(),fileId=nextRaceId(),legacyPath=`${A}/${postId}/${fileId}.png`;await p.admin("insert into public.rs_posts(id,owner_id,caption,claimed_speed_kmh,route_snapshot,media_path,visibility,moderation_state) values($1,$2,$3,88,$4::jsonb,$5,'community','published')",[postId,A,'ก'.repeat(280),JSON.stringify({title:'Real prior route',revision:2,category:'scooter'}),legacyPath]);await p.admin("insert into storage.objects(bucket_id,name,metadata) values('ride-community',$1,'{\"size\":100,\"mimetype\":\"image/png\"}')",[legacyPath]);const detail=await p.value(B,'select public.rs_community_post($1) value',[postId]);model.validateCommunityDetail(detail,B,postId);assert.equal(detail.post.content_version,0);assert.equal(detail.post.legacy_claimed_speed_kmh,88);assert.equal(detail.post.route.source_id,null);assert.equal(detail.post.route.geometryStatus,'unavailable');assert.deepEqual(detail.post.media[0],{media_id:detail.post.media[0].media_id,validation:'legacy_unverified',mime:'image/png',sha256:null,byte_count:null,width:null,height:null,blurhash:null});
 const report=request('report',{post_id:postId,expected_revision:1,comment_id:null,reason:'privacy',detail:'ตรวจสอบ'}),operation=nextRaceId(),ack=await mutate(B,operation,report);model.validateCommunityReceipt(ack,B,{operationId:operation,request:report});assert.equal((await p.service('select public.rs_community_reports(null,30) value')).rows[0].value.items.length,1);await assert.rejects(p.as(B,'select public.rs_moderate_community_post($1,true)',[postId]),/permission denied/);await p.service('select public.rs_moderate_community_post($1,true)',[postId]);assert.equal((await p.value(B,'select public.rs_community_post($1) value',[postId])).error.code,'COMMUNITY_UNAVAILABLE');
});
test('private table/helper deny and exact service boundary preserve fixed paths, publication bytes and new RPC ownership',async()=>{
 const rows=(await p.admin("select tablename,rowsecurity from pg_tables where schemaname='ride_private' and tablename like 'community_%'")).rows;assert.equal(rows.length,8);assert.ok(rows.every(x=>x.rowsecurity));for(const row of rows)await assert.rejects(p.as(A,`select * from ride_private.${row.tablename}`),/permission denied/);
 const funcs=(await p.admin("select n.nspname,p.proname,p.prosecdef,p.proconfig,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') app,has_function_privilege('service_role',p.oid,'execute') service from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like 'rs_%community%' or p.proname like '%pre_community_v1'")).rows;
 assert.ok(funcs.filter(x=>x.nspname==='ride_private').every(x=>!x.app&&!x.anon&&!x.service));assert.ok(funcs.filter(x=>x.nspname==='public').every(x=>x.prosecdef&&!x.anon&&x.proconfig.includes('search_path=""')));assert.equal(funcs.find(x=>x.proname==='rs_finish_community_media').app,false);assert.equal(funcs.find(x=>x.proname==='rs_community_feed').app,true);
});
test('legacy/profile unsafe controls cannot poison canonical peer pages while new content stays strictly rejected',async()=>{
 await p.admin('update public.rs_profiles set display_name=$2 where user_id=$1',[A,'Rider\u0007 Name']);const created=await post(A,{visibility:'public'});const page=await feed(B);model.validateCommunityPage(page,B,{schema_version:1,mode:'latest'});assert.equal(page.items[0].profile.name,'Rider Name');assert.equal(page.items[0].post_id,created.id);const legacy=nextRaceId();await p.admin("insert into public.rs_posts(id,owner_id,caption,description,visibility,moderation_state) values($1,$2,$3,$4,'community','published')",[legacy,A,'Old\u0007caption','Existing\ntext']);const detail=await p.value(B,'select public.rs_community_post($1) value',[legacy]);model.validateCommunityDetail(detail,B,legacy);assert.equal(detail.post.caption,'Oldcaption');assert.equal(detail.post.description,'Existing\ntext');
});
function encode(points){let lat=0,lng=0,out='';for(const[a,b]of points){for(const n of[Math.round(a*1e5)-lat,Math.round(b*1e5)-lng]){let bits=n<0?~(n<<1):n<<1;while(bits>=32){out+=String.fromCharCode((32|(bits&31))+63);bits>>=5;}out+=String.fromCharCode(bits+63);}lat=Math.round(a*1e5);lng=Math.round(b*1e5);}return out;}
test('real M2 self-reported null-category ride retains disconnected gaps, explicit saved route wins and publication freezes revision',async()=>{
 const rideId=nextRaceId(),capture=nextRaceId(),segments=[[[13.7,100.5],[13.705,100.5]],[[13.71,100.51],[13.715,100.51]]],payload={schema_version:1,started_at:'2026-10-01T01:00:00.000Z',ended_at:'2026-10-01T01:01:00.000Z',active_duration_ms:60000,elapsed_duration_ms:60000,clock_anomaly:false,distance_m:1000,max_speed_mps:20,average_speed_mps:1000/60,reported_provider:'expo_android',capture_count:1,accepted_fix_count:4,rejected_fix_count:0,geometry_status:'complete',vehicle:null,geometry:{encoding:'polyline5',fragments:segments.map((points,part_index)=>({segment_id:nextRaceId(),capture_id:capture,part_index,polyline:encode(points),point_count:points.length}))}};
 await p.as(A,'select public.rs_sync_ride_summary($1,$2,0,$3::jsonb)',[nextRaceId(),rideId,JSON.stringify(payload)]);const rideBinding={ride_id:rideId,ride_revision:1},selection={ride:rideBinding,route:null,include_ride_route:true},review=await p.value(A,'select public.rs_community_attachment_review($1::jsonb,null,true) value',[JSON.stringify(rideBinding)]);model.validateAttachmentReview(review,A,selection);assert.equal(review.ride.speed_status,'self_reported');assert.equal(review.route.category,null);assert.equal(review.route.segments.length,2);assert.ok(review.route.segments[0][0].latitude>13.7);assert.ok(review.route.segments[1].at(-1).latitude<13.715);
 const routeId=nextRaceId();await route(p,A,routeId);const routeBinding={route_id:routeId,route_revision:1},both=await p.value(A,'select public.rs_community_attachment_review($1::jsonb,$2::jsonb,true) value',[JSON.stringify(rideBinding),JSON.stringify(routeBinding)]);model.validateAttachmentReview(both,A,{...selection,route:routeBinding});assert.equal(both.route.source,'route');assert.equal(both.route.source_id,routeId);
 const published=await post(A,{visibility:'public',ride:rideBinding,include_ride_route:true});await p.as(A,'select public.rs_sync_ride_summary($1,$2,1,$3::jsonb)',[nextRaceId(),rideId,JSON.stringify({...payload,max_speed_mps:21})]);const detail=await p.value(B,'select public.rs_community_post($1) value',[published.id]);model.validateCommunityDetail(detail,B,published.id);assert.equal(detail.post.ride.ride_revision,1);assert.equal(detail.post.ride.max_speed_mps,20);assert.equal((await p.value(A,'select public.rs_community_attachment_review($1::jsonb,null,false) value',[JSON.stringify(rideBinding)])).error.code,'COMMUNITY_SOURCE_CHANGED');
});

test('recognized business rejection commits admission, exact successful replay is free and unknown SQL failure stays uncertain',async()=>{
 const missing=nextRaceId(),body=request('like',{post_id:missing,expected_revision:1,liked:true});
 for(let n=0;n<3;n++)assert.equal((await mutate(B,nextRaceId(),body)).error.code,'COMMUNITY_UNAVAILABLE');
 const count=async()=>Number((await p.admin("select coalesce(sum(hits),0) n from ride_private.race_admission where subject=$1 and label='community_control_day'",[B])).rows[0].n);
 assert.equal(await count(),3);const published=await post(A,{visibility:'public'}),operation=nextRaceId(),valid={...body,post_id:published.id},ack=await mutate(B,operation,valid);assert.equal(await count(),4);assert.deepEqual(await mutate(B,operation,valid),ack);assert.equal(await count(),4);
 await p.admin("update ride_private.race_admission set hits=60 where subject=$1 and label='community_control_minute'",[B]);const limited=await mutate(B,nextRaceId(),valid);model.validateCommunityError(limited);assert.equal(limited.error.code,'COMMUNITY_RATE_LIMITED');assert.ok(limited.error.retry_after_ms>0);assert.deepEqual(await mutate(B,operation,valid),ack);assert.equal(await count(),4);
 await db.exec("create function ride_private.community_test_failure() returns trigger language plpgsql as $$begin raise exception 'unreviewed failure' using errcode='XX000';end$$;create trigger community_test_failure before insert on ride_private.community_likes for each row execute function ride_private.community_test_failure()");
 const uncertain=nextRaceId();await assert.rejects(mutate(C,uncertain,valid),e=>e.code==='XX000');assert.equal(await p.value(C,'select public.rs_community_operation($1) value',[uncertain]),null);assert.equal((await p.admin('select count(*)::int n from ride_private.community_likes where user_id=$1',[C])).rows[0].n,0);
});

test('latest and comment keysets preserve original microseconds, malformed or foreign cursors are fixed errors',async()=>{
 const first=await post(A,{visibility:'public'}),second=await post(B,{visibility:'public'}),base=new Date(Date.now()-10000).toISOString().slice(0,19);
 await p.admin('update public.rs_posts set created_at=$2::timestamptz where id=$1',[first.id,`${base}.123456Z`]);await p.admin('update public.rs_posts set created_at=$2::timestamptz where id=$1',[second.id,`${base}.123455Z`]);
 const page=await feed(C,'latest',null,1);model.validateCommunityPage(page,C,{schema_version:1,mode:'latest'});assert.equal(page.items[0].post_id,first.id);const next=await feed(C,'latest',page.next_cursor,1);model.validateCommunityPage(next,C,{schema_version:1,mode:'latest'},page.next_cursor);assert.equal(next.items[0].post_id,second.id);
 for(const cursor of[{...page.next_cursor,owner_id:B},{...page.next_cursor,after:null},{...page.next_cursor,after:{...page.next_cursor.after,created_at:null}},{...page.next_cursor,after:{...page.next_cursor.after,week_score:2}}])assert.equal((await feed(C,'latest',cursor,1)).error.code,'COMMUNITY_INVALID');
 const ids=[nextRaceId(),nextRaceId()];for(const id of ids)await mutate(B,nextRaceId(),request('comment',{post_id:first.id,expected_revision:1,comment_id:id,body:'ข้อความจริง'}));
 await p.admin('update ride_private.community_comments set created_at=$2::timestamptz where comment_id=$1',[ids[0],`${base}.654322Z`]);await p.admin('update ride_private.community_comments set created_at=$2::timestamptz where comment_id=$1',[ids[1],`${base}.654321Z`]);
 const comments=await p.value(C,'select public.rs_community_comments($1,null,1) value',[first.id]);model.validateCommunityComments(comments,C,first.id);assert.equal(comments.items[0].comment_id,ids[1]);const commentNext=await p.value(C,'select public.rs_community_comments($1,$2::jsonb,1) value',[first.id,JSON.stringify(comments.next_cursor)]);model.validateCommunityComments(commentNext,C,first.id,comments.next_cursor);assert.equal(commentNext.items[0].comment_id,ids[0]);
});

test('additive upgrade retains genuine legacy records while invalid old route revisions cannot overflow or poison pages',async()=>{
 const scratch=new PGlite();try{
  await scratch.exec('create role anon nologin;create role authenticated nologin;create role service_role nologin bypassrls;');await scratch.exec(schema);for(const owner of owners)await scratch.query('insert into auth.users values($1)',[owner]);const directory=new URL('../migrations/',import.meta.url);for(const file of(await readdir(directory)).filter(x=>x.endsWith('.sql')&&x<'202610010011_community_media.sql').sort())await scratch.exec(await readFile(new URL(file,directory),'utf8'));const q=ports(scratch);await profiles(q);
  const original=(await q.admin("select p.proname,p.prosrc,p.proargnames,p.pronargdefaults,p.prorettype,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') app,has_function_privilege('service_role',p.oid,'execute') service from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('rs_reserve_avatar','rs_reserve_vehicle_photo','rs_reserve_submission','rs_race_mutate','rs_account_deletion_objects','rs_purge_account_data')")).rows;assert.equal(original.length,6);
  const existing=[];for(const routeSnapshot of[{title:'Old route',revision:'999999999999999999999999999999',category:'scooter'},{title:'Old\u0007route',revision:2,category:'scooter'},{title:'Genuine route',revision:2147483647,category:'scooter'}]){const id=nextRaceId();existing.push(id);await q.admin("insert into public.rs_posts(id,owner_id,caption,route_snapshot,visibility,moderation_state) values($1,$2,'Actual old content',$3::jsonb,'community','published')",[id,A,JSON.stringify(routeSnapshot)]);}
  await scratch.exec(await readFile(new URL('202610010011_community_media.sql',directory),'utf8'));for(const old of original){const moved=(await q.admin("select p.prosrc,has_function_privilege('authenticated',p.oid,'execute') app,has_function_privilege('service_role',p.oid,'execute') service from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='ride_private' and p.proname=$1",[`${old.proname}_pre_community_v1`])).rows[0];assert.equal(moved.prosrc,old.prosrc);assert.equal(moved.app,false);assert.equal(moved.service,false);const current=(await q.admin("select p.proargnames,p.pronargdefaults,p.prorettype,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') app,has_function_privilege('service_role',p.oid,'execute') service from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname=$1",[old.proname])).rows[0];for(const key of['proargnames','pronargdefaults','prorettype','anon','app','service'])assert.deepEqual(current[key],old[key]);}
  for(let n=0;n<existing.length;n++){const detail=await q.value(B,'select public.rs_community_post($1) value',[existing[n]]);model.validateCommunityDetail(detail,B,existing[n]);assert.equal(detail.post.content_version,0);assert.equal(detail.post.caption,'Actual old content');if(n<2)assert.equal(detail.post.route,null);else assert.equal(detail.post.route.source_revision,2147483647);}
  const trusted=nextRaceId();await q.admin("insert into public.rs_posts(id,owner_id,caption,route_snapshot,visibility,moderation_state) values($1,$2,'New trusted legacy row',$3::jsonb,'community','published')",[trusted,A,JSON.stringify({title:'Poison\u0007title',revision:3,category:'scooter'})]);assert.equal((await q.value(B,'select public.rs_community_post($1) value',[trusted])).post.route,null);
 }finally{await scratch.close();}
});

test('history fingerprint stays compact, yet profile/child eligibility changes invalidate the exact cursor',async()=>{
 const routeId=nextRaceId();await route(p,A,routeId);const first=await post(A,{visibility:'public',description:'Long actual content '.repeat(180),route:{route_id:routeId,route_revision:1}}),second=await post(B,{visibility:'public'});
 const full=await p.value(C,'select public.rs_community_post($1) value',[first.id]),key=(await p.admin('select ride_private.community_feed_key($1,$2) value',[C,first.id])).rows[0].value;
 assert.equal(Object.hasOwn(key,'route'),false);assert.equal(Object.hasOwn(key,'description'),false);assert.equal(Object.hasOwn(key,'media'),false);assert.ok(JSON.stringify(key).length<700);assert.ok(JSON.stringify(full.post).length>3000);
 let page=await feed(C,'latest',null,1);assert.ok(page.next_cursor);await p.admin('update public.rs_profiles set display_name=$2 where user_id=$1',[A,'Changed real name']);assert.equal((await feed(C,'latest',page.next_cursor,1)).error.code,'COMMUNITY_CHANGED');
 await mutate(D,nextRaceId(),request('comment',{post_id:second.id,expected_revision:1,comment_id:nextRaceId(),body:'Actual comment'}));page=await feed(C,'latest',null,1);await p.admin('insert into public.rs_blocks(blocker_id,blocked_id) values($1,$2)',[C,D]);assert.equal((await feed(C,'latest',page.next_cursor,1)).error.code,'COMMUNITY_CHANGED');
});

test('canonical privacy and deletion apply exactly one CAS revision to genuine legacy posts',async()=>{
 const id=nextRaceId();await p.admin("insert into public.rs_posts(id,owner_id,caption,visibility,moderation_state) values($1,$2,'Actual legacy content','community','published')",[id,A]);const audience=request('audience',{post_id:id,expected_revision:1,visibility:'private'}),audienceOperation=nextRaceId(),changed=await mutate(A,audienceOperation,audience);model.validateCommunityReceipt(changed,A,{operationId:audienceOperation,request:audience});assert.equal(changed.result.content_revision,2);assert.equal((await p.value(A,'select public.rs_community_post($1) value',[id])).post.content_revision,2);assert.deepEqual(await mutate(A,audienceOperation,audience),changed);
 const deletion=request('delete_post',{post_id:id,expected_revision:2}),deleteOperation=nextRaceId(),deleted=await mutate(A,deleteOperation,deletion);model.validateCommunityReceipt(deleted,A,{operationId:deleteOperation,request:deletion});assert.equal(deleted.result.content_revision,3);assert.deepEqual(await mutate(A,deleteOperation,deletion),deleted);assert.equal((await p.value(A,'select public.rs_community_post($1) value',[id])).error.code,'COMMUNITY_UNAVAILABLE');
});

test('owner metadata discovers hidden sharing for CAS revocation/deletion without exposing content or weakening viewers',async()=>{
 const ownerModel=communityModule('communityOwnerModel'),first=await post(A,{visibility:'public',description:'Private moderated text'}),second=await post(A,{visibility:'friends'}),other=await post(B,{visibility:'public'}),draftId=nextRaceId();await reserve(A,draftId);
 await p.service('select public.rs_moderate_community_post($1,true)',[first.id]);assert.equal((await p.value(A,'select public.rs_community_post($1) value',[first.id])).error.code,'COMMUNITY_UNAVAILABLE');const get=id=>p.value(A,'select public.rs_community_owner_post($1) value',[id]);const metadata=await get(first.id);ownerModel.validateCommunityOwnerDetail(metadata,A,first.id);assert.equal(metadata.post.state,'hidden');assert.equal(JSON.stringify(metadata).includes('Private moderated text'),false);assert.equal((await p.value(B,'select public.rs_community_owner_post($1) value',[first.id])).error.code,'COMMUNITY_UNAVAILABLE');const draft=await get(draftId);ownerModel.validateCommunityOwnerDetail(draft,A,draftId);assert.equal(draft.post.state,'draft');
 let page=await p.value(A,'select public.rs_community_owner_posts(null,30) value');ownerModel.validateCommunityOwnerPage(page,A);assert.equal(page.items.length,2);assert.ok(page.items.every(x=>x.post_id!==draftId&&x.post_id!==other.id));
 const privateRequest=request('audience',{post_id:first.id,expected_revision:metadata.post.content_revision,visibility:'private'}),operation=nextRaceId(),privateAck=await mutate(A,operation,privateRequest);model.validateCommunityReceipt(privateAck,A,{operationId:operation,request:privateRequest});await p.service('select public.rs_moderate_community_post($1,false)',[first.id]);assert.equal((await p.value(B,'select public.rs_community_post($1) value',[first.id])).error.code,'COMMUNITY_UNAVAILABLE');assert.equal((await get(first.id)).post.visibility,'private');
 await p.service('select public.rs_moderate_community_post($1,true)',[second.id]);const secondMeta=await get(second.id),deleted=await mutate(A,nextRaceId(),request('delete_post',{post_id:second.id,expected_revision:secondMeta.post.content_revision}));assert.equal(deleted.result.state,'deleted');assert.equal((await get(second.id)).post.state,'deleted');
 const base=new Date(Date.now()-10000).toISOString().slice(0,19);await p.admin('update ride_private.community_posts set updated_at=$2::timestamptz where post_id=$1',[first.id,`${base}.123456Z`]);await p.admin('update ride_private.community_posts set updated_at=$2::timestamptz where post_id=$1',[second.id,`${base}.123455Z`]);page=await p.value(A,'select public.rs_community_owner_posts(null,1) value');ownerModel.validateCommunityOwnerPage(page,A);assert.equal(page.items[0].post_id,first.id);const next=await p.value(A,'select public.rs_community_owner_posts($1::jsonb,1) value',[JSON.stringify(page.next_cursor)]);ownerModel.validateCommunityOwnerPage(next,A,page.next_cursor);assert.equal(next.items[0].post_id,second.id);assert.equal((await p.value(A,'select public.rs_community_owner_posts($1::jsonb,1) value',[JSON.stringify({...page.next_cursor,owner_id:B})])).error.code,'COMMUNITY_INVALID');
 const deletion=nextRaceId();await p.service('select public.rs_begin_account_deletion($1,$2)',[A,deletion]);assert.equal((await p.value(A,'select public.rs_community_owner_posts(null,30) value')).error.code,'ACCOUNT_DELETION_PENDING');
});

test('aggregate readiness is read-only and exposes only role/catalog/capacity counters',async()=>{
 const sql=await readFile(new URL('../ops/m7-community-readiness.sql',import.meta.url),'utf8'),value=(await p.admin(sql)).rows[0].readiness;assert.equal(value.private_tables.length,8);assert.ok(value.private_tables.every(x=>x.rls&&!x.anon_read&&!x.app_read&&!x.app_write));assert.equal(value.predecessor_helpers.length,6);assert.ok(value.predecessor_helpers.every(x=>!x.app_execute&&!x.service_execute));assert.equal(value.public_functions.length,25);assert.ok(value.public_functions.every(x=>x.definer&&!x.anon_execute&&x.search_path.includes('search_path=""')));assert.ok(value.retired_app_functions.every(x=>!x.app_execute));assert.deepEqual(value.media_bucket,{public:false,max_bytes:1048576,mime_types:['image/jpeg']});assert.equal(value.storage_policies.some(x=>x.name==='rs_media_insert'),false);assert.equal(Number(value.app_reserved_actual_bytes),0);assert.equal(value.app_capacity_bytes,805306368);assert.equal(value.race_policy_enabled,false);assert.equal(JSON.stringify(value).includes(A),false);assert.equal(value.posts,0);
});

test('comment deletion authority is exactly its author, including on an owned post',async()=>{
 const created=await post(A,{visibility:'public'}),commentId=nextRaceId();await mutate(B,nextRaceId(),request('comment',{post_id:created.id,expected_revision:1,comment_id:commentId,body:'Author-owned comment'}));const ownerPage=await p.value(A,'select public.rs_community_comments($1,null,30) value',[created.id]);model.validateCommunityComments(ownerPage,A,created.id);assert.equal(ownerPage.items[0].can_delete,false);const deletion=request('delete_comment',{post_id:created.id,expected_revision:1,comment_id:commentId});assert.equal((await mutate(A,nextRaceId(),deletion)).error.code,'COMMUNITY_UNAVAILABLE');const authorPage=await p.value(B,'select public.rs_community_comments($1,null,30) value',[created.id]);model.validateCommunityComments(authorPage,B,created.id);assert.equal(authorPage.items[0].can_delete,true);const operation=nextRaceId(),ack=await mutate(B,operation,deletion);model.validateCommunityReceipt(ack,B,{operationId:operation,request:deletion});assert.equal(ack.result.state,'deleted');assert.deepEqual(await mutate(B,operation,deletion),ack);
});
