import {compileRaceCourse,verifyRouteTime} from '../functions/_shared/verify-route-time.mjs';
import {createHash} from 'node:crypto';
import {A,B,id,request,friends} from './live-fixture.mjs';
let serial=200000;
export const nextRaceId=()=>id(++serial);
const base={latitude:13.7,longitude:100.5};
export const racePoint=(east,north)=>({latitude:base.latitude+north/110625,longitude:base.longitude+east/108186});
const encode=points=>{let lat=0,lon=0,out='';const part=n=>{let x=n<0?~(n<<1):n<<1,s='';while(x>=32){s+=String.fromCharCode((32|(x&31))+63);x>>=5;}return s+String.fromCharCode(x+63);};for(const p of points){const x=Math.round(p.latitude*1e5),y=Math.round(p.longitude*1e5);out+=part(x-lat)+part(y-lon);lat=x;lon=y;}return out;};
export const raceMutate=(p,owner,operation,body)=>p.value(owner,'select public.rs_race_mutate($1,$2::jsonb) value',[operation,JSON.stringify(body)]);
export const raceRead=(p,owner,race)=>p.value(owner,'select public.rs_get_race($1) value',[race]);
export async function approvedRaceCourse(p,owner=A){
 const routeId=nextRaceId(),courseId=nextRaceId(),sessionId=nextRaceId(),approvalId=nextRaceId();
 const start=racePoint(0,0),finish=racePoint(0,800),document={schema_version:1,title:'Private course fixture',category:'scooter',visibility:'private',stops:[{lat:start.latitude,lng:start.longitude,label:'Private staging'},{lat:finish.latitude,lng:finish.longitude,label:'Private finish'}],source:{kind:'recorded',segments:[encode([start,finish])]}};
 await p.as(owner,'select public.rs_save_route_v2($1,$2,0,$3::jsonb)',[nextRaceId(),routeId,JSON.stringify(document)]);
 const source=await p.value(owner,'select public.rs_get_route_owner($1) value',[routeId]);
 const boundary=[racePoint(-60,-60),racePoint(60,-60),racePoint(60,860),racePoint(-60,860)];
 const gates=[30,400,750].map((north,index)=>({index,kind:index===0?'start':index===2?'finish':'checkpoint',a:racePoint(-25,north),b:racePoint(25,north),forward_point:racePoint(0,north+10),progress_min_m:north-5,progress_max_m:north+5}));
 const config={schema_version:1,method:'route_time_v1',staging_polygon:[racePoint(-8,5),racePoint(8,5),racePoint(8,20),racePoint(-8,20)],gates,corridor_half_width_m:30,maximum_speed_mps:50};
 const configuration=compileRaceCourse({...config,route_geometry:source.segments[0],boundary_polygon:boundary});
 const startsAt=new Date(Date.now()-60000).toISOString(),endsAt=new Date(Date.now()+3600000).toISOString();
 await p.admin('insert into public.rs_courses(id,name,closed_course_approved,boundary_polygon) values($1,$2,true,$3::jsonb)',[courseId,'Disposable private test course',JSON.stringify(boundary)]);
 await p.admin('insert into public.rs_course_sessions(id,course_id,starts_at,ends_at,approved) values($1,$2,$3,$4,true)',[sessionId,courseId,startsAt,endsAt]);
 const approvalRequest={schema_version:1,route_owner_id:owner,route_id:routeId,route_revision:1,route_geometry_hash:source.geometryHash,course_id:courseId,session_id:sessionId,reviewer_ref:'Disposable automated test only',config};
 const approved=(await p.service('select public.rs_approve_race_course($1,$2::jsonb) value',[approvalId,JSON.stringify(approvalRequest)])).rows[0].value;
 const projection=await p.value(owner,'select public.rs_get_route_projection($1) value',[routeId]);
 return {routeId,courseId,sessionId,approvalId,startsAt,endsAt,configuration,approvalRequest,approved,projection,document};
}
export async function createRace(p,{owner=A,peer=B,mode='async',course=null}={}){
 await friends(p,owner,peer);await p.admin('update ride_private.race_policy set enabled=true');
 const c=course??await approvedRaceCourse(p,owner),raceId=nextRaceId(),operation=nextRaceId();
 const body=request('race_create',{race_id:raceId,mode,approval_id:c.approvalId,route_id:c.routeId,route_revision:1,reviewed_projection_hash:c.projection.geometryHash,starts_at:c.startsAt,ends_at:c.endsAt,friends:[{user_id:peer,friendship_generation:10}],acknowledgement_version:1,evidence_consent_version:1});
 const receipt=await raceMutate(p,owner,operation,body);if(receipt.error)throw new Error(JSON.stringify(receipt));return {...c,raceId,owner,peer,receipt,createRequest:body,createOperation:operation};
}
export async function acceptRace(p,fixture,owner=fixture.peer){const view=await raceRead(p,owner,fixture.raceId),operation=nextRaceId(),body=request('member_action',{race_id:fixture.raceId,expected_revision:view.revision,expected_member_generation:view.self_member.member_generation,expected_friendship_generation:view.self_member.friendship_generation,decision:'accept',acknowledgement_version:1,evidence_consent_version:1});const receipt=await raceMutate(p,owner,operation,body);if(receipt.error)throw new Error(JSON.stringify(receipt));return {receipt,operation,body};}
export async function reserveRaceAttempt(p,fixture,owner=fixture.owner){const view=await raceRead(p,owner,fixture.raceId),attemptId=nextRaceId(),captureId=nextRaceId(),operation=nextRaceId(),body=request('attempt_reserve',{race_id:fixture.raceId,expected_revision:view.revision,expected_member_generation:view.self_member.member_generation,attempt_id:attemptId,ride_id:nextRaceId(),capture_id:captureId,platform:'android',provider:'expo_location',vehicle_local_id:null});const receipt=await raceMutate(p,owner,operation,body);if(receipt.error)throw new Error(JSON.stringify(receipt));return {attemptId,captureId,owner,operation,body,receipt};}
export async function stageRaceAttempt(p,fixture,attempt,extra={}){const view=await raceRead(p,attempt.owner,fixture.raceId),wall=Date.now(),body={schema_version:1,race_id:fixture.raceId,member_generation:view.self_member.member_generation,attempt_id:attempt.attemptId,capture_id:attempt.captureId,lobby_epoch:view.lobby_epoch,sequence:1,platform:'android',provider:'expo_location',timestamp_ms:wall-20,received_wall_ms:wall,received_monotonic_ms:1000,...racePoint(0,12),horizontal_accuracy_m:1,is_simulated_by_software:null,is_produced_by_accessory:null,mocked:null,...extra};const proof=await p.value(attempt.owner,'select public.rs_race_stage($1::jsonb) value',[JSON.stringify(body)]);return {body,proof};}
export async function probeRaceAttempt(p,fixture,attempt){const generation=nextRaceId(),probes=[];for(let n=0;n<3;n++){const probe=nextRaceId();const response=await p.value(attempt.owner,'select public.rs_race_clock($1,$2,$3,$4) value',[probe,fixture.raceId,attempt.captureId,generation]);if(response.error)throw new Error(JSON.stringify(response));probes.push(response);}return {generation,probes};}
export async function armRaceAttempt(p,fixture,attempt){const stage=await stageRaceAttempt(p,fixture,attempt),clock=await probeRaceAttempt(p,fixture,attempt),operation=nextRaceId(),body=request('attempt_arm',{attempt_id:attempt.attemptId,expected_revision:attempt.receipt.result.attempt.revision,stage_proof_id:stage.proof.proof_id,capture_id:attempt.captureId,clock_probe_ids:clock.probes.map(x=>x.probe_id)});const receipt=await raceMutate(p,attempt.owner,operation,body);if(receipt.error)throw new Error(JSON.stringify(receipt));return {stage,clock,operation,body,receipt};}
export async function bindRaceEvidence(p,attempt,armed){const operation=nextRaceId(),body=request('evidence_bind',{attempt_id:attempt.attemptId,expected_revision:armed.receipt.result.attempt.revision,capture_id:attempt.captureId,first_sequence:1,last_sequence:80,sample_count:80,byte_length:50000,sha256:'a'.repeat(64)});const receipt=await raceMutate(p,attempt.owner,operation,body);if(receipt.error)throw new Error(JSON.stringify(receipt));return {operation,body,receipt};}
export async function scheduledRace(p,fixture){
 await acceptRace(p,fixture);const ready=[],attempts=[];
 for(const owner of[fixture.owner,fixture.peer]){const a=await reserveRaceAttempt(p,fixture,owner),armed=await armRaceAttempt(p,fixture,a),view=await raceRead(p,owner,fixture.raceId),body=request('race_ready',{race_id:fixture.raceId,expected_revision:view.revision,expected_member_generation:view.self_member.member_generation,expected_ready_revision:view.self_member.ready_revision,lobby_epoch:view.lobby_epoch,attempt_id:a.attemptId,capture_id:a.captureId,stage_proof_id:armed.stage.proof.proof_id,clock_probe_ids:armed.clock.probes.map(x=>x.probe_id)}),response=await raceMutate(p,owner,nextRaceId(),body);if(response.error)throw Error(JSON.stringify(response));ready.push({user_id:owner,member_generation:view.self_member.member_generation,ready_revision:response.result.ready_revision,ready_lease_id:response.result.ready_lease_id,attempt_id:a.attemptId});attempts.push({...a,armed});}
 const view=await raceRead(p,fixture.owner,fixture.raceId),body=request('race_schedule',{race_id:fixture.raceId,expected_revision:view.revision,lobby_epoch:view.lobby_epoch,ready}),response=await raceMutate(p,fixture.owner,nextRaceId(),body);if(response.error)throw Error(JSON.stringify(response));return{response,attempts,ready};
}

// Disposable engine fixture only: represent a completed original capture in the
// past without waiting for a real course traversal. Never targets a hosted DB.
export async function completedRaceEvidence(p,fixture,attempt,armed,{extraProbe=null}={}){
 const mode=fixture.createRequest.mode,base=Date.now()-(mode==='live'?210000:45000),mono=1000,firstSequence=25;
 await p.admin('update ride_private.race_attempts set armed_at=$2 where id=$1',[attempt.attemptId,new Date(base-100).toISOString()]);
 const clock_probes=armed.clock.probes.map((probe,index)=>({probe_id:probe.probe_id,clock_generation:armed.clock.generation,request_started_monotonic_ms:mono-500+index*100,received_monotonic_ms:mono-480+index*100,request_started_wall_ms:base-500+index*100,received_wall_ms:base-480+index*100}));
 if(extraProbe)clock_probes.push({probe_id:extraProbe,clock_generation:armed.clock.generation,request_started_monotonic_ms:mono+500,received_monotonic_ms:mono+520,request_started_wall_ms:base+500,received_wall_ms:base+520});
 for(const probe of clock_probes)await p.admin('update ride_private.race_clock_probes set server_received_at=$2,server_sent_at=$2 where owner_id=$3 and probe_id=$1',[probe.probe_id,new Date(probe.request_started_wall_ms+10).toISOString(),attempt.owner]);
 const step=mode==='live'?1000:500,samples=Array.from({length:mode==='live'?200:80},(_,index)=>({sequence:firstSequence+index,received_monotonic_ms:mono+index*step,received_wall_ms:base+index*step,timestamp_ms:base+index*step-50,...racePoint(0,12+(mode==='live'?Math.max(0,index-3)*4:index*10)),speed_mps:mode==='live'?4:20,horizontal_accuracy_m:1,speed_accuracy_mps:null,is_simulated_by_software:null,is_produced_by_accessory:null,mocked:null}));
 const view=await raceRead(p,attempt.owner,fixture.raceId);let commonStart=mode==='live'?new Date(base+3500).toISOString():null;
 if(mode==='live'){await p.admin("update public.rs_course_sessions set starts_at=$2 where id=$1",[fixture.sessionId,new Date(base-60000).toISOString()]);await p.admin('update ride_private.races set starts_at=$2,common_start_at=$3,state=\'running\' where id=$1',[fixture.raceId,new Date(base-60000).toISOString(),commonStart]);await p.admin('update ride_private.race_attempts set common_start_at=$2,schedule_epoch=$3 where id=$1',[attempt.attemptId,commonStart,view.schedule_epoch]);commonStart=(await raceRead(p,attempt.owner,fixture.raceId)).common_start_at;}
 const evidence={schema_version:1,method:'route_time_v1',race_id:fixture.raceId,attempt_id:attempt.attemptId,approval_id:fixture.approvalId,config_hash:fixture.approved.config_hash,mode,schedule_epoch:mode==='live'?view.schedule_epoch:null,common_start_at:commonStart,source:'ride_journal_v1',platform:'android',provider:'expo_location',ride_id:attempt.body.ride_id,capture_id:attempt.captureId,first_sequence:firstSequence,last_sequence:samples.at(-1).sequence,capture_truncated:false,foreground_continuous:true,clock_anomaly:false,clock_generation:armed.clock.generation,arm_clock_probe_ids:armed.body.clock_probe_ids,lifecycle:[{kind:'armed',received_monotonic_ms:mono-100,received_wall_ms:base-100},{kind:'finish_observed',received_monotonic_ms:samples.at(-1).received_monotonic_ms,received_wall_ms:samples.at(-1).received_wall_ms}],clock_probes,samples};
 const bytes=Buffer.from(JSON.stringify(evidence)),sha256=createHash('sha256').update(bytes).digest('hex'),operation=nextRaceId(),body=request('evidence_bind',{attempt_id:attempt.attemptId,expected_revision:armed.receipt.result.attempt.revision,capture_id:attempt.captureId,first_sequence:firstSequence,last_sequence:evidence.last_sequence,sample_count:samples.length,byte_length:bytes.length,sha256});
 const bound=await raceMutate(p,attempt.owner,operation,body);if(bound.error)throw Error(JSON.stringify(bound));
 const reservation=bound.result.reservation;await p.as(attempt.owner,"insert into storage.objects(bucket_id,name,owner_id,metadata) values('ride-race-evidence',$1,$2,$3::jsonb)",[reservation.path,attempt.owner,JSON.stringify({size:bytes.length,mimetype:'application/json'})]);
 const queued=await raceMutate(p,attempt.owner,nextRaceId(),request('evidence_queue',{attempt_id:attempt.attemptId,expected_revision:bound.result.attempt.revision,sha256}));if(queued.error)throw Error(JSON.stringify(queued));
 const claim=(await p.service('select public.rs_claim_race_attempt($1,$2) value',[attempt.attemptId,attempt.owner])).rows[0].value;
 const result={...verifyRouteTime(evidence,claim),evidence_sha256:sha256};return{evidence,bytes,sha256,bound,claim,result,reservation};
}
