/** Generated by motion/scripts/generate-registry.mjs from the verified family. */
export const motionRoles = [
  "garage-scooter",
  "garage-bigbike",
  "garage-car",
  "podium-first",
  "podium-second",
  "podium-third",
  "ranked-today",
  "ranked-week",
  "ranked-month",
  "auth-onboarding",
  "empty-state",
  "challenge-lobby",
  "speedometer-glow",
  "profile-license"
] as const;
export type MotionRole = (typeof motionRoles)[number];
export type MotionTheme = "dark" | "light";

const themedAssets = {
  "garage-scooter-dark": {
    video: require("../../../assets/motion/v5/garage-scooter-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-scooter-dark-poster.jpg") as number,
  },
  "garage-scooter-light": {
    video: require("../../../assets/motion/v5/garage-scooter-light.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-scooter-light-poster.jpg") as number,
  },
  "garage-bigbike-dark": {
    video: require("../../../assets/motion/v5/garage-bigbike-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-bigbike-dark-poster.jpg") as number,
  },
  "garage-bigbike-light": {
    video: require("../../../assets/motion/v5/garage-bigbike-light.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-bigbike-light-poster.jpg") as number,
  },
  "garage-car-dark": {
    video: require("../../../assets/motion/v5/garage-car-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-car-dark-poster.jpg") as number,
  },
  "garage-car-light": {
    video: require("../../../assets/motion/v5/garage-car-light.mp4") as number,
    poster: require("../../../assets/motion/v5/garage-car-light-poster.jpg") as number,
  },
  "podium-first-dark": {
    video: require("../../../assets/motion/v5/podium-first-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-first-dark-poster.jpg") as number,
  },
  "podium-first-light": {
    video: require("../../../assets/motion/v5/podium-first-light.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-first-light-poster.jpg") as number,
  },
  "podium-second-dark": {
    video: require("../../../assets/motion/v5/podium-second-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-second-dark-poster.jpg") as number,
  },
  "podium-second-light": {
    video: require("../../../assets/motion/v5/podium-second-light.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-second-light-poster.jpg") as number,
  },
  "podium-third-dark": {
    video: require("../../../assets/motion/v5/podium-third-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-third-dark-poster.jpg") as number,
  },
  "podium-third-light": {
    video: require("../../../assets/motion/v5/podium-third-light.mp4") as number,
    poster: require("../../../assets/motion/v5/podium-third-light-poster.jpg") as number,
  },
  "ranked-today-dark": {
    video: require("../../../assets/motion/v5/ranked-today-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-today-dark-poster.jpg") as number,
  },
  "ranked-today-light": {
    video: require("../../../assets/motion/v5/ranked-today-light.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-today-light-poster.jpg") as number,
  },
  "ranked-week-dark": {
    video: require("../../../assets/motion/v5/ranked-week-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-week-dark-poster.jpg") as number,
  },
  "ranked-week-light": {
    video: require("../../../assets/motion/v5/ranked-week-light.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-week-light-poster.jpg") as number,
  },
  "ranked-month-dark": {
    video: require("../../../assets/motion/v5/ranked-month-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-month-dark-poster.jpg") as number,
  },
  "ranked-month-light": {
    video: require("../../../assets/motion/v5/ranked-month-light.mp4") as number,
    poster: require("../../../assets/motion/v5/ranked-month-light-poster.jpg") as number,
  },
  "auth-onboarding-dark": {
    video: require("../../../assets/motion/v5/auth-onboarding-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/auth-onboarding-dark-poster.jpg") as number,
  },
  "auth-onboarding-light": {
    video: require("../../../assets/motion/v5/auth-onboarding-light.mp4") as number,
    poster: require("../../../assets/motion/v5/auth-onboarding-light-poster.jpg") as number,
  },
  "empty-state-dark": {
    video: require("../../../assets/motion/v5/empty-state-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/empty-state-dark-poster.jpg") as number,
  },
  "empty-state-light": {
    video: require("../../../assets/motion/v5/empty-state-light.mp4") as number,
    poster: require("../../../assets/motion/v5/empty-state-light-poster.jpg") as number,
  },
  "challenge-lobby-dark": {
    video: require("../../../assets/motion/v5/challenge-lobby-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/challenge-lobby-dark-poster.jpg") as number,
  },
  "challenge-lobby-light": {
    video: require("../../../assets/motion/v5/challenge-lobby-light.mp4") as number,
    poster: require("../../../assets/motion/v5/challenge-lobby-light-poster.jpg") as number,
  },
  "speedometer-glow-dark": {
    video: require("../../../assets/motion/v5/speedometer-glow-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/speedometer-glow-dark-poster.jpg") as number,
  },
  "speedometer-glow-light": {
    video: require("../../../assets/motion/v5/speedometer-glow-light.mp4") as number,
    poster: require("../../../assets/motion/v5/speedometer-glow-light-poster.jpg") as number,
  },
  "profile-license-dark": {
    video: require("../../../assets/motion/v5/profile-license-dark.mp4") as number,
    poster: require("../../../assets/motion/v5/profile-license-dark-poster.jpg") as number,
  },
  "profile-license-light": {
    video: require("../../../assets/motion/v5/profile-license-light.mp4") as number,
    poster: require("../../../assets/motion/v5/profile-license-light-poster.jpg") as number,
  },
} as const;

/** Metro receives explicit static requires; the compatibility alias adds no media. */
export const ambientAssets = {
  ...themedAssets,
  "garage-scooter": themedAssets["garage-scooter-dark"],
} as const;

export type AmbientAsset = keyof typeof ambientAssets;

export const motionRoleAssets = {
  "garage-scooter": { dark: "garage-scooter-dark", light: "garage-scooter-light" },
  "garage-bigbike": { dark: "garage-bigbike-dark", light: "garage-bigbike-light" },
  "garage-car": { dark: "garage-car-dark", light: "garage-car-light" },
  "podium-first": { dark: "podium-first-dark", light: "podium-first-light" },
  "podium-second": { dark: "podium-second-dark", light: "podium-second-light" },
  "podium-third": { dark: "podium-third-dark", light: "podium-third-light" },
  "ranked-today": { dark: "ranked-today-dark", light: "ranked-today-light" },
  "ranked-week": { dark: "ranked-week-dark", light: "ranked-week-light" },
  "ranked-month": { dark: "ranked-month-dark", light: "ranked-month-light" },
  "auth-onboarding": { dark: "auth-onboarding-dark", light: "auth-onboarding-light" },
  "empty-state": { dark: "empty-state-dark", light: "empty-state-light" },
  "challenge-lobby": { dark: "challenge-lobby-dark", light: "challenge-lobby-light" },
  "speedometer-glow": { dark: "speedometer-glow-dark", light: "speedometer-glow-light" },
  "profile-license": { dark: "profile-license-dark", light: "profile-license-light" },
} as const satisfies Record<MotionRole, Record<MotionTheme, AmbientAsset>>;

/** The caller supplies the actual resolved app theme; no hidden system observer. */
export function resolveAmbientAsset(role: MotionRole, theme: MotionTheme): AmbientAsset {
  const variants = motionRoleAssets[role];
  if (!variants || (theme !== "dark" && theme !== "light")) {
    throw new RangeError("Unknown motion material or theme");
  }
  return variants[theme];
}
