import test from 'node:test';import assert from 'node:assert/strict';import {communityModule,owner,peer,uuid,stamp,document,photo} from './communityFixtures.mjs';
const model=communityModule('localModel'),content=communityModule('model'),plain=v=>JSON.parse(JSON.stringify(v));
const operation=()=>({owner_id:owner,operationId:uuid(900),request:{schema_version:1,action:'publish',post_id:uuid(200),expected_revision:0,document:document()},queuedAt:stamp,lastError:null});
const descriptor=()=>{const {media_id,validation,...value}=photo();return value;};
const draft=()=>({owner_id:owner,draft_id:uuid(201),post_id:uuid(200),revision:1,document:document(),photos:[{media_id:uuid(10),descriptor:descriptor(),reservation:null,commit:null}],post_revision:0,status:'local',operationId:null,error:null,created_at:stamp,updated_at:stamp});
test('private restart metadata binds exact owner, UUID, reviewed request and rejects collision/foreign/corrupt storage',()=>{assert.deepEqual(plain(model.parseCommunityOperations([operation()],owner)),[operation()]);for(const value of [[operation(),operation()],[{...operation(),owner_id:peer}],[{...operation(),request:{...operation().request,access_token:'not allowed'}}],[{...operation(),lastError:'raw sensitive error'}]])assert.throws(()=>model.parseCommunityOperations(value,owner));assert.throws(()=>model.parseCommunityOperations(Array.from({length:33},(_,i)=>({...operation(),operationId:uuid(900+i)})),owner),/COMMUNITY_CAPACITY/);});
test('blank incomplete draft survives restart but cannot become a publication',()=>{const value={...draft(),document:{...document(),caption:'',ride:null,route:null,include_ride_route:false,media_ids:[]},photos:[]};assert.deepEqual(plain(model.parseCommunityDrafts([value],owner)),[value]);assert.throws(()=>content.freezePublicationDocument(value.document),/COMMUNITY_INVALID/);assert.throws(()=>model.parseCommunityDrafts([value],peer),/COMMUNITY_LOCAL_INVALID/);});
test('canonical commit may replace only pixel-derived blurhash and never hash/pixels/path of local bytes',()=>{const d=draft(),p=d.photos[0],commit={post_id:d.post_id,media_id:p.media_id,descriptor:{...p.descriptor,blurhash:'LEHV6nWB2yk8pyo0adR*.7kCMdnj'}};d.photos=[{...p,reservation:{post_id:d.post_id,media_id:p.media_id,bucket:'ride-post-media',path:`${owner}/${d.post_id}/${p.media_id}.jpg`,expires_at:stamp,state:'committed'},commit}];assert.equal(model.parseCommunityDrafts([d],owner)[0].photos[0].commit.descriptor.blurhash,commit.descriptor.blurhash);assert.throws(()=>model.parseCommunityDrafts([{...d,photos:[{...d.photos[0],commit:{...commit,descriptor:{...commit.descriptor,sha256:'a'.repeat(64)}}}]}],owner),/COMMUNITY_LOCAL_INVALID/);assert.throws(()=>model.parseCommunityDrafts([{...d,photos:[{...d.photos[0],reservation:{...d.photos[0].reservation,path:`${peer}/foreign.jpg`}}]}],owner),/COMMUNITY_LOCAL_INVALID/);});
test('ordered photos, finite drafts and pending publication identity never silently truncate',()=>{const d=draft();for(const changed of [{...d,document:{...d.document,media_ids:[]}},{...d,status:'pending',operationId:null},{...d,photos:[...d.photos,...d.photos]},{...d,document:{...d.document,caption:'bad\ud800'}}])assert.throws(()=>model.parseCommunityDrafts([changed],owner));assert.throws(()=>model.parseCommunityDrafts(Array.from({length:5},(_,i)=>({...d,draft_id:uuid(201+i),post_id:uuid(300+i),photos:[],document:{...d.document,media_ids:[]}})),owner),/COMMUNITY_CAPACITY/);});
