import test from 'node:test';import assert from 'node:assert/strict';import {communityModule,owner,uuid,hold} from './communityFixtures.mjs';
const row=()=>({post_id:uuid(102),content_revision:3,visibility:'friends',state:'hidden',updated_at:'2026-10-01T09:00:00.000001Z'});
function fixture(){let cells=[],index=0,effects=[];const calls=[];const hooks={useRef:v=>{const n=index++;return cells[n]??={current:v};},useState:v=>{const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,next=>cells[n].value=typeof next==='function'?next(cells[n].value):next];},useCallback:(fn,deps)=>{const n=index++,old=cells[n];if(!old||deps?.some((v,i)=>v!==old.deps?.[i]))cells[n]={deps,value:fn};return cells[n].value;},useLayoutEffect(fn){index++;fn();},useEffect(fn,deps){const n=index++,old=cells[n];if(!old||deps?.some((v,i)=>v!==old.deps?.[i]))effects.push(()=>{old?.cleanup?.();cells[n]={deps,cleanup:fn()};});}};
 const jsx=(type,props)=>({type,props}),deps={react:hooks,'react/jsx-runtime':{jsx,jsxs:jsx},'@shopify/flash-list':{FlashList:'FlashList'},'react-native':{View:'View'},'../../components/ui':Object.fromEntries(['Button','Heading','Note','Panel','Row','Screen','T'].map(x=>[x,x])),'../routes/RouteSheet':{RouteSheet:'RouteSheet'},'./CommunityParts':{CommunityChoices:'Choices',CommunityStatus:'Status'}};
 const port={ownerId:owner,generation:'A1',current:g=>g===port.generation,guard:g=>{if(g!==port.generation)throw Error('ACCOUNT_CHANGED');},gate:{signedIn:true,profileReady:true,focused:true,foreground:true,moving:false,online:true},ready:true,units:'kmh',locale:'en',pending:[],latest:null,busy:false,rows:[row()],read:{loaded:true,loading:false,fresh:true,error:null,hasMore:false},detailRead:{loaded:true,loading:false,fresh:true,error:null,hasMore:false},onBack:()=>calls.push('back'),onSignIn:()=>calls.push('signIn'),mutate:async()=>{},retry:async()=>calls.push('retry'),refresh:async()=>calls.push('refresh'),loadMore:async()=>calls.push('more'),reviewPost:async()=>row(),currentPost:p=>p.content_revision===port.rows[0]?.content_revision,apply:async(p,action,visibility)=>{calls.push([p,action,visibility]);return uuid(900);}};
 const component=communityModule('CommunityOwnerScreen',deps).CommunityOwnerScreen;
 return{port,calls,render(){index=0;effects=[];const tree=component({port,t:(key,v)=>v?key+':'+JSON.stringify(v):key});effects.forEach(fn=>fn());return tree;}};
}
function all(tree,type){const items=[];function walk(v){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(walk);return;}if(v.type===type)items.push(v);if(v.type==='RouteSheet'&&!v.props.visible)return;if(v.type==='FlashList')v.props.data.forEach(item=>walk(v.props.renderItem({item})));if(v.props)for(const key of ['children','ListHeaderComponent','ListFooterComponent'])walk(v.props[key]);}walk(tree);return items;}
const button=(tree,label)=>{const found=all(tree,'Button').find(v=>v.props.label===label);assert.ok(found,label);return found.props;};
test('hidden owner settings render only status metadata and audience change never claims moderation release',async()=>{const f=fixture();await button(f.render(),'m7.owner.review').onPress();let tree=f.render();assert.equal(all(tree,'Note').some(v=>v.props.children==='m7.owner.hidden'),true);assert.equal(all(tree,'Note').some(v=>v.props.children==='m7.owner.metadata'),true);const choices=all(tree,'Choices')[0].props;choices.onChange('public');tree=f.render();await button(tree,'m7.confirmAudience').onPress();assert.equal(f.calls[0][1],'audience');assert.equal(f.calls[0][2],'public');assert.equal(f.calls[0][0].content_revision,3);assert.equal(JSON.stringify(tree).includes('caption'),false);});
test('a retained review or audience input cannot mutate a newer post, moving screen or later owner',async()=>{const f=fixture();await button(f.render(),'m7.owner.review').onPress();const tree=f.render(),confirm=button(tree,'m7.confirmAudience'),choose=all(tree,'Choices')[0].props.onChange;f.port.gate.moving=true;f.render();choose('public');f.port.gate.moving=false;f.render();assert.equal(all(f.render(),'RouteSheet')[0].props.visible,false);f.port.rows=[{...row(),content_revision:4}];f.render();await confirm.onPress();assert.equal(f.calls.length,0);f.port.generation='B2';f.render();await confirm.onPress();assert.equal(f.calls.length,0);});
test('held review after background return leaves no consent or transient lock and deletion has a separate confirmation',async()=>{const f=fixture(),wait=hold();f.port.reviewPost=()=>wait.promise;const task=button(f.render(),'m7.owner.review').onPress();f.port.gate.foreground=false;f.render();f.port.gate.foreground=true;f.render();wait.resolve(row());await task;let tree=f.render();assert.equal(all(tree,'RouteSheet')[0].props.visible,false);assert.equal(button(tree,'m7.owner.review').disabled,false);f.port.reviewPost=async()=>row();await button(f.render(),'m7.owner.review').onPress();tree=f.render();assert.equal(all(tree,'Button').some(v=>v.props.label==='m7.confirmDelete'),false);button(tree,'m7.deletePost').onPress();tree=f.render();await button(tree,'m7.confirmDelete').onPress();assert.equal(f.calls.at(-1)[1],'delete_post');});
test('failed unread owner list never claims empty and deleted settings expose no write affordance',async()=>{const f=fixture();f.port.rows=[];f.port.read={loaded:false,loading:false,fresh:false,error:'COMMUNITY_UNAVAILABLE',hasMore:false};assert.equal(all(f.render(),'Note').some(v=>v.props.children==='m7.owner.empty'),false);f.port.rows=[{...row(),state:'deleted'}];f.port.read={loaded:true,loading:false,fresh:true,error:null,hasMore:false};f.port.reviewPost=async()=>f.port.rows[0];await button(f.render(),'m7.owner.review').onPress();const tree=f.render();assert.equal(all(tree,'Note').some(v=>v.props.children==='m7.owner.deleted'),true);assert.equal(all(tree,'Button').some(v=>['m7.confirmAudience','m7.deletePost'].includes(v.props.label)),false);});
test('owner resources are flat, bilingual and keep i18next interpolation syntax',()=>{const {m7OwnerEn,m7OwnerTh}=communityModule('../../lib/communityOwnerI18n');assert.deepEqual(Object.keys(m7OwnerEn).sort(),Object.keys(m7OwnerTh).sort());for(const values of [m7OwnerEn,m7OwnerTh]){assert.match(values['m7.owner.revision'],/\{\{revision\}\}/);assert.match(values['m7.owner.revision'],/\{\{time\}\}/);}});
test('closed review cannot be reused by a retained confirmation after close or reopen of the same post',async()=>{const f=fixture();await button(f.render(),'m7.owner.review').onPress();let tree=f.render();const prior=button(tree,'m7.confirmAudience');all(tree,'RouteSheet')[0].props.onClose();f.render();await prior.onPress();assert.equal(f.calls.length,0);await button(f.render(),'m7.owner.review').onPress();f.render();await prior.onPress();assert.equal(f.calls.length,0);});
test('audience edit retires old audience and delete confirmations, even for the same current post',async()=>{const f=fixture();await button(f.render(),'m7.owner.review').onPress();let tree=f.render();const oldAudience=button(tree,'m7.confirmAudience');button(tree,'m7.deletePost').onPress();tree=f.render();const oldDelete=button(tree,'m7.confirmDelete');all(tree,'Choices')[0].props.onChange('public');f.render();await oldDelete.onPress();await oldAudience.onPress();assert.equal(f.calls.length,0);await button(f.render(),'m7.confirmAudience').onPress();assert.equal(f.calls.at(-1)[2],'public');});
test('closing a sheet during held parent preflight revokes its caller consent before a write is accepted',async()=>{const f=fixture(),wait=hold();f.port.apply=async(_row,_action,_audience,guard)=>{await wait.promise;guard();f.calls.push('write');return uuid(900);};await button(f.render(),'m7.owner.review').onPress();let tree=f.render();const pending=button(tree,'m7.confirmAudience').onPress();all(tree,'RouteSheet')[0].props.onClose();f.render();wait.resolve();await pending;assert.equal(f.calls.length,0);});
test('metadata row capacity reports its finite list bound rather than a photo storage error',()=>{const f=fixture();f.port.read={loaded:true,loading:false,fresh:false,error:'COMMUNITY_CAPACITY',hasMore:true};const tree=f.render();assert.equal(all(tree,'Note').some(v=>v.props.children==='m7.owner.capacity'),true);assert.equal(all(tree,'FlashList')[0].props.scrollEnabled,true);f.port.gate.moving=true;assert.equal(all(f.render(),'FlashList')[0].props.scrollEnabled,false);});
test('a durable accepted owner change is presented even when parent retires its canonical getter',async()=>{const f=fixture();f.port.apply=async(p,action,visibility,guard)=>{guard();f.calls.push([p,action,visibility]);f.port.currentPost=()=>false;return uuid(900);};await button(f.render(),'m7.owner.review').onPress();await button(f.render(),'m7.confirmAudience').onPress();const tree=f.render();assert.equal(f.calls.length,1);assert.equal(all(tree,'Status')[0].props.operation,uuid(900));assert.equal(all(tree,'Status')[0].props.error,null);assert.equal(all(tree,'RouteSheet')[0].props.visible,false);});
test('Auth-only owners can explicitly review and delete their retained metadata without a social profile',async()=>{const f=fixture();f.port.gate.profileReady=false;assert.equal(button(f.render(),'m7.owner.review').disabled,false);await button(f.render(),'m7.owner.review').onPress();let tree=f.render();button(tree,'m7.deletePost').onPress();tree=f.render();assert.equal(button(tree,'m7.confirmDelete').disabled,false);await button(tree,'m7.confirmDelete').onPress();assert.equal(f.calls.at(-1)[1],'delete_post');assert.equal(all(f.render(),'Status')[0].props.operation,uuid(900));});
test('Auth-only owner can reconcile exact pending privacy work through the control recovery guard',async()=>{const f=fixture();f.port.gate.profileReady=false;f.port.guard=(_generation,kind)=>{if(kind!=='control')throw Error('COMMUNITY_CHANGED');};await all(f.render(),'Status')[0].props.retry();assert.deepEqual(f.calls,['retry']);});
test('accepted durable owner intent stays visible when connectivity ends after queue acceptance',async()=>{const f=fixture();f.port.apply=async(_post,_action,_visibility,guard)=>{guard();f.port.gate.online=false;return uuid(900);};await button(f.render(),'m7.owner.review').onPress();await button(f.render(),'m7.confirmAudience').onPress();const status=all(f.render(),'Status')[0].props;assert.equal(status.operation,uuid(900));assert.equal(status.error,null);});
