import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import ts from 'typescript';
import {owner,peer,uuid,stamp,hold} from './communityFixtures.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url)),tick=()=>new Promise(r=>setImmediate(r));
const metadata=()=>({post_id:uuid(102),content_revision:3,visibility:'friends',state:'hidden',updated_at:'2026-10-01T09:00:00.000001Z'});
function harness(){
 let cells=[],index=0,dirty=false,focused=true,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'captured-owner'},moving=false,closed=false,holds={},canonical=metadata();const layouts=[],effects=[],listeners=new Set(),cache=new Map(),calls=[],navigation=[];
 const same=(a,b)=>a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i])),memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;},enqueue=(queue,fn,deps)=>{const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};queue.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}};
 const react={useRef:v=>{const n=index++;return cells[n]??={current:v};},useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useState:v=>{const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,next=>{const value=typeof next==='function'?next(cells[n].value):next;if(!Object.is(value,cells[n].value)){cells[n].value=value;dirty=true;}}];},useEffect:(fn,deps)=>enqueue(effects,fn,deps),useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps),useSyncExternalStore:(subscribe,get)=>{const n=index++;if(cells[n]?.subscribe!==subscribe){cells[n]?.remove?.();cells[n]={subscribe,remove:subscribe(()=>dirty=true)};}return get();}};
 const jsx=(type,props)=>({type,props}),native={View:'View',Platform:{OS:'ios'},AppState:{currentState:'active',addEventListener(_n,fn){listeners.add(fn);return{remove:()=>listeners.delete(fn)};}}};
 async function wait(key){const value=holds[key];delete holds[key];if(value)await value.promise;}
 const community={ready:true,pending:[],latest:null,busy:false,privacyPending:false,privacyKey:'p1',guardOwner(){if(closed||scope.userId!==session?.user.id)throw Error('ACCOUNT_CHANGED');},retry:async()=>{},async mutate(request,guard){calls.push(['preflight',request]);await wait('mutation');guard();calls.push(['write',request]);return uuid(900);}};
 const services={async getCommunityOwnerPosts(captured,capturedSession,cursor){calls.push(['list',captured,capturedSession,cursor]);const result={owner_id:captured.userId,server_now:stamp,items:[canonical],next_cursor:null};await wait('list');return result;},async getCommunityOwnerPost(captured,capturedSession,id){calls.push(['get',captured,capturedSession,id]);const result={owner_id:captured.userId,server_now:stamp,post:canonical};await wait('get');return result;}};
 function override(key){if(key==='react')return react;if(key==='react/jsx-runtime')return{jsx,jsxs:jsx};if(key==='react-native')return native;if(key==='expo-router')return{useIsFocused:()=>focused,router:{push:v=>navigation.push(v),back:()=>navigation.push('back')}};
  if(key.endsWith('/state/AuthState'))return{useAuth:()=>({ready:true,scope,session}),isAccountCurrent:value=>value===scope&&!closed};if(key.endsWith('/state/AppState'))return{useApp:()=>({ready:true,storageError:null,data:{unit:'kmh'}})};if(key.endsWith('/state/RideState'))return{useRide:()=>({movingLocked:moving})};if(key.endsWith('/state/CommunityState'))return{useCommunity:()=>community};if(key.endsWith('/state/SocialState'))return{useSocial:()=>({ready:true,profileReady:true})};if(key.endsWith('/lib/i18n'))return{useI18n:()=>({language:'th',t:key=>key})};if(key.endsWith('/components/ui'))return{Button:'Button',Heading:'Heading',Screen:'Screen',T:'T',Note:'Note'};if(key.endsWith('/CommunityOwnerScreen'))return{CommunityOwnerScreen:'OwnerScreen'};if(key.endsWith('/communityOwnerService'))return services;return undefined;
 }
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith('community-posts.tsx'))source+='\nexport {AccountCommunityPosts as __testHost};\n';const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,performance:{now:()=>1000},require:key=>{const replacement=override(key);if(replacement!==undefined)return replacement;if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);if(!existsSync(next))for(const ext of ['.ts','.tsx'])if(existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}
 const component=load(resolve(root,'app/community-posts.tsx'));
 const h={calls,navigation,community,get port(){return h.tree.props.port;},render(){index=0;dirty=false;h.tree=component.__testHost();while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.port;},async settle(){for(let i=0;i<8;i++){await tick();if(dirty)h.render();}return h.render();},hold:key=>holds[key]=hold(),os(value){native.AppState.currentState=value;for(const fn of listeners)fn(value);},focus(value){focused=value;h.render();},move(value){moving=value;h.render();},privacy(value){community.privacyPending=value;community.privacyKey+='x';h.render();},canonical:v=>canonical=v,guest(){session=null;scope={userId:null,generation:2};index=0;return component.default();},switch(userId){for(const c of cells){c?.cleanup?.();c?.remove?.();}cells=[];scope={userId,generation:scope.generation+1};session={user:{id:userId},access_token:'new-'+scope.generation};h.render();},close(){closed=true;for(const c of cells){c?.cleanup?.();c?.remove?.();}}};return h;
}
test('actual owner host has no viewer/media calls and only a freshly selected hidden metadata CAS may mutate',async()=>{const h=harness();h.render();await h.settle();const p=h.port,row=await p.reviewPost(uuid(102));assert.equal(row.state,'hidden');assert.equal(p.currentPost(row),true);await p.apply(row,'audience','private');assert.deepEqual(JSON.parse(JSON.stringify(h.calls.at(-1))),['write',{schema_version:1,action:'audience',post_id:uuid(102),expected_revision:3,visibility:'private'}]);assert.equal(h.calls.some(v=>['signer','viewer','route'].includes(v[0])),false);h.close();});
test('held owner getter and retained callbacks are retired by OS background ABA before React cleanup',async()=>{const h=harness();h.render();await h.settle();const p=h.port,w=h.hold('get'),pending=assert.rejects(p.reviewPost(uuid(102)),/COMMUNITY_CHANGED/);await tick();h.os('background');h.os('active');const n=h.calls.length;assert.throws(()=>p.refresh(),/COMMUNITY_CHANGED/);w.resolve();await pending;assert.equal(h.calls.length,n);await h.settle();assert.equal(h.port.read.fresh,true);h.close();});
test('held canonical preflight cannot append a write after movement or privacy retirement',async()=>{const h=harness();h.render();await h.settle();let p=h.port,row=await p.reviewPost(uuid(102)),w=h.hold('mutation'),pending=assert.rejects(p.apply(row,'delete_post'),/COMMUNITY_MOVING/);await tick();h.move(true);w.resolve();await pending;assert.equal(h.calls.some(v=>v[0]==='write'),false);h.move(false);await h.settle();p=h.port;row=await p.reviewPost(uuid(102));w=h.hold('mutation');pending=assert.rejects(p.apply(row,'audience','public'),/COMMUNITY_CHANGED/);await tick();h.privacy(true);w.resolve();await pending;assert.equal(h.calls.some(v=>v[0]==='write'),false);h.close();});
test('guest issues no reader request and old A owner ports remain closed after A B A',async()=>{const guest=harness();assert.equal(guest.guest().type,'Screen');assert.equal(guest.calls.length,0);guest.close();const h=harness();h.render();await h.settle();const p=h.port,row=await p.reviewPost(uuid(102));h.switch(peer);await h.settle();h.switch(owner);await h.settle();const n=h.calls.length;await assert.rejects(p.apply(row,'delete_post'),/COMMUNITY_CHANGED|ACCOUNT_CHANGED/);assert.equal(h.calls.length,n);h.close();});
test('actual owner host repeats the UI consent guard after held canonical provider preflight',async()=>{const h=harness();h.render();await h.settle();const p=h.port,row=await p.reviewPost(uuid(102)),w=h.hold('mutation');let reviewed=true;const task=assert.rejects(p.apply(row,'audience','public',()=>{if(!reviewed)throw Error('COMMUNITY_REVIEW_REQUIRED');}),/COMMUNITY_REVIEW_REQUIRED/);await tick();reviewed=false;w.resolve();await task;assert.equal(h.calls.some(v=>v[0]==='write'),false);h.close();});
