import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {createHash} from 'node:crypto';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {owner,peer,uuid,stamp,hold,post} from './communityFixtures.mjs';

const source=fileURLToPath(new URL('../src/',import.meta.url)),require=createRequire(import.meta.url),tick=()=>new Promise(done=>setImmediate(done));
const plain=value=>JSON.parse(JSON.stringify(value));
const request=()=>({schema_version:1,action:'like',post_id:post().post_id,expected_revision:1,liked:true});
const document=()=>({schema_version:1,caption:'เส้นทางวันนี้',description:'',visibility:'friends',ride:null,route:null,include_ride_route:false,media_ids:[]});
const pendingDraft=()=>({owner_id:owner,draft_id:uuid(800),post_id:uuid(801),revision:1,document:document(),photos:[],post_revision:0,status:'pending',operationId:uuid(900),error:null,created_at:stamp,updated_at:stamp});
const publish=draft=>({schema_version:1,action:'publish',post_id:draft.post_id,expected_revision:draft.post_revision,document:draft.document});
const stored=draft=>({owner_id:owner,operationId:draft.operationId,request:publish(draft),queuedAt:stamp,lastError:null});
function publishedPhotoDraft(){const bytes=Uint8Array.from([255,216,1,255,217]),descriptor={mime:'image/jpeg',sha256:createHash('sha256').update(bytes).digest('hex'),byte_count:5,width:1,height:1,blurhash:null},draft={...pendingDraft(),status:'published',post_revision:1,document:{...document(),media_ids:[uuid(802)]},photos:[{media_id:uuid(802),descriptor,reservation:{post_id:uuid(801),media_id:uuid(802),bucket:'ride-post-media',path:`${owner}/${uuid(801)}/${uuid(802)}.jpg`,expires_at:stamp,state:'committed'},commit:{post_id:uuid(801),media_id:uuid(802),descriptor}}]};return {bytes,draft};}
function localPhotoDraft(){const {bytes,draft}=publishedPhotoDraft();return {bytes,draft:{...draft,status:'local',post_revision:0,operationId:null,photos:draft.photos.map(p=>({...p,reservation:null,commit:null}))}};}
function ack(scope,operation){const r=operation.request;return {owner_id:scope.userId,operation_id:operation.operationId,request:r,applied_at:stamp,result:r.action==='audience'||r.action==='delete_post'?{kind:'post',post_id:r.post_id,content_revision:r.expected_revision+1,engagement_revision:1,state:r.action==='delete_post'?'deleted':'published',visibility:r.action==='audience'?r.visibility:'private'}:r.action==='publish'?{kind:'post',post_id:r.post_id,content_revision:1,engagement_revision:1,state:'published',visibility:r.document.visibility}:{kind:'like',post_id:r.post_id,content_revision:r.expected_revision,engagement_revision:2,liked:r.liked,like_count:4}};}
function harness(){
 let cells=[],index=0,dirty=false,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'fixture-community-A'},serial=1000,moving=false,appReady=true,authReady=true,error=null,failDisk=false,failPublished=false,failRemoval=false,heldPost=null,heldSend=null,heldFlush=null,heldUpload=null,mono=0,ownerState='hidden',ownerRevision=1;
 const layouts=[],effects=[],listeners=new Set(),cache=new Map(),owned=new Map([[owner,{communityDrafts:[],communityOperations:[]}]]),disk=new Map([[owner,{communityDrafts:[],communityOperations:[]}]]),events=[],receipts=new Map(),photos=new Map();
 const same=(a,b)=>!!a&&a.length===b.length&&a.every((value,i)=>value===b[i]);
 const memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;};
 const effect=(queue,fn,deps)=>{const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};queue.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}};
 const react={createContext(value){return {value,Provider:'Provider'};},useContext:c=>c.value,useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useRef:value=>{const n=index++;return cells[n]??={current:value};},useState:value=>{const n=index++;cells[n]??={value:typeof value==='function'?value():value};return [cells[n].value,value=>{cells[n].value=typeof value==='function'?value(cells[n].value):value;dirty=true;}];},useLayoutEffect:(fn,deps)=>effect(layouts,fn,deps),useEffect:(fn,deps)=>effect(effects,fn,deps),useSyncExternalStore:(subscribe,get)=>{const n=index++;if(cells[n]?.subscribe!==subscribe){cells[n]?.remove?.();cells[n]={subscribe,remove:subscribe(()=>{dirty=true;})};}return get();}};
 const native={currentState:'active',addEventListener(_name,fn){listeners.add(fn);return {remove:()=>listeners.delete(fn)};}};
 function app(){const captured=scope;return {ready:appReady,storageError:error,data:owned.get(captured.userId)??{communityDrafts:[],communityOperations:[]},getOwned:()=>captured===scope&&appReady?owned.get(captured.userId):null,
  update(patch){if(captured!==scope||!appReady||error==='LOCAL_READ_FAILED')return false;owned.set(captured.userId,{...owned.get(captured.userId),...plain(patch)});events.push(['update',captured.userId]);dirty=true;return true;},
  async flushStorage(){events.push(['flush',captured.userId]);const wait=heldFlush;heldFlush=null;if(wait)await wait.promise;if(captured!==scope)throw Error('ACCOUNT_CHANGED');if(failDisk||failPublished&&owned.get(captured.userId).communityDrafts.some(d=>d.status==='published'))throw Error('LOCAL_WRITE_FAILED');disk.set(captured.userId,plain(owned.get(captured.userId)));},
  async retryStorage(){events.push(['retryStorage',captured.userId]);if(captured!==scope)throw Error('ACCOUNT_CHANGED');}};}
 const service={
  async getCommunityPost(captured,_session,id){events.push(['post',captured.userId,id]);const wait=heldPost;heldPost=null;if(wait)await wait.promise;return {owner_id:captured.userId,server_now:stamp,post:{...post(),post_id:id}};},
  async getCommunityOperation(captured,_session,id){events.push(['status',captured.userId,id,native.currentState]);return receipts.get(id)??null;},
  async mutateCommunity(captured,_session,operation){events.push(['send',captured.userId,operation.operationId,native.currentState]);const receipt=ack(captured,operation);receipts.set(operation.operationId,receipt);const wait=heldSend;heldSend=null;if(wait)await wait.promise;return receipt;}
 };
 const photoKey=(id,key)=>`${id}/${key.post_id}/${key.media_id}`;
 const photoDisk={async read(id,key){return photos.get(photoKey(id,key))??null;},async list(id){return [...photos.keys()].filter(k=>k.startsWith(id+'/')).map(k=>({post_id:k.split('/')[1],media_id:k.split('/')[2]}));},async writeNew(id,key,bytes){if(photos.has(photoKey(id,key)))throw Error('LOCAL_WRITE_FAILED');photos.set(photoKey(id,key),Uint8Array.from(bytes));},async remove(id,key){events.push(['removePhoto',id,key.media_id]);if(failRemoval)throw Error('LOCAL_WRITE_FAILED');photos.delete(photoKey(id,key));},async removeOwner(id){events.push(['removePhotos',id]);for(const key of [...photos.keys()])if(key.startsWith(id+'/'))photos.delete(key);}};
 const overrides={react,'react/jsx-runtime':{jsx:(_type,props)=>({props}),jsxs:(_type,props)=>({props})},'react-native':{AppState:native},'expo-crypto':{randomUUID:()=>uuid(serial++),CryptoDigestAlgorithm:{SHA256:'SHA-256'},async digest(_algorithm,bytes){const value=createHash('sha256').update(bytes).digest();return value.buffer.slice(value.byteOffset,value.byteOffset+value.byteLength);}},'./AppState':{useApp:app},'./AuthState':{useAuth:()=>({scope,session,ready:authReady}),isAccountCurrent:s=>s===scope,accountClient:(captured,auth)=>({storage:{from:bucket=>({async upload(path,bytes,options){events.push(['upload',captured.userId,bucket,path,bytes.byteLength,plain(options),Array.from(new Uint8Array(bytes))]);assert.equal(auth.user.id,captured.userId);const wait=heldUpload;heldUpload=null;if(wait)await wait.promise;return {error:null};}})}})},'./RideState':{useRide:()=>({movingLocked:moving})},'./SocialState':{useSocial:()=>({pending:[],accountRevision:1,latest:null})},'../features/community/service':service,'../features/community/communityOwnerService':{async getCommunityOwnerPost(captured,_session,id){events.push(['ownerPost',captured.userId,id]);const wait=heldPost;heldPost=null;if(wait)await wait.promise;return {owner_id:captured.userId,server_now:stamp,post:{post_id:id,content_revision:ownerRevision,visibility:'friends',state:ownerState,updated_at:stamp}};}},'../features/community/photoDisk':{communityPhotoDisk:photoDisk}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(readFileSync(path,'utf8'),{fileName:path,reportDiagnostics:true,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}});if(code.diagnostics?.some(d=>d.category===ts.DiagnosticCategory.Error))throw Error('Invalid source '+path);runInNewContext(code.outputText,{module,exports:module.exports,console,Date,Promise,Error,TextEncoder,TextDecoder,Uint8Array,ArrayBuffer,URL,performance:{now:()=>mono},require:name=>{if(name in overrides)return overrides[name];if(!name.startsWith('.'))return require(name);const base=resolve(dirname(path),name),file=['.ts','.tsx'].map(ext=>base+ext).find(existsSync)??base;return load(file);}});return module.exports;}
 const provider=load(resolve(source,'state/CommunityState.tsx'));
 const h={provider,events,owned,disk,receipts,photos,get scope(){return scope;},get session(){return session;},get state(){return h.tree.props.value;},render(){index=0;dirty=false;h.tree=provider.CommunityProvider({children:null});while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.state;},async settle(){for(let n=0;n<12;n++){await tick();if(dirty)h.render();}return h.render();},ownerMetadata:(state,revision=1)=>{ownerState=state;ownerRevision=revision;},holdPost:()=>heldPost=hold(),holdSend:()=>heldSend=hold(),holdFlush:()=>heldFlush=hold(),holdUpload:()=>heldUpload=hold(),os(value){native.currentState=value;for(const fn of listeners)fn(value);},move(value){moving=value;return h.render();},readiness(authValue,appValue){authReady=authValue;appReady=appValue;return h.render();},storage(value,fail=false){error=value;failDisk=fail;return h.render();},failAck(value){failPublished=value;},failRemoval(value){failRemoval=value;},seed(drafts,ops=[]){const value={communityDrafts:plain(drafts),communityOperations:plain(ops)};owned.set(scope.userId,value);disk.set(scope.userId,plain(value));},switch(id){scope={userId:id,generation:scope.generation+1};session=id?{user:{id},access_token:'fixture-'+id}:null;if(!owned.has(id)){owned.set(id,{communityDrafts:[],communityOperations:[]});disk.set(id,{communityDrafts:[],communityOperations:[]});}return h.render();},close(){for(const cell of cells){cell?.cleanup?.();cell?.remove?.();}}};return h;
}

test('actual provider waits for hydrated owner and durable intent before scoped canonical status/write',async()=>{const h=harness();h.readiness(false,false);await h.settle();assert.equal(h.events.length,0);assert.equal(h.state.ready,false);h.readiness(true,true);await h.settle();h.events.length=0;await h.state.mutate(request());await h.settle();assert.ok(h.events.findIndex(e=>e[0]==='flush')<h.events.findIndex(e=>e[0]==='status'));assert.equal(h.owned.get(owner).communityOperations.length,0);assert.equal(h.state.latest.status,'applied');assert.equal('rows' in h.state,false);h.close();});
test('held preflight background or movement ABA cannot enqueue a newly reviewed mutation after return',async()=>{for(const policy of ['os','move']){const h=harness();h.render();await h.settle();h.events.length=0;const wait=h.holdPost(),pending=h.state.mutate(request());await tick();if(policy==='os'){h.os('background');h.os('active');}else{h.move(true);h.move(false);}wait.resolve();await assert.rejects(pending,/COMMUNITY_INACTIVE|COMMUNITY_REVIEW_REQUIRED|COMMUNITY_CHANGED/);assert.equal(h.events.some(e=>['update','status','send'].includes(e[0])),false);h.close();}});
test('host captured focus ticket is repeated after a held canonical preflight, including blur-return ABA',async()=>{const h=harness();h.render();await h.settle();let focus=1;const captured=focus,guard=()=>{if(focus!==captured)throw Error('COMMUNITY_REVIEW_REQUIRED');},wait=h.holdPost(),pending=h.state.mutate(request(),guard);await tick();focus++;focus++;wait.resolve();await assert.rejects(pending,/COMMUNITY_REVIEW_REQUIRED/);assert.equal(h.events.some(e=>e[0]==='send'),false);assert.equal(h.owned.get(owner).communityOperations.length,0);h.close();});
test('held durable queue flush repeats its activity lease before first egress and keeps the same recoverable operation',async()=>{const h=harness();h.render();await h.settle();h.events.length=0;const wait=h.holdFlush(),pending=h.state.mutate(request());await tick();assert.equal(h.owned.get(owner).communityOperations.length,1);const op=h.owned.get(owner).communityOperations[0];h.os('background');h.os('active');wait.resolve();assert.equal(await pending,null);assert.equal(h.events.some(e=>['status','send'].includes(e[0])),false);assert.equal(h.disk.get(owner).communityOperations[0].operationId,op.operationId);await h.state.retry();await h.settle();assert.equal(h.events.find(e=>e[0]==='send')[2],op.operationId);assert.equal(h.owned.get(owner).communityOperations.length,0);h.close();});
test('failed local publication ACK flush retains the exact outbox and avoids false applied; retry uses canonical status only',async()=>{const h=harness(),draft=pendingDraft();h.seed([draft],[stored(draft)]);h.failAck(true);h.render();await h.settle();assert.equal(h.disk.get(owner).communityDrafts[0].status,'pending');assert.equal(h.owned.get(owner).communityOperations.length,1);assert.notEqual(h.state.latest?.status,'applied');const sends=h.events.filter(e=>e[0]==='send').length;assert.equal(sends,1);h.failAck(false);await h.state.retry();await h.settle();assert.equal(h.disk.get(owner).communityDrafts[0].status,'published');assert.equal(h.owned.get(owner).communityOperations.length,0);assert.equal(h.events.filter(e=>e[0]==='send').length,sends);h.close();});
test('restart with reviewed pending draft and absent queue recreates its same UUID and reconciles prior server receipt',async()=>{const h=harness(),draft=pendingDraft();h.seed([draft]);h.receipts.set(draft.operationId,ack(h.scope,{operationId:draft.operationId,request:publish(draft)}));h.render();await h.settle();await h.state.retry();await h.settle();assert.equal(h.disk.get(owner).communityDrafts[0].status,'published');assert.equal(h.events.some(e=>e[0]==='send'),false);assert.ok(h.events.some(e=>e[0]==='status'&&e[2]===draft.operationId));assert.equal(h.owned.get(owner).communityOperations.length,0);h.close();});
test('held ACK and retained callbacks cannot settle replacement owner or acquire a newer account token',async()=>{const h=harness();h.render();await h.settle();const old=h.state,wait=h.holdSend(),pending=old.mutate(request());await tick();h.switch(peer);await h.settle();wait.resolve();await pending;await h.settle();assert.equal(h.owned.get(peer).communityOperations.length,0);assert.equal(h.state.latest,null);const before=h.events.length;await assert.rejects(old.mutate(request()),/ACCOUNT_CHANGED/);assert.equal(h.events.length,before);assert.equal(h.events.filter(e=>e[0]==='send').length,1);h.close();});
test('unread or failed local storage cannot issue community egress while original durable intent remains recoverable',async()=>{const h=harness();h.render();await h.settle();h.storage(null,true);h.events.length=0;assert.equal(await h.state.mutate(request()),null);await h.settle();assert.equal(h.events.some(e=>['status','send'].includes(e[0])),false);assert.equal(h.owned.get(owner).communityOperations.length,1);h.storage('LOCAL_READ_FAILED');assert.equal(h.state.ready,false);await assert.rejects(h.state.retry(),/COMMUNITY_INACTIVE/);h.close();});
test('private upload rejects another owner, changed reserved path, committed replay and oversized bytes before storage egress',async()=>{const h=harness();h.render();await h.settle();const bytes=Uint8Array.from([255,216,1,255,217]),reservation={post_id:uuid(801),media_id:uuid(802),bucket:'ride-post-media',path:`${owner}/${uuid(801)}/${uuid(802)}.jpg`,expires_at:stamp,state:'reserved'},upload=h.provider.uploadCommunityPhoto,scope=h.scope,session=h.session;await upload(scope,session,reservation,bytes,h.state.guardOwner);const sent=h.events.find(e=>e[0]==='upload');assert.deepEqual(sent.slice(1),[owner,'ride-post-media',reservation.path,5,{contentType:'image/jpeg',upsert:false,cacheControl:'60'},Array.from(bytes)]);h.events.length=0;for(const bad of [{...reservation,path:`${peer}/${reservation.post_id}/${reservation.media_id}.jpg`},{...reservation,state:'committed'},{...reservation,bucket:'avatars'}])await assert.rejects(upload(scope,session,bad,bytes,h.state.guardOwner),/COMMUNITY_MEDIA_INVALID|COMMUNITY_INVALID_RESPONSE/);await assert.rejects(upload(scope,{...session,user:{id:peer}},reservation,bytes,h.state.guardOwner),/ACCOUNT_CHANGED/);await assert.rejects(upload(scope,session,reservation,new Uint8Array(1048577),h.state.guardOwner),/COMMUNITY_MEDIA_INVALID/);assert.equal(h.events.length,0);h.close();});
test('an in-flight private upload uses copied bytes and the pinned JWT, then rejects a replacement owner',async()=>{const h=harness();h.render();await h.settle();const original=Uint8Array.from([255,216,1,255,217]),reservation={post_id:uuid(801),media_id:uuid(802),bucket:'ride-post-media',path:`${owner}/${uuid(801)}/${uuid(802)}.jpg`,expires_at:stamp,state:'reserved'},wait=h.holdUpload(),pending=h.provider.uploadCommunityPhoto(h.scope,h.session,reservation,original,h.state.guardOwner);original[2]=99;await tick();h.switch(peer);wait.resolve();await assert.rejects(pending,/ACCOUNT_CHANGED/);assert.equal(h.events.filter(e=>e[0]==='upload').length,1);assert.equal(h.events.find(e=>e[0]==='upload')[1],owner);assert.deepEqual(h.events.find(e=>e[0]==='upload')[6],[255,216,1,255,217]);h.close();});
test('private candidate bytes are digest-bound across provider ports and stale owner callbacks cannot read them',async()=>{const h=harness();h.render();await h.settle();const bytes=Uint8Array.from([255,216,1,255,217]),descriptor={mime:'image/jpeg',sha256:createHash('sha256').update(bytes).digest('hex'),byte_count:bytes.length,width:1,height:1,blurhash:null},key={post_id:uuid(801),media_id:uuid(802)},scope=h.scope,guard=h.state.guardOwner;await h.provider.communityPhotos.put(scope,key,bytes,descriptor,guard);assert.deepEqual(await h.provider.communityPhotos.read(scope,key,descriptor,guard),bytes);await assert.rejects(h.provider.communityPhotos.read(scope,key,{...descriptor,sha256:'b'.repeat(64)},guard),/COMMUNITY_PHOTO_INVALID/);h.switch(peer);await assert.rejects(h.provider.communityPhotos.read(scope,key,descriptor,guard),/ACCOUNT_CHANGED/);assert.equal(h.photos.size,1);h.close();});
test('confirmed published retirement is restart-recoverable after metadata flush failure and leaves no orphan bytes',async()=>{const h=harness(),{bytes,draft}=publishedPhotoDraft();h.seed([draft]);h.photos.set(`${owner}/${draft.post_id}/${uuid(802)}`,bytes);h.render();await h.settle();h.storage(null,true);await assert.rejects(h.state.retirePublished(),/LOCAL_WRITE_FAILED/);assert.equal(h.disk.get(owner).communityDrafts.length,1);assert.equal(h.photos.size,0);const persisted=h.disk.get(owner).communityDrafts;h.close();const resumed=harness();resumed.seed(persisted);resumed.render();await resumed.settle();await resumed.state.retirePublished();await resumed.settle();assert.equal(resumed.disk.get(owner).communityDrafts.length,0);assert.equal(resumed.photos.size,0);resumed.close();});
test('failed candidate removal retains confirmed published metadata so a later retirement retries safely',async()=>{const h=harness(),{bytes,draft}=publishedPhotoDraft();h.seed([draft]);h.photos.set(`${owner}/${draft.post_id}/${uuid(802)}`,bytes);h.render();await h.settle();h.failRemoval(true);await assert.rejects(h.state.retirePublished(),/LOCAL_WRITE_FAILED/);assert.equal(h.disk.get(owner).communityDrafts[0].status,'published');assert.equal(h.photos.size,1);h.failRemoval(false);await h.state.retirePublished();await h.settle();assert.equal(h.disk.get(owner).communityDrafts.length,0);assert.equal(h.photos.size,0);h.close();});
test('local discard removes only its own unreferenced private copy and pending reviewed publication cannot be discarded',async()=>{const h=harness(),{bytes,draft}=localPhotoDraft(),key=`${owner}/${draft.post_id}/${uuid(802)}`;h.seed([draft]);h.photos.set(key,bytes);h.photos.set(`${peer}/${draft.post_id}/${uuid(802)}`,bytes);h.render();await h.settle();await h.state.discardDraft(draft.draft_id);assert.equal(h.disk.get(owner).communityDrafts.length,0);assert.equal(h.photos.has(key),false);assert.equal(h.photos.size,1);h.readiness(false,true);const pending=pendingDraft();h.seed([pending],[stored(pending)]);h.render();await assert.rejects(h.state.discardDraft(pending.draft_id),/COMMUNITY_CHANGED/);assert.equal(h.disk.get(owner).communityDrafts[0].status,'pending');assert.equal(h.disk.get(owner).communityOperations[0].operationId,pending.operationId);h.close();});
test('failed local discard flush preserves restart metadata and private bytes; a stale caller lease cannot discard it',async()=>{const h=harness(),{bytes,draft}=localPhotoDraft(),key=`${owner}/${draft.post_id}/${uuid(802)}`;h.seed([draft]);h.photos.set(key,bytes);h.render();await h.settle();h.storage(null,true);await assert.rejects(h.state.discardDraft(draft.draft_id),/LOCAL_WRITE_FAILED/);assert.equal(h.disk.get(owner).communityDrafts.length,1);assert.equal(h.photos.has(key),true);const saved=h.disk.get(owner).communityDrafts;h.close();const resumed=harness();resumed.seed(saved);resumed.photos.set(key,bytes);resumed.render();await resumed.settle();let epoch=1;const lease=epoch,guard=()=>{if(lease!==epoch)throw Error('COMMUNITY_REVIEW_REQUIRED');};epoch++;await assert.rejects(resumed.state.discardDraft(draft.draft_id,guard),/COMMUNITY_REVIEW_REQUIRED/);assert.equal(resumed.disk.get(owner).communityDrafts.length,1);assert.equal(resumed.photos.has(key),true);await resumed.state.discardDraft(draft.draft_id);assert.equal(resumed.disk.get(owner).communityDrafts.length,0);assert.equal(resumed.photos.has(key),false);resumed.close();});
test('confirmed account closure fences transport synchronously and removes only its own private candidate bytes',async()=>{const h=harness();h.render();await h.settle();const key={post_id:uuid(801),media_id:uuid(802)};h.photos.set(`${owner}/${key.post_id}/${key.media_id}`,new Uint8Array([1]));h.photos.set(`${peer}/${key.post_id}/${key.media_id}`,new Uint8Array([2]));const old=h.state,pending=h.provider.clearCommunityAccount(h.scope);await assert.rejects(old.mutate(request()),/ACCOUNT_CHANGED/);await pending;assert.equal(h.photos.has(`${owner}/${key.post_id}/${key.media_id}`),false);assert.equal(h.photos.has(`${peer}/${key.post_id}/${key.media_id}`),true);h.close();});


test('hidden owned post privacy actions use only owner metadata while engagement keeps the strict viewer reader',async()=>{for(const action of ['audience','delete_post']){const h=harness();h.render();await h.settle();h.events.length=0;const intent={schema_version:1,action,post_id:uuid(801),expected_revision:1,...(action==='audience'?{visibility:'private'}:{})};await h.state.mutate(intent);await h.settle();assert.equal(h.events.filter(e=>e[0]==='ownerPost').length,1);assert.equal(h.events.some(e=>e[0]==='post'),false);assert.equal(h.state.latest.status,'applied');assert.equal(h.receipts.get(h.state.latest.operationId).result.content_revision,2);h.events.length=0;await h.state.mutate(request());assert.equal(h.events.some(e=>e[0]==='post'),true);assert.equal(h.events.some(e=>e[0]==='ownerPost'),false);h.close();}});

test('owned privacy preflight rejects changed or retired metadata and stale activity before queueing',async()=>{for(const [state,revision] of [['hidden',2],['deleted',1],['draft',0]]){const h=harness();h.render();await h.settle();h.ownerMetadata(state,revision);h.events.length=0;await assert.rejects(h.state.mutate({schema_version:1,action:'audience',post_id:uuid(801),expected_revision:1,visibility:'private'}),/COMMUNITY_CHANGED/);assert.equal(h.events.some(e=>['update','status','send'].includes(e[0])),false);h.close();}const h=harness();h.render();await h.settle();const wait=h.holdPost(),pending=h.state.mutate({schema_version:1,action:'delete_post',post_id:uuid(801),expected_revision:1});h.os('background');h.os('active');wait.resolve();await assert.rejects(pending,/COMMUNITY_INACTIVE/);assert.equal(h.events.some(e=>e[0]==='send'),false);h.close();});
