import {createRequire} from 'node:module';import {readFileSync,existsSync} from 'node:fs';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),root=resolve(dirname(fileURLToPath(import.meta.url)),'../src/features/community');
export const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,owner=uuid(1),peer=uuid(2),stamp='2026-10-01T10:00:00.000Z';
export function communityModule(name,deps={},globals={}){const cache=new Map();function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const result=ts.transpileModule(readFileSync(path,'utf8'),{fileName:path,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}});if(result.diagnostics?.some(v=>v.category===ts.DiagnosticCategory.Error))throw Error('Invalid community source: '+path+' '+result.diagnostics.map(v=>ts.flattenDiagnosticMessageText(v.messageText,' ')).join('; '));runInNewContext(result.outputText,{module,exports:module.exports,Date,console,URL,Headers,Response,Uint8Array,ArrayBuffer,TextEncoder,process:{env:{}},...globals,require:key=>{if(key in deps)return deps[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);for(const ext of ['.ts','.tsx'])if(!existsSync(next)&&existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}return load(resolve(root,existsSync(resolve(root,`${name}.ts`))?`${name}.ts`:`${name}.tsx`));}
export const hold=()=>{let resolve;return {promise:new Promise(r=>{resolve=r;}),resolve};};
export const filter=()=>({schema_version:1,mode:'latest'});
export const photo=(n=10)=>({media_id:uuid(n),validation:'decoded_jpeg_v1',mime:'image/jpeg',sha256:'b'.repeat(64),byte_count:1000,width:1200,height:800,blurhash:null});
export const ride=()=>({ride_id:uuid(70),ride_revision:2,summary_hash:'c'.repeat(64),started_at:'2026-10-01T08:00:00.000Z',ended_at:'2026-10-01T09:00:00.000Z',active_duration_ms:3000000,distance_m:24000,max_speed_mps:20,average_speed_mps:8,speed_status:'self_reported',vehicle:null});
export const route=()=>({source:'ride',source_id:uuid(70),source_revision:2,title:null,category:'scooter',segments:[[{latitude:13.7,longitude:100.5},{latitude:13.71,longitude:100.51}],[{latitude:13.72,longitude:100.55},{latitude:13.73,longitude:100.56}]],geometryStatus:'trimmed',privacyTrimMeters:200,geometryHash:'d'.repeat(64),provider:'recorded',attribution:null});
export const post=(n=2)=>({post_id:uuid(n+100),owner_id:uuid(n),profile:{name:'Rider '+n,handle:'rider'+n},content_version:1,content_revision:1,engagement_revision:1,caption:'เส้นทางสวยมากวันนี้',description:'ช่วงเช้าบรรยากาศดี',visibility:'friends',created_at:'2026-10-01T09:00:00.000001+00:00',updated_at:'2026-10-01T09:00:00.000001+00:00',ride:ride(),route:route(),legacy_claimed_speed_kmh:null,media:[photo()],engagement:{likes:3,comments:1,liked:false,saved:false},week_score:null});
export const page=()=>({owner_id:owner,server_now:stamp,filter:filter(),window:{timezone:'Asia/Bangkok',starts_at:null,ends_at:null,as_of:stamp},feed_revision:'a'.repeat(64),items:[post()],next_cursor:null});
export const document=()=>({schema_version:1,caption:'เส้นทางวันนี้',description:'',visibility:'friends',ride:{ride_id:uuid(70),ride_revision:2},route:null,include_ride_route:true,media_ids:[uuid(10)]});
export const comment=()=>({comment_id:uuid(90),post_id:uuid(102),owner_id:peer,profile:{name:'Rider 2',handle:'rider2'},body:'เส้นทางน่าสนใจครับ',created_at:'2026-10-01T09:10:00.000Z',can_delete:false});
