import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import {createHash} from 'node:crypto';import ts from 'typescript';
import {communityModule,owner,peer,uuid,stamp,hold,ride,route} from './communityFixtures.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url)),tick=()=>new Promise(done=>setImmediate(done));
const {CommunityPhotoStore}=communityModule('CommunityPhotoStore');
const blank=()=>({schema_version:1,caption:'',description:'',visibility:'friends',ride:null,route:null,include_ride_route:false,media_ids:[]});
function harness(){
 let cells=[],index=0,dirty=false,focused=true,moving=false,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'owner-fixture'},rows=[],next=1000,choicesHold=null,pickerHold=null,pickerResult={canceled:true,assets:[]},failPrepareAt=0,preparedCount=0;
 const effects=[],layouts=[],listeners=new Set(),cache=new Map(),calls=[],files=new Map();
 const same=(a,b)=>!!a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));const memo=(fn,deps)=>{const at=index++;if(!cells[at]||!same(cells[at].deps,deps))cells[at]={deps,value:fn()};return cells[at].value;};
 const enqueue=(queue,fn,deps)=>{const at=index++,old=cells[at];if(!old||!same(old.deps,deps)){cells[at]={deps};queue.push(()=>{old?.cleanup?.();cells[at].cleanup=fn();});}};
 const react={useRef:v=>{const at=index++;return cells[at]??={current:v};},useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useState:v=>{const at=index++;cells[at]??={value:typeof v==='function'?v():v};return[cells[at].value,value=>{cells[at].value=typeof value==='function'?value(cells[at].value):value;dirty=true;}];},useEffect:(fn,deps)=>enqueue(effects,fn,deps),useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps)};
 const native={Platform:{OS:'ios'},AppState:{currentState:'active',addEventListener(_n,fn){listeners.add(fn);return {remove:()=>listeners.delete(fn)};}}},jsx=(type,props)=>({type,props}),key=(who,p)=>[who,p.post_id,p.media_id].join('/');
 const store=new CommunityPhotoStore({current:value=>value===scope,disk:{async read(who,p){return files.get(key(who,p))??null;},async list(who){return [...files.keys()].filter(k=>k.startsWith(who+'/')).map(k=>({post_id:k.split('/')[1],media_id:k.split('/')[2]}));},async writeNew(who,p,b){files.set(key(who,p),Uint8Array.from(b));},async remove(who,p){files.delete(key(who,p));},async removeOwner(who){for(const k of files.keys())if(k.startsWith(who+'/'))files.delete(k);}},sha256:async b=>createHash('sha256').update(b).digest('hex')});
 const app={ready:true,storageError:null,data:{unit:'kmh'},flushStorage:async()=>{calls.push(['flush']);}};
 const community={ready:true,pending:[],latest:null,busy:false,privacyKey:'initial',get drafts(){return rows;},guardOwner(){if(!session||session.user.id!==scope.userId)throw Error('ACCOUNT_CHANGED');},signed(){community.guardOwner();if(native.AppState.currentState!=='active'||moving)throw Error('COMMUNITY_INACTIVE');return session;},readDrafts(){community.guardOwner();return rows;},async updateDrafts(reduce){rows=reduce(rows);dirty=true;await app.flushStorage();},async retirePublished(){rows=rows.filter(r=>r.status!=='published');dirty=true;await app.flushStorage();},async retry(){},async mutate(){},async enqueuePublication(request,id,guard){guard();calls.push(['enqueue',id,request]);return id;}};
 const savedRide={ride_id:uuid(70),revision:2,payload:{...ride(),vehicle:null},speed_status:'self_reported'};
 const services={async reserveCommunityPost(s,c,post){calls.push(['reservePost',s,c,post]);return {owner_id:s.userId,post_id:post,revision:0,state:'draft'};},async reserveCommunityMedia(s,c,post,media){calls.push(['reserveMedia',s,c,media]);return {post_id:post,media_id:media,bucket:'ride-post-media',path:s.userId+'/'+post+'/'+media+'.jpg',expires_at:stamp,state:'reserved'};},async commitCommunityMedia(_s,_c,post,media,descriptor){return {post_id:post,media_id:media,descriptor};},async getCommunityAttachmentReview(s,c,selection){calls.push(['review',s,c,selection]);return {owner_id:s.userId,server_now:stamp,ride:selection.ride?ride():null,route:selection.route?{...route(),source:'route',source_id:selection.route.route_id,source_revision:selection.route.route_revision,title:'Saved',category:'scooter'}:selection.include_ride_route?route():null};}};
 const overrides={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':native,'expo-crypto':{randomUUID:()=>uuid(next++)},'expo-router':{useIsFocused:()=>focused,router:{back(){calls.push(['back']);},push(){}}},'expo-image-picker':{async launchImageLibraryAsync(options){calls.push(['picker',options]);if(pickerHold)await pickerHold.promise;return pickerResult;}},'../components/ui':Object.fromEntries(['Button','Heading','Note','Panel','Screen','T'].map(n=>[n,n])),'../components/AccountGate':{AccountGate:'AccountGate'},'../features/routes/RouteSheet':{RouteSheet:'RouteSheet'},'../features/community/CommunityComposer':{CommunityComposer:'CommunityComposer'},'../features/community/imagePreparation':{async prepareCommunityPhoto(source,guard){guard();preparedCount++;calls.push(['prepare',source]);if(preparedCount===failPrepareAt)throw Error('COMMUNITY_PHOTO_INVALID');const bytes=new Uint8Array(1000).fill(preparedCount),descriptor={mime:'image/jpeg',sha256:createHash('sha256').update(bytes).digest('hex'),byte_count:1000,width:600,height:400,blurhash:null};return {uri:'file:///generated.jpg',bytes,descriptor,dispose:async()=>calls.push(['dispose'])};}},'../features/community/photoPreview':{async communityPhotoPreview(photoStore,s,k,d,guard){await photoStore.read(s,k,d,guard);guard();return {uri:'file:///private/'+k.media_id,dispose:()=>calls.push(['preview-dispose'])};}},'../features/community/service':services,'../features/rides/syncService':{async listRideSummaries(s,c,options){calls.push(['rides',s,c,options]);const wait=choicesHold;choicesHold=null;if(wait)await wait.promise;return {items:[savedRide],next_cursor:null};}},'../features/routes/syncService':{async listRoutesOwner(s,c){calls.push(['routes',s,c]);return {items:[{id:uuid(80),revision:3,document:{title:'Saved road',category:'scooter'}}],next_cursor:null};}},'../lib/i18n':{useI18n:()=>({language:'th',t:key=>key})},'../state/AppState':{useApp:()=>app},'../state/AuthState':{useAuth:()=>({scope,session,ready:true}),isAccountCurrent:s=>s===scope},'../state/CommunityState':{useCommunity:()=>community,communityPhotos:store,async uploadCommunityPhoto(s,c,r,b,guard){guard();calls.push(['upload',s,c,r,b]);}},'../state/RideState':{useRide:()=>({movingLocked:moving})},'../state/SocialState':{useSocial:()=>({profileReady:true})}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith('compose.tsx'))source+='\nexport {AccountComposer as __test};\n';const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,URL,Uint8Array,TextEncoder,process:{env:{}},require:name=>{if(name in overrides)return overrides[name];if(!name.startsWith('.'))return require(name);let p=resolve(dirname(path),name);if(!existsSync(p))for(const ext of ['.ts','.tsx'])if(existsSync(p+ext)){p+=ext;break;}return load(p);}});return module.exports;}
 const component=load(resolve(root,'app/compose.tsx'));
 const find=(node,label)=>{if(!node||typeof node!=='object')return null;if(node.type==='Button'&&node.props.label===label)return node;for(const child of [node.props?.children].flat(Infinity)){const value=find(child,label);if(value)return value;}return null;};
 const h={calls,files,rows:()=>rows,get port(){return h.tree.type==='CommunityComposer'?h.tree.props.port:null;},render(){index=0;dirty=false;h.tree=component.__test();while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.port;},async settle(){for(let i=0;i<12;i++){await tick();if(dirty)h.render();}return h.render();},async create(){h.render();find(h.tree,'m7.newDraft').props.onPress();return h.settle();},holdChoices(){return choicesHold=hold();},pick(assets){pickerResult={canceled:false,assets};},holdPicker(){return pickerHold=hold();},failPrepare(n){failPrepareAt=n;},os(status){native.AppState.currentState=status;for(const fn of listeners)fn(status);},focus(value){focused=value;return h.render();},move(value){moving=value;return h.render();},switch(){for(const cell of cells)cell?.cleanup?.();cells=[];scope={userId:peer,generation:2};session={user:{id:peer},access_token:'peer-fixture'};rows=[];return h.render();},close(){for(const cell of cells)cell?.cleanup?.();}};return h;
}
test('new/resumed owner draft defaults friends and chooser attaches real self-reported fields without a fabricated hash',async()=>{const h=harness();await h.create();assert.equal(h.port.draft.document.visibility,'friends');assert.equal(h.port.ridesRead.fresh,true);assert.equal(h.port.rides[0].summary.max_speed_mps,20);assert.equal('summary_hash' in h.port.rides[0].summary,false);assert.equal(h.port.routes[0].title,'Saved road');h.close();});
test('rapid different-field edits serialize against the freshest durable document',async()=>{const h=harness();await h.create();const a=h.port.changeDraft({caption:'ทริปเช้าวันนี้'}),b=h.port.changeDraft({description:'ถนนและท้องฟ้า'});await Promise.all([a,b]);await h.settle();assert.equal(h.port.draft.document.caption,'ทริปเช้าวันนี้');assert.equal(h.port.draft.document.description,'ถนนและท้องฟ้า');h.close();});
test('held source choices cannot survive OS background/resume before React cleanup',async()=>{const h=harness(),blocked=h.holdChoices();await h.create();h.os('background');h.os('active');blocked.resolve();await tick();h.render();assert.equal(h.port.ridesRead.fresh,false);assert.equal(h.port.rides.length,0);await h.settle();assert.equal(h.port.ridesRead.fresh,true);assert.equal(h.calls.filter(c=>c[0]==='rides').length,2);h.close();});
test('picker reply after background ABA stops before preparing or adopting a photo',async()=>{const h=harness();await h.create();const wait=h.holdPicker();h.pick([{uri:'file:///source.jpg',width:600,height:400}]);const task=assert.rejects(h.port.choosePhotos(),/COMMUNITY_REVIEW_REQUIRED/);await tick();h.os('background');h.os('active');wait.resolve();await task;assert.equal(h.calls.some(c=>c[0]==='prepare'),false);assert.equal(h.files.size,0);h.close();});
test('multiple-photo preparation keeps the first genuine local candidate when a later preparation fails',async()=>{const h=harness();await h.create();h.pick([{uri:'file:///one.jpg',width:600,height:400},{uri:'file:///two.jpg',width:600,height:400}]);h.failPrepare(2);await assert.rejects(h.port.choosePhotos(),/COMMUNITY_PHOTO_INVALID/);await h.settle();assert.equal(h.rows()[0].photos.length,1);assert.equal(h.files.size,1);assert.equal(h.rows()[0].photos[0].commit,null);assert.equal(h.calls.some(c=>c[0]==='upload'),false);h.close();});
test('canonical review and exact consent enqueue use immutable current saved bindings',async()=>{const h=harness();await h.create();await h.port.changeDraft({caption:'ทริปวันนี้',ride:{ride_id:uuid(70),ride_revision:2},include_ride_route:true});await h.settle();const reviewed=await h.port.reviewPublish();await h.settle();assert.equal(reviewed.ride.summary_hash,'c'.repeat(64));const id=await h.port.publish(reviewed);await h.settle();const queued=h.calls.find(c=>c[0]==='enqueue');assert.equal(id,queued[1]);assert.equal(queued[2].document.ride.ride_id,uuid(70));assert.equal(queued[2].document.ride.ride_revision,2);assert.equal(h.rows()[0].status,'pending');assert.equal(h.rows()[0].operationId,id);h.close();});
test('old owner or hidden-screen callbacks cannot dispatch or write a new account',async()=>{const h=harness();await h.create();const old=h.port;h.focus(false);const before=h.calls.length;await assert.rejects(old.changeDraft({caption:'stale'}),/COMMUNITY_REVIEW_REQUIRED/);assert.equal(h.calls.length,before);h.switch();await assert.rejects(old.choosePhotos(),/ACCOUNT_CHANGED/);assert.equal(h.rows().length,0);h.close();});
