import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import ts from 'typescript';
import {owner,peer,uuid,stamp,post,page,comment,hold} from './communityFixtures.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url)),tick=()=>new Promise(r=>setImmediate(r));
/** Actual route, host hooks, readers and media lease. Only React/OS and captured
 * SDK replies are fixtures; lifecycle and binding checks execute product code. */
function harness(kind='feed'){
 let cells=[],index=0,dirty=false,focused=true,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'A'},moving=false,appReady=true,now=1000,closed=false,params={postId:uuid(102)},holds={},socialPages=[],canonical=post();
 const layouts=[],effects=[],listeners=new Set(),cache=new Map(),calls=[],navigation=[],shares=[];
 const same=(a,b)=>a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i])),memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;},enqueue=(queue,fn,deps)=>{const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};queue.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}};
 const react={useRef:v=>{const n=index++;return cells[n]??={current:v};},useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useState:v=>{const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,next=>{const value=typeof next==='function'?next(cells[n].value):next;if(!Object.is(value,cells[n].value)){cells[n].value=value;dirty=true;}}];},useEffect:(fn,deps)=>enqueue(effects,fn,deps),useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps),useSyncExternalStore:(subscribe,get)=>{const n=index++;if(cells[n]?.subscribe!==subscribe){cells[n]?.remove?.();cells[n]={subscribe,remove:subscribe(()=>dirty=true)};}return get();}};
 const jsx=(type,props)=>({type,props}),native={View:'View',Platform:{OS:'ios'},Share:{share:async value=>{shares.push(value);}},AppState:{currentState:'active',addEventListener(_n,fn){listeners.add(fn);return{remove:()=>listeners.delete(fn)};}}};
 async function wait(key){const value=holds[key];delete holds[key];if(value)await value.promise;}
 const community={ready:true,pending:[],latest:null,busy:false,privacyPending:false,privacyKey:'private-1',appliedVersion:0,guardOwner(){if(closed||scope.userId!==session?.user.id)throw Error('ACCOUNT_CHANGED');},async retry(){calls.push({kind:'retry'});},async mutate(request,guard){calls.push({kind:'preflight',request});await wait('mutation');guard?.();calls.push({kind:'write',request});return uuid(900);}};
 const social={ready:true,fresh:true,profileReady:true,async refresh(){calls.push({kind:'socialRefresh'});},async mutate(request){calls.push({kind:'block',request});return uuid(901);}};
 const service={async getCommunityFeed(requested,captured,filter,cursor){calls.push({kind:'feed',requested,captured,filter,cursor});const row={...canonical,week_score:filter.mode==='top_week'?1:null},result={...page(),owner_id:requested.userId,filter,items:[row],...(filter.mode==='top_week'?{window:{timezone:'Asia/Bangkok',starts_at:'2026-09-27T17:00:00Z',ends_at:'2026-10-04T17:00:00Z',as_of:stamp}}:{})};await wait('feed');return result;},async getCommunityPost(requested,captured,id){calls.push({kind:'post',requested,captured,id});const result={owner_id:requested.userId,server_now:stamp,post:canonical};await wait('post');return result;},async getCommunityComments(requested,captured,id,cursor){calls.push({kind:'comments',requested,captured,id,cursor});const result={owner_id:requested.userId,server_now:stamp,post_id:id,content_revision:canonical.content_revision,items:[comment()],next_cursor:null};await wait('comments');return result;},async getCommunityMediaURL(requested,captured,p,media){calls.push({kind:'signer',requested,captured,p,media});await wait('signer');return{postId:p.post_id,mediaId:media.media_id,sha256:media.sha256,url:'https://project.supabase.co/signed/photo',expiresIn:60};}};
 const auth=()=>({ready:true,scope,session}),app=()=>({ready:appReady,storageError:null,data:{unit:'kmh'},colors:{},motion:false,dark:true});
 function override(path,key){if(key==='react')return react;if(key==='react/jsx-runtime')return{jsx,jsxs:jsx};if(key==='react-native')return native;if(key==='expo-router')return{useIsFocused:()=>focused,useLocalSearchParams:()=>params,router:{push:value=>navigation.push(value),back:()=>navigation.push('back')}};if(key==='expo-linking')return{createURL:(path,value)=>`ridespeed://${path}?postId=${value.queryParams.postId}`};if(key==='expo-crypto')return{randomUUID:()=>uuid(999)};
  if(key.endsWith('/state/AuthState'))return{useAuth:auth,isAccountCurrent:value=>value===scope&&!closed};if(key.endsWith('/state/AppState'))return{useApp:app};if(key.endsWith('/state/RideState'))return{useRide:()=>({movingLocked:moving})};if(key.endsWith('/state/CommunityState'))return{useCommunity:()=>community};if(key.endsWith('/state/SocialState'))return{useSocial:()=>social};if(key.endsWith('/lib/i18n'))return{useI18n:()=>({language:'th',t:key=>key})};if(key.endsWith('/components/ui'))return{Button:'Button',Row:'Row',Screen:'Screen',T:'T',Note:'Note'};
  if(key.endsWith('/CommunityFeed'))return{CommunityFeed:'Feed'};if(key.endsWith('/CommunityDetail'))return{CommunityDetail:'Detail'};if(key.endsWith('/CommunityRoutePreview'))return{CommunityRoutePreview:'Preview'};
  if(key==='./service'||key.endsWith('/community/service'))return service;if(key==='../social/service')return{getSocialSnapshot:async(requested,captured,limit,cursor)=>{calls.push({kind:'pair',requested,captured,limit,cursor});await wait('pair');return socialPages.shift()??{owner_id:requested.userId,self:{profile_ready:true},items:[],next_cursor:null};}};
  return undefined;
 }
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith(kind==='feed'?'community.tsx':'community-post.tsx'))source+=`\nexport {${kind==='feed'?'AccountCommunity':'AccountPost'} as __testHost};\n`;const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,performance:{now:()=>now},require:key=>{const replacement=override(path,key);if(replacement!==undefined)return replacement;if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);if(!existsSync(next))for(const ext of ['.ts','.tsx'])if(existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}
 const component=load(resolve(root,kind==='feed'?'app/(tabs)/community.tsx':'app/community-post.tsx'));
 const h={calls,navigation,shares,community,social,get port(){return h.tree.props.children[0].props.port;},get preview(){return h.tree.props.children.at(-1).props;},render(){index=0;dirty=false;h.tree=component.__testHost({postId:uuid(102)});while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.port;},async settle(){for(let i=0;i<8;i++){await tick();if(dirty)h.render();}return h.render();},hold:key=>holds[key]=hold(),os(status){native.AppState.currentState=status;for(const fn of listeners)fn(status);},focus(value){focused=value;h.render();},move(value){moving=value;h.render();},privacy(value){community.privacyPending=value;community.privacyKey+='x';h.render();},params(value){params=value;index=0;return component.default();},canonical(value){canonical=value;},pairPages(values){socialPages=values;},switch(userId){for(const c of cells){c?.cleanup?.();c?.remove?.();}cells=[];scope={userId,generation:scope.generation+1};session=userId?{user:{id:userId},access_token:`${userId}-${scope.generation}`}:null;h.render();},close(){closed=true;for(const c of cells){c?.cleanup?.();c?.remove?.();}}};return h;
}
const binding=p=>({post_id:p.post_id,owner_id:p.owner_id,content_revision:p.content_revision}),mediaBinding=p=>({...binding(p),media_id:p.media[0].media_id,sha256:p.media[0].sha256});

test('held feed reply and retained callbacks fail closed across batched background/resume before React',async()=>{const h=harness(),wait=h.hold('feed');h.render();await tick();const old=h.port;h.os('background');h.os('active');const before=h.calls.length;await assert.rejects(old.refresh(),/COMMUNITY_CHANGED/);assert.equal(h.calls.length,before);wait.resolve();await tick();assert.equal(h.render().page,null);await h.settle();assert.equal(h.port.read.fresh,true);h.close();});
test('detail parent/comments and private media authority are retired on blur and account ABA',async()=>{const h=harness('detail'),wait=h.hold('comments');h.render();await tick();assert.equal(h.calls.filter(c=>c.kind==='comments').length,1);const old=h.port;h.focus(false);wait.resolve();await h.settle();assert.equal(h.port.detail,null);h.focus(true);await h.settle();h.switch(peer);await h.settle();h.switch(owner);await h.settle();const before=h.calls.length;await assert.rejects(old.getMediaURL(mediaBinding(post())),/COMMUNITY_CHANGED/);await assert.rejects(old.refresh(),/COMMUNITY_CHANGED/);assert.equal(h.calls.length,before);h.close();});
test('strict post route rejects missing/array/extra/arbitrary params and guest constructors emit no request',async()=>{const h=harness('detail');for(const value of [{},{postId:[uuid(102)]},{postId:uuid(102),ownerId:owner},{postId:'arbitrary'}])assert.equal(h.params(value).type,'Screen');assert.equal(h.calls.length,0);h.switch(null);await h.settle();assert.equal(h.port.gate.signedIn,false);assert.equal(h.calls.length,0);h.close();});
test('pending privacy clears list and retires held signer before a cached URL can return',async()=>{const h=harness();h.render();await h.settle();const p=h.port,row=p.rows[0],wait=h.hold('signer'),pending=assert.rejects(p.getMediaURL(mediaBinding(row)),/COMMUNITY_CHANGED/);await tick();h.privacy(true);assert.equal(h.port.page,null);assert.equal(h.port.rows.length,0);assert.equal(h.port.postCurrent(binding(row)),false);wait.resolve();await pending;h.privacy(false);await h.settle();await h.port.getMediaURL(mediaBinding(h.port.rows[0]));assert.equal(h.calls.filter(c=>c.kind==='signer').length,2);h.close();});
test('foreign descriptors never reach signer and canonical trimmed route retains gaps without peers/GPS',async()=>{const h=harness();h.render();await h.settle();const row=h.port.rows[0];await assert.rejects(h.port.getMediaURL({...mediaBinding(row),sha256:'f'.repeat(64)}),/COMMUNITY_CHANGED/);assert.equal(h.calls.filter(c=>c.kind==='signer').length,0);h.port.onOpenRoute(binding(row));h.render();assert.equal(h.preview.post.route.segments.length,2);h.privacy(true);assert.equal(h.preview.post,null);h.close();});
test('held share preflight and mutation caller guard cannot dispatch after movement or focus retirement',async()=>{const h=harness();h.render();await h.settle();let p=h.port,row=p.rows[0],wait=h.hold('post'),task=assert.rejects(p.onShare(binding(row)),/COMMUNITY_MOVING/);await tick();h.move(true);wait.resolve();await task;assert.equal(h.shares.length,0);h.move(false);await h.settle();p=h.port;row=p.rows[0];wait=h.hold('mutation');task=assert.rejects(p.mutate({schema_version:1,action:'like',post_id:row.post_id,expected_revision:row.content_revision,liked:true}),/COMMUNITY_CHANGED/);await tick();h.focus(false);wait.resolve();await task;assert.equal(h.calls.filter(c=>c.kind==='write').length,0);h.close();});
test('block uses the exact genuinely read pair generation, never the loaded provider friend list',async()=>{const h=harness('detail');h.render();await h.settle();h.pairPages([{self:{profile_ready:true},items:[{user_id:peer,generation:8}],next_cursor:null}]);await h.port.blockAuthor(binding(h.port.detail.post));assert.equal(h.calls.at(-1).request.expected_generation,8);assert.equal(h.calls.at(-1).request.other_id,peer);h.close();});
test('block passes absent-pair null only after exhausted canonical pages; capped incomplete read writes nothing',async()=>{const h=harness('detail');h.render();await h.settle();h.pairPages([{self:{profile_ready:true},items:[],next_cursor:{updated_at:stamp,user_id:uuid(3)}},{self:{profile_ready:true},items:[],next_cursor:null}]);await h.port.blockAuthor(binding(h.port.detail.post));assert.equal(h.calls.at(-1).request.expected_generation,null);const before=h.calls.filter(c=>c.kind==='block').length;h.pairPages(Array.from({length:34},(_,i)=>({self:{profile_ready:true},items:[],next_cursor:{updated_at:stamp,user_id:uuid(i+10)}})));await assert.rejects(h.port.blockAuthor(binding(h.port.detail.post)),/COMMUNITY_UNAVAILABLE/);assert.equal(h.calls.filter(c=>c.kind==='block').length,before);h.close();});
test('held canonical pair response cannot block after lifecycle retirement',async()=>{const h=harness('detail');h.render();await h.settle();const wait=h.hold('pair'),task=assert.rejects(h.port.blockAuthor(binding(h.port.detail.post)),/COMMUNITY_CHANGED/);await tick();h.os('background');h.os('active');wait.resolve();await task;assert.equal(h.calls.some(c=>c.kind==='block'),false);h.close();});
test('post share contains only the canonical post UUID and a current revision is required',async()=>{const h=harness('detail');h.render();await h.settle();const row=h.port.detail.post;await h.port.onShare(binding(row));assert.equal(h.shares.length,1);assert.equal(h.shares[0].message,`ridespeed://community-post?postId=${row.post_id}`);h.canonical({...row,content_revision:2});await assert.rejects(h.port.onShare(binding(row)),/COMMUNITY_CHANGED/);assert.equal(h.shares.length,1);h.close();});
test('route selection cannot reopen after a movement/privacy boundary even when the same post becomes fresh again',async()=>{const h=harness();h.render();await h.settle();h.port.onOpenRoute(binding(h.port.rows[0]));h.render();assert.ok(h.preview.post);h.move(true);assert.equal(h.preview.post,null);h.move(false);await h.settle();assert.equal(h.preview.post,null);h.port.onOpenRoute(binding(h.port.rows[0]));h.render();assert.ok(h.preview.post);h.privacy(true);h.privacy(false);await h.settle();assert.equal(h.preview.post,null);h.close();});
test('guest has a usable sign-in callback without read or media authority',async()=>{const h=harness();h.switch(null);await h.settle();assert.equal(h.port.current(h.port.generation),true);h.port.onSignIn();assert.equal(h.navigation.at(-1),'/auth');assert.equal(h.calls.length,0);h.close();});
