import test from 'node:test';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
import {communityModule,owner,peer,uuid,stamp,hold} from './communityFixtures.mjs';
const row=(id=100,time='2026-10-01T09:00:00.000001+00:00')=>({post_id:uuid(id),content_revision:1,visibility:'friends',state:'published',updated_at:time});
const page=(items=[row()],next_cursor=null)=>({owner_id:owner,server_now:stamp,items,next_cursor});
test('strict owned metadata is bounded, immutable and rejects hidden content or foreign cursor authority',()=>{const m=communityModule('communityOwnerModel');const decoded=m.validateCommunityOwnerPage(page(),owner);assert.equal(Object.isFrozen(decoded.items[0]),true);for(const value of [page([{...row(),caption:'private'}]),page([{...row(),content_revision:0}]),page([{...row(),state:'draft'}]),{...page(),owner_id:peer},page([row(),row()]),page(Array.from({length:31},(_,i)=>row(i)))])assert.throws(()=>m.validateCommunityOwnerPage(value,owner),/COMMUNITY_INVALID_RESPONSE/);assert.throws(()=>m.validateCommunityOwnerCursor({owner_id:peer,updated_at:stamp,post_id:uuid(100)},owner),/COMMUNITY_INVALID_RESPONSE/);assert.equal(m.validateCommunityOwnerDetail({owner_id:owner,server_now:stamp,post:{...row(),state:'draft',content_revision:0}},owner,uuid(100)).post.state,'draft');});
test('owned keyset preserves microseconds and validates strict descending page progress',()=>{const m=communityModule('communityOwnerModel'),first=row(100,'2026-10-01T09:00:00.000002Z'),second=row(101);const cursor={owner_id:owner,updated_at:first.updated_at,post_id:first.post_id};assert.equal(m.validateCommunityOwnerPage(page([second]),owner,cursor).items.length,1);assert.throws(()=>m.validateCommunityOwnerPage(page([first]),owner,cursor),/COMMUNITY_INVALID_RESPONSE/);assert.throws(()=>m.validateCommunityOwnerPage(page([second,first]),owner),/COMMUNITY_INVALID_RESPONSE/);assert.throws(()=>m.validateCommunityOwnerPage(page([first],{...cursor,post_id:second.post_id}),owner),/COMMUNITY_INVALID_RESPONSE/);});
function sdk(){let current={userId:owner,generation:1},response=page(),wait=null;const scope=current,session={user:{id:owner},access_token:'captured-owner-A'},requests=[];const service=communityModule('communityOwnerService',{'../../state/AuthState':{isAccountCurrent:s=>s===current,accountClient:(_scope,captured)=>createClient('https://configured.test','publishable-test',{accessToken:async()=>captured.access_token,global:{fetch:async(input,init)=>{requests.push({path:new URL(String(input)).pathname,body:JSON.parse(init.body),token:new Headers(init.headers).get('authorization')});return new Response(JSON.stringify(wait?await wait.promise:response),{status:200,headers:{'content-type':'application/json'}});}}})}});return{service,scope,session,requests,response:v=>response=v,hold:()=>wait=hold(),aba(){current={userId:peer,generation:2};current={userId:owner,generation:3};}};}
test('actual SDK owner reads send captured JWT, bounded metadata selector and no content or caller owner',async()=>{const f=sdk();await f.service.getCommunityOwnerPosts(f.scope,f.session);assert.deepEqual(f.requests[0],{path:'/rest/v1/rpc/rs_community_owner_posts',body:{p_cursor:null,p_limit:20},token:'Bearer captured-owner-A'});f.response({owner_id:owner,server_now:stamp,post:{...row(),state:'hidden'}});assert.equal((await f.service.getCommunityOwnerPost(f.scope,f.session,uuid(100))).post.state,'hidden');assert.deepEqual(f.requests[1].body,{p_post_id:uuid(100)});const n=f.requests.length;await assert.rejects(f.service.getCommunityOwnerPosts(f.scope,f.session,null,31),/COMMUNITY_INVALID/);assert.equal(f.requests.length,n);});
test('held captured owner read rejects ABA and typed rate error preserves finite backoff',async()=>{const f=sdk(),w=f.hold(),task=f.service.getCommunityOwnerPosts(f.scope,f.session);await new Promise(r=>setImmediate(r));f.aba();w.resolve(page());await assert.rejects(task,/ACCOUNT_CHANGED/);const g=sdk();g.response({error:{code:'COMMUNITY_RATE_LIMITED',retry_after_ms:600}});await assert.rejects(g.service.getCommunityOwnerPosts(g.scope,g.session),e=>e.message==='COMMUNITY_RATE_LIMITED'&&e.retryAfterMs===600);});
function reader(){let active=true,now=1000,response=page(),held=null;const calls=[],m=communityModule('CommunityOwnerReader');const r=new m.CommunityOwnerReader({ownerId:owner,guard(){if(!active)throw Error('COMMUNITY_CHANGED');},monotonicNow:()=>now,page:async cursor=>{calls.push(['page',cursor]);if(response instanceof Error)throw response;return held?await held.promise:response;},detail:async id=>{calls.push(['detail',id]);return held?await held.promise:{owner_id:owner,server_now:stamp,post:row(Number(id.slice(-12)))};}});return{r,calls,response:v=>response=v,hold:()=>held=hold(),release(){held=null;},active:v=>active=v,now:v=>now=v};}
test('finite owner reader retires held page/detail and never exposes stale metadata as CAS authority',async()=>{const f=reader(),w=f.hold(),task=f.r.refresh();f.r.invalidate();w.resolve(page());await task;assert.equal(f.r.getSnapshot().rows.length,0);f.release();await f.r.refresh();await f.r.select(uuid(100));const selected=f.r.getSnapshot().detail.post;assert.equal(f.r.current(selected),true);f.r.suspend();assert.equal(f.r.current(selected),false);const n=f.calls.length;f.active(false);await assert.rejects(f.r.refresh(),/COMMUNITY_CHANGED/);assert.equal(f.calls.length,n);});
test('refresh supersedes a held append; bounded capacity and failures never become an empty success',async()=>{const f=reader();f.response(page([row(102)],{owner_id:owner,updated_at:row(102).updated_at,post_id:uuid(102)}));await f.r.refresh();const w=f.hold(),append=f.r.loadMore();f.release();f.response(page([row(200,'2026-10-01T09:30:00Z')]));await f.r.refresh();w.resolve(page([row(101)]));await append;assert.equal(f.r.getSnapshot().rows[0].post_id,uuid(200));f.response({...page(),owner_id:peer});await f.r.refresh();assert.equal(f.r.getSnapshot().read.fresh,false);assert.equal(f.r.getSnapshot().read.error,'COMMUNITY_INVALID_RESPONSE');assert.equal(f.r.getSnapshot().loaded,true);});
test('finite metadata capacity is explicit and no earlier owned setting is silently dropped',async()=>{const f=reader();for(let n=0;n<11;n++){const items=Array.from({length:30},(_,i)=>row(1000-n*30-i)),last=items.at(-1);f.response(page(items,{owner_id:owner,updated_at:last.updated_at,post_id:last.post_id}));if(n===0)await f.r.refresh();else await f.r.loadMore();}const state=f.r.getSnapshot();assert.equal(state.rows.length,300);assert.equal(state.rows[0].post_id,uuid(1000));assert.equal(state.read.fresh,false);assert.equal(state.read.error,'COMMUNITY_CAPACITY');});
test('typed owner-read rate backoff coalesces retries and getter network delay consumes current-CAS lifetime',async()=>{const f=reader(),error=Error('COMMUNITY_RATE_LIMITED');error.name='CommunityServiceError';error.retryAfterMs=600;f.response(error);await f.r.refresh();const n=f.calls.length;await Promise.all([f.r.refresh(),f.r.refresh()]);assert.equal(f.calls.length,n);f.now(1600);f.response(page());await f.r.refresh();assert.equal(f.r.getSnapshot().read.fresh,true);const w=f.hold(),task=f.r.select(uuid(100));f.now(16601);w.resolve({owner_id:owner,server_now:stamp,post:row()});await task;assert.equal(f.r.current(row()),false);});
