import test from 'node:test';import assert from 'node:assert/strict';import {communityModule,owner,uuid,stamp,document,hold} from './communityFixtures.mjs';
const {CommunityCoordinator}=communityModule('CommunityCoordinator');
const request=(post_id=uuid(200))=>({schema_version:1,action:'publish',post_id,expected_revision:0,document:document()});
const stored=(n=900,q=request())=>({owner_id:owner,operationId:uuid(n),request:q,queuedAt:stamp,lastError:null});
const ack=op=>({owner_id:owner,operation_id:op.operationId,request:op.request,applied_at:stamp,result:{kind:'post',post_id:op.request.post_id,content_revision:1,engagement_revision:1,state:'published',visibility:op.request.document.visibility}});
function fixture(initial=[]){let rows=initial,durable=false,active=true,current=true,failDisk=false,next=950,now=0;const calls=[],receipts=new Map();let sender=async op=>{const value=ack(op);receipts.set(op.operationId,value);return value;},apply=async value=>{calls.push(['applied',value.operation_id]);};const f={rows:()=>rows,calls,receipts,send:fn=>sender=fn,apply:fn=>apply=fn,disk:v=>failDisk=v,active:v=>active=v,retire:()=>current=false,now:v=>now=v};f.coordinator=new CommunityCoordinator({ownerId:owner,guard:()=>{if(!current)throw Error('ACCOUNT_CHANGED');},canSend:()=>active,read:()=>rows,update:async reduce=>{rows=reduce(rows);durable=false;if(failDisk)throw Error('LOCAL_WRITE_FAILED');},flush:async()=>{if(failDisk)throw Error('LOCAL_WRITE_FAILED');durable=true;},operationId:()=>uuid(next++),nowISO:()=>stamp,monotonicNow:()=>now,status:async op=>{assert.equal(durable,true);calls.push(['status',op.operationId]);return receipts.get(op.operationId)??null;},send:async op=>{assert.equal(durable,true);calls.push(['send',op.operationId]);return sender(op);},applied:value=>apply(value)});return f;}

test('failed durable draft settlement retains the outbox and does not announce an applied result',async()=>{const f=fixture([stored()]);f.receipts.set(uuid(900),ack(stored()));f.apply(async()=>{throw Error('LOCAL_WRITE_FAILED');});await f.coordinator.retry();assert.equal(f.rows().length,1);assert.equal(f.coordinator.getSnapshot().latest,null);f.apply(async value=>{f.calls.push(['applied',value.operation_id]);});await f.coordinator.retry();assert.equal(f.rows().length,0);assert.equal(f.coordinator.getSnapshot().latest.status,'applied');assert.equal(f.calls.some(x=>x[0]==='send'),false);});

test('a retired enqueue acceptance lease produces no new pending mutation or transport',async()=>{const f=fixture();let current=true;const task=f.coordinator.enqueue(request(),uuid(960),()=>{if(!current)throw Error('COMMUNITY_INACTIVE');});current=false;assert.equal(await task,null);assert.equal(f.rows().length,0);assert.equal(f.calls.length,0);});
test('publish is persisted before egress; exact receipt retires one operation without creating a local fake feed item',async()=>{const f=fixture();assert.equal(await f.coordinator.enqueue(request()),uuid(950));assert.deepEqual(f.calls.map(x=>x[0]),['status','send','applied']);assert.equal(f.rows().length,0);assert.equal(f.coordinator.getSnapshot().latest.status,'applied');});
test('ambiguous ACK/restart reuses the same exact operation and does not resend a known published post',async()=>{const f=fixture([stored()]);f.receipts.set(uuid(900),ack(stored()));await f.coordinator.retry();assert.deepEqual(f.calls.map(x=>x[0]),['status','applied']);assert.equal(f.rows().length,0);const live=fixture();live.send(async op=>{live.receipts.set(op.operationId,ack(op));throw Error('COMMUNITY_UNAVAILABLE');});await live.coordinator.enqueue(request());assert.equal(live.rows().length,0);assert.equal(live.calls.filter(x=>x[0]==='send').length,1);});
test('unknown publish blocks later audience/delete actions on that post while independent post may progress',async()=>{const same={schema_version:1,action:'delete_post',post_id:uuid(200),expected_revision:1},f=fixture([stored(900),stored(901,same),stored(902,request(uuid(300)))]);f.send(async op=>{if(op.request.post_id===uuid(200))throw Error('COMMUNITY_UNAVAILABLE');return ack(op);});await f.coordinator.retry();assert.deepEqual(f.rows().map(v=>v.operationId),[uuid(900),uuid(901)]);assert.deepEqual(f.calls.filter(x=>x[0]==='send').map(x=>x[1]),[uuid(900),uuid(902)]);});
test('rate deadline and definitive stale revision are reconciled with exact status before dropping anything',async()=>{const f=fixture([stored()]);f.send(async()=>({error:{code:'COMMUNITY_RATE_LIMITED',retry_after_ms:2000}}));await f.coordinator.retry();const count=f.calls.length;await f.coordinator.retry();assert.equal(f.calls.length,count);assert.equal(f.rows().length,1);f.now(2000);f.send(async()=>({error:{code:'COMMUNITY_REVISION_CONFLICT'}}));await f.coordinator.retry();assert.equal(f.rows().length,0);assert.equal(f.coordinator.getSnapshot().latest.status,'rejected');});
test('failed disk/ACK removal retains recovery metadata and retry uses canonical status only',async()=>{const f=fixture();f.disk(true);assert.equal(await f.coordinator.enqueue(request()),null);assert.equal(f.calls.length,0);f.disk(false);f.send(async op=>{f.receipts.set(op.operationId,ack(op));f.disk(true);return ack(op);});await f.coordinator.retry();assert.equal(f.rows().length,1);f.disk(false);await f.coordinator.retry();assert.equal(f.rows().length,0);assert.equal(f.calls.filter(x=>x[0]==='send').length,1);});
test('held owner reply cannot settle another account and background retry produces no transport',async()=>{const f=fixture([stored()]),wait=hold();f.send(()=>wait.promise);const task=f.coordinator.retry();await new Promise(done=>setImmediate(done));f.retire();wait.resolve(ack(stored()));await task;assert.equal(f.rows().length,1);assert.equal(f.calls.some(x=>x[0]==='applied'),false);const bg=fixture([stored()]);bg.active(false);await bg.coordinator.retry();assert.equal(bg.calls.length,0);});
