import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {communityModule,owner,peer,uuid,photo,stamp,hold} from './communityFixtures.mjs';

const controllerPath=new URL('../src/features/community/CommunityDraftController.ts',import.meta.url);
const emptyDocument=()=>({schema_version:1,caption:'',description:'',visibility:'friends',ride:null,route:null,include_ride_route:false,media_ids:[]});
const descriptor=()=>{const {media_id,validation,...value}=photo();return value;};
const copy=value=>JSON.parse(JSON.stringify(value));
function fixture(){
 assert.equal(existsSync(controllerPath),true,'The pure CommunityDraftController implementation must exist');
 const {CommunityDraftController}=communityModule('CommunityDraftController');
 let rows=[],disk=[],current=true,active=true,activity=1,serial=800,reservationState='reserved',queueFailure=false,flushFailure=false;
 const calls=[],waits=new Map(),pause=async point=>{if(waits.has(point))await waits.get(point).promise;};
 const port={ownerId:owner,guard(kind){if(!current)throw Error('ACCOUNT_CHANGED');if(kind!=='owner'&&!active)throw Error('COMMUNITY_INACTIVE');},activityVersion:()=>activity,read:()=>rows,
  async update(reduce){calls.push('update');await pause('write');rows=copy(reduce(rows));},async flush(){calls.push('flush');await pause('flush');if(flushFailure){flushFailure=false;throw Error('LOCAL_WRITE_FAILED');}disk=copy(rows);},operationId:()=>uuid(++serial),nowISO:()=>stamp,
  async reservePost(id){calls.push(['reservePost',id]);await pause('reservePost');return {owner_id:owner,post_id:id,revision:0,state:'draft'};},
  async reserveMedia(postId,mediaId){calls.push(['reserveMedia',postId,mediaId]);await pause('reserveMedia');return {post_id:postId,media_id:mediaId,bucket:'ride-post-media',path:`${owner}/${postId}/${mediaId}.jpg`,expires_at:'2026-09-30T10:00:00.000Z',state:reservationState};},
  async readPhoto(postId,mediaId,value){calls.push(['readPhoto',postId,mediaId]);await pause('readPhoto');return new Uint8Array(value.byte_count);},
  async upload(reservation,bytes,options){calls.push(['upload',copy(reservation),bytes.byteLength,copy(options)]);await pause('upload');},
  async commitMedia(postId,mediaId,value){calls.push(['commitMedia',postId,mediaId]);await pause('commitMedia');return {post_id:postId,media_id:mediaId,descriptor:{...value,blurhash:'LEHV6nWB2yk8pyo0adR*.7kCMdnj'}};},
  async attachmentReview(selection){calls.push(['attachments',copy(selection)]);await pause('attachments');return {owner_id:owner,server_now:stamp,ride:null,route:null};},
  async enqueue(request,operationId){calls.push(['enqueue',copy(request),operationId]);assert.equal(disk.find(d=>d.operationId===operationId)?.status,'pending','No publication egress before the frozen pending draft is durable');if(queueFailure){queueFailure=false;return null;}return operationId;}
 };
 const controller=new CommunityDraftController(port);
 return {controller,port,calls,get rows(){return rows;},get disk(){return disk;},seed(value){rows=copy(value);disk=copy(value);},hold(point){const wait=hold();waits.set(point,wait);return wait;},invalidate(){current=false;},activityABA(){active=false;activity++;active=true;activity++;},setActive(value){active=value;activity++;},committed(){reservationState='committed';},queueFails(){queueFailure=true;},flushFails(){flushFailure=true;}};
}
async function filled(f){const created=await f.controller.create();await f.controller.edit(created.draft_id,{...created.document,caption:'ทริปวันนี้'});return f.rows[0];}
async function withPhoto(f){const draft=await filled(f);await f.controller.setPhotos(draft.draft_id,[{media_id:photo().media_id,descriptor:descriptor()}]);return f.rows[0];}
function receipt(draft){return {owner_id:owner,operation_id:draft.operationId,request:{schema_version:1,action:'publish',post_id:draft.post_id,expected_revision:draft.post_revision,document:draft.document},applied_at:stamp,result:{kind:'post',post_id:draft.post_id,content_revision:1,engagement_revision:1,state:'published',visibility:draft.document.visibility}};}

test('a blank local draft is editable and durable but cannot be reviewed as a publication',async()=>{const f=fixture(),draft=await f.controller.create();assert.deepEqual(copy(draft.document),emptyDocument());assert.equal(f.disk.length,1);await assert.rejects(f.controller.review(draft.draft_id),/COMMUNITY_INVALID/);assert.equal(f.calls.some(v=>Array.isArray(v)&&v[0]==='reservePost'),false);await f.controller.edit(draft.draft_id,{...draft.document,caption:'เส้นทางของฉัน'});assert.equal(f.disk[0].revision,2);});
test('four drafts and six ordered photos are bounded; an existing media ID cannot change its bytes',async()=>{const f=fixture();for(let i=0;i<4;i++)await f.controller.create();await assert.rejects(f.controller.create(),/COMMUNITY_CAPACITY/);const id=f.rows[0].draft_id,photos=Array.from({length:6},(_,i)=>({media_id:uuid(10+i),descriptor:descriptor()}));await f.controller.setPhotos(id,photos);await assert.rejects(f.controller.setPhotos(id,[...photos,{media_id:uuid(16),descriptor:descriptor()}]),/COMMUNITY_CAPACITY/);await assert.rejects(f.controller.setPhotos(id,[{...photos[0],descriptor:{...descriptor(),sha256:'e'.repeat(64)}}]),/COMMUNITY_OPERATION_CONFLICT/);assert.deepEqual(f.rows[0].document.media_ids,photos.map(p=>p.media_id));});
test('review reserves and commits exact private bytes before using canonical attachments; committed replay skips local upload',async()=>{const f=fixture(),draft=await withPhoto(f),review=await f.controller.review(draft.draft_id);assert.equal(review.media[0].validation,'decoded_jpeg_v1');assert.equal(review.media[0].blurhash,'LEHV6nWB2yk8pyo0adR*.7kCMdnj');const upload=f.calls.find(v=>Array.isArray(v)&&v[0]==='upload');assert.deepEqual(upload[3],{contentType:'image/jpeg',upsert:false});assert.equal(upload[1].path,`${owner}/${draft.post_id}/${photo().media_id}.jpg`);assert.equal(f.disk[0].photos[0].commit.descriptor.sha256,descriptor().sha256);assert.equal(f.rows[0].status,'local');f.calls.length=0;f.committed();await f.controller.review(draft.draft_id);assert.equal(f.calls.some(v=>Array.isArray(v)&&['readPhoto','upload'].includes(v[0])),false);assert.equal(f.calls.some(v=>Array.isArray(v)&&v[0]==='commitMedia'),true);});
test('reordering preserves exact matching reservation and canonical commit without changing a photo identity',async()=>{const f=fixture(),draft=await filled(f),first={media_id:uuid(10),descriptor:descriptor()},second={media_id:uuid(11),descriptor:descriptor()};await f.controller.setPhotos(draft.draft_id,[first,second]);await f.controller.review(draft.draft_id);const prior=copy(f.rows[0].photos);await f.controller.setPhotos(draft.draft_id,[second,first]);assert.deepEqual(f.rows[0].photos[0],prior[1]);assert.deepEqual(f.rows[0].photos[1],prior[0]);});
test('held owner or background-to-foreground activity changes cannot produce a reusable review or start the next upload step',async()=>{for(const point of ['reservePost','reserveMedia','readPhoto','upload','commitMedia','attachments'])for(const change of ['invalidate','activityABA']){const f=fixture(),draft=await withPhoto(f),wait=f.hold(point),pending=f.controller.review(draft.draft_id);await new Promise(r=>setTimeout(r,0));f[change]();wait.resolve();await assert.rejects(pending,/ACCOUNT_CHANGED|COMMUNITY_REVIEW_REQUIRED/);assert.equal(f.calls.some(v=>Array.isArray(v)&&v[0]==='enqueue'),false);}});
test('an edit during held canonical attachment review retires the old document and consent token',async()=>{const f=fixture(),draft=await filled(f),wait=f.hold('attachments'),pending=f.controller.review(draft.draft_id);await new Promise(r=>setTimeout(r,0));await f.controller.edit(draft.draft_id,{...draft.document,caption:'ฉบับแก้ไข'});wait.resolve();await assert.rejects(pending,/COMMUNITY_CHANGED/);assert.equal(f.rows[0].document.caption,'ฉบับแก้ไข');assert.equal(f.rows[0].status,'local');});
test('publish requires the exact in-memory reviewed token and first flushes one immutable UUID and document',async()=>{const f=fixture(),draft=await filled(f),review=await f.controller.review(draft.draft_id);await assert.rejects(f.controller.publish(copy(review)),/COMMUNITY_REVIEW_REQUIRED/);const operationId=await f.controller.publish(review);assert.equal(operationId,f.rows[0].operationId);assert.equal(f.rows[0].status,'pending');const op=f.calls.find(v=>Array.isArray(v)&&v[0]==='enqueue');assert.deepEqual(op[1].document,copy(review.document));await assert.rejects(f.controller.edit(draft.draft_id,{...draft.document,caption:'late'}),/COMMUNITY_CHANGED/);});
test('an ambiguous queue failure retains pending reviewed contents and restart recreates only that identical operation',async()=>{const f=fixture(),draft=await filled(f),review=await f.controller.review(draft.draft_id);f.queueFails();await f.controller.publish(review);const pending=copy(f.rows[0]),first=f.calls.find(v=>Array.isArray(v)&&v[0]==='enqueue');const g=fixture();g.seed([pending]);await g.controller.retryPending();const recovered=g.calls.find(v=>Array.isArray(v)&&v[0]==='enqueue');assert.deepEqual(recovered.slice(1),first.slice(1));assert.equal(g.calls.some(v=>Array.isArray(v)&&['reservePost','attachments','upload'].includes(v[0])),false);});
test('a failed pending flush cannot send; recovery flushes before recreating the same operation',async()=>{const f=fixture(),draft=await filled(f),review=await f.controller.review(draft.draft_id);f.flushFails();await assert.rejects(f.controller.publish(review),/LOCAL_WRITE_FAILED/);assert.equal(f.calls.some(v=>Array.isArray(v)&&v[0]==='enqueue'),false);assert.equal(f.rows[0].status,'pending');await f.controller.retryPending(draft.draft_id);assert.equal(f.calls.filter(v=>Array.isArray(v)&&v[0]==='enqueue').length,1);});
test('canonical ACK settles only matching owner and frozen request, even if the composer is not foreground',async()=>{const f=fixture(),draft=await filled(f),review=await f.controller.review(draft.draft_id);await f.controller.publish(review);const pending=f.rows[0],ack=receipt(pending);const wrong=copy(ack);wrong.request.document.caption='wrong';await assert.rejects(f.controller.applied(wrong),/COMMUNITY_INVALID_RESPONSE/);f.setActive(false);await f.controller.applied(ack);assert.equal(f.disk[0].status,'published');assert.equal(f.disk[0].post_revision,1);const foreign=copy(ack);foreign.owner_id=peer;await assert.rejects(f.controller.applied(foreign),/COMMUNITY_INVALID_RESPONSE/);});
test('definite rejection unlocks for new review; ambiguous outcomes retain pending publication',async()=>{const f=fixture(),draft=await filled(f);await f.controller.publish(await f.controller.review(draft.draft_id));const id=f.rows[0].operationId;await f.controller.rejected(id,'COMMUNITY_UNAVAILABLE');assert.equal(f.rows[0].status,'pending');await f.controller.rejected(id,'COMMUNITY_SOURCE_CHANGED');assert.equal(f.rows[0].status,'local');assert.equal(f.rows[0].operationId,null);assert.equal(f.rows[0].error,'COMMUNITY_SOURCE_CHANGED');});
test('closed or obsolete owners cannot enqueue pending recovery or settle a retained receipt',async()=>{const f=fixture(),draft=await filled(f);await f.controller.publish(await f.controller.review(draft.draft_id));const ack=receipt(f.rows[0]),count=f.calls.length;f.controller.close();await assert.rejects(f.controller.retryPending(),/ACCOUNT_CHANGED/);await assert.rejects(f.controller.applied(ack),/ACCOUNT_CHANGED/);assert.equal(f.calls.length,count);});
test('an immutable upload conflict or lost ACK can reconcile canonical commit without an overwrite',async()=>{const f=fixture(),draft=await withPhoto(f);f.port.upload=async(reservation,bytes,options)=>{f.calls.push(['upload',copy(reservation),bytes.byteLength,copy(options)]);throw Error('object already exists');};const review=await f.controller.review(draft.draft_id);assert.equal(review.media[0].validation,'decoded_jpeg_v1');assert.equal(f.calls.filter(v=>Array.isArray(v)&&v[0]==='upload').length,1);assert.equal(f.calls.find(v=>Array.isArray(v)&&v[0]==='upload')[3].upsert,false);});
test('canonical commit cannot change bytes or manufacture a decoded media proof from a malformed descriptor',async()=>{const f=fixture(),draft=await withPhoto(f);f.port.commitMedia=async(postId,mediaId,value)=>({post_id:postId,media_id:mediaId,descriptor:{...value,sha256:'f'.repeat(64)}});await assert.rejects(f.controller.review(draft.draft_id),/COMMUNITY_INVALID_RESPONSE/);assert.equal(f.rows[0].photos[0].commit,null);assert.equal(f.rows[0].status,'local');});

test('restart of interrupted preparing draft resumes canonical checks and never restores prior consent',async()=>{const f=fixture(),draft=await withPhoto(f),oldReview=await f.controller.review(draft.draft_id),saved=copy(f.disk[0]);saved.status='preparing';const g=fixture();g.seed([saved]);g.committed();await assert.rejects(g.controller.publish(oldReview),/COMMUNITY_REVIEW_REQUIRED/);const reviewed=await g.controller.review(draft.draft_id);assert.equal(reviewed.draft_id,draft.draft_id);assert.equal(g.disk[0].status,'local');assert.equal(g.calls.some(v=>Array.isArray(v)&&['upload','enqueue'].includes(v[0])),false);assert.equal(g.calls.some(v=>Array.isArray(v)&&v[0]==='attachments'),true);});
test('a ready review is retired by activity ABA or by preparing a newer review of the same document',async()=>{for(const mode of ['activity','review']){const f=fixture(),draft=await filled(f),old=await f.controller.review(draft.draft_id);if(mode==='activity')f.activityABA();else await f.controller.review(draft.draft_id);await assert.rejects(f.controller.publish(old),/COMMUNITY_REVIEW_REQUIRED/);assert.equal(f.calls.some(v=>Array.isArray(v)&&v[0]==='enqueue'),false);}});
test('raw port failures become bounded errors and an inactive scope is fenced before parsing a stale server reply',async()=>{const f=fixture(),draft=await filled(f);f.port.reservePost=async()=>{throw Error('database credential or raw provider detail');};await assert.rejects(f.controller.review(draft.draft_id),e=>e.message==='COMMUNITY_UNAVAILABLE');const g=fixture(),second=await filled(g),wait=g.hold('reservePost');g.port.reservePost=async()=>{await wait.promise;return {unexpected:'stale'};};const pending=g.controller.review(second.draft_id);await new Promise(r=>setTimeout(r,0));g.invalidate();wait.resolve();await assert.rejects(pending,e=>e.message==='ACCOUNT_CHANGED');});
test('canonical preparation rechecks the reducer fresh row even if a read snapshot lags a concurrent content edit',async()=>{const f=fixture(),draft=await filled(f);f.port.attachmentReview=async()=>{const old=copy(f.rows),fresh=copy(f.rows);fresh[0].revision++;fresh[0].document.caption='new authoritative edit';fresh[0].status='local';f.seed(fresh);f.port.read=()=>old;return {owner_id:owner,server_now:stamp,ride:null,route:null};};await assert.rejects(f.controller.review(draft.draft_id),/COMMUNITY_CHANGED/);assert.equal(f.disk[0].document.caption,'new authoritative edit');assert.equal(f.disk[0].revision,draft.revision+1);});
test('two concurrent publish callbacks can enqueue only one reviewed frozen operation',async()=>{const f=fixture(),draft=await filled(f),review=await f.controller.review(draft.draft_id);const outcomes=await Promise.allSettled([f.controller.publish(review),f.controller.publish(review)]);assert.equal(outcomes.filter(v=>v.status==='fulfilled').length,1);assert.equal(f.calls.filter(v=>Array.isArray(v)&&v[0]==='enqueue').length,1);});
test('an owner change during held durable reduction rejects before changing owner metadata or flushing',async()=>{const f=fixture(),draft=await filled(f),wait=f.hold('write'),pending=f.controller.edit(draft.draft_id,{...draft.document,caption:'late owner edit'});await new Promise(r=>setTimeout(r,0));f.invalidate();wait.resolve();await assert.rejects(pending,/ACCOUNT_CHANGED/);assert.equal(f.disk[0].document.caption,'ทริปวันนี้');});
