import test from 'node:test';import assert from 'node:assert/strict';
import {communityModule,owner,peer,post,page,filter,hold,uuid,stamp,comment} from './communityFixtures.mjs';
const {CommunityReader,CommunityDetailReader}=communityModule('CommunityReader'),tick=()=>new Promise(r=>setImmediate(r)),plain=value=>JSON.parse(JSON.stringify(value));
const binding=value=>({post_id:value.post_id,owner_id:value.owner_id,content_revision:value.content_revision});
function feedPage(start=0,count=1,more=false,selected=filter()){
 const value=page();value.filter=selected;value.items=Array.from({length:count},(_,i)=>({...post(start+i+2),created_at:new Date(Date.parse('2026-10-01T09:00:00Z')-(start+i)*1000).toISOString(),updated_at:stamp}));
 if(more){const last=value.items.at(-1);value.next_cursor={owner_id:owner,mode:selected.mode,feed_revision:value.feed_revision,...{starts_at:value.window.starts_at,ends_at:value.window.ends_at,as_of:value.window.as_of},after:{created_at:last.created_at,post_id:last.post_id,week_score:last.week_score}};}return value;
}
function setup(){let current=true,now=1000,reply=feedPage(),wait=null,error=null;const calls=[];
 const reader=new CommunityReader({ownerId:owner,guard(){if(!current)throw Error('ACCOUNT_CHANGED');},monotonicNow:()=>now,async page(selected,cursor){calls.push({filter:selected,cursor});const captured=plain({...reply,filter:selected}),held=wait,failed=error;wait=null;if(held)await held.promise;if(failed)throw failed;return captured;}});
 return{reader,calls,response:v=>reply=v,fail:v=>error=v,hold(){return wait=hold();},retire(){current=false;},resume(){current=true;},advance:ms=>now+=ms};
}
test('reader construction has no I/O, failures stay unread, only successful empty page is authoritative',async()=>{const h=setup();assert.equal(h.calls.length,0);h.fail(Error('raw backend body secret=do-not-display'));await h.reader.refresh();assert.equal(h.reader.getSnapshot().loaded,false);assert.equal(h.reader.getSnapshot().page,null);assert.equal(h.reader.getSnapshot().read.error,'COMMUNITY_UNAVAILABLE');h.fail(null);h.response(feedPage(0,0));await h.reader.refresh();assert.equal(h.reader.getSnapshot().loaded,true);assert.equal(h.reader.getSnapshot().read.fresh,true);assert.equal(h.reader.getSnapshot().rows.length,0);});
test('current source is exact immutable canonical row, denied during failed/refresh/suspended authority',async()=>{const h=setup();await h.reader.refresh();const row=h.reader.getSnapshot().rows[0],key=binding(row);assert.equal(h.reader.current(key),true);assert.equal(Object.isFrozen(h.reader.sourcePost(key)),true);assert.equal(h.reader.sourcePost({...key,owner_id:owner}),null);assert.equal(h.reader.current({...key,content_revision:2}),false);const wait=h.hold(),task=h.reader.refresh();assert.equal(h.reader.current(key),false);wait.resolve();await task;h.reader.suspend();assert.equal(h.reader.getSnapshot().rows.length,1);assert.equal(h.reader.getSnapshot().read.fresh,false);assert.equal(h.reader.sourcePost(key),null);});
test('filter/privacy invalidation retire held page and old owner response without error adoption',async()=>{const h=setup(),wait=h.hold(),old=h.reader.refresh();await tick();await h.reader.setFilter({schema_version:1,mode:'friends'});wait.resolve();await old;assert.equal(h.reader.getSnapshot().page.filter.mode,'friends');const held=h.hold(),fresh=h.reader.refresh();await tick();h.retire();h.reader.invalidate();held.resolve();await fresh;assert.equal(h.reader.getSnapshot().page,null);assert.equal(h.reader.getSnapshot().rows.length,0);assert.equal(h.reader.getSnapshot().read.loading,false);const n=h.calls.length;await assert.rejects(h.reader.refresh(),/ACCOUNT_CHANGED/);assert.equal(h.calls.length,n);});
test('finite same-lane reads coalesce but fresh refresh supersedes held append and never mixes feed versions',async()=>{const h=setup();h.response(feedPage(0,1,true));await h.reader.refresh();h.response(feedPage(1,1));const wait=h.hold(),more=h.reader.loadMore();assert.equal(h.reader.loadMore(),more);await tick();h.response(feedPage(20,1));const refresh=h.reader.refresh();assert.equal(h.reader.refresh(),refresh);await refresh;wait.resolve();await more;assert.equal(h.reader.getSnapshot().rows[0].post_id,post(22).post_id);assert.equal(h.reader.getSnapshot().rows.length,1);});
test('changed opaque cursor triggers at most one fresh first page and drops obsolete source authority',async()=>{const h=setup();h.response(feedPage(0,1,true));await h.reader.refresh();h.fail(Error('COMMUNITY_CHANGED'));await h.reader.loadMore();assert.equal(h.calls.length,3);assert.equal(h.calls.at(-1).cursor,null);assert.equal(h.reader.getSnapshot().page,null);assert.equal(h.reader.getSnapshot().rows.length,0);assert.equal(h.reader.getSnapshot().read.fresh,false);});
test('only typed bounded rate error supplies shared monotonic backoff; invalidation cannot reset it',async()=>{const h=setup();h.fail(Object.assign(Error('COMMUNITY_RATE_LIMITED'),{name:'CommunityServiceError',retryAfterMs:5000}));await h.reader.refresh();assert.equal(h.reader.getSnapshot().retryAfterMs,5000);h.reader.invalidate();const count=h.calls.length;await h.reader.refresh();await h.reader.loadMore();assert.equal(h.calls.length,count);h.advance(4999);await h.reader.refresh();assert.equal(h.calls.length,count);h.advance(1);h.fail(null);await h.reader.refresh();assert.equal(h.calls.length,count+1);assert.equal(h.reader.getSnapshot().retryAfterMs,null);});
test('strict owner/filter/geometry decoder and 300 bound fail honestly without clipping or authorizing cached media',async()=>{const h=setup();const bad=feedPage();bad.owner_id=peer;h.response(bad);await h.reader.refresh();assert.equal(h.reader.getSnapshot().read.error,'COMMUNITY_INVALID_RESPONSE');h.response(feedPage(0,30,true));await h.reader.refresh();for(let start=30;start<300;start+=30){h.response(feedPage(start,30,true));await h.reader.loadMore();}assert.equal(h.reader.getSnapshot().rows.length,300);h.response(feedPage(300,1));await h.reader.loadMore();assert.equal(h.reader.getSnapshot().rows.length,300);assert.equal(h.reader.getSnapshot().read.error,'COMMUNITY_CAPACITY');assert.equal(h.reader.current(binding(h.reader.getSnapshot().rows[0])),false);});
function detailSetup(){let current=true,now=0,detail=post(),detailWait=null,commentsWait=null,error=null,commentsError=null,commentRows=[comment()],commentCursor=null,commentRevision=1;const calls=[];
 const reader=new CommunityDetailReader({ownerId:owner,guard(){if(!current)throw Error('ACCOUNT_CHANGED');},monotonicNow:()=>now,async detail(id){calls.push({kind:'detail',id});const held=detailWait,captured={owner_id:owner,server_now:stamp,post:plain(detail)},failed=error;detailWait=null;if(held)await held.promise;if(failed)throw failed;return captured;},async comments(id,cursor){calls.push({kind:'comments',id,cursor});const held=commentsWait,captured={owner_id:owner,server_now:stamp,post_id:id,content_revision:commentRevision,items:plain(commentRows).map(row=>({...row,post_id:id})),next_cursor:commentCursor},failed=commentsError;commentsWait=null;if(held)await held.promise;if(failed)throw failed;return captured;}});
 return{reader,calls,post(value){detail=value;commentRevision=value.content_revision;},comments(rows,cursor=null){commentRows=rows;commentCursor=cursor;},revision(value){commentRevision=value;},holdDetail(){return detailWait=hold();},holdComments(){return commentsWait=hold();},fail(value){error=value;},failComments(value){commentsError=value;},retire(){current=false;},advance(ms){now+=ms;}};
}
test('detail starts without I/O; failed parent cannot start child reads or fabricate comments absence',async()=>{const h=detailSetup();assert.equal(h.calls.length,0);h.fail(Error('COMMUNITY_UNAVAILABLE'));await h.reader.select(post().post_id);assert.equal(h.calls.length,1);assert.equal(h.reader.getSnapshot().loaded,false);assert.equal(h.reader.getSnapshot().commentsLoaded,false);assert.equal(h.reader.getSnapshot().commentsRead.fresh,false);h.fail(null);h.comments([]);await h.reader.refresh();assert.equal(h.reader.getSnapshot().commentsLoaded,true);assert.equal(h.reader.getSnapshot().commentsRead.fresh,true);});
test('changed selected post retires old parent and child replies and exact current row is required',async()=>{const h=detailSetup(),wait=h.holdDetail(),old=h.reader.select(post().post_id);await tick();h.post(post(3));await h.reader.select(post(3).post_id);wait.resolve();await old;assert.equal(h.reader.getSnapshot().detail.post.post_id,post(3).post_id);assert.equal(h.reader.current(binding(post())),false);const held=h.holdComments(),task=h.reader.refresh();await tick();h.reader.invalidate();held.resolve();await task;assert.equal(h.reader.getSnapshot().detail,null);assert.equal(h.reader.getSnapshot().comments.length,0);assert.equal(h.reader.current(binding(post(3))),false);});
test('parent revision change retires held append; comments with another revision cannot authorize current detail',async()=>{const h=detailSetup(),first=comment();h.comments([first],{created_at:first.created_at,id:first.comment_id});await h.reader.select(post().post_id);const wait=h.holdComments();h.comments([{...first,comment_id:uuid(91),created_at:'2026-10-01T09:11:00Z'}]);const append=h.reader.loadMoreComments();await tick();h.post({...post(),content_revision:2});h.comments([]);await h.reader.refresh();wait.resolve();await append;assert.equal(h.reader.getSnapshot().detail.post.content_revision,2);assert.equal(h.reader.getSnapshot().comments.length,0);h.revision(3);await h.reader.refresh();assert.equal(h.reader.getSnapshot().read.fresh,false);assert.equal(h.reader.getSnapshot().commentsRead.error,'COMMUNITY_CHANGED');assert.equal(h.reader.current(binding({...post(),content_revision:2})),false);});
test('detail suspension/closure clears all child/private authority even when guard is already inactive',async()=>{const h=detailSetup();await h.reader.select(post().post_id);const wait=h.holdComments(),task=h.reader.refresh();await tick();h.retire();h.reader.suspend();wait.resolve();await task;assert.equal(h.reader.getSnapshot().detail,null);assert.equal(h.reader.getSnapshot().comments.length,0);assert.equal(h.reader.getSnapshot().commentsRead.loading,false);h.reader.close();await assert.rejects(h.reader.select(post().post_id),/COMMUNITY_CHANGED/);});
test('same owner after a retired generation cannot receive its earlier held feed or dispatch queued obsolete ports',async()=>{const h=setup(),wait=h.hold(),old=h.reader.refresh();await tick();h.retire();h.reader.invalidate();h.resume();h.response(feedPage(20,1));await h.reader.refresh();wait.resolve();await old;assert.equal(h.reader.getSnapshot().rows[0].post_id,post(22).post_id);const before=h.calls.length,queued=h.reader.refresh();h.reader.close();await queued;assert.equal(h.calls.length,before);assert.equal(h.reader.getSnapshot().rows.length,0);});
test('detail and comment lanes coalesce; comment rate error gates every lane until conservative delay expires',async()=>{const h=detailSetup();h.failComments(Object.assign(Error('COMMUNITY_RATE_LIMITED'),{name:'CommunityServiceError',retryAfterMs:5000}));const wait=h.holdDetail(),task=h.reader.select(post().post_id);await tick();const same=h.reader.refresh();assert.equal(h.reader.refresh(),same);wait.resolve();await Promise.all([task,same]);assert.equal(h.calls.filter(v=>v.kind==='detail').length,1);assert.equal(h.reader.getSnapshot().commentsLoaded,false);assert.equal(h.reader.getSnapshot().commentsRead.error,'COMMUNITY_RATE_LIMITED');const before=h.calls.length;await h.reader.refresh();await h.reader.loadMoreComments();assert.equal(h.calls.length,before);h.advance(5000);h.failComments(null);await h.reader.refresh();assert.equal(h.reader.getSnapshot().commentsRead.fresh,true);});
test('300 accumulated comments stay intact with a visible capacity error instead of silently dropping a child row',async()=>{const h=detailSetup(),rows=(start,count)=>Array.from({length:count},(_,i)=>({...comment(),comment_id:uuid(500+start+i),created_at:new Date(Date.parse('2026-10-01T09:10:00Z')+(start+i)*1000).toISOString()}));let values=rows(0,30),last=values.at(-1);h.comments(values,{created_at:last.created_at,id:last.comment_id});await h.reader.select(post().post_id);for(let start=30;start<300;start+=30){values=rows(start,30);last=values.at(-1);h.comments(values,{created_at:last.created_at,id:last.comment_id});await h.reader.loadMoreComments();}assert.equal(h.reader.getSnapshot().comments.length,300);h.comments(rows(300,1));await h.reader.loadMoreComments();assert.equal(h.reader.getSnapshot().comments.length,300);assert.equal(h.reader.getSnapshot().commentsRead.error,'COMMUNITY_CAPACITY');assert.equal(h.reader.getSnapshot().commentsRead.fresh,false);});
