import test from 'node:test';import assert from 'node:assert/strict';import {communityModule,uuid} from './communityFixtures.mjs';
const model=communityModule('content');
test('150 Unicode codepoints accepts emoji without imposing the UTF16 input limit',()=>{assert.equal(model.codepointCount('🏍️'),2);assert.equal(model.validateCaption('🚗'.repeat(150)),true);assert.equal(model.validateCaption('🚗'.repeat(151)),false);assert.equal(model.validateCaption('ก'.repeat(150)),true);});
test('Thai vowel/tone sequences are preserved literally and malformed surrogates are rejected',()=>{const text='เส้นทางนี้สวยมาก วิ่งด้วยกันอย่างปลอดภัย';assert.equal(model.validateCaption(text),true);assert.equal(model.validateCaption('\ud83d'),false);assert.equal(model.validateCaption('a\u0000b'),false);assert.equal(model.validateDescription('คำอธิบาย\nเพิ่มอีกบรรทัด'),true);});
test('legacy280 captions remain readable without permitting a new oversized publication',()=>{const old='ก'.repeat(280);assert.equal(model.readableCaption(old,0),true);assert.equal(model.readableCaption(old,1),false);assert.equal(model.readableCaption('ก'.repeat(281),0),false);assert.equal(model.validateCaption(old),false);});
test('a manifest preserves six distinct image IDs and rejects duplicates or a seventh',()=>{const ids=Array.from({length:6},(_,i)=>uuid(i+10));assert.equal(model.validMediaIds(ids),true);assert.equal(model.validMediaIds([...ids,uuid(50)]),false);assert.equal(model.validMediaIds([ids[0],ids[0]]),false);assert.equal(model.validMediaIds(['https://image.invalid/photo.jpg']),false);});
test('image compression planning keeps both edges within1600 while retaining aspect ratio',()=>{assert.deepEqual(JSON.parse(JSON.stringify(model.outputSize(4000,3000))),{width:1600,height:1200});assert.deepEqual(JSON.parse(JSON.stringify(model.outputSize(3000,4000))),{width:1200,height:1600});assert.deepEqual(JSON.parse(JSON.stringify(model.outputSize(900,400))),{width:900,height:400});assert.throws(()=>model.outputSize(50000,50000),/COMMUNITY_PHOTO_TOO_LARGE/);assert.throws(()=>model.outputSize(0,100),/COMMUNITY_PHOTO_INVALID/);});
test('images require a real digest/bytes/dimensions while unsupported placeholder generation stays null',()=>{assert.equal(model.validPhotoDescriptor({mime:'image/jpeg',sha256:'a'.repeat(64),byte_count:1048576,width:1600,height:1600,blurhash:null}),true);assert.equal(model.validPhotoDescriptor({mime:'image/jpeg',sha256:'a'.repeat(64),byte_count:1048577,width:1600,height:1600,blurhash:null}),false);assert.equal(model.validPhotoDescriptor({mime:'image/png',sha256:'a'.repeat(64),byte_count:20,width:1600,height:1600,blurhash:null}),false);assert.equal(model.validPhotoDescriptor({mime:'image/jpeg',sha256:'not-a-hash',byte_count:20,width:1600,height:1600,blurhash:'fake'}),false);});
test('post content must contain a real attachment/photo or non-whitespace text',()=>{assert.equal(model.hasPublicationContent({caption:' \n',description:'',media_ids:[],ride:null,route:null}),false);assert.equal(model.hasPublicationContent({caption:'',description:'',media_ids:[uuid(10)],ride:null,route:null}),true);assert.equal(model.hasPublicationContent({caption:'',description:'',media_ids:[],ride:{ride_id:uuid(8),ride_revision:1},route:null}),true);});
