import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {indexedDB} from 'fake-indexeddb';
import {communityModule,owner,peer,uuid,hold} from './communityFixtures.mjs';
const {CommunityPhotoStore}=communityModule('CommunityPhotoStore');
const digest=async bytes=>createHash('sha256').update(bytes).digest('hex'),key={post_id:uuid(100),media_id:uuid(200)},bytes=Uint8Array.from([255,216,1,2,3,255,217]),descriptor={mime:'image/jpeg',sha256:await digest(bytes),byte_count:bytes.length,width:10,height:10,blurhash:null};
function fixture(){let current={userId:owner,generation:1},held=null;const rows=new Map(),events=[],token=(o,k)=>`${o}/${k.post_id}/${k.media_id}`;const disk={async read(o,k){return rows.get(token(o,k))??null;},async list(o){return [...rows.keys()].filter(k=>k.startsWith(o+'/')).map(k=>({post_id:k.split('/')[1],media_id:k.split('/')[2]}));},async writeNew(o,k,v){events.push(['write',o]);if(held)await held.promise;if(rows.has(token(o,k)))throw Error('exists');rows.set(token(o,k),Uint8Array.from(v));},async remove(o,k){rows.delete(token(o,k));},async removeOwner(o){events.push(['remove',o]);for(const k of [...rows.keys()])if(k.startsWith(o+'/'))rows.delete(k);}};const store=new CommunityPhotoStore({current:s=>s===current,disk,sha256:digest});return{store,rows,events,get scope(){return current;},hold:()=>held=hold(),switch:()=>current={userId:peer,generation:2}};}
test('private exact bytes survive restart/replay and a reused media key cannot replace them',async()=>{const f=fixture();await f.store.put(f.scope,key,bytes,descriptor);await f.store.put(f.scope,key,bytes,descriptor);assert.equal(f.events.length,1);assert.deepEqual(await f.store.read(f.scope,key,descriptor),bytes);const edited=Uint8Array.from([1,2,3]),next={...descriptor,sha256:await digest(edited),byte_count:3};await assert.rejects(f.store.put(f.scope,key,edited,next),/COMMUNITY_PHOTO_INVALID/);assert.deepEqual(await f.store.read(f.scope,key,descriptor),bytes);});
test('copied input/digest and owner generation protect private bytes across asynchronous writes',async()=>{const f=fixture(),source=Uint8Array.from(bytes),scope=f.scope,wait=f.hold(),task=f.store.put(scope,key,source,descriptor);source[2]=99;await new Promise(done=>setImmediate(done));f.switch();wait.resolve();await assert.rejects(task,/ACCOUNT_CHANGED/);await assert.rejects(f.store.read(scope,key,descriptor),/ACCOUNT_CHANGED/);assert.deepEqual([...f.rows.values()][0],bytes);assert.equal(f.events[0][1],owner);});
test('confirmed closure drains held writes, removes only that owner and cannot reopen',async()=>{const f=fixture(),scope=f.scope,wait=f.hold(),task=f.store.put(scope,key,bytes,descriptor);await new Promise(done=>setImmediate(done));const close=f.store.closeOwner(scope);wait.resolve();await assert.rejects(task,/ACCOUNT_CHANGED/);await close;assert.equal(f.rows.size,0);assert.deepEqual(f.events.map(e=>e[0]),['write','remove']);await assert.rejects(f.store.put(scope,key,bytes,descriptor),/ACCOUNT_CHANGED/);});
test('24-photo cap includes orphaned immutable slots and digest failure never issues a write',async()=>{const f=fixture();for(let n=0;n<24;n++)await f.store.put(f.scope,{post_id:uuid(100+n),media_id:uuid(200+n)},bytes,descriptor);await assert.rejects(f.store.put(f.scope,{post_id:uuid(500),media_id:uuid(600)},bytes,descriptor),/COMMUNITY_CAPACITY/);assert.equal(f.rows.size,24);const bad=fixture();await assert.rejects(bad.store.put(bad.scope,key,bytes,{...descriptor,sha256:'a'.repeat(64)}),/COMMUNITY_PHOTO_INVALID/);assert.equal(bad.events.length,0);});
test('actual IndexedDB adapter uses immutable owner/post/media keys and closure leaves another owner intact',async()=>{const {communityPhotoDisk:disk}=communityModule('photoDisk.web',{}, {indexedDB});await disk.writeNew(owner,key,bytes);await disk.writeNew(peer,key,bytes);await assert.rejects(disk.writeNew(owner,key,bytes),/LOCAL_WRITE_FAILED/);assert.deepEqual(await disk.read(owner,key),bytes);assert.equal((await disk.list(owner)).length,1);await disk.removeOwner(owner);assert.equal(await disk.read(owner,key),null);assert.deepEqual(await disk.read(peer,key),bytes);await disk.removeOwner(peer);});
