import test from 'node:test';import assert from 'node:assert/strict';import {communityModule,owner,post} from './communityFixtures.mjs';
function fixture(){let cells=[],cursor=0,epoch=1,active=true,allowed=true,tree;const same=(a,b)=>a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i])),hooks={useRef:value=>{const n=cursor++;return cells[n]??={current:value};},useMemo:(fn,deps)=>{const n=cursor++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;},useState:initial=>{const n=cursor++;cells[n]??={value:initial};return[cells[n].value,value=>cells[n].value=typeof value==='function'?value(cells[n].value):value];},useLayoutEffect:fn=>{cursor++;fn();},useEffect:fn=>{cursor++;fn();}};
 const jsx=(type,props)=>({type,props}),row=post(),port={generation:'A1',current:g=>allowed&&g===port.generation,postCurrent:b=>allowed&&b.post_id===row.post_id&&b.content_revision===row.content_revision,gate:{moving:false,online:true}},props={post:row,port,t:key=>key,onClose(){}};
 const component=communityModule('CommunityRoutePreview',{react:hooks,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'react-native':{View:'View',ActivityIndicator:'Loading'},'../../components/ui':{Button:'Button',Note:'Note',Row:'Row',T:'T'},'../../lib/i18n':{useI18n:()=>({language:'th'})},'../../lib/useScreenActivity':{useScreenActivity:()=>({active,capture:()=>active?epoch:null,accepts:value=>active&&value===epoch})},'../../state/AppState':{useApp:()=>({colors:{accent:'#FF5A1F',bg:'#000'},dark:true,motion:false})},'../map/ActiveMapSurface':{__esModule:true,default:'MapSurface'},'../routes/RouteSheet':{RouteSheet:'Sheet'},'../routes/RoutingAttribution':{RoutingAttribution:'Credit'}}).CommunityRoutePreview;
 const h={props,render(){cursor=0;tree=component(props);return tree;},os(){epoch++;},blocked(){allowed=false;},moving(){port.gate.moving=true;},find(type){const results=[];function walk(v){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(walk);return;}if(v.type===type)results.push(v);if(v.props)walk(v.props.children);}walk(tree);return results;}};return h;
}
test('actual route preview maps only canonical trimmed fragments, never joins gaps or adds rider/private pins',()=>{const h=fixture();h.render();const map=h.find('MapSurface')[0].props;assert.equal(map.track.segments.length,2);assert.equal(map.track.segments[0].at(-1).longitude,100.51);assert.equal(map.track.segments[1][0].longitude,100.55);assert.equal(map.peers.length,0);assert.equal(map.pins.length,0);assert.equal(map.userFix,null);assert.equal(map.mode,'browse');assert.equal(map.locale,'th');assert.equal(map.theme,'dark');});
test('hidden/legacy/moving/blocked geometry has no active renderer and cannot fabricate a route',()=>{for(const policy of ['hidden','legacy','moving','blocked']){const h=fixture();if(policy==='hidden')h.props.post={...h.props.post,route:{...h.props.post.route,geometryStatus:'hidden',segments:[],geometryHash:null}};if(policy==='legacy')h.props.post={...h.props.post,route:{source:'legacy',title:'Earlier route',category:'scooter',geometryStatus:'unavailable',segments:[]}};if(policy==='moving')h.moving();if(policy==='blocked')h.blocked();h.render();assert.equal(h.find('Sheet')[0].props.visible,false,policy);assert.equal(h.find('MapSurface').length,0,policy);}});
test('held old map status cannot cross activity/permission revocation; errors and unsupported builds are visible',()=>{const h=fixture();h.render();const old=h.find('MapSurface')[0].props;h.os();old.onStatus({state:'unsupported',reason:'native-module'});h.render();assert.equal(h.find('Note').length,0);const map=h.find('MapSurface')[0].props;map.onStatus({state:'unsupported',reason:'native-module'});h.render();assert.equal(h.find('Note').some(v=>v.props.error&&v.props.children==='m7.unavailable'),true);h.blocked();map.onStatus({state:'ready'});h.render();assert.equal(h.find('MapSurface').length,0);});
