import {test} from 'node:test';
import assert from 'node:assert/strict';
import {existsSync,readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url));
const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,owner=uuid(1),friend=uuid(2),capture=uuid(4);
const room=()=>({owner_id:owner,server_now:new Date().toISOString(),id:uuid(3),host_id:owner,title:'Real group',revision:3,state:'active',expires_at:'2030-10-01T13:00:00Z',host_lease_until:'2030-10-01T12:00:45Z',viewer_role:'host',self_state:'accepted',self_generation:1,members:[{user_id:owner,handle:'owner',display_name:'Owner',role:'host',state:'accepted',generation:1,host_friendship_generation:null},{user_id:friend,handle:'friend',display_name:'Friend',role:'member',state:'requested',generation:4,host_friendship_generation:7}],route_snapshot:{route_id:uuid(9),title:'Hidden route',revision:1,category:'scooter',segments:[],geometryStatus:'hidden',geometryHash:null,privacyTrimMeters:200,provider:'draft',attribution:null},topic:`rs-convoy:${uuid(6)}`,topic_generation:1,change_revision:1,self_consent:{revision:0,precision:'none',lease_id:null,capture_id:null,expires_at:null,last_sequence:0},self_code:null});
function fixture(name){
 const refs=[],states=[],effects=[],calls=[];let ri=0,si=0,ei=0,scheduled=[];
 const scope={generation:1,userId:owner},source={signed:true,focused:true,moving:false,current:true,active:true,permission:{granted:false,canAskAgain:true},cameraRequests:0,resolves:0,data:{ready:true,loading:false,fresh:true,profileReady:true,busy:false,summaries:[],room:null,links:[],pending:[],latest:null,error:null,reviewRequired:[],secretPersistence:'session',incomingFriendIntent:null,consumeIncomingFriendIntent:()=>null,refresh:async()=>{},openRoom:async()=>{},mutate:async request=>{calls.push(request);return uuid(50);},retry:async()=>{},resolveFriendLink:async intent=>{source.resolves++;return source.friendResolution??{owner_id:owner,server_now:new Date().toISOString(),preview:null};},resolveCode:async()=>({owner_id:owner,server_now:new Date().toISOString(),preview:null}),createFriendLink:async()=>uuid(50),createConvoy:async()=>uuid(50),rotateCode:async()=>uuid(50),getFriendLinkUrl:async()=>null,getRoomCode:async()=>null,receiveEnabled:false,setReceive:value=>{calls.push({receive:value});},share:{armed:false,pending:false,expiresAt:null,error:null},captureReady:true,captureId:capture,ghost:false,presenceReady:true,grantLocation:async(duration,proof)=>{calls.push({grant:duration,proof});return uuid(50);},stopSharing:async()=>{calls.push({stop:true});}}};
 const react={useRef:value=>refs[ri++]??=( {current:value}),useState:value=>{const i=si++;if(!(i in states))states[i]=typeof value==='function'?value():value;return [states[i],next=>{states[i]=typeof next==='function'?next(states[i]):next;}];},useCallback:value=>value,useMemo:fn=>fn(),useLayoutEffect:fn=>fn(),useEffect:(fn,deps)=>{const i=ei++,old=effects[i];if(!old||!deps||deps.some((v,j)=>v!==old.deps?.[j]))scheduled.push(()=>{old?.cleanup?.();effects[i]={deps,cleanup:fn()};});}};
 const jsx=(type,props)=>({type,props}),colors={bg:'#000',ink:'#FFF',line:'#333',raised:'#111',accent:'#FF5A1F',muted:'#999',good:'#2EE6A6'},ui=Object.fromEntries(['Button','Field','Note','Panel','Row','T','Heading','Empty','Segments','Icon'].map(key=>[key,key]));
 const deps={react,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'react-native':{View:'View',FlatList:'FlatList',RefreshControl:'RefreshControl',Switch:'Switch',ActivityIndicator:'ActivityIndicator',Platform:{OS:'ios'},Share:{share:async()=>{}},AppState:{get currentState(){return source.active?'active':'background';},addEventListener:()=>({remove(){}})}},'expo-router':{useIsFocused:()=>source.focused,router:{push:()=>{},replace:()=>{}}},'expo-camera':{CameraView:'CameraView',useCameraPermissions:()=>[source.permission,async()=>{source.cameraRequests++;return source.permission={granted:true,canAskAgain:true};}]},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},'../../state/AuthState':{useAuth:()=>({session:source.signed?{user:{id:owner}}:null,scope}),isAccountCurrent:()=>source.current},'../../state/LiveState':{useLive:()=>source.data},'../../state/RideState':{useRide:()=>({movingLocked:source.moving})},'../../state/AppState':{useApp:()=>({colors,motion:false,dark:true})},'../../components/ui':ui,'../../lib/i18n':{useI18n:()=>({t:key=>key,locale:'en-US'}),errorKey:value=>String(value?.message??value)},'../../lib/useNow':{useNow:()=>Date.now()},'../routes/RouteSheet':{RouteSheet:'RouteSheet'},'../routes/SharedRouteSnapshot':{default:'SharedRouteSnapshot'},'./LiveSurface':{LiveHeader:'LiveHeader',LiveReadState:'LiveReadState',LivePending:'LivePending',LiveOutcome:'LiveOutcome'},'./QrCode':{default:'QrCode'},'./convoyRouteService':{getConvoyRoutePage:async()=>({routes:[],nextCursor:null}),reviewConvoyRoute:async()=>null}};
 const cache=new Map();function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(existsSync(path)?readFileSync(path,'utf8'):'',{fileName:path,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText;runInNewContext(code,{module,exports:module.exports,Date,console,URL,require:key=>{if(key in deps)return deps[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);for(const ext of ['.ts','.tsx'])if(!existsSync(next)&&existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}
 const Screen=load(resolve(root,'features/live',`${name}.tsx`)).default;return {source,calls,render(){assert.equal(typeof Screen,'function');ri=si=ei=0;scheduled=[];const tree=Screen({});scheduled.forEach(fn=>fn());return tree;}};
}
function all(tree,type){const rows=[];const visit=node=>{if(!node||typeof node!=='object')return;if(node.type===type)rows.push(node);if(Array.isArray(node))node.forEach(visit);else if(node.props)Object.values(node.props).forEach(visit);};visit(tree);return rows;}
const press=(tree,label)=>{const button=all(tree,'Button').find(node=>node.props.label===label);assert.ok(button,label);return button.props.onPress();};
const tick=async()=>{await Promise.resolve();await Promise.resolve();};
test('friend scanning requests camera only after its rationale and captures one local intent without resolving automatically',async()=>{
 const f=fixture('FriendLinksScreen');let tree=f.render();assert.equal(f.source.cameraRequests,0);assert.equal(all(tree,'CameraView').length,0);await press(tree,'m5b.scan');tree=f.render();assert.equal(f.source.cameraRequests,0);await press(tree,'m5b.openCamera');tree=f.render();assert.equal(f.source.cameraRequests,1);const camera=all(tree,'CameraView')[0];assert.ok(camera);const link=`ridespeed://friend/v1/${uuid(7)}#token=${'A'.repeat(43)}`;camera.props.onBarcodeScanned({data:link});camera.props.onBarcodeScanned({data:link});tree=f.render();assert.equal(all(tree,'CameraView').length,0);assert.equal(f.source.resolves,0);assert.equal(all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel').props.value,link);await press(tree,'m5b.reviewLink');assert.equal(f.source.resolves,1);assert.equal(f.calls.length,0);
});
test('a delayed friend preview after focus loss cannot restore its identity or leave a permanent spinner',async()=>{
 const f=fixture('FriendLinksScreen');let resolve;f.source.friendResolution=new Promise(done=>{resolve=done;});let tree=f.render();all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel').props.onChangeText(`ridespeed://friend/v1/${uuid(7)}#token=${'A'.repeat(43)}`);tree=f.render();const loading=press(tree,'m5b.reviewLink');f.source.focused=false;f.render();resolve({owner_id:owner,server_now:new Date().toISOString(),preview:{proof_id:uuid(8),link_id:uuid(7),issuer_id:friend,handle:'friend',display_name:'Private friend',expires_at:'2030-10-01T12:05:00Z'}});await loading;f.source.focused=true;tree=f.render();assert.equal(all(tree,'T').some(node=>node.props.children==='Private friend'),false);assert.equal(all(tree,'Button').find(node=>node.props.label==='m5b.reviewLink').props.busy,false);
});

test('editing a different invite while its prior resolver is held invalidates the prior identity preview',async()=>{
 const f=fixture('FriendLinksScreen');let resolve;f.source.friendResolution=new Promise(done=>{resolve=done;});let tree=f.render();const field=()=>all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel');field().props.onChangeText(`ridespeed://friend/v1/${uuid(7)}#token=${'A'.repeat(43)}`);tree=f.render();const waiting=press(tree,'m5b.reviewLink');tree=f.render();const newer=`ridespeed://friend/v1/${uuid(17)}#token=${'A'.repeat(43)}`;field().props.onChangeText(newer);tree=f.render();resolve({owner_id:owner,server_now:new Date().toISOString(),preview:{proof_id:uuid(8),link_id:uuid(7),issuer_id:friend,handle:'friend',display_name:'Prior link identity',expires_at:'2030-10-01T12:05:00Z'}});await waiting;tree=f.render();assert.equal(field().props.value,newer);assert.equal(all(tree,'T').some(node=>node.props.children==='Prior link identity'),false);assert.equal(all(tree,'Button').find(node=>node.props.label==='m5b.reviewLink').props.busy,false);
});
test('a guest does not consume the incoming private link before login, and the signed screen populates it without resolving',()=>{
 const f=fixture('FriendLinksScreen'),intent={linkId:uuid(7),token:'A'.repeat(43)};let consumed=0;f.source.signed=false;f.source.data.incomingFriendIntent=intent;f.source.data.consumeIncomingFriendIntent=()=>{consumed++;return intent;};f.render();assert.equal(consumed,0);f.source.signed=true;f.render();const tree=f.render();assert.equal(consumed,1);assert.equal(all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel').props.value,`ridespeed://friend/v1/${uuid(7)}#token=${intent.token}`);assert.equal(f.source.resolves,0);
});
test('a new warm invite fences a held prior preview without resolving the new link automatically',async()=>{
 const f=fixture('FriendLinksScreen');let resolve;f.source.friendResolution=new Promise(done=>{resolve=done;});let tree=f.render();all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel').props.onChangeText(`ridespeed://friend/v1/${uuid(7)}#token=${'A'.repeat(43)}`);tree=f.render();const waiting=press(tree,'m5b.reviewLink');const intent={linkId:uuid(17),token:'A'.repeat(43)};f.source.data={...f.source.data,incomingFriendIntent:intent,consumeIncomingFriendIntent:()=>intent};f.render();resolve({owner_id:owner,server_now:new Date().toISOString(),preview:{proof_id:uuid(8),link_id:uuid(7),issuer_id:friend,handle:'friend',display_name:'Stale warm identity',expires_at:'2030-10-01T12:05:00Z'}});await waiting;tree=f.render();assert.equal(all(tree,'Field').find(node=>node.props.label==='m5b.linkLabel').props.value,`ridespeed://friend/v1/${intent.linkId}#token=${intent.token}`);assert.equal(all(tree,'T').some(node=>node.props.children==='Stale warm identity'),false);assert.equal(all(tree,'Button').find(node=>node.props.label==='m5b.reviewLink').props.busy,false);assert.equal(f.source.resolves,1);
});
test('convoy receive toggles do not grant or acquire location and a held old member button cannot approve a replacement',async()=>{
 const f=fixture('ConvoyScreen');f.source.data.room=room();let tree=f.render();const receive=all(tree,'Switch')[0];assert.ok(receive);receive.props.onValueChange(true);assert.deepEqual(f.calls,[{receive:true}]);const memberRow=all(tree,'FlatList')[0].props.renderItem({item:room().members[1]});const approve=all(memberRow,'Button').find(node=>node.props.label==='m5b.approve');assert.ok(approve);f.source.data={...f.source.data,room:{...room(),members:[room().members[0],{...room().members[1],generation:5}]}};f.render();await approve.props.onPress();await tick();assert.equal(f.calls.length,1);
});
test('location disclosure binds the reviewed capture and refuses confirmation after capture replacement',async()=>{
 const f=fixture('ConvoyScreen');f.source.data.room=room();let tree=f.render();await press(tree,'m5b.sharePosition');tree=f.render();const confirm=all(tree,'Button').find(node=>node.props.label==='m5b.confirmShare');assert.ok(confirm);f.source.data={...f.source.data,captureId:uuid(99)};f.render();await confirm.props.onPress();assert.equal(f.calls.length,0);
});

test('sending shows explicit presence guidance without enabling presence or opening disclosure implicitly',()=>{
 const f=fixture('ConvoyScreen');f.source.data.room=room();f.source.data.presenceReady=false;const tree=f.render();assert.equal(all(tree,'Button').some(node=>node.props.label==='m5b.sharePosition'),false);assert.equal(all(tree,'Note').some(node=>node.props.children==='m5b.presenceRequired'),true);assert.equal(all(tree,'Button').some(node=>node.props.label==='m5b.presenceSettings'),true);assert.equal(f.calls.length,0);
});
test('unread or failed live data never claims no links or trips, and native Views contain no raw text',()=>{
 for(const name of ['FriendLinksScreen','ConvoyScreen']){const f=fixture(name);f.source.data.fresh=false;f.source.data.error='LIVE_UNAVAILABLE';let tree=f.render();assert.equal(all(tree,'Empty').length,0);f.source.data={...f.source.data,fresh:true,error:null};tree=f.render();assert.equal(all(tree,'Empty').length,1);for(const node of all(tree,'View'))assert.equal([node.props.children].flat(Infinity).some(v=>typeof v==='string'||typeof v==='number'),false,name);}
});
