import {test} from 'node:test';
import assert from 'node:assert/strict';
import {liveModule,owner,uuid,grant,operation,receipt,copy,hold,tick,stamp} from './helpers/live.mjs';
const {LiveCoordinator}=liveModule('LiveCoordinator');
function setup(rows=[]){let state={operations:copy(rows)},id=40,active=true,current=true,writeError=false;const calls=[],acks=[];const port={ownerId:owner,current:()=>current,eligible:()=>active,read:()=>state,update:async change=>{state=change(state);calls.push('write');},flush:async()=>{calls.push('flush');if(writeError)throw Error('LOCAL_WRITE_FAILED');},send:async op=>{calls.push('send');return receipt(op);},status:async()=>{calls.push('status');return null;},refresh:async r=>{calls.push('refresh');acks.push(r);},operationId:()=>uuid(++id),nowISO:()=>stamp};return {port,calls,acks,get state(){return state;},set active(v){active=v;},set current(v){current=v;},set writeError(v){writeError=v;}};}
test('restored enable-sensitive operation checks status and waits for explicit exact-ID review before sending',async()=>{
 const f=setup([operation()]),c=new LiveCoordinator(f.port);await c.retry();assert.deepEqual(f.calls.filter(v=>v==='send'),[]);assert.deepEqual(c.getSnapshot().reviewRequired,[uuid(10)]);await c.retry(uuid(10));assert.equal(f.state.operations.length,0);assert.equal(c.getSnapshot().latest.status,'applied');assert.ok(f.calls.lastIndexOf('flush')<f.calls.lastIndexOf('refresh'));
});
test('fresh enqueue flushes before egress and durable grant ACK does not change immutable pending off intent',async()=>{
 const f=setup(),h=hold();f.port.send=async op=>{f.calls.push('send');await h.promise;return receipt(op);};const c=new LiveCoordinator(f.port),first=c.enqueue(grant());await tick();assert.deepEqual(f.calls.slice(0,3),['write','flush','flush']);assert.equal(f.calls.at(-1),'send');
 const revoke={schema_version:1,action:'location_revoke',convoy_id:uuid(3),expected_member_generation:2,expected_consent_revision:2,expected_lease_id:uuid(5)},second=c.enqueue(revoke);await tick();f.active=false;c.suspend();h.resolve();await Promise.all([first,second]);assert.equal(f.state.operations.length,1);assert.equal(f.state.operations[0].request.action,'location_revoke');assert.equal(f.acks.length,0);assert.equal(c.getSnapshot().latest.status,'applied');
});
test('generic SDK business-shaped errors retain exact pending but typed error plus exact statusnull retires',async()=>{
 const f=setup();f.port.send=async()=>{throw Error('CONVOY_CHANGED');};const c=new LiveCoordinator(f.port);await c.enqueue(grant());assert.equal(f.state.operations.length,1);assert.equal(c.getSnapshot().latest,null);const unchanged=copy(f.state.operations[0]);f.port.send=async()=>({error:{code:'CONVOY_CHANGED'}});await c.retry();assert.equal(f.state.operations.length,0);assert.equal(c.getSnapshot().latest.status,'rejected');assert.equal(unchanged.request.capture_id,uuid(4));
});
test('failed ACK disk removal restores immutable operation for status-only replay and never resends after durable receipt',async()=>{
 const f=setup(),c=new LiveCoordinator(f.port);f.port.send=async op=>{f.writeError=true;return receipt(op);};await c.enqueue(grant());assert.equal(f.state.operations.length,1);assert.equal(f.state.operations[0].operationId,uuid(41));f.writeError=false;f.port.status=async id=>receipt(f.state.operations.find(v=>v.operationId===id));await c.retry();assert.equal(f.state.operations.length,0);assert.equal(f.acks.length,1);
});
test('background before status resolution forbids new send while held valid ACK can settle ownership-only',async()=>{
 const f=setup([operation()]),h=hold();f.port.status=async()=>h.promise;const c=new LiveCoordinator(f.port),work=c.retry(uuid(10));await tick();f.active=false;c.suspend();h.resolve(null);await work;assert.equal(f.state.operations.length,1);assert.equal(f.calls.includes('send'),false);
 const g=setup(),k=hold();g.port.send=async op=>{await k.promise;return receipt(op);};const d=new LiveCoordinator(g.port),pending=d.enqueue(grant());await tick();g.active=false;d.suspend();k.resolve();await pending;assert.equal(g.state.operations.length,0);assert.equal(g.acks.length,0);
});
test('unread owner and closed A→B→A scopes never become writable empty operations',async()=>{
 const f=setup([operation()]);f.port.read=()=>{throw Error('LOCAL_READ_FAILED');};const c=new LiveCoordinator(f.port);await c.enqueue(grant());assert.equal(f.calls.includes('write'),false);assert.equal(c.getSnapshot().error,'LOCAL_READ_FAILED');
 const g=setup(),h=hold();g.port.send=async op=>{await h.promise;return receipt(op);};const d=new LiveCoordinator(g.port),p=d.enqueue(grant());await tick();g.current=false;d.close();h.resolve();await p;assert.equal(g.state.operations.length,1);assert.equal(g.acks.length,0);
});
const cancelled=op=>({owner_id:owner,operation_id:op.operationId,request:op.request,state:'cancelled',cancelled_at:stamp});
test('off cancels restored unknown grant using exact original UUID/request, never re-grants or drops statusnull',async()=>{
 const f=setup([operation()]),c=new LiveCoordinator(f.port);f.port.cancelGrant=async op=>{f.calls.push('cancel');assert.deepEqual(op,{operationId:uuid(10),request:grant()});return cancelled(op);};await c.retry();assert.equal(f.state.operations.length,1);assert.equal(await c.cancelGrant(uuid(10)),true);assert.equal(f.state.operations.length,0);assert.equal(f.calls.includes('send'),false);assert.equal(c.getSnapshot().latest.error,'LIVE_OPERATION_CANCELLED');assert.ok(f.calls.lastIndexOf('flush')>f.calls.indexOf('cancel'));
});
test('off cancellation can fence an in-flight grant; delayed old applied reply cannot rearm or refresh after durable cancellation',async()=>{
 const f=setup(),h=hold(),c=new LiveCoordinator(f.port);f.port.send=async op=>{f.calls.push('send');await h.promise;return receipt(op);};const first=c.enqueue(grant());await tick();f.port.cancelGrant=async op=>cancelled(op);assert.equal(await c.cancelGrant(uuid(41)),true);assert.equal(f.state.operations.length,0);h.resolve();await first;assert.equal(f.acks.length,0);assert.equal(c.getSnapshot().latest.error,'LIVE_OPERATION_CANCELLED');assert.equal(c.getSnapshot().error,'LIVE_OPERATION_CANCELLED');
});
test('applied cancellation reply settles original receipt without another send; unknown/invalid proof retains exact row',async()=>{
 const f=setup([operation()]),c=new LiveCoordinator(f.port);f.port.cancelGrant=async op=>receipt(op);assert.equal(await c.cancelGrant(uuid(10)),true);assert.equal(f.state.operations.length,0);assert.equal(f.acks.length,1);assert.equal(f.calls.includes('send'),false);
 for(const response of [()=>Promise.reject(Error('network')),(op)=>({...cancelled(op),owner_id:uuid(90)}),()=>({error:{code:'LIVE_RATE_LIMITED'}})]){const g=setup([operation()]),d=new LiveCoordinator(g.port);g.port.cancelGrant=response;assert.equal(await d.cancelGrant(uuid(10)),false);assert.deepEqual(g.state.operations[0].request,grant());assert.equal(g.calls.includes('send'),false);await d.retry(uuid(10));assert.equal(g.calls.includes('send'),false);}
});
test('cancellation removal disk failure preserves proof-recoverable original; close and background fence new cancellation egress',async()=>{
 const f=setup([operation()]),c=new LiveCoordinator(f.port);f.port.cancelGrant=async op=>{f.writeError=true;return cancelled(op);};assert.equal(await c.cancelGrant(uuid(10)),false);assert.equal(f.state.operations.length,1);f.writeError=false;f.port.cancelGrant=async op=>cancelled(op);assert.equal(await c.cancelGrant(uuid(10)),true);assert.equal(f.state.operations.length,0);
 const g=setup([operation()]),d=new LiveCoordinator(g.port);g.port.cancelGrant=async()=>{throw Error('must not run');};g.active=false;assert.equal(await d.cancelGrant(uuid(10)),false);d.close();g.active=true;assert.equal(await d.cancelGrant(uuid(10)),false);assert.equal(g.state.operations.length,1);
});
test('simultaneous original applied ACK and applied cancellation proof share durable settlement so stop can continue to revoke',async()=>{
 for(const heldFlush of [false,true]){const f=setup(),send=hold(),cancel=hold(),flush=hold(),c=new LiveCoordinator(f.port);let emptyWrites=0;const update=f.port.update;f.port.update=async change=>{await update(change);if(!f.state.operations.length)emptyWrites++;};f.port.flush=async()=>{f.calls.push('flush');if(heldFlush&&!f.state.operations.length)await flush.promise;};let sent;f.port.send=async op=>{sent=op;f.calls.push('send');return send.promise;};f.port.cancelGrant=()=>cancel.promise;const first=c.enqueue(grant());await tick();const stop=c.cancelGrant(uuid(41));await tick();send.resolve(receipt(sent));cancel.resolve(receipt(sent));await tick();if(heldFlush)flush.resolve();assert.equal(await stop,true);await first;assert.equal(f.state.operations.length,0);assert.equal(emptyWrites,1);assert.equal(f.acks.length,1);assert.equal(c.getSnapshot().error,null);}
});
test('typed cancelled original and cancellation proof share one terminal settlement across response order and held flush',async()=>{
 for(const proofFirst of [false,true])for(const heldFlush of [false,true]){const f=setup(),send=hold(),cancel=hold(),flush=hold(),c=new LiveCoordinator(f.port);let emptyWrites=0;const update=f.port.update;f.port.update=async change=>{await update(change);if(!f.state.operations.length)emptyWrites++;};f.port.flush=async()=>{f.calls.push('flush');if(heldFlush&&!f.state.operations.length)await flush.promise;};let sent;f.port.send=async op=>{sent=op;return send.promise;};f.port.cancelGrant=()=>cancel.promise;const first=c.enqueue(grant());await tick();const stop=c.cancelGrant(uuid(41));await tick();if(proofFirst){cancel.resolve(cancelled(sent));await tick();send.resolve({error:{code:'LIVE_OPERATION_CANCELLED'}});}else{send.resolve({error:{code:'LIVE_OPERATION_CANCELLED'}});await tick();cancel.resolve(cancelled(sent));}await tick();if(heldFlush)flush.resolve();assert.equal(await stop,true);await first;assert.equal(f.state.operations.length,0);assert.equal(emptyWrites,1);assert.equal(f.acks.length,0);assert.equal(c.getSnapshot().latest.error,'LIVE_OPERATION_CANCELLED');assert.equal(c.getSnapshot().error,'LIVE_OPERATION_CANCELLED');}
});
test('concurrent terminal settlement flush failure retains exact original and recovers proof without another grant',async()=>{
 for(const applied of [false,true]){const f=setup(),send=hold(),cancel=hold(),flush=hold(),c=new LiveCoordinator(f.port);let sent,failed=false;f.port.flush=async()=>{f.calls.push('flush');if(!f.state.operations.length&&!failed){await flush.promise;failed=true;throw Error('LOCAL_WRITE_FAILED');}};f.port.send=async op=>{sent=op;f.calls.push('send');return send.promise;};f.port.cancelGrant=()=>cancel.promise;const first=c.enqueue(grant());await tick();const stop=c.cancelGrant(uuid(41));await tick();send.resolve(applied?receipt(sent):{error:{code:'LIVE_OPERATION_CANCELLED'}});cancel.resolve(applied?receipt(sent):cancelled(sent));await tick();flush.resolve();assert.equal(await stop,false);await first;assert.equal(f.state.operations.length,1);assert.deepEqual({operationId:f.state.operations[0].operationId,request:f.state.operations[0].request},sent);assert.equal(c.getSnapshot().latest,null);f.port.cancelGrant=async op=>applied?receipt(op):cancelled(op);assert.equal(await c.cancelGrant(sent.operationId),true);assert.equal(f.state.operations.length,0);assert.equal(f.calls.filter(v=>v==='send').length,1);assert.equal(c.getSnapshot().latest.status,applied?'applied':'rejected');}
});
