import {test} from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import ts from 'typescript';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url));
const hold=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};},tick=()=>new Promise(done=>setImmediate(done));
const peer=(id='actual-authorized-A',lng=100.5)=>({id,coordinate:{latitude:13.73,longitude:lng},name:'ผู้ขี่',presence:'riding',updatedAtMs:100});
function hookHarness(){const cells=[],layouts=[],effects=[];let index=0,tree;const same=(a,b)=>!!a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));const memo=(fn,deps)=>{const at=index++;if(!cells[at]||!same(cells[at].deps,deps))cells[at]={deps,value:fn()};return cells[at].value;};const enqueue=(queue,fn,deps)=>{const at=index++,old=cells[at];if(!old||!same(old.deps,deps)){cells[at]={deps,cleanup:old?.cleanup};queue.push(()=>{old?.cleanup?.();cells[at].cleanup=fn();});}};
 const react={forwardRef:fn=>fn,memo:fn=>fn,useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useRef:value=>{const at=index++;return cells[at]??={current:value};},useState:value=>{const at=index++;cells[at]??={value:typeof value==='function'?value():value};return [cells[at].value,next=>{cells[at].value=typeof next==='function'?next(cells[at].value):next;}];},useLayoutEffect:(fn,deps=[])=>enqueue(layouts,fn,deps),useEffect:(fn,deps=[])=>enqueue(effects,fn,deps),useImperativeHandle:(ref,fn)=>{ref.current=fn();}};
 return {react,render(Surface,props,ref,dom){index=0;tree=Surface(props,ref);if(dom&&tree.props.ref)tree.props.ref.current=dom;while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return tree;},close(){for(const c of cells)c?.cleanup?.();}};
}
function loadSource(overrides,sandbox={}){const cache=new Map();function load(path){if(path.endsWith('.png'))return 1;if(path.endsWith('.css'))return {};if(path.endsWith('.json'))return JSON.parse(readFileSync(path,'utf8'));if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(readFileSync(path,'utf8'),{fileName:path,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,require:key=>{if(key in overrides)return overrides[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);if(!existsSync(next))for(const ext of ['.ts','.tsx'])if(existsSync(next+ext)){next+=ext;break;}return load(next);},URL,console,setTimeout,clearTimeout,TextEncoder,performance,...sandbox},{filename:path});return module.exports;}return load;}
const base={theme:'dark',locale:'th',initialCamera:{center:{latitude:13.73,longitude:100.5},zoom:12},contentInsets:{top:80,bottom:380,right:20,left:20},mode:'browse',reducedMotion:false,online:true,retryToken:0,track:null,pins:[],peers:[],userFix:null,selectedPinId:null,onStatus:()=>{}};
function web(){const hooks=hookHarness(),ref={current:null},maps=[],writes=[],visibility=[];const area={style:{}},credits={setAttribute(){},parentElement:area,getBoundingClientRect:()=>({height:44})};const dom={querySelector:s=>s.includes('attrib')?credits:area,addEventListener(){},removeEventListener(){},getBoundingClientRect:()=>({left:0,top:0})};
 class ControlledMap{constructor(){this.layers=new Map();this.sources=new Map();this.events=new Map();this.touchPitch={enable(){},disable(){}};maps.push(this);}on(name,fn){this.events.set(name,fn);return this;}emit(name,...args){this.events.get(name)?.(...args);}addControl(){}setPadding(){}getSource(id){return this.sources.get(id);}addSource(id,options){const source={id,data:options.data,setData(value){const waiting=hold();writes.push({id,value,waiting,source});return waiting.promise.then(()=>{source.data=value;});}};this.sources.set(id,source);}getLayer(id){return this.layers.get(id);}addLayer(layer){this.layers.set(layer.id,{...layer,layout:{...layer.layout}});}setLayoutProperty(id,key,value){this.layers.get(id).layout[key]=value;if(key==='visibility')visibility.push({id,value});}async loadImage(){return {data:{}};}hasImage(){return false;}addImage(){}getZoom(){return 12;}getBearing(){return 0;}off(){}getCanvas(){return {};}getContainer(){return dom;}resize(){}remove(){this.removed=true;}setStyle(){this.layers.clear();this.sources.clear();}}
 const jsx=(type,props)=>({type,props}),load=loadSource({react:hooks.react,'react/jsx-runtime':{jsx,jsxs:jsx},'expo-asset':{Asset:{fromModule:()=>({uri:'local-original-vehicle.png'})}},'expo-constants':{default:{expoConfig:{}}},'maplibre-gl':{Marker:class{setLngLat(){return this;}addTo(){return this;}remove(){}},Map:ControlledMap,AttributionControl:class {},setWorkerUrl(){}}},{window:{location:{origin:'https://preview.test'}},requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},document:{createElement:()=>({append(){},setAttribute(){},style:{},getContext:()=>({getExtension:()=>({loseContext(){}})})})},ResizeObserver:class {observe(){}disconnect(){}}});const Surface=load(resolve(root,'features/map/MapSurface.web.tsx')).default;let props=base;
 const render=patch=>{props={...props,...patch};return hooks.render(Surface,props,ref,dom);};render({});
 return {render,maps,writes,visibility,close:()=>hooks.close(),async mount(){await tick();assert.equal(maps.length,1);maps[0].emit('style.load');await tick();},map:()=>maps[0],peerWrites:()=>writes.filter(w=>w.id==='rs-peers'),visible:()=>['rs-peer','rs-peer-name','rs-cluster','rs-cluster-count'].some(id=>maps[0].getLayer(id)?.layout.visibility==='visible')};
}
test('actual web adapter hides before an outstanding worker finishes, then reveals only the newest authorized replacement',async()=>{
 const h=web();h.render({peers:[peer()]});await h.mount();const old=h.peerWrites()[0];assert.equal(h.visible(),false);assert.equal(old.value.features[0].properties.id,'actual-authorized-A');h.render({peers:[]});assert.equal(h.visible(),false,'off hides synchronously before empty worker update');h.render({peers:[peer('actual-authorized-B',100.501)]});assert.equal(h.visible(),false);
 old.waiting.resolve();await tick();assert.equal(h.visible(),false,'completed old worker cannot reveal its GPS');const newest=h.peerWrites()[1];assert.equal(newest.value.features[0].properties.id,'actual-authorized-B');newest.waiting.resolve();await tick();assert.equal(h.visible(),true);assert.equal(h.map().getSource('rs-peers').data.features[0].properties.id,'actual-authorized-B');h.render({peers:[]});assert.equal(h.visible(),false);h.peerWrites().at(-1).waiting.resolve();await tick();assert.equal(h.visible(),false);h.close();
});
test('actual web style/source replacement and renderer teardown reject delayed old worker reveal',async()=>{
 const h=web();h.render({peers:[peer()]});await h.mount();const old=h.peerWrites()[0];h.render({theme:'light',peers:[peer('actual-authorized-B')]});h.map().emit('style.load');await tick();assert.equal(h.visible(),false);old.waiting.resolve();await tick();assert.equal(h.visible(),false);const current=h.peerWrites().at(-1);current.waiting.resolve();await tick();assert.equal(h.visible(),true);h.render({peers:[peer('actual-authorized-C')]});assert.equal(h.visible(),false);const last=h.peerWrites().at(-1);h.close();last.waiting.resolve();await tick();assert.equal(h.visible(),false);assert.equal(h.map().removed,true);
});
test('actual native adapter unmounts the peer source and all layers immediately when authorized peers become empty',()=>{
 const hooks=hookHarness(),ref={current:null},jsx=(type,props)=>({type,props}),native={Map:'NativeMap',Camera:'NativeCamera',GeoJSONSource:'GeoJSONSource',Layer:'Layer',ViewAnnotation:'ViewAnnotation'},load=loadSource({react:hooks.react,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'@maplibre/maplibre-react-native':native,'react-native-reanimated':{},'react-native':{View:'View',Text:'Text',Pressable:'Pressable',StyleSheet:{absoluteFill:{}}}}),Surface=load(resolve(root,'features/map/MapSurface.native.tsx')).default;
 let props={...base,peers:[peer()]};const render=patch=>{props={...props,...patch};return hooks.render(Surface,props,ref);},flatten=node=>!node||typeof node!=='object'?[]:[node,...[node.props?.children].flat(Infinity).flatMap(flatten)];let tree=render({}),map=flatten(tree).find(n=>n.type==='NativeMap');map.props.onDidFinishLoadingStyle();tree=render({});assert.equal(flatten(tree).filter(n=>n.props?.peers!==undefined&&n.props?.sourceRef!==undefined).length,1);tree=render({peers:[]});assert.equal(flatten(tree).filter(n=>n.props?.peers!==undefined&&n.props?.sourceRef!==undefined).length,0);tree=render({peers:[peer('actual-authorized-B')]});assert.equal(flatten(tree).filter(n=>n.props?.peers!==undefined&&n.props?.sourceRef!==undefined).length,1);hooks.close();
});
