import assert from 'node:assert/strict';
import {test} from 'node:test';
import {liveModule} from './helpers/live.mjs';
const {PeerPresentation, samplePresentation}=liveModule('../map/peerPresentation');

const peer=(sequence,longitude=100.5,extra={})=>({id:'rider',name:'ผู้ขับขี่',presence:'online',coordinate:{latitude:13.7,longitude},updatedAtMs:10000+sequence*1000,
 sample:{topicGeneration:1,expiresMonotonicMs:20000,position:{user_id:'rider',display_name:'ผู้ขับขี่',latitude:13.7,longitude,accuracy_m:5,heading_deg:90,captured_at:new Date(10000+sequence*1000).toISOString(),received_at:new Date(10000+sequence*1000).toISOString(),expires_at:new Date(40000).toISOString(),member_generation:1,consent_revision:1,sequence,authority:'unverified_live'}},...extra});
test('fresh consecutive fixes interpolate without inventing speed',()=>{const p=new PeerPresentation();p.update([peer(1)],1000,false);const f=p.update([peer(2,100.5001)],2000,false);const mid=samplePresentation(f,2500);assert.equal(mid.features.length,1);assert.ok(mid.features[0].geometry.coordinates[0]>100.5&&mid.features[0].geometry.coordinates[0]<100.5001);assert.equal(mid.features[0].properties.speed,undefined);});
test('duplicate observations do not restart or extend animation / permission',()=>{const p=new PeerPresentation();p.update([peer(1)],1000,false);const f=p.update([peer(2,100.5001)],2000,false);const again=peer(2,100.5001);again.sample.expiresMonotonicMs=30000;const r=p.update([again],2600,false);assert.equal(r[0].motion.startMonotonicMs,f[0].motion.startMonotonicMs);assert.equal(r[0].motion.expiresMonotonicMs,20000);assert.equal(samplePresentation(r,20000).features.length,0);});
test('a repeated fix cannot extend the history used by a later animation',()=>{const p=new PeerPresentation();p.update([peer(1)],1000,false);const repeated=peer(1);repeated.sample.expiresMonotonicMs=30000;p.update([repeated],19000,false);const later=peer(2,100.5001);later.sample.expiresMonotonicMs=35000;assert.equal(p.update([later],21000,false)[0].motion.durationMs,0);});
test('revocation removes all retained state; rejoin snaps',()=>{const p=new PeerPresentation();p.update([peer(1)],1000,false);assert.deepEqual(p.update([],1500,false),[]);const f=p.update([peer(2,100.5001)],2000,false);assert.equal(f[0].motion.durationMs,0);});
test('consent and topic changes cannot interpolate across permissions',()=>{for(const field of ['topicGeneration','consent_revision','member_generation']){const p=new PeerPresentation();p.update([peer(1)],1000,false);const next=peer(2,100.5001);if(field==='topicGeneration')next.sample[field]++;else next.sample.position[field]++;assert.equal(p.update([next],2000,false)[0].motion.durationMs,0);}});
test('reduced motion snaps, and expired / invalid samples disappear',()=>{const p=new PeerPresentation();p.update([peer(1)],1000,false);const f=p.update([peer(2,100.5001)],2000,true);assert.equal(f[0].motion.durationMs,0);assert.equal(samplePresentation(f,2100).features[0].geometry.coordinates[0],100.5001);assert.equal(p.update([peer(2)],20000,false).length,0);assert.equal(p.update([peer(2)],NaN,false).length,0);});
test('sample and outer identity must match; coordinates must be finite',()=>{const p=new PeerPresentation();assert.equal(p.update([peer(1,NaN)],1000,false).length,0);assert.equal(p.update([peer(1,100.5,{id:'someone-else'})],1000,false).length,0);});
test('no motion state is retained for a removed member among 50',()=>{const p=new PeerPresentation();const all=Array.from({length:50},(_,i)=>{const row=peer(1);row.id=`p${i}`;row.sample.position.user_id=row.id;return row;});assert.equal(p.update(all,1000,false).length,50);assert.equal(p.update(all.slice(20),1500,false).length,30);assert.equal(samplePresentation(p.update([],2000,false),2500).features.length,0);});
