import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {RaceEvidenceStore} from '../src/features/races/RaceEvidenceStore.ts';
const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=async text=>createHash('sha256').update(text).digest('hex');
function harness(){let scope={userId:uuid(1),generation:1};const disk=new Map(),closed=[],behavior={hold:null,fail:false,writes:0};const store=new RaceEvidenceStore({current:s=>s===scope,sha256:hash,disk:{read:async(o,a)=>disk.get(`${o}:${a}`)??null,async writeNew(o,a,text){behavior.writes++;if(behavior.hold)await behavior.hold.promise;if(behavior.fail)throw Error('disk');if(disk.has(`${o}:${a}`))throw Error('exists');disk.set(`${o}:${a}`,text);},async removeAttempt(o,a){disk.delete(`${o}:${a}`);},async removeOwner(o){closed.push(o);for(const key of disk.keys())if(key.startsWith(o+':'))disk.delete(key);}}});return {store,disk,behavior,closed,get scope(){return scope;},switch(){scope={userId:uuid(2),generation:2};}};}
const payload=(extra={})=>{const text=JSON.stringify({race_id:uuid(3),attempt_id:uuid(4),ride_id:uuid(5),capture_id:uuid(6),first_sequence:2,last_sequence:5,samples:[{sequence:2,mocked:null},{sequence:3,mocked:true},{sequence:4},{sequence:5}],...extra});return {text,byteLength:new TextEncoder().encode(text).length,firstSequence:2,lastSequence:5,sampleCount:4};};
test('immutable upload bytes survive lost acknowledgement/restart and cannot be replaced under the same attempt',async()=>{const h=harness(),value=payload(),ref=await h.store.put(h.scope,uuid(4),value);assert.equal(ref.sha256,await hash(value.text));assert.equal(await h.store.read(h.scope,ref),value.text);assert.deepEqual(await h.store.put(h.scope,uuid(4),value),ref);assert.equal(h.behavior.writes,1);await assert.rejects(h.store.put(h.scope,uuid(4),payload({private_changed:true})),/RACE_EVIDENCE_BOUND/);h.disk.set(`${h.scope.userId}:${uuid(4)}`,value.text+' ');await assert.rejects(h.store.read(h.scope,ref),/RACE_EVIDENCE_UNAVAILABLE/);});
test('owner closure waits for in-flight bytes, then erases them without recreating a closed owner',async()=>{const h=harness();let resolve;h.behavior.hold={promise:new Promise(r=>resolve=r)};const scope=h.scope,pending=h.store.put(scope,uuid(4),payload());await new Promise(r=>setImmediate(r));const rejected=assert.rejects(pending,/ACCOUNT_CHANGED/);const removal=h.store.closeOwner(scope);resolve();await rejected;await removal;assert.equal(h.disk.size,0);await assert.rejects(h.store.put(scope,uuid(4),payload()),/ACCOUNT_CHANGED/);assert.deepEqual(h.closed,[scope.userId]);});
test('held old-account results and malformed range metadata cannot publish or borrow another owner',async()=>{const h=harness();let resolve;h.behavior.hold={promise:new Promise(r=>resolve=r)};const old=h.scope,pending=h.store.put(old,uuid(4),payload());await new Promise(r=>setImmediate(r));const rejected=assert.rejects(pending,/ACCOUNT_CHANGED/);h.switch();resolve();await rejected;await assert.rejects(h.store.read(h.scope,{owner_id:old.userId,attempt_id:uuid(4)}),/ACCOUNT_CHANGED/);await assert.rejects(h.store.put(h.scope,uuid(4),{...payload(),sampleCount:3}),/RACE_EVIDENCE_UNAVAILABLE/);assert.equal(h.behavior.writes,1);});
test('terminal-copy release removes only the initiating owner attempt and cannot use a foreign reference',async()=>{const h=harness(),reference=await h.store.put(h.scope,uuid(4),payload());h.disk.set(`${uuid(2)}:${uuid(4)}`,'foreign');h.disk.set(`${uuid(1)}:${uuid(8)}`,'unresolved');await assert.rejects(h.store.removeTerminal(h.scope,{...reference,owner_id:uuid(2)}),/ACCOUNT_CHANGED/);await h.store.removeTerminal(h.scope,reference);assert.equal(h.disk.has(`${uuid(1)}:${uuid(4)}`),false);assert.equal(h.disk.get(`${uuid(2)}:${uuid(4)}`),'foreign');assert.equal(h.disk.get(`${uuid(1)}:${uuid(8)}`),'unresolved');});
