import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import {IDBFactory} from 'fake-indexeddb';
const require=createRequire(import.meta.url),ts=require('typescript'),owner='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002',attempt='00000000-0000-4000-8000-000000000003';
function load(path,dependencies={},globals={}){const module={exports:{}};vm.runInNewContext(ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}}).outputText,{module,exports:module.exports,require:name=>{if(!(name in dependencies))throw Error(name);return dependencies[name];},...globals});return module.exports.raceEvidenceDisk;}
test('actual IndexedDB adapter persists exact bytes, refuses replacement and deletes only one owner',async()=>{const indexedDB=new IDBFactory(),port=load('../src/features/races/evidenceDisk.web.ts',{}, {indexedDB});await port.writeNew(owner,attempt,'original');await port.writeNew(other,attempt,'other');await assert.rejects(port.writeNew(owner,attempt,'replacement'));assert.equal(await port.read(owner,attempt),'original');const restarted=load('../src/features/races/evidenceDisk.web.ts',{}, {indexedDB});assert.equal(await restarted.read(owner,attempt),'original');await restarted.removeOwner(owner);assert.equal(await restarted.read(owner,attempt),null);assert.equal(await restarted.read(other,attempt),'other');await assert.rejects(port.writeNew('../other',attempt,'escape'));});
test('actual native adapter waits for the SDK57 move, cleans partial bytes and confines deletion to the UUID owner directory',async()=>{
 const rows=new Map(),dirs=new Set();let release;const hold=new Promise(r=>release=r);const path=(...parts)=>parts.map(p=>typeof p==='string'?p:p.path).join('/');
 class Directory{constructor(...parts){this.path=path(...parts);}get exists(){return dirs.has(this.path);}create(){dirs.add(this.path);}delete(){for(const key of rows.keys())if(key.startsWith(this.path+'/'))rows.delete(key);dirs.delete(this.path);}}
 class File{constructor(...parts){this.path=path(...parts);}get exists(){return rows.has(this.path);}get size(){return rows.get(this.path)?.length??0;}text(){return Promise.resolve(rows.get(this.path));}create(){if(rows.has(this.path))throw Error('exists');rows.set(this.path,'');}write(value){rows.set(this.path,value);}delete(){rows.delete(this.path);}async move(target,options){assert.equal(options.overwrite,false);await hold;if(rows.has(target.path))throw Error('exists');rows.set(target.path,rows.get(this.path));rows.delete(this.path);this.path=target.path;}}
 const port=load('../src/features/races/evidenceDisk.ts',{'expo-file-system':{Directory,File,Paths:{document:'private-documents'}},'expo-crypto':{randomUUID:()=>attempt}});let finished=false;const writing=port.writeNew(owner,attempt,'original').then(()=>finished=true);await new Promise(r=>setImmediate(r));assert.equal(finished,false);assert.equal(await port.read(owner,attempt),null);release();await writing;assert.equal(await port.read(owner,attempt),'original');await port.writeNew(other,attempt,'other');await assert.rejects(port.writeNew(owner,attempt,'replacement'));assert.equal([...rows.keys()].some(key=>key.endsWith('.partial')),false);await port.removeOwner(owner);assert.equal(await port.read(owner,attempt),null);assert.equal(await port.read(other,attempt),'other');await assert.rejects(port.removeOwner('../../elsewhere'));await assert.rejects(port.writeNew(owner,'../elsewhere','escape'));
});
