import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url));
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const member=(n=1)=>({user_id:id(n),role:n===1?'host':'member',state:'accepted',member_generation:3,friendship_generation:n===1?null:7,profile:{name:`Rider ${n}`,handle:`rider${n}`,avatar_id:null},evidence_consent_version:1,consented_at:'2026-10-01T01:00:00Z',ready_revision:1,ready:false,ready_until:null});
const approval=()=>({id:id(4),route_id:id(5),route_revision:2,route_geometry_hash:'a'.repeat(64),config_hash:'b'.repeat(64),course_id:id(6),session_id:id(7),method:'route_time_v1',category:'scooter',starts_at:'2026-10-01T10:00:00Z',ends_at:'2026-10-01T11:00:00Z',distance_m:1000,maximum_duration_s:1800});
const race=()=>({id:id(3),creator_id:id(1),revision:4,mode:'async',metric:'route_time',method:'route_time_v1',state:'open',approval:approval(),route_summary:{title:'Private course',revision:2,category:'scooter'},route_snapshot:{route_id:id(5),revision:2,title:'Private course',category:'scooter',segments:[],geometryStatus:'hidden',privacyTrimMeters:200,geometryHash:null,provider:'draft',attribution:null},starts_at:approval().starts_at,ends_at:approval().ends_at,lobby_epoch:id(8),common_start_at:null,schedule_epoch:null,topic:null,topic_generation:1,host_lease_until:null,self_member:member(),members:[member(),member(2)],self_ready:null,schedule_ready:null,updated_at:'2026-10-01T09:00:00Z',terminal_reason:null});
function fixture(name){
 const states=[],refs=[],effects=[],callbacks=[],calls=[];let si=0,ri=0,ei=0,ci=0,scheduled=[];
 const port={ownerId:id(1),generation:'A1',gate:{signedIn:true,profileReady:true,native:true,foreground:true,focused:true,moving:false,online:true},current:gen=>gen===port.generation,guard:(gen,kind)=>{if(gen!==port.generation)throw Error('ACCOUNT_CHANGED');if(!port.gate.foreground||!port.gate.focused)throw Error('RACE_REVIEW_REQUIRED');if(kind!=='terminal'&&port.gate.moving)throw Error('RACE_MOVING');},ready:true,fresh:true,loading:false,busy:false,error:null,pilotEnabled:true,races:[],racesPage:{fresh:true,loading:false,error:null,hasMore:false},routes:[],routesPage:{fresh:true,loading:false,error:null,hasMore:false},friends:[],friendsPage:{fresh:true,loading:false,error:null,hasMore:false},approvals:{route_id:null,route_revision:null,items:[],fresh:true,loading:false,error:null},race:null,detailLoading:false,detailFresh:true,detailError:null,course:null,courseLoading:false,courseError:null,attempt:null,results:null,resultsLoading:false,resultsFresh:true,resultsError:null,countdown:{phase:'idle',secondsRemaining:null,uncertaintyMs:null,error:null},eligibility:{captureReady:true,stageReady:true,clockReady:true,canSchedule:true,attemptLimitReached:false},pending:[],latest:null,reviewRequired:[],retryAfterMs:null,onSignIn:()=>calls.push(['signIn']),onEditProfile:()=>{},onBack:()=>{},refresh:async()=>calls.push(['refresh']),loadMore:async()=>{},loadMoreRoutes:async()=>{},loadMoreFriends:async()=>{},openRace:async value=>calls.push(['open',value]),loadApprovals:async()=>{},reviewCreate:async value=>({...value,approval:approval(),projection:race().route_snapshot,reviewed_projection_hash:'c'.repeat(64)}),create:async(...args)=>{calls.push(['create',...args]);return id(20);}};
 for(const key of ['memberAction','loadCourse','loadResults','reserve','arm','readyAttempt','unready','schedule','cancel','abort','retry','cancelActivation','finishAttempt','rematch'])port[key]=async(...args)=>{calls.push([key,...args]);return id(20);};
 const react={useState:value=>{const i=si++;if(!(i in states))states[i]=typeof value==='function'?value():value;return [states[i],next=>{states[i]=typeof next==='function'?next(states[i]):next;}];},useRef:value=>refs[ri++]??={current:value},useCallback:(value,deps)=>{const i=ci++,old=callbacks[i];if(!old||!deps||deps.some((v,j)=>v!==old.deps?.[j]))callbacks[i]={value,deps};return callbacks[i].value;},useMemo:fn=>fn(),useLayoutEffect:fn=>fn(),useEffect:(fn,deps)=>{const i=ei++,old=effects[i];if(!old||!deps||deps.some((v,j)=>v!==old.deps?.[j]))scheduled.push(()=>{old?.cleanup?.();effects[i]={deps,cleanup:fn()};});}};
 const jsx=(type,props)=>({type,props}),ui=Object.fromEntries(['Button','Field','Note','Panel','Row','T','Empty','Segments','Icon','Glass'].map(v=>[v,v]));
 const deps={'./useRaceCountdownHaptics':{useRaceCountdownHaptics:()=>{}},'../RaceCourseMap':{__esModule:true,default:'RaceCourseMap'},react,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'react-native':{View:'View',ScrollView:'ScrollView',FlatList:'FlatList',Pressable:'Pressable',RefreshControl:'RefreshControl',ActivityIndicator:'ActivityIndicator',StyleSheet:{absoluteFill:{},hairlineWidth:1,create:v=>v}},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},'../../../components/ui':ui,'../../../state/AppState':{useApp:()=>({dark:true,motion:false,colors:{bg:'#000',surface:'#0A0A0A',raised:'#111',ink:'#FFF',muted:'#AAA',line:'#333',accent:'#FF5A1F',good:'#2EE6A6',danger:'#FF3B5C'}})},'../../motion':{AmbientLoop:'AmbientLoop'},'../../motion/assets':{resolveAmbientAsset:(role,theme)=>`${role}-${theme}`},'../../routes/RouteSheet':{RouteSheet:'RouteSheet'},'../../routes/SharedRouteSnapshot':{default:'SharedRouteSnapshot'}};
 const cache=new Map();function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(readFileSync(path,'utf8'),{fileName:path,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}}).outputText;runInNewContext(code,{module,exports:module.exports,Date,console,URL,require:key=>{if(key in deps)return deps[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);for(const ext of ['.ts','.tsx'])if(!existsSync(next)&&existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}
 const exports=load(resolve(root,'features/races/ui',`${name}.tsx`)),Screen=exports.default??exports[name];
 return {port,calls,load,render(extra={}){si=ri=ei=ci=0;scheduled=[];const tree=Screen({port,t:key=>key,...extra});scheduled.forEach(fn=>fn());return tree;}};
}
function all(tree,type){const found=[];const visit=value=>{if(!value||typeof value!=='object')return;if(value.type===type)found.push(value);if(value.type==='RouteSheet'&&!value.props.visible)return;if(Array.isArray(value))value.forEach(visit);else if(value.props)Object.values(value.props).forEach(visit);};visit(tree);return found;}
function button(tree,label){const item=all(tree,'Button').find(v=>v.props.label===label);assert.ok(item,label);return item.props;}
const tick=async()=>{await Promise.resolve();await Promise.resolve();};
function consentChecks(f,tree){return all(tree,f.load(resolve(root,'features/races/ui/RaceSurface.tsx')).ConsentChecks)[0].props;}
async function selectTrial(f){
 f.port.routes=[{id:id(5),revision:2,title:'Approved route',category:'scooter'}];f.port.friends=[{user_id:id(2),friendship_generation:7,name:'Friend',handle:'friend'}];f.port.approvals={route_id:id(5),route_revision:2,items:[approval()],fresh:true,error:null,loading:false};
 let tree=f.render({visible:true,onClose:()=>{}});button(tree,'Approved route').onPress();await tick();tree=f.render({visible:true,onClose:()=>{}});const session=all(tree,'Button').find(b=>b.props.label.includes('2026-10-01'));assert.ok(session);session.props.onPress();tree=f.render({visible:true,onClose:()=>{}});button(tree,'Friend · @friend').onPress();return f.render({visible:true,onClose:()=>{}});
}
test('unread race pages show recovery without claiming no races',()=>{const f=fixture('RaceHub');f.port.fresh=false;f.port.racesPage.fresh=false;f.port.racesPage.error='RACE_UNAVAILABLE';const tree=f.render();assert.equal(all(tree,'Empty').length,0);assert.ok(button(tree,'m5c.refresh'));});
test('a retained race row cannot open another account generation',async()=>{const f=fixture('RaceHub');f.port.races=[race()];const tree=f.render(),row=all(tree,'FlatList')[0].props.renderItem({item:race()});const open=button(row,'m5c.open');f.port.generation='B1';f.render();await open.onPress();assert.deepEqual(f.calls,[]);});
test('live countdown reads parent presentation and keeps terminal stop usable while moving',async()=>{const f=fixture('RaceLobby');f.port.race={...race(),mode:'live',state:'countdown'};f.port.attempt={id:id(10),owner_id:id(1),revision:2,race_id:id(3),member_generation:3,capture_id:id(11),state:'armed'};f.port.countdown={phase:'countdown',secondsRemaining:7,uncertaintyMs:60,error:null};f.port.gate.moving=true;let tree=f.render();assert.ok(all(tree,'T').some(v=>v.props.children===7));const stop=button(tree,'m5c.stopAttempt');assert.equal(stop.disabled,false);await stop.onPress();assert.equal(f.calls[0][0],'abort');f.port.countdown={...f.port.countdown,secondsRemaining:4};tree=f.render();assert.ok(all(tree,'T').some(v=>v.props.children===4));});
test('a retained arm button refuses a replaced capture and never starts a second recorder',async()=>{const f=fixture('RaceLobby');f.port.race=race();f.port.attempt={id:id(10),owner_id:id(1),revision:2,race_id:id(3),member_generation:3,capture_id:id(11),state:'reserved'};let tree=f.render();await button(tree,'m5c.prepareAttempt').onPress();tree=f.render();const checks=all(tree,f.load(resolve(root,'features/races/ui/RaceSurface.tsx')).ConsentChecks)[0].props;checks.onSafety(true);checks.onEvidence(true);tree=f.render();const arm=button(tree,'m5c.confirmArm');f.port.attempt={...f.port.attempt,capture_id:id(12)};f.render();await arm.onPress();assert.deepEqual(f.calls,[]);});
test('browser detail explains native qualification instead of offering a recorder',()=>{const f=fixture('RaceDetail');f.port.race=race();f.port.gate.native=false;const tree=f.render();assert.equal(all(tree,'Button').some(v=>v.props.label==='m5c.reserveAttempt'),false);assert.ok(all(tree,'Note').some(v=>v.props.children==='m5c.nativeOnly'));});
test('creation requires both independent consents and rejects a changed friend generation after review',async()=>{const f=fixture('RaceCreate');let tree=await selectTrial(f);await button(tree,'m5c.review').onPress();tree=f.render({visible:true,onClose:()=>{}});let send=button(tree,'m5c.create');assert.equal(send.disabled,true);consentChecks(f,tree).onSafety(true);tree=f.render({visible:true,onClose:()=>{}});send=button(tree,'m5c.create');assert.equal(send.disabled,true);await send.onPress();assert.deepEqual(f.calls,[]);consentChecks(f,tree).onEvidence(true);tree=f.render({visible:true,onClose:()=>{}});send=button(tree,'m5c.create');assert.equal(send.disabled,false);f.port.friends=[{...f.port.friends[0],friendship_generation:8}];f.render({visible:true,onClose:()=>{}});await send.onPress();assert.deepEqual(f.calls,[]);});
test('a held create review cannot reappear after background and leaves refresh usable',async()=>{const f=fixture('RaceCreate');let done;f.port.reviewCreate=()=>new Promise(resolve=>{done=resolve;});let tree=await selectTrial(f);const waiting=button(tree,'m5c.review').onPress();f.port.gate.foreground=false;f.render({visible:true,onClose:()=>{}});done({mode:'async',route_id:id(5),route_revision:2,approval_id:id(4),starts_at:approval().starts_at,ends_at:approval().ends_at,friends:[{user_id:id(2),friendship_generation:7}],approval:approval(),projection:race().route_snapshot,reviewed_projection_hash:'c'.repeat(64)});await waiting;f.port.gate.foreground=true;tree=f.render({visible:true,onClose:()=>{}});assert.equal(all(tree,'Button').some(v=>v.props.label==='m5c.create'),false);assert.equal(button(tree,'m5c.review').busy,false);});
test('closing and reopening a sheet releases its transient review spinner without discarding durable parent work',async()=>{const f=fixture('RaceCreate');let done;f.port.reviewCreate=()=>new Promise(resolve=>{done=resolve;});let tree=await selectTrial(f);const waiting=button(tree,'m5c.review').onPress();tree=f.render({visible:true,onClose:()=>{}});assert.equal(button(tree,'m5c.review').busy,true);all(tree,'RouteSheet')[0].props.onClose();f.render({visible:false,onClose:()=>{}});f.render({visible:true,onClose:()=>{}});tree=f.render({visible:true,onClose:()=>{}});assert.equal(button(tree,'m5c.review').busy,false);assert.equal(button(tree,'m5c.approvalRetry').disabled,false);done({mode:'async',route_id:id(5),route_revision:2,approval_id:id(4),starts_at:approval().starts_at,ends_at:approval().ends_at,friends:[{user_id:id(2),friendship_generation:7}],approval:approval(),projection:race().route_snapshot,reviewed_projection_hash:'c'.repeat(64)});await waiting;tree=f.render({visible:true,onClose:()=>{}});assert.equal(all(tree,'Button').some(v=>v.props.label==='m5c.create'),false);assert.deepEqual(f.calls,[]);});
test('rematch startCreate opens a fresh creation review without auto-selecting a course or sending',()=>{const f=fixture('RaceHub');f.render({startCreate:true});const tree=f.render({startCreate:true});const create=all(tree,f.load(resolve(root,'features/races/ui/RaceCreate.tsx')).default)[0];assert.ok(create);assert.equal(create.props.visible,true);assert.deepEqual(f.calls,[]);});
test('race translation registry exports literal-compatible dotted keys with Thai and English parity',()=>{const f=fixture('RaceHub'),{m5cEn,m5cTh}=f.load(resolve(root,'lib/raceI18n.ts'));assert.deepEqual(Object.keys(m5cTh).sort(),Object.keys(m5cEn).sort());assert.equal(typeof m5cEn['m5c.actions.attempt_arm'],'string');assert.equal(typeof m5cTh['m5c.retryEvidence'],'string');assert.equal('m5c' in m5cEn,false);});
test('a create review accepts shuffled JSON key order while preserving exact selection bindings',async()=>{const f=fixture('RaceCreate');f.port.reviewCreate=async s=>({approval:approval(),projection:race().route_snapshot,reviewed_projection_hash:'c'.repeat(64),friends:s.friends,ends_at:s.ends_at,starts_at:s.starts_at,approval_id:s.approval_id,route_revision:s.route_revision,route_id:s.route_id,mode:s.mode});let tree=await selectTrial(f);await button(tree,'m5c.review').onPress();tree=f.render({visible:true,onClose:()=>{}});consentChecks(f,tree).onSafety(true);consentChecks(f,tree).onEvidence(true);tree=f.render({visible:true,onClose:()=>{}});await button(tree,'m5c.create').onPress();assert.equal(f.calls.length,1);assert.equal(f.calls[0][0],'create');assert.deepEqual(JSON.parse(JSON.stringify(f.calls[0][2])),{acknowledgement_version:1,evidence_consent_version:1});});
test('the 31st loaded route is reachable and a fourth competitor cannot be selected',async()=>{const f=fixture('RaceCreate');f.port.routes=Array.from({length:31},(_,i)=>({id:id(i+100),revision:1,title:'Route '+i,category:'scooter'}));f.port.friends=Array.from({length:4},(_,i)=>({user_id:id(i+200),friendship_generation:1,name:'Friend '+i,handle:'friend'+i}));let tree=f.render({visible:true,onClose:()=>{}});assert.ok(button(tree,'Route 30'));for(let i=0;i<3;i++){button(tree,`Friend ${i} · @friend${i}`).onPress();tree=f.render({visible:true,onClose:()=>{}});}assert.equal(button(tree,'Friend 3 · @friend3').disabled,true);});
test('ready does not imply location sharing and requires its own explicit review of both consents',async()=>{const f=fixture('RaceLobby');f.port.race={...race(),mode:'live',state:'lobby'};f.port.attempt={id:id(10),owner_id:id(1),revision:2,race_id:id(3),member_generation:3,capture_id:id(11),state:'armed'};let tree=f.render();await button(tree,'m5c.ready').onPress();assert.deepEqual(f.calls,[]);tree=f.render();const sheet=all(tree,'RouteSheet').find(v=>v.props.visible);assert.ok(sheet);assert.equal(button(sheet,'m5c.ready').disabled,true);consentChecks(f,tree).onSafety(true);consentChecks(f,tree).onEvidence(true);tree=f.render();await button(all(tree,'RouteSheet').find(v=>v.props.visible),'m5c.ready').onPress();assert.equal(f.calls.length,1);assert.equal(f.calls[0][0],'readyAttempt');});
test('terminal cancellation bypasses a held arm request and is never blocked by its local spinner',async()=>{const f=fixture('RaceLobby');f.port.race=race();f.port.attempt={id:id(10),owner_id:id(1),revision:2,race_id:id(3),member_generation:3,capture_id:id(11),state:'reserved'};let done;f.port.arm=()=>new Promise(resolve=>{done=resolve;});let tree=f.render();await button(tree,'m5c.prepareAttempt').onPress();tree=f.render();consentChecks(f,tree).onSafety(true);consentChecks(f,tree).onEvidence(true);tree=f.render();const waiting=button(tree,'m5c.confirmArm').onPress();tree=f.render();await button(tree,'m5c.stopAttempt').onPress();assert.equal(f.calls[0][0],'abort');done(id(20));await waiting;});
test('explicit consented arming permits the parent to acquire stage proof and clock probes without preprobing',async()=>{const f=fixture('RaceLobby');f.port.race=race();f.port.attempt={id:id(10),owner_id:id(1),revision:2,race_id:id(3),member_generation:3,capture_id:id(11),state:'reserved'};f.port.eligibility.stageReady=false;f.port.eligibility.clockReady=false;let tree=f.render();await button(tree,'m5c.prepareAttempt').onPress();assert.deepEqual(f.calls,[]);tree=f.render();consentChecks(f,tree).onSafety(true);consentChecks(f,tree).onEvidence(true);tree=f.render();const confirm=button(tree,'m5c.confirmArm');assert.equal(confirm.disabled,false);await confirm.onPress();assert.equal(f.calls[0][0],'arm');});
test('evidence recovery dispatches the same exact attempt without acquiring another recorder',async()=>{for(const state of ['upload_pending','queued','verifying']){const f=fixture('RaceLobby');f.port.race=race();f.port.attempt={id:id(10),owner_id:id(1),revision:5,race_id:id(3),member_generation:3,capture_id:id(11),state};f.port.eligibility.captureReady=false;const tree=f.render();await button(tree,'m5c.retryEvidence').onPress();assert.equal(f.calls.length,1);assert.equal(f.calls[0][0],'finishAttempt');assert.deepEqual(JSON.parse(JSON.stringify(f.calls[0][1])),{attempt_id:id(10),expected_revision:5,race_id:id(3),member_generation:3,capture_id:id(11)});}});
test('new account generations cannot retain another rider\'s creation selections or consent',async()=>{const f=fixture('RaceCreate');let tree=await selectTrial(f);await button(tree,'m5c.review').onPress();tree=f.render({visible:true,onClose:()=>{}});consentChecks(f,tree).onSafety(true);consentChecks(f,tree).onEvidence(true);f.port.generation='B1';f.port.routes=[];f.port.friends=[];f.port.approvals={route_id:null,route_revision:null,items:[],fresh:true,error:null,loading:false};f.render({visible:true,onClose:()=>{}});tree=f.render({visible:true,onClose:()=>{}});assert.equal(all(tree,'Button').some(v=>v.props.label==='m5c.create'),false);assert.equal(all(tree,'Field').some(v=>v.props.label==='m5c.startsAt'),false);assert.deepEqual(f.calls,[]);});
test('results keep overlapping chains tied, nullable speed unavailable and processing separate from verified',()=>{const f=fixture('RaceResults');f.port.race=race();const result=(n,lower,upper)=>({attempt_id:id(n),owner_id:id(1),race_id:id(3),approval_id:id(4),config_hash:'b'.repeat(64),elapsed_lower_ms:lower,elapsed_upper_ms:upper,verified_at:'2026-10-01T10:30:00Z',distance_m:1000,maximum_speed_mps:null,average_speed_mps:10,provenance_unknown:true});f.port.results={race_id:id(3),items:[result(20,10000,11000),result(21,10900,12000),result(22,11900,13000),result(23,14000,15000)],statuses:[{user_id:id(1),state:'processing'}]};const tree=f.render(),ranks=all(tree,'T').filter(v=>v.props.size===28).map(v=>v.props.children);assert.deepEqual(ranks,[1,1,1,4]);assert.equal(all(tree,'T').filter(v=>v.props.children==='m5c.speedUnavailable').length,4);assert.ok(all(tree,'T').some(v=>v.props.children==='m5c.resultStates.processing'));assert.equal(all(tree,'T').some(v=>v.props.children==='m5c.resultStates.verified'),false);});
test('every native View in rendered screens contains elements rather than raw whitespace',async()=>{for(const name of ['RaceHub','RaceDetail','RaceLobby','RaceResults','RaceCreate']){const f=fixture(name);f.port.race=race();const tree=name==='RaceCreate'?await selectTrial(f):f.render();for(const node of all(tree,'View'))assert.equal([node.props.children].flat(Infinity).some(v=>typeof v==='string'||typeof v==='number'),false,name);}});
test('detail and restarted lobby mount the approved private-course component without disabling invitation map capability',()=>{for(const name of ['RaceDetail','RaceLobby']){const f=fixture(name);f.port.race=race();const tree=f.render(),privateMap=all(tree,'RaceCourseMap');assert.equal(privateMap.length,1,name);assert.equal(privateMap[0].props.port,f.port);for(const preview of all(tree,'SharedRouteSnapshot'))assert.notEqual(preview.props.map,false);}});
