import {test} from 'node:test';import assert from 'node:assert/strict';import {raceModule} from './helpers/races.mjs';
const {RaceGatePreview}=raceModule('gatePreview');
export const course=()=>({origin:{latitude:13,longitude:100},gates:[{index:0,kind:'start',a:{latitude:12.9998,longitude:100.0001},b:{latitude:13.0002,longitude:100.0001},forward_point:{latitude:13,longitude:100.0002},progress_min_m:0,progress_max_m:30},{index:1,kind:'finish',a:{latitude:12.9998,longitude:100.0011},b:{latitude:13.0002,longitude:100.0011},forward_point:{latitude:13,longitude:100.0012},progress_min_m:100,progress_max_m:150}],geometry_error_margin_m:.25,maximum_accuracy_m:15,maximum_gap_ms:1500,maximum_crossing_span_ms:3000});
export const fix=(sequence,x,ms=sequence*1000)=>({sequence,latitude:13,longitude:100+x,accuracyM:2,timestampMs:ms});
test('provisional preview follows finite ordered directed gates and retains real before/after observations',()=>{const p=new RaceGatePreview(course());assert.equal(p.accept(fix(0,0)).crossing,null);const start=p.accept(fix(1,.0002));assert.equal(start.crossing.index,0);assert.equal(start.crossing.before.sequence,0);assert.equal(start.crossing.after.sequence,1);for(let i=2;i<=5;i++)p.accept(fix(i,.0002*i));assert.equal(p.accept(fix(6,.0012)).state,'finish');});
test('uncertain side does not create an interpolated crossing; wide bracket is rejected',()=>{const p=new RaceGatePreview(course());p.accept(fix(0,0));p.accept(fix(1,.0001));p.accept(fix(2,.0001));p.accept(fix(3,.0001));assert.equal(p.accept(fix(4,.0002)).state,'invalid');});
test('skipped finite gate and starting after start gate cannot be assigned optimistic time',()=>{const p=new RaceGatePreview(course());assert.equal(p.accept(fix(0,.0002)).state,'invalid');const outside=new RaceGatePreview(course());outside.accept({...fix(0,0),latitude:13.001});assert.equal(outside.accept({...fix(1,.0002),latitude:13.001}).state,'invalid');});
test('missing original sequence/gap/backward timestamps invalidate preview instead of stitching fixes',()=>{for(const bad of [fix(2,.0002),fix(1,.0002,1600),fix(1,.0002,0)]){const p=new RaceGatePreview(course());p.accept(fix(0,0));assert.equal(p.accept(bad).state,'invalid');}});
test('one uncertain motion segment spanning two gates is rejected, never declared finished',()=>{const p=new RaceGatePreview(course());p.accept(fix(0,0));assert.equal(p.accept(fix(1,.0012)).state,'invalid');});
