import test from 'node:test';
import assert from 'node:assert/strict';
import {buildRaceEvidence} from '../src/features/races/evidenceModel.ts';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,copy=v=>JSON.parse(JSON.stringify(v));
function rawInput(){const capture={id:id(4),segmentId:id(5),provider:'expo_location',count:4,truncated:false,startedAtMs:1000,endedAtMs:null,startedMonotonicMs:0,endedMonotonicMs:null};return {binding:{scope:{userId:id(1),generation:1},rideId:id(3),captureId:capture.id,segmentId:capture.segmentId,generation:1,platform:'android',provider:capture.provider,startedWallMs:1000,startedMonotonicMs:0},read:{ride:{id:id(3),ownerId:id(1),clockAnomaly:false,captures:[capture]},capture,receipts:Array.from({length:4},(_,seq)=>({seq,captureId:capture.id,segmentId:capture.segmentId,accepted:seq!==1,receivedAtMs:1000+seq*1000,receivedMonotonicMs:seq*1000,sample:{timestampMs:1000+seq*1000,latitude:13,longitude:100+seq*.0001,speedMps:null,horizontalAccuracyM:seq===1?80:5,speedAccuracyMps:null,mocked:seq===1?true:null,isSimulatedBySoftware:null,isProducedByAccessory:null}}))},race:{id:id(6),mode:'async',schedule_epoch:null,common_start_at:null,approval:{id:id(7),config_hash:'a'.repeat(64)}},attempt:{id:id(8),owner_id:id(1),race_id:id(6),approval_id:id(7),config_hash:'a'.repeat(64),ride_id:id(3),capture_id:id(4),platform:'android',provider:'expo_location',state:'armed',schedule_epoch:null,common_start_at:null},clockGeneration:id(9),armClockProbeIds:[id(10),id(11),id(12)],clockProbes:[10,11,12].map((n,index)=>({probe_id:id(n),clock_generation:id(9),request_started_monotonic_ms:index*10,request_started_wall_ms:1000+index*10,received_monotonic_ms:index*10+5,received_wall_ms:1005+index*10})),lifecycle:[{kind:'armed',received_monotonic_ms:100,received_wall_ms:1100},{kind:'finish_observed',received_monotonic_ms:3100,received_wall_ms:4100}]};}
function input(){const value=rawInput();for(const receipt of value.read.receipts){receipt.receivedMonotonicMs+=100;receipt.receivedAtMs+=100;receipt.sample.timestampMs+=100;}return value;}
test('evidence exports the exact continuous raw range, retaining failed quality and nullable provenance',()=>{const source=input(),frozen=buildRaceEvidence(source),value=JSON.parse(frozen.text);assert.equal(value.samples.length,4);assert.equal(value.samples[1].mocked,true);assert.equal(value.samples[1].horizontal_accuracy_m,80);assert.equal(value.samples[0].is_simulated_by_software,null);assert.equal(value.samples[0].received_monotonic_ms,100);assert.equal(frozen.byteLength,new TextEncoder().encode(frozen.text).length);source.read.receipts[0].sample.latitude=99;assert.equal(JSON.parse(frozen.text).samples[0].latitude,13);assert.ok(Object.isFrozen(frozen));});
test('legacy clocks, missing receipts, changed owner/capture, browser and truncation cannot qualify',()=>{for(const mutate of [v=>delete v.read.receipts[1].receivedMonotonicMs,v=>v.read.receipts.splice(1,1),v=>v.read.ride.ownerId=id(99),v=>v.read.capture.id=id(99),v=>v.binding.platform='web',v=>v.read.capture.truncated=true,v=>v.read.ride.clockAnomaly=true,v=>v.attempt.capture_id=id(99)]){const value=input();mutate(value);assert.throws(()=>buildRaceEvidence(value),/RACE_EVIDENCE_UNAVAILABLE/);}});
test('the exporter never fabricates original probe/lifecycle readings or crosses a live schedule binding',()=>{for(const mutate of [v=>delete v.clockProbes[0].request_started_wall_ms,v=>v.clockProbes[0].clock_generation=id(99),v=>v.clockProbes.push(copy(v.clockProbes[0])),v=>v.armClockProbeIds=[id(99),id(11),id(12)],v=>v.lifecycle.reverse(),v=>v.lifecycle[1].received_monotonic_ms=10,v=>{v.race.mode='live';v.race.common_start_at='2026-10-01T00:00:00Z';v.race.schedule_epoch=id(99);}]){const value=input();mutate(value);assert.throws(()=>buildRaceEvidence(value),/RACE_EVIDENCE_UNAVAILABLE/);}});
