import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {resolve,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import {owner,peer,uuid,stamp,snapshot,attempt,copy,hold,tick} from './helpers/races.mjs';

const require=createRequire(import.meta.url),ts=require('typescript'),root=fileURLToPath(new URL('../src/',import.meta.url));
/** Actual provider, reader, both coordinators and OriginalCaptureBus. Native
 * lifecycle, captured transport and durable storage are controlled ports. The
 * disabled production pilot literal is enabled in this VM fixture only; no
 * production gate or operator-approval implementation is changed. */
function harness(){
 const cells=[],effects=[],layouts=[],listeners=new Set(),timers=new Map(),cache=new Map(),owned=new Map(),reads=[],sends=[],statuses=[],cancellations=[],controllers=[],readers=[],coordinators=[],proofs=[],receipts=new Map(),fileWrites=[],fileRemovals=[],originalReads=[],heartbeats=[];
 let index=0,dirty=false,timerId=0,next=100,mono=1000,wall=Date.parse(stamp),pathname='/races',scope={userId:owner,generation:1},session={user:{id:owner},access_token:'fixture-A-1'},bus;
 const behavior={storageError:null,writeFailure:false,flushHold:null,sendHold:null,readHold:null,attemptReadHold:null,attemptListHold:null,heartbeatHold:null,moving:false,gpsStarts:0,flushes:0};
 let race=snapshot();race.mode='async';race.state='open';let ownAttempt=null;
 const configuration={origin:{latitude:13,longitude:100},gates:[{index:0,kind:'start',a:{latitude:12.9998,longitude:100.0001},b:{latitude:13.0002,longitude:100.0001},forward_point:{latitude:13,longitude:100.0002},progress_min_m:0,progress_max_m:30},{index:1,kind:'finish',a:{latitude:12.9998,longitude:100.0011},b:{latitude:13.0002,longitude:100.0011},forward_point:{latitude:13,longitude:100.0012},progress_min_m:100,progress_max_m:150}],geometry_error_margin_m:.25,maximum_accuracy_m:15,maximum_gap_ms:1500,maximum_crossing_span_ms:3000,minimum_duration_ms:10000,maximum_duration_ms:1800000};
 const course={race_id:race.id,approval_id:race.approval.id,config_hash:race.approval.config_hash,route_geometry_hash:race.approval.route_geometry_hash,configuration};
 const blank=()=>({raceOperations:[],raceEvidence:[]});owned.set(owner,blank());
 const native={currentState:'active',addEventListener(_event,fn){listeners.add(fn);return {remove:()=>listeners.delete(fn)};}};
 const React={createContext(value){const context={value};context.Provider={context};return context;},useContext:c=>c.value,createElement(type,props,...children){if(type?.context)type.context.value=props.value;return {type,props,children};},
  useState(value){const at=index++;if(!(at in cells))cells[at]={value:typeof value==='function'?value():value,set:nextValue=>{cells[at].value=typeof nextValue==='function'?nextValue(cells[at].value):nextValue;dirty=true;}};return[cells[at].value,cells[at].set];},
  useRef(value){const at=index++;return cells[at]??={current:value};},useMemo(fn,deps){const at=index++;if(!cells[at]||deps.some((v,i)=>v!==cells[at].deps[i]))cells[at]={deps,value:fn()};return cells[at].value;},useCallback(fn,deps){return React.useMemo(()=>fn,deps);},
  useEffect(fn,deps){enqueue(effects,fn,deps);},useLayoutEffect(fn,deps){enqueue(layouts,fn,deps);},useSyncExternalStore(subscribe,get){const at=index++;if(cells[at]?.subscribe!==subscribe){cells[at]?.remove?.();cells[at]={subscribe,remove:subscribe(()=>dirty=true)};}return get();},
 };
 function enqueue(queue,fn,deps){const at=index++,old=cells[at];if(!old||!deps||!old.deps||deps.length!==old.deps.length||deps.some((v,i)=>v!==old.deps[i])){cells[at]={deps};queue.push(()=>{old?.cleanup?.();cells[at].cleanup=fn();});}}
 class FixedDate extends Date{constructor(...args){super(...(args.length?args:[wall]));}static now(){return wall;}}
 const app=()=>({ready:true,storageError:behavior.storageError,data:owned.get(scope.userId)??blank(),vehicle:null,getOwned:()=>owned.get(scope.userId)??blank(),update(patch){if(behavior.writeFailure||behavior.storageError==='LOCAL_READ_FAILED')return false;owned.set(scope.userId,{...(owned.get(scope.userId)??blank()),...patch});dirty=true;return true;},flushStorage:async()=>{behavior.flushes++;if(behavior.flushHold)await behavior.flushHold.promise;},retryStorage:async()=>{}});
 const service={
  async listRaces(requested,_session){reads.push({kind:'list',scope:requested});return {owner_id:requested.userId,server_now:stamp,items:requested.userId===owner?[copy(race)]:[],next_cursor:null};},
  async getRace(requested,_session,id){reads.push({kind:'race',scope:requested,id});if(behavior.readHold?.kind==='race')await behavior.readHold.promise;return requested.userId===owner?copy(race):null;},
  async getRaceAttempt(requested,_session,id){reads.push({kind:'attempt',scope:requested,id});const value=requested.userId===owner&&ownAttempt?.id===id?copy(ownAttempt):null;if(behavior.attemptReadHold)await behavior.attemptReadHold.promise;return value;},
  async listRaceAttempts(requested,_session,id){reads.push({kind:'attempts',scope:requested,id});const value={owner_id:requested.userId,race_id:id,items:requested.userId===owner&&ownAttempt?[copy(ownAttempt)]:[]};const blocked=behavior.attemptListHold;behavior.attemptListHold=null;if(blocked)await blocked.promise;return value;},
  async getRaceCourse(requested,_session,id){reads.push({kind:'course',scope:requested,id});return copy(course);},
  async getRaceResults(requested,_session,id){return {owner_id:requested.userId,race_id:id,server_now:stamp,items:[],statuses:[]};},async listRaceApprovals(){return {items:[],server_now:stamp};},
  async getRaceOperation(requested,_session,id){statuses.push({scope:requested,id});return receipts.get(id)??null;},
  async mutateRace(requested,_session,op){sends.push({scope:requested,op:copy(op),foreground:native.currentState});if(behavior.sendHold?.action===op.request.action)await behavior.sendHold.promise;
   const q=op.request;let result;if(q.action==='attempt_reserve'){ownAttempt={...attempt(),id:q.attempt_id,race_id:q.race_id,owner_id:requested.userId,ride_id:q.ride_id,capture_id:q.capture_id,platform:q.platform,provider:q.provider,state:'reserved',revision:1,armed_at:null};result={action:q.action,attempt:copy(ownAttempt)};}
   else if(q.action==='attempt_arm'){ownAttempt={...ownAttempt,state:'armed',revision:ownAttempt.revision+1,armed_at:new Date(wall).toISOString()};result={action:q.action,attempt:copy(ownAttempt)};}
   else if(q.action==='attempt_abort'){if(q.expected_revision!==ownAttempt.revision)return {error:{code:'RACE_ATTEMPT_CHANGED'}};ownAttempt={...ownAttempt,state:'aborted',revision:ownAttempt.revision+1,terminal_reason:q.reason,terminal_at:new Date(wall).toISOString()};result={action:q.action,attempt:copy(ownAttempt)};}
   else throw Error(`Unexpected fixture action ${q.action}`);
   const value={owner_id:requested.userId,operation_id:op.operation_id,request:op.request,applied_at:new Date(wall).toISOString(),result};receipts.set(op.operation_id,value);return value;
  },
  async cancelRaceActivation(requested,_session,op){cancellations.push({scope:requested,op});return receipts.get(op.operation_id)??{kind:'cancelled',owner_id:requested.userId,operation_id:op.operation_id,request:op.request,cancelled_at:new Date(wall).toISOString()};},
  async probeRaceClock(requested,_session,value){mono+=10;wall+=10;proofs.push(value);return {owner_id:requested.userId,...value,server_received_at:new Date(wall-8).toISOString(),server_sent_at:new Date(wall-5).toISOString()};},
  async publishRaceStage(requested,_session,value){return {owner_id:requested.userId,race_id:value.race_id,member_generation:value.member_generation,attempt_id:value.attempt_id,capture_id:value.capture_id,lobby_epoch:value.lobby_epoch,sequence:value.sequence,proof_id:uuid(next++),received_at:new Date(wall).toISOString(),expires_at:new Date(wall+3000).toISOString()};},async heartbeatRace(requested,_session,value){heartbeats.push({scope:requested,value,foreground:native.currentState});if(behavior.heartbeatHold)await behavior.heartbeatHold.promise;return {owner_id:requested.userId,race_id:value.race_id,server_now:new Date(wall).toISOString(),host_lease_until:new Date(wall+45000).toISOString(),self_ready:null};},
 };
 const overrides={react:React,'react-native':{AppState:native,Platform:{OS:'ios'}},'expo-crypto':{randomUUID:()=>uuid(next++)},'expo-router':{usePathname:()=>pathname,router:{push(){}}},
  './AppState':{useApp:app},'./AuthState':{useAuth:()=>({ready:true,scope,session}),isAccountCurrent:s=>s===scope},'../../state/AuthState':{isAccountCurrent:s=>s===scope},
  './RideState':{useRide:()=>({originalCapture:bus,movingLocked:behavior.moving,start(){behavior.gpsStarts++;},readOriginalCapture:async(...args)=>{originalReads.push(args);throw Error('Candidate not expected');}})},
  './SocialState':{useSocial:()=>({profileReady:true,friends:[],fresh:true,pages:{friends:{fresh:true,error:null,loading:false,hasMore:false}},refresh:async()=>{},loadMoreFriends:async()=>{}})},
  '../features/races/service':service,'../features/routes/syncService':{listRoutesOwner:async()=>({items:[],next_cursor:null}),getRouteProjection:async()=>null},
  '../features/races/evidenceStorage':{raceEvidenceStorage:{closeOwner:async()=>{},put:async(...args)=>{fileWrites.push(args);throw Error('Candidate not expected');},read:async()=>{throw Error('Candidate not expected');},removeTerminal:async(...args)=>{fileRemovals.push(args);}}},
  '../features/races/evidenceService':{uploadRaceEvidence:async()=>{},requestRaceVerification:async()=>{}},
 };
 const sandbox={Promise,Error,Date:FixedDate,JSON,Set,Map,WeakMap,TextEncoder,TextDecoder,URL,performance:{now:()=>mono},setInterval:(fn,delay)=>{const id=++timerId;timers.set(id,{fn,delay});return id;},clearInterval:id=>timers.delete(id),console,process:{env:{}}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith('RaceState.tsx')){assert.ok(source.includes('const pilotEnabled=false'));source=source.replace('const pilotEnabled=false','const pilotEnabled=true');}const code=ts.transpileModule(source,{fileName:path,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.React,esModuleInterop:true}}).outputText;vm.runInNewContext(code,{...sandbox,module,exports:module.exports,require:name=>{if(name in overrides)return overrides[name];if(!name.startsWith('.'))return require(name);const base=resolve(dirname(path),name),target=['.ts','.tsx'].map(ext=>base+ext).find(existsSync)??base;return load(target);}});return module.exports;}
 for(const [name,list,key] of [['RaceReader',readers,'./RaceReader'],['RaceCoordinator',coordinators,'../features/races/RaceCoordinator'],['RaceAttemptCoordinator',controllers,'../features/races/RaceAttemptCoordinator']]){const actual=load(resolve(root,name==='RaceReader'?'state/RaceReader.ts':`features/races/${name}.ts`));const Base=actual[name];overrides[key]={...actual,[name]:class extends Base{constructor(...args){super(...args);this.testPort=args[0];this.closedCount=0;list.push(this);}close(){this.closedCount++;super.close();}}};}
 const {OriginalCaptureBus}=load(resolve(root,'features/races/OriginalCaptureBus.ts'));bus=new OriginalCaptureBus(b=>b.scope===scope);
 const provider=load(resolve(root,'state/RaceState.tsx'));
 const h={behavior,owned,reads,sends,statuses,receipts,cancellations,controllers,readers,coordinators,proofs,bus,service,timers,fileWrites,fileRemovals,originalReads,heartbeats,
  get scope(){return scope;},get race(){return race;},get attempt(){return ownAttempt;},get state(){return provider.useRace();},
  render(){index=0;dirty=false;provider.RaceProvider({children:null});while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return provider.useRace();},
  async settle(){for(let i=0;i<20;i++){await tick();if(dirty)h.render();}return h.render();},
  switch(id){scope={userId:id,generation:scope.generation+1};session=id?{user:{id},access_token:`fixture-${id}-${scope.generation}`}:null;if(!owned.has(id))owned.set(id,blank());return h.render();},
  background(){native.currentState='background';listeners.forEach(f=>f('background'));return h.render();},foreground(){native.currentState='active';listeners.forEach(f=>f('active'));return h.render();},
  recorderBackground(){native.currentState='background';bus.invalidate('background');listeners.forEach(f=>f('background'));return h.render();},
  advance(ms){mono+=ms;wall+=ms;},bind(){bus.bind({scope,rideId:uuid(13),captureId:uuid(5),segmentId:uuid(15),platform:'ios',provider:'expo_location',startedWallMs:wall,startedMonotonicMs:mono});return h.render();},
  pulse(delay){for(const timer of [...timers.values()])if(timer.delay===delay)timer.fn();},
  sample(seq=0){const b=bus.getBinding();bus.accept({captureId:b.captureId,segmentId:b.segmentId,seq,accepted:true,receivedAtMs:wall,receivedMonotonicMs:mono,sample:{timestampMs:wall,latitude:13,longitude:100,horizontalAccuracyM:2,speedMps:0,speedAccuracyMps:null,mocked:null,isSimulatedBySoftware:null,isProducedByAccessory:null}});},
  async open(){await h.state.port.openRace(race.id);await h.settle();return h.state;},async reserve(){const p=h.state.port,r=p.race;await p.reserve({race_id:r.id,expected_revision:r.revision,lobby_epoch:r.lobby_epoch,expected_member_generation:r.self_member.member_generation,expected_friendship_generation:r.self_member.friendship_generation},{acknowledgement_version:1,evidence_consent_version:1});return h.settle();},
  async arm(){const p=h.state.port,a=p.attempt;return p.arm({attempt_id:a.id,expected_revision:a.revision,race_id:a.race_id,member_generation:a.member_generation,capture_id:a.capture_id},{acknowledgement_version:1,evidence_consent_version:1});},
  seed(patch){owned.set(scope.userId,{...owned.get(scope.userId),...patch});return h.render();},terminal(state='verified'){ownAttempt={...ownAttempt,state,revision:ownAttempt.revision+1,terminal_at:new Date(wall).toISOString()};return h.state.port.refresh();},live(host=true){race.mode='live';race.state='lobby';if(!host)race.creator_id=peer;return h.render();},delete:()=>provider.clearRaceAccount(scope),
 };h.render();return h;
}

test('native race provider passively observes the existing recorder and starts no GPS watcher',async()=>{const h=harness();await h.settle();assert.equal(h.state.port.eligibility.captureReady,false);h.bind();await h.settle();assert.equal(h.state.port.eligibility.captureReady,true);assert.equal(h.behavior.gpsStarts,0);assert.equal(h.proofs.length,0);assert.equal(h.sends.length,0);});

test('replacing an attempt controller leaves owner reader and durable control coordinator alive',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();assert.ok(h.state.port.attempt);assert.ok(h.controllers.length>=2);assert.equal(h.readers.at(-1).closedCount,0);assert.equal(h.coordinators.at(-1).closedCount,0);const before=h.reads.length;await h.state.port.refresh();await h.settle();assert.ok(h.reads.length>before);assert.equal(h.state.port.error,null);});

test('background synchronously disarms native authority and retains a durable abort without network',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();await h.arm();await h.settle();assert.equal(h.controllers.at(-1).getSnapshot().phase,'armed');const sends=h.sends.length;h.background();await h.settle();assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');const pending=h.owned.get(owner).raceOperations;assert.equal(pending.length,1);assert.equal(pending[0].request.action,'attempt_abort');assert.ok(h.behavior.flushes>0);assert.equal(h.sends.length,sends);assert.equal(h.sends.some(s=>s.foreground!=='active'),false);});

test('held native arm response after owner ABA never arms the replacement scope or adopts private evidence',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();const blocked=hold();h.behavior.sendHold={action:'attempt_arm',...blocked};const arming=h.arm();await tick();await tick();const old=h.scope;h.switch(peer);await h.settle();h.switch(owner);await h.settle();blocked.resolve();await arming;await h.settle();assert.notEqual(h.scope,old);assert.equal(h.controllers.at(-1).getSnapshot().phase,'idle');assert.equal(h.state.port.attempt,null);assert.equal(h.owned.get(owner).raceEvidence.length,0);assert.equal(h.behavior.gpsStarts,0);});

test('held periodic older bundle cannot replace a newer armed canonical bundle',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();const blocked=hold(),before=h.reads.filter(r=>r.kind==='attempts').length;h.behavior.attemptListHold=blocked;h.pulse(6000);await tick();await tick();await tick();assert.ok(h.reads.filter(r=>r.kind==='attempts').length>before);h.sample();await h.arm();await h.settle();assert.equal(h.state.port.attempt.state,'armed');blocked.resolve();await h.settle();assert.equal(h.state.port.attempt.state,'armed');assert.equal(h.state.port.attempt.revision,2);assert.equal(h.controllers.at(-1).getSnapshot().phase,'armed');});

test('background stop survives a held applied arm by reconciling the exact current attempt CAS on foreground',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();const blocked=hold();h.behavior.sendHold={action:'attempt_arm',...blocked};const arming=h.arm();await tick();await tick();h.background();await h.settle();assert.equal(h.sends.some(s=>s.foreground!=='active'),false);blocked.resolve();await arming;await h.settle();assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');h.foreground();await h.settle();assert.equal(h.attempt.state,'aborted');assert.equal(h.state.port.attempt.state,'aborted');assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');});

test('original recorder invalidation disarms and terminates the pinned attempt after the bus clears its binding',async()=>{for(const reason of ['stop','source_error','storage_error']){const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();await h.arm();await h.settle();assert.equal(h.controllers.at(-1).getSnapshot().phase,'armed');h.bus.invalidate(reason);await h.settle();assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');assert.equal(h.attempt.state,'aborted');assert.equal(h.sends.at(-1).op.request.action,'attempt_abort');assert.equal(h.sends.at(-1).op.request.reason,reason==='stop'?'user_stop':reason==='storage_error'?'storage_error':'capture_changed');}});

test('recorder binding invalidation before OS background notification retains abort without background transport',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();await h.arm();await h.settle();const before=h.sends.length;h.recorderBackground();await h.settle();assert.equal(h.bus.getBinding(),null);assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');assert.equal(h.sends.length,before);assert.equal(h.owned.get(owner).raceOperations[0].request.reason,'background');});

test('failed first stop-intent write remains retryable after storage recovers',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();await h.arm();await h.settle();h.behavior.writeFailure=true;h.bus.invalidate('stop');await h.settle();assert.equal(h.attempt.state,'armed');assert.equal(h.controllers.at(-1).getSnapshot().phase,'invalid');h.behavior.writeFailure=false;await h.state.stopCompetitiveAttempt();await h.settle();assert.equal(h.attempt.state,'aborted');});

const evidenceRef=(a,n=a.id)=>({owner_id:owner,attempt_id:n,race_id:a.race_id,ride_id:a.ride_id,capture_id:a.capture_id,sha256:'c'.repeat(64),byte_length:1024,first_sequence:0,last_sequence:3,sample_count:4});

test('canonical terminal proof releases only its local upload copy after exact unknown operation recovery',async()=>{
 const h=harness();h.bind();await h.settle();await h.open();await h.reserve();const a=copy(h.attempt),ref=evidenceRef(a),other=evidenceRef(a,uuid(800)),request={schema_version:1,action:'evidence_queue',attempt_id:a.id,expected_revision:3,sha256:ref.sha256},op={operation_id:uuid(801),request,queued_at:stamp,last_error:null};
 h.seed({raceEvidence:[ref,other],raceOperations:[op]});await h.terminal();await h.settle();assert.equal(h.state.port.attempt.state,'verified');assert.equal(h.owned.get(owner).raceOperations.length,1);assert.deepEqual(h.fileRemovals,[]);assert.equal(h.owned.get(owner).raceEvidence.length,2);
 const evidence={bucket:'ride-race-evidence',path:`${owner}/${a.id}/route-time-v1.json`,attempt_id:a.id,capture_id:a.capture_id,sha256:ref.sha256,byte_length:ref.byte_length,first_sequence:0,last_sequence:3,sample_count:4,upload_deadline:'2026-10-01T02:05:00Z'};
 h.receipts.set(op.operation_id,{owner_id:owner,operation_id:op.operation_id,request,applied_at:stamp,result:{action:'evidence_queue',attempt:{...a,state:'queued',revision:4,armed_at:stamp,evidence}}});await h.state.port.retry();await h.settle();
 assert.equal(h.owned.get(owner).raceOperations.length,0);assert.equal(h.fileRemovals.length,1);assert.equal(h.fileRemovals[0][0],h.scope);assert.equal(h.fileRemovals[0][1].attempt_id,a.id);assert.deepEqual(h.owned.get(owner).raceEvidence,[other]);assert.ok(h.behavior.flushes>0);
});

test('full local evidence capacity rejects a new candidate before journal export or immutable file creation',async()=>{
 const h=harness();h.bind();await h.settle();await h.open();await h.reserve();const a=copy(h.attempt),binding=h.bus.getBinding();h.seed({raceEvidence:Array.from({length:32},(_,i)=>evidenceRef(a,uuid(900+i)))});
 const candidate={binding,attempt:a,firstSequence:0,lastSequence:3,sampleCount:4};await assert.rejects(h.controllers.at(-1).testPort.onFrozenCandidate(candidate),/RACE_CAPACITY/);assert.equal(h.originalReads.length,0);assert.equal(h.fileWrites.length,0);assert.equal(h.fileRemovals.length,0);assert.equal(h.owned.get(owner).raceEvidence.length,32);
});

test('native host lobby heartbeat uses no capture or readiness and held replies cannot refresh after background or deletion',async()=>{
 for(const boundary of ['background','deletion']){const h=harness();h.live();await h.settle();await h.open();const blocked=hold();h.behavior.heartbeatHold=blocked;h.pulse(5000);await tick();assert.equal(h.heartbeats.length,1);assert.equal(h.heartbeats[0].value.attempt_id,null);assert.equal(h.heartbeats[0].value.stage_proof_id,null);assert.equal(h.heartbeats[0].value.clock_probe_ids,null);assert.equal(h.bus.getBinding(),null);assert.equal(h.behavior.gpsStarts,0);const before=h.reads.length;if(boundary==='background')h.background();else await h.delete();blocked.resolve();await h.settle();assert.equal(h.reads.length,before);h.pulse(5000);await h.settle();assert.equal(h.heartbeats.length,1);}
});

test('peer lobby never sends the independent host heartbeat',async()=>{const h=harness();h.live(false);await h.settle();await h.open();h.pulse(5000);await h.settle();assert.equal(h.heartbeats.length,0);assert.equal(h.behavior.gpsStarts,0);});

test('idle focused host transport stays below the30-per-minute shared read cap with independent heartbeats',async()=>{const h=harness();h.live();await h.settle();await h.open();const initial=h.reads.length;for(let seconds=1;seconds<=60;seconds++){h.advance(1000);if(seconds%5===0)h.pulse(5000);if(seconds%6===0)h.pulse(6000);await h.settle();}const readCalls=h.reads.slice(initial);assert.equal(readCalls.filter(r=>r.kind==='race').length,10);assert.equal(readCalls.filter(r=>r.kind==='attempts').length,10);assert.equal(readCalls.length,20);assert.equal(h.heartbeats.length,12);assert.equal(h.proofs.length,0);assert.equal(h.controllers.at(-1).getSnapshot().phase,'idle');});

test('a held slow poll coalesces subsequent timer reads without changing attempt clock or stage authority',async()=>{const h=harness();h.live();await h.settle();await h.open();const blocked=hold();h.behavior.attemptListHold=blocked;const before=h.reads.length;h.pulse(6000);await tick();await tick();await tick();for(let i=0;i<5;i++){h.advance(6000);h.pulse(6000);await h.settle();}assert.equal(h.reads.length-before,2);assert.equal(h.proofs.length,0);assert.equal(h.controllers.at(-1).getSnapshot().phase,'idle');blocked.resolve();await h.settle();h.pulse(6000);await h.settle();assert.equal(h.reads.length-before,4);});

test('a captured native arm callback cannot start probes or control after canonical detail loses freshness',async()=>{const h=harness();h.bind();await h.settle();await h.open();await h.reserve();h.sample();const arm=h.arm,sends=h.sends.length;h.readers.at(-1).suspend();await assert.rejects(arm(),/RACE_CHANGED/);assert.equal(h.proofs.length,0);assert.equal(h.sends.length,sends);assert.equal(h.controllers.at(-1).getSnapshot().phase,'idle');});
