import {test} from 'node:test';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
import {raceModule,owner,peer,operation,receipt,clock,uuid,raceId,hold,tick,attempt} from './helpers/races.mjs';
function setup(){let active={userId:owner,generation:1},token='original-rider-jwt',response=receipt();const scope=active,requests=[];let deferred=null;const client=createClient('https://configured.test','publishable-test',{accessToken:async()=>token,global:{fetch:async(url,options)=>{requests.push({url:String(url),headers:options.headers,body:JSON.parse(options.body)});const value=deferred?await deferred.promise:response;return new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});}}});const service=raceModule('service',{'../../state/AuthState':{accountClient:(s,session)=>{const captured=session.access_token;return createClient('https://configured.test','publishable-test',{accessToken:async()=>captured,global:{fetch:client.rest.fetch}});},isAccountCurrent:s=>s===active}});return{service,scope,session:{user:{id:owner},access_token:token},requests,setResponse:v=>{response=v;},hold:()=>{deferred=hold();return deferred;},change:()=>{active={userId:peer,generation:2};},restore:()=>{active={userId:owner,generation:3};},token:v=>{token=v;}};}

test('restart attempt read sends only captured own race ID and rejects held response after owner ABA',async()=>{const h=setup(),page={owner_id:owner,race_id:raceId,items:[attempt()]};h.setResponse(page);assert.equal((await h.service.listRaceAttempts(h.scope,h.session,raceId)).items.length,1);assert.match(h.requests[0].url,/\/rpc\/rs_list_race_attempts$/);assert.deepEqual(h.requests[0].body,{p_race:raceId});assert.equal(new Headers(h.requests[0].headers).get('authorization'),'Bearer original-rider-jwt');
 h.setResponse({error:{code:'RACE_UNAVAILABLE'}});await assert.rejects(h.service.listRaceAttempts(h.scope,h.session,raceId),/RACE_UNAVAILABLE/);const wait=h.hold(),task=h.service.listRaceAttempts(h.scope,h.session,raceId);await tick();h.change();h.restore();wait.resolve(page);await assert.rejects(task,/ACCOUNT_CHANGED/);
});
test('actual Supabase transport sends immutable race operation with captured JWT, never mutable global owner/token',async()=>{const h=setup(),op=operation();h.token('foreign-global-jwt');const result=await h.service.mutateRace(h.scope,h.session,op);assert.equal(result.operation_id,op.operation_id);assert.match(h.requests[0].url,/\/rpc\/rs_race_mutate$/);assert.deepEqual(h.requests[0].body,{p_operation:op.operation_id,p_request:op.request});assert.equal(new Headers(h.requests[0].headers).get('authorization'),'Bearer original-rider-jwt');});
test('held actual SDK response cannot adopt after A→B→A owner scope replacement',async()=>{const h=setup(),wait=h.hold(),task=h.service.mutateRace(h.scope,h.session,operation());await tick();h.change();h.restore();wait.resolve(receipt());await assert.rejects(task,/ACCOUNT_CHANGED/);assert.equal(h.requests.length,1);});
test('validated errors remain fixed unions; reads carry authoritative retry interval and never raw SQL detail',async()=>{const h=setup();h.setResponse({error:{code:'RACE_RATE_LIMITED',retry_after_ms:2345}});assert.deepEqual(await h.service.mutateRace(h.scope,h.session,operation()),{error:{code:'RACE_RATE_LIMITED',retry_after_ms:2345}});await assert.rejects(h.service.getRace(h.scope,h.session,raceId),e=>e.message==='RACE_RATE_LIMITED'&&e.retryAfterMs===2345);h.setResponse({code:'P0001',message:'RACE_CHANGED private sql'});await assert.rejects(h.service.getRace(h.scope,h.session,raceId),/RACE_INVALID_RESPONSE/);});
test('cancellation transmits exact original activation; probes bind original IDs and invalid heartbeat never leaves device',async()=>{const h=setup(),op=operation();h.setResponse({kind:'cancelled',owner_id:owner,operation_id:op.operation_id,request:op.request,cancelled_at:'2026-10-01T02:00:00Z'});assert.equal((await h.service.cancelRaceActivation(h.scope,h.session,op)).kind,'cancelled');assert.deepEqual(h.requests[0].body,{p_operation:op.operation_id,p_request:op.request});const binding={probe_id:uuid(20),race_id:raceId,capture_id:uuid(5),clock_generation:uuid(14)};h.setResponse(clock());assert.equal((await h.service.probeRaceClock(h.scope,h.session,binding)).probe_id,binding.probe_id);const count=h.requests.length;await assert.rejects(h.service.heartbeatRace(h.scope,h.session,{race_id:raceId,member_generation:1,ready_lease_id:uuid(4),attempt_id:null,stage_proof_id:null,clock_probe_ids:null}),/RACE_INVALID/);assert.equal(h.requests.length,count);});
