import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import ts from 'typescript';import {hold,uuid,snapshot,attempt,tick} from './helpers/races.mjs';
const mod={exports:{}},source=ts.transpileModule(readFileSync(new URL('../src/state/RaceReader.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports',source)(mod,mod.exports);
function setup(){let current=true,wait=null,fail=false;const read=async value=>{if(wait)await wait.promise;if(fail)throw Error('failure');return value;},reader=new mod.exports.RaceReader({guard:()=>{if(!current)throw Error('ACCOUNT_CHANGED');},list:()=>read({items:[snapshot()],next_cursor:null}),routes:()=>read({items:[],next_cursor:null}),race:id=>read({...snapshot(),id}),course:id=>read({race_id:id,approval_id:uuid(6),config_hash:'b'.repeat(64)}),attempt:()=>read(attempt()),attempts:id=>read(id===uuid(3)?[attempt()]:[]),results:id=>read({race_id:id,items:[],statuses:[]}),approvals:()=>read({items:[snapshot().approval]})});return{reader,hold:()=>{wait=hold();return wait;},fail:()=>{fail=true;},closeOwner:()=>{current=false;}};}
test('failed initial race read never presents authoritative empty data; suspension rejects held success',async()=>{const h=setup();h.fail();await h.reader.list();assert.equal(h.reader.getSnapshot().loaded,false);assert.equal(h.reader.getSnapshot().fresh,false);assert.equal(h.reader.getSnapshot().racesPage.error,'RACE_UNAVAILABLE');const fresh=setup(),wait=fresh.hold(),task=fresh.reader.list();await tick();fresh.reader.suspend();wait.resolve();await task;assert.equal(fresh.reader.getSnapshot().loaded,false);assert.equal(fresh.reader.getSnapshot().racesPage.loading,false);});
test('old selected race cannot restore its course or attempt into a newer selection',async()=>{const h=setup();await h.reader.open(uuid(3));const wait=h.hold(),task=h.reader.loadCourse(),next=h.reader.open(uuid(99));assert.equal(h.reader.getSnapshot().race,null);wait.resolve();await Promise.all([task,next]);assert.equal(h.reader.getSnapshot().race.id,uuid(99));assert.equal(h.reader.getSnapshot().course,null);await h.reader.loadAttempt(uuid(4));assert.equal(h.reader.getSnapshot().attempt,null);});
test('background removes review/read authority, and owner closure discards every held lane',async()=>{const h=setup();await h.reader.refresh();assert.equal(h.reader.getSnapshot().fresh,true);await h.reader.open(uuid(3));await h.reader.loadApprovals({id:uuid(7),revision:2,title:'route',category:'scooter'});h.reader.suspend();assert.equal(h.reader.getSnapshot().detailFresh,false);assert.equal(h.reader.getSnapshot().approvals.fresh,false);const wait=h.hold(),task=h.reader.refresh();h.closeOwner();wait.resolve();await task;assert.equal(h.reader.getSnapshot().fresh,false);assert.equal(h.reader.getSnapshot().detailFresh,false);});
test('race and original own attempt schedule are adopted as one bundle, including restart discovery',async()=>{
 let race=snapshot(),own=attempt(),wait=null;const reader=new mod.exports.RaceReader({guard:()=>{},race:async()=>structuredClone(race),attempts:async()=>{if(wait)await wait.promise;return[structuredClone(own)];}});await reader.open(uuid(3));assert.equal(reader.getSnapshot().attemptId,own.id);
 const epoch='2026-10-01T02:01:00Z';race={...race,revision:4,state:'countdown',schedule_epoch:uuid(88),common_start_at:epoch};own={...own,revision:3,schedule_epoch:race.schedule_epoch,common_start_at:epoch};wait=hold();const task=reader.refreshDetail();await tick();assert.equal(reader.getSnapshot().race.common_start_at,null);assert.equal(reader.getSnapshot().attempt.common_start_at,null);wait.resolve();await task;assert.equal(reader.getSnapshot().race.common_start_at,epoch);assert.equal(reader.getSnapshot().attempt.common_start_at,epoch);
 race={...race,revision:2};await reader.refreshDetail();assert.equal(reader.getSnapshot().race.revision,4);assert.equal(reader.getSnapshot().detailFresh,false);
});
test('a mismatched scheduled own attempt never becomes countdown authority',async()=>{const race={...snapshot(),state:'countdown',schedule_epoch:uuid(88),common_start_at:'2026-10-01T02:01:00Z'},reader=new mod.exports.RaceReader({guard:()=>{},race:async()=>race,attempts:async()=>[attempt()]});await reader.open(uuid(3));assert.equal(reader.getSnapshot().race,null);assert.equal(reader.getSnapshot().detailFresh,false);assert.equal(reader.getSnapshot().detailError,'RACE_CHANGED');assert.equal(reader.getSnapshot().detailLoading,false);});

test('latest result read wins and a changed canonical race invalidates held result authority',async()=>{
 let race=snapshot(),calls=0,first=hold();const reader=new mod.exports.RaceReader({guard:()=>{},race:async()=>structuredClone(race),attempts:async()=>[attempt()],results:async()=>{const n=++calls;if(n===1)await first.promise;return{race_id:race.id,items:[{marker:n}],statuses:[]};}});await reader.open(uuid(3));const old=reader.loadResults();await tick();await reader.loadResults();assert.equal(reader.getSnapshot().results.items[0].marker,2);first.resolve();await old;assert.equal(reader.getSnapshot().results.items[0].marker,2);
 first=hold();calls=0;const held=reader.loadResults();await tick();race={...race,revision:4};await reader.refreshDetail();assert.equal(reader.getSnapshot().resultsFresh,false);assert.equal(reader.getSnapshot().resultsLoading,false);first.resolve();await held;assert.equal(reader.getSnapshot().resultsFresh,false);assert.equal(reader.getSnapshot().results,null);
});

test('terminal own history survives withdrawal while active prior-member attempts cannot become fresh authority',async()=>{
 let own={...attempt(),state:'aborted',terminal_reason:'user_stop',terminal_at:'2026-10-01T02:05:00Z'},courseReads=0;const race={...snapshot(),self_member:{...snapshot().self_member,state:'withdrawn',member_generation:3}},reader=new mod.exports.RaceReader({guard:()=>{},race:async()=>race,attempts:async()=>[own],course:async()=>{courseReads++;return {race_id:race.id,approval_id:uuid(6),config_hash:'b'.repeat(64)};}});await reader.open(uuid(3));assert.equal(reader.getSnapshot().detailFresh,true);assert.equal(reader.getSnapshot().attempt.state,'aborted');await reader.loadCourse();assert.equal(courseReads,0);assert.equal(reader.getSnapshot().course,null);
 own=attempt();await reader.refreshDetail();assert.equal(reader.getSnapshot().detailFresh,false);assert.equal(reader.getSnapshot().attempt.state,'aborted');
});

test('a newly verified own attempt invalidates an older held result status even if race revision stays unchanged',async()=>{let own=attempt();const wait=hold(),reader=new mod.exports.RaceReader({guard:()=>{},race:async()=>snapshot(),attempts:async()=>[structuredClone(own)],results:async()=>{await wait.promise;return{race_id:uuid(3),items:[],statuses:[{user_id:own.owner_id,state:'in_progress'}]};}});await reader.open(uuid(3));const task=reader.loadResults();await tick();own={...own,revision:3,state:'verified',terminal_at:'2026-10-01T02:05:00Z'};await reader.refreshDetail();wait.resolve();await task;assert.equal(reader.getSnapshot().attempt.state,'verified');assert.equal(reader.getSnapshot().resultsFresh,false);assert.equal(reader.getSnapshot().results,null);assert.equal(reader.getSnapshot().resultsLoading,false);});
