import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {owner,peer,snapshot,uuid,raceModule} from './helpers/races.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url));
const copy=value=>JSON.parse(JSON.stringify(value));
const course=()=>({race_id:uuid(3),approval_id:uuid(6),config_hash:'b'.repeat(64),route_geometry_hash:'a'.repeat(64),configuration:{schema_version:1,method:'route_time_v1',projection:'wgs84_ecef_enu_v1',origin:{latitude:13,longitude:100},route_geometry:[{latitude:13,longitude:100},{latitude:13,longitude:100.004}],boundary_polygon:[{latitude:12.999,longitude:99.999},{latitude:13.001,longitude:99.999},{latitude:13.001,longitude:100.005},{latitude:12.999,longitude:100.005}],staging_polygon:[{latitude:12.9999,longitude:100},{latitude:13.0001,longitude:100},{latitude:13.0001,longitude:100.00005},{latitude:12.9999,longitude:100.00005}],gates:[{index:0,kind:'start',a:{latitude:12.9998,longitude:100.0001},b:{latitude:13.0002,longitude:100.0001},forward_point:{latitude:13,longitude:100.0002},progress_min_m:0,progress_max_m:30},{index:1,kind:'finish',a:{latitude:12.9998,longitude:100.0038},b:{latitude:13.0002,longitude:100.0038},forward_point:{latitude:13,longitude:100.0039},progress_min_m:390,progress_max_m:420}],corridor_half_width_m:30,maximum_speed_mps:40,geometry_error_margin_m:.25,maximum_accuracy_m:15,maximum_gap_ms:1500,maximum_crossing_span_ms:3000,maximum_duration_ms:1800000,minimum_duration_ms:10000,maximum_acceleration_mps2:15,maximum_backtrack_m:5,whole_capture_residual_ms:250,server_time_drift_allowance_ms:250,live_start_gate_window_ms:10000}});
const port=()=>({ownerId:owner,generation:'A1',current:g=>g==='A1',gate:{signedIn:true,focused:true,foreground:true,moving:false,online:true},ready:true,detailFresh:true,detailError:null,courseLoading:false,courseError:null,race:snapshot(),course:course()});
const t=(key,values={})=>`${key}${Object.keys(values).length?JSON.stringify(values):''}`;
test('private course authority needs the exact current accepted consented participant and approval hashes',()=>{
 const model=raceModule('courseMapModel'),base=port();assert.ok(model.authorizedRaceCourse(base));
 for(const mutation of [p=>p.ownerId=peer,p=>p.current=()=>false,p=>p.detailFresh=false,p=>p.courseError='RACE_CHANGED',p=>p.gate.focused=false,p=>p.gate.foreground=false,p=>p.race.self_member.state='invited',p=>p.race.self_member.evidence_consent_version=null,p=>p.race.state='cancelled',p=>p.course.route_geometry_hash='c'.repeat(64),p=>p.course.config_hash='c'.repeat(64),p=>p.course.race_id=uuid(99)]){const value={...copy(base),current:base.current};mutation(value);assert.equal(model.authorizedRaceCourse(value),null);}
});
test('map geometry comes only from full approved course and keeps route/gates/staging independent',()=>{
 const model=raceModule('courseMapModel'),input=course(),geometry=model.raceCourseMapGeometry(input,t);
 assert.equal(geometry.track.kind,'recorded');assert.deepEqual(copy(geometry.track.segments[0]),input.configuration.route_geometry);assert.deepEqual(copy(geometry.track.segments[1]),[input.configuration.gates[0].a,input.configuration.gates[0].b]);assert.equal(geometry.pins.length,2);assert.equal(geometry.pins[0].role,'start');assert.equal(geometry.pins[1].role,'finish');assert.equal(geometry.track.segments.at(-1).length,input.configuration.staging_polygon.length+1);assert.ok(geometry.coordinates.some(p=>p.longitude===input.configuration.gates[1].forward_point.longitude));
 input.configuration.route_geometry[0].latitude=50;assert.equal(geometry.track.segments[0][0].latitude,13);
 assert.throws(()=>model.raceCourseMapGeometry({...course(),configuration:{...course().configuration,route_geometry:[]}},t),/RACE_INVALID_RESPONSE/);
});
function harness(){
 const cells=[],effects=[],layouts=[],listeners=new Set(),fits=[],cache=new Map();let index=0,focused=true,p=port(),handle={fitCoordinates:(...args)=>fits.push(copy(args))};
 const same=(a,b)=>!!a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i])),memo=(fn,deps)=>{const i=index++;if(!cells[i]||!same(cells[i].deps,deps))cells[i]={deps,value:fn()};return cells[i].value;};
 const enqueue=(queue,fn,deps)=>{const i=index++,old=cells[i];if(!old||!deps||!same(old.deps,deps)){cells[i]={deps};queue.push(()=>{old?.cleanup?.();cells[i].cleanup=fn();});}};
 const react={useMemo:memo,useRef:value=>{const i=index++;return cells[i]??={current:value};},useState:value=>{const i=index++;cells[i]??={value:typeof value==='function'?value():value};return[cells[i].value,next=>{cells[i].value=typeof next==='function'?next(cells[i].value):next;}];},useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps),useEffect:(fn,deps)=>enqueue(effects,fn,deps),useCallback:(fn,deps)=>memo(()=>fn,deps)};
 const native={View:'View',ActivityIndicator:'ActivityIndicator',StyleSheet:{absoluteFill:{},create:v=>v},AppState:{currentState:'active',addEventListener(_name,fn){listeners.add(fn);return{remove(){listeners.delete(fn);}};}}},jsx=(type,props)=>({type,props});
 const deps={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':native,'expo-router':{useIsFocused:()=>focused},'../../components/ui':{Button:'Button',Note:'Note',T:'T',Row:'Row',Icon:'Icon'},'../../state/AppState':{useApp:()=>({dark:true,motion:false,colors:{bg:'#000',accent:'#FF5A1F',line:'#333',ink:'#FFF'}})},'../../lib/i18n':{useI18n:()=>({language:'th',t})},'../map/ActiveMapSurface':{__esModule:true,default:'MapSurface'}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,Date,Promise,Error,TextEncoder,console,require:key=>{if(key in deps)return deps[key];if(!key.startsWith('.'))return require(key);let target=resolve(dirname(path),key);if(!existsSync(target))for(const ext of ['.ts','.tsx'])if(existsSync(target+ext)){target+=ext;break;}return load(target);}});return module.exports;}
 const component=load(resolve(root,'features/races/RaceCourseMap.tsx')).default;
 const h={fits,get port(){return p;},render(){index=0;const tree=component({port:p,t});for(const node of all(tree))if(node.type==='MapSurface'&&node.props.ref)node.props.ref.current=handle;while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return tree;},os(status){native.AppState.currentState=status;for(const fn of listeners)fn(status);},focus(value){focused=value;},handle(value){handle=value;},replace(value){p=value;},close(){for(const cell of cells)cell?.cleanup?.();}};return h;
}
const all=node=>!node||typeof node!=='object'?[]:[node,...[node.props?.children].flat(Infinity).flatMap(all)];
const map=tree=>all(tree).find(n=>n.type==='MapSurface');
test('real map adapter receives private route/gates with no remote peers, user fix or GPS watcher',()=>{const h=harness(),tree=h.render(),m=map(tree);assert.ok(m);assert.equal(m.props.peers.length,0);assert.equal(m.props.userFix,null);assert.equal(m.props.mode,'browse');assert.equal(m.props.theme,'dark');assert.equal(m.props.locale,'th');assert.equal(m.props.track.segments[0].length,2);assert.equal(m.props.pins.length,2);m.props.onStatus({state:'ready'});h.render();assert.equal(h.fits.length,1);h.render();assert.equal(h.fits.length,1);h.close();});
test('held renderer status and overview callbacks cannot restore old course authority after full OS resume or owner change',()=>{const h=harness(),tree=h.render(),m=map(tree),overview=all(tree).find(n=>n.type==='Button'&&n.props.label==='m5c.mapOverview');h.os('background');h.os('active');m.props.onStatus({state:'ready'});overview.props.onPress();assert.equal(h.fits.length,0);h.replace({...h.port,ownerId:peer,generation:'B1',current:()=>false});assert.equal(map(h.render()),undefined);m.props.onStatus({state:'ready'});overview.props.onPress();assert.equal(h.fits.length,0);h.close();});
test('movement uses glance mode and disables fitting/retry; renderer failures and offline are visible accessible content',()=>{const h=harness();h.port.gate.moving=true;let tree=h.render(),m=map(tree);assert.equal(m.props.mode,'glance');assert.equal(all(tree).find(n=>n.type==='Button'&&n.props.label==='m5c.mapOverview').props.disabled,true);m.props.onStatus({state:'unsupported',reason:'native-module'});tree=h.render();assert.ok(all(tree).some(n=>n.type==='Note'&&n.props.children==='m5c.mapUnsupported'));h.port.gate.online=false;tree=h.render();assert.ok(all(tree).some(n=>n.type==='Note'&&n.props.children==='m5c.mapOffline'));h.close();});
test('course revocation or stale detail removes private map immediately without a coordinate fallback',()=>{const h=harness();h.render();h.port.detailFresh=false;assert.equal(map(h.render()),undefined);h.port.detailFresh=true;h.port.race.self_member.state='withdrawn';assert.equal(map(h.render()),undefined);h.close();});
test('a focused course map accepts fresh renderer events after returning from another screen',()=>{const h=harness();h.render();h.focus(false);assert.equal(map(h.render()),undefined);h.focus(true);let tree=h.render();map(tree).props.onStatus({state:'ready'});h.render();assert.equal(h.fits.length,1);h.close();});
test('an accepted restarted attempt can explicitly load its course without restoring recording authority',async()=>{const h=harness(),calls=[];h.port.course=null;h.port.guard=(...args)=>calls.push(['guard',...args]);h.port.loadCourse=async binding=>calls.push(['course',binding]);const tree=h.render(),load=all(tree).find(n=>n.type==='Button'&&n.props.label==='m5c.loadCourse');assert.ok(load);assert.equal(map(tree),undefined);load.props.onPress();await Promise.resolve();assert.deepEqual(calls.map(c=>c[0]),['guard','course']);const held=load.props.onPress;h.os('background');h.os('active');held();await Promise.resolve();assert.equal(calls.length,2);h.close();});
test('course fit waits for an actual renderer handle and ready status before recording completion',()=>{const h=harness();h.handle(null);let tree=h.render();map(tree).props.onStatus({state:'ready'});h.render();assert.equal(h.fits.length,0);h.handle({fitCoordinates:(...args)=>h.fits.push(copy(args))});h.render();assert.equal(h.fits.length,1);h.render();assert.equal(h.fits.length,1);h.close();});
