import {createRequire} from 'node:module';import {readFileSync,existsSync} from 'node:fs';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript'),root=resolve(dirname(fileURLToPath(import.meta.url)),'../src/features/ranked');
export const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,owner=uuid(1),peer=uuid(2),stamp='2026-10-01T10:00:00.000Z';
export function rankedModule(name,deps={}){const cache=new Map();function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const compilation=ts.transpileModule(readFileSync(path,'utf8'),{fileName:path,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,esModuleInterop:true,jsx:ts.JsxEmit.ReactJSX}});if(compilation.diagnostics?.some(value=>value.category===ts.DiagnosticCategory.Error))throw Error('Invalid ranked source: '+path+' '+compilation.diagnostics.map(value=>ts.flattenDiagnosticMessageText(value.messageText,' ')).join('; '));const code=compilation.outputText;runInNewContext(code,{module,exports:module.exports,Date,console,URL,Headers,Response,TextEncoder,TextDecoder,require:key=>{if(key in deps)return deps[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);for(const ext of ['.ts','.tsx'])if(!existsSync(next)&&existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}return load(resolve(root,existsSync(resolve(root,`${name}.ts`))?`${name}.ts`:`${name}.tsx`));}
export const filter=()=>({schema_version:1,period:'today',metric:'sustained_speed',category:'scooter',class_key:'all',scope:'global',course:null});
export const row=(n=2,position=1)=>({record_id:uuid(n+100),user_id:uuid(n),rank:position,position,tied:false,profile:{name:'Rider '+n,handle:'rider'+n},category:'scooter',class_key:'scooter:unknown',class_scheme_version:1,metadata_authority:'unknown',completed_at:'2026-10-01T09:00:00.000Z',verified_at:'2026-10-01T09:10:00.000Z',provenance_unknown:true,metric:'sustained_speed',method:'sustained_min_3s_v1',sustained_kmh:120/(position+1),quality:'submitted_evidence_consistency'});
export const page=()=>({owner_id:owner,server_now:stamp,filter:filter(),period:{timezone:'Asia/Bangkok',starts_at:'2026-09-30T17:00:00.000Z',ends_at:'2026-10-01T17:00:00.000Z',as_of:stamp},board_revision:'a'.repeat(64),capabilities:{speed:true,route_time:true,publication:true},items:[row()],podium:[row()],self:null,self_status:'no_record',next_cursor:null});
export const course=()=>({approval_id:uuid(50),config_hash:'b'.repeat(64),mode:'async',title:'Operator public board',category:'scooter',route_revision:2});
export const coursePage=()=>({owner_id:owner,server_now:stamp,items:[course()],next_cursor:null});
export const timeFilter=()=>({...filter(),metric:'route_time',course:{approval_id:uuid(50),config_hash:'b'.repeat(64),mode:'async'}});
export const timeRow=(n=2,position=1)=>{const {sustained_kmh,...rest}=row(n,position);return {...rest,metadata_authority:'self_reported',class_key:'scooter:gt125_le160',metric:'route_time',method:'route_time_v1',quality:'native_evidence_consistency',elapsed_lower_ms:10000,elapsed_upper_ms:11000,course:timeFilter().course};};
export const hold=()=>{let resolve;return {promise:new Promise(r=>{resolve=r;}),resolve};};
