import test from 'node:test';import assert from 'node:assert/strict';
import {rankedModule,owner,peer,uuid,filter,page,row,hold} from './rankedFixtures.mjs';
const {RankedReportReview}=rankedModule('RankedReportReview');
const request=()=>({schema_version:1,action:'report_record',metric:'sustained_speed',record_id:row().record_id,reason:'suspected_cheating',detail:''});
function fixture(){let active=true,response=page(),block=null,serial=900;const calls=[];const review=new RankedReportReview({ownerId:owner,guard:()=>{if(!active)throw Error('RANKED_INACTIVE');},token:()=>uuid(++serial),page:async(f,c)=>{calls.push({f,c});const value=response,wait=block;block=null;if(wait)await wait.promise;return value;}});return {review,calls,response:v=>response=v,active:v=>active=v,hold:()=>block=hold(),arm:()=>review.arm(page(),row().record_id,peer)};}
test('opaque owner memory requires a fresh real board row before a report can be queued',async()=>{const h=fixture(),token=h.arm();assert.throws(()=>h.review.assertReviewed(request()),/RANKED_CHANGED/);assert.equal((await h.review.review(token)).record_id,row().record_id);h.review.assertReviewed(request());assert.throws(()=>h.review.assertReviewed({...request(),record_id:uuid(777)}),/RANKED_CHANGED/);assert.equal(h.calls.length,1);assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].f)),filter());});
test('withdrawn, hidden or filtered-out record loses report authority rather than retaining a stale target',async()=>{const h=fixture(),token=h.arm();h.response({...page(),items:[],podium:[]});assert.equal(await h.review.review(token),null);assert.equal(h.review.current(token),false);assert.throws(()=>h.review.assertReviewed(request()),/RANKED_CHANGED/);});
test('a complete background/resume before held response finishes cannot revive target authority',async()=>{const h=fixture(),token=h.arm(),wait=h.hold(),task=h.review.review(token);h.active(false);h.review.clear();h.active(true);wait.resolve();await assert.rejects(task,/RANKED_CHANGED/);assert.equal(h.review.getSnapshot(),null);assert.throws(()=>h.review.assertReviewed(request()),/RANKED_CHANGED/);});
test('replacing the target and owner closure retire old callbacks without dispatch or settlement',async()=>{const h=fixture(),old=h.arm(),wait=h.hold(),task=h.review.review(old),next=h.arm();wait.resolve();await assert.rejects(task,/RANKED_CHANGED/);assert.equal(h.review.current(next),true);const count=h.calls.length;await assert.rejects(h.review.review(old),/RANKED_CHANGED/);assert.equal(h.calls.length,count);h.review.close();await assert.rejects(h.review.review(next),/RANKED_CHANGED/);assert.equal(h.calls.length,count);});
test('server error or malformed owner/board cannot create a successful report review',async()=>{const h=fixture(),token=h.arm();h.response({...page(),owner_id:peer});await assert.rejects(h.review.review(token),/RANKED_INVALID_RESPONSE/);assert.throws(()=>h.review.assertReviewed(request()),/RANKED_CHANGED/);h.active(false);const count=h.calls.length;await assert.rejects(h.review.review(token),/RANKED_INACTIVE/);assert.equal(h.calls.length,count);});
test('report can find an exact current row through strict same-board pagination',async()=>{const h=fixture(),token=h.arm(),first={...page(),items:[row(3)],podium:[],next_cursor:{owner_id:owner,filter_hash:'b'.repeat(64),board_revision:'a'.repeat(64),starts_at:page().period.starts_at,ends_at:page().period.ends_at,as_of:page().period.as_of,after_position:1}};h.response(first);const base=h.review.port.page;h.review.port.page=async(f,c)=>c?{...page(),items:[row(2,2)],podium:[]}:base(f,c);assert.equal((await h.review.review(token)).position,2);h.review.assertReviewed(request());});
