import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {rankedModule,filter,page,row,coursePage,hold,owner} from './rankedFixtures.mjs';
const model=rankedModule('model'),mod={exports:{}};
const code=ts.transpileModule(readFileSync(new URL('../src/state/RankedReader.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
new Function('require','module','exports',code)(name=>{if(name==='../features/ranked/model')return model;throw Error(name);},mod,mod.exports);
function setup(){let active=true,now=1000,response=page(),pending=null,error=null;const calls=[];
 const reader=new mod.exports.RankedReader({guard:()=>{if(!active)throw Error('RANKED_CHANGED');},monotonicNow:()=>now,page:async(f,c)=>{calls.push({filter:f,cursor:c});const result=structuredClone({...response,filter:f});const wait=pending;pending=null;if(wait)await wait.promise;if(error)throw error;return result;},courses:async()=>coursePage()},filter());
 return {reader,calls,hold:()=>{pending=hold();return pending;},setResponse:value=>response=value,setError:value=>error=value,advance:ms=>now+=ms,suspend:()=>{active=false;reader.suspend();},resume:()=>{active=true;},};
}
test('an unread failed board never becomes an authoritative empty board',async()=>{const h=setup();assert.equal(h.calls.length,0);h.setError(Error('RANKED_UNAVAILABLE'));await h.reader.refresh();const s=h.reader.getSnapshot();assert.equal(s.loaded,false);assert.equal(s.page,null);assert.equal(s.read.fresh,false);assert.equal(s.read.error,'RANKED_UNAVAILABLE');});
test('retired filter and foreground reads cannot adopt delayed rows',async()=>{const h=setup(),wait=h.hold(),old=h.reader.refresh();await h.reader.setFilter({...filter(),period:'week'});wait.resolve();await old;assert.equal(h.reader.getSnapshot().filter.period,'week');assert.equal(h.reader.getSnapshot().page.filter.period,'week');const held=h.hold(),next=h.reader.refresh();h.suspend();held.resolve();await next;assert.equal(h.reader.getSnapshot().read.fresh,false);assert.equal(h.reader.getSnapshot().read.loading,false);});
test('a changed board cursor restarts once and never mixes revisions',async()=>{const h=setup(),p=page();p.next_cursor={owner_id:owner,filter_hash:'b'.repeat(64),board_revision:p.board_revision,starts_at:p.period.starts_at,ends_at:p.period.ends_at,as_of:p.period.as_of,after_position:1};h.setResponse(p);await h.reader.refresh();h.setError(Error('RANKED_CHANGED'));await h.reader.loadMore();assert.equal(h.reader.getSnapshot().read.fresh,false);assert.equal(h.reader.getSnapshot().read.hasMore,false);assert.equal(h.calls.length,3);h.setError(null);const fresh={...page(),board_revision:'c'.repeat(64),items:[row(3)]};h.setResponse(fresh);await h.reader.refresh();assert.deepEqual(h.reader.getSnapshot().rows,[row(3)]);assert.equal(h.calls.at(-1).cursor,null);});
test('rate backoff prevents hidden or repeated manual egress and recovers on the same filter',async()=>{const h=setup();h.setError(Object.assign(Error('RANKED_RATE_LIMITED'),{retryAfterMs:5000}));await h.reader.refresh();const count=h.calls.length;await h.reader.refresh();await h.reader.loadMore();assert.equal(h.calls.length,count);h.advance(5000);h.setError(null);await h.reader.refresh();assert.equal(h.calls.length,count+1);assert.equal(h.reader.getSnapshot().read.fresh,true);});
test('rank deltas compare only current owner and the same server period and filter',async()=>{const h=setup();await h.reader.refresh();h.setResponse({...page(),board_revision:'c'.repeat(64),items:[{...row(),rank:2,position:2}],podium:[],self:null});await h.reader.refresh();assert.equal(h.reader.getSnapshot().rankChanges[row().record_id],-1);await h.reader.setFilter({...filter(),scope:'friends'});assert.deepEqual(h.reader.getSnapshot().rankChanges,{});});
test('equivalent UTC boundary encodings preserve rank deltas without changing period authority',async()=>{const h=setup();await h.reader.refresh();const updated=page();updated.period={...updated.period,starts_at:updated.period.starts_at.replace('Z','+00:00'),ends_at:updated.period.ends_at.replace('Z','+00:00')};updated.items=[{...row(),rank:2,position:2}];h.setResponse(updated);await h.reader.refresh();assert.equal(h.reader.getSnapshot().rankChanges[row().record_id],-1);});
test('held course discovery cannot publish after reader closure',async()=>{const wait=hold(),reader=new mod.exports.RankedReader({guard:()=>{},monotonicNow:()=>1000,page:async()=>page(),courses:async()=>{await wait.promise;return coursePage();}},filter());const task=reader.loadCourses();reader.close();wait.resolve();await task;assert.deepEqual(reader.getSnapshot().courses,[]);assert.equal(reader.getSnapshot().coursesRead.loading,false);});
