import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {dirname,resolve} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import ts from 'typescript';import {owner,peer,uuid,stamp,row,hold} from './rankedFixtures.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url)),tick=()=>new Promise(r=>setImmediate(r));
/** Real route hosts + finite owner reader + OS activity hook. Transport replies,
 * React scheduling and already-covered durable RankedProvider are fixtures. */
function harness(kind='publication'){
 let cells=[],index=0,dirty=false,focused=true,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'A-1'},moving=false,appReady=true,now=1000,heldCandidates=null,heldGetter=null,heldReport=null,routeToken='opaque-A';const layouts=[],effects=[],listeners=new Set(),cache=new Map(),calls=[];let clearCount=0;
 const same=(a,b)=>a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i])),memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;},enqueue=(queue,fn,deps)=>{const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};queue.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}};
 const react={useRef:v=>{const n=index++;return cells[n]??={current:v};},useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useState:v=>{const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,next=>{const value=typeof next==='function'?next(cells[n].value):next;if(!Object.is(value,cells[n].value)){cells[n].value=value;dirty=true;}}];},useEffect:(fn,deps)=>enqueue(effects,fn,deps),useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps),useSyncExternalStore:(subscribe,get)=>{const n=index++;if(cells[n]?.subscribe!==subscribe){cells[n]?.remove?.();cells[n]={subscribe,remove:subscribe(()=>dirty=true)};}return get();}};
 const native={Platform:{OS:'ios'},AppState:{currentState:'active',addEventListener(_n,fn){listeners.add(fn);return{remove:()=>listeners.delete(fn)};}}},jsx=(type,props)=>({type,props}),pub=id=>({owner_id:scope.userId,metric:'sustained_speed',record_id:id,revision:3,audience:'private',updated_at:stamp});
 const service={async getRankedOwnRecords(requested,captured,cursor){const wait=heldCandidates;heldCandidates=null;calls.push({kind:'candidate',requested,captured,cursor});const {user_id,rank,position,tied,profile,...base}=row();const result={owner_id:requested.userId,server_now:stamp,items:[{...base,publication:{revision:0,audience:'private',updated_at:null}}],next_cursor:null};if(wait)await wait.promise;return result;},async getRankedPublications(requested,captured,cursor){calls.push({kind:'settings',requested,captured,cursor});return{owner_id:requested.userId,server_now:stamp,items:[pub(uuid(102))],next_cursor:null};},async getRankedPublication(requested,captured,metric,id){const wait=heldGetter;heldGetter=null;calls.push({kind:'getter',requested,captured,metric,id});const result={...pub(id),owner_id:requested.userId};if(wait)await wait.promise;return result;}};
 const ranked={ready:true,pending:[],latest:null,error:null,appliedVersion:0,reportTarget:{token:'opaque-A',row:row()},async mutate(request){calls.push({kind:'write',request,scope});return uuid(900);},async retry(){calls.push({kind:'retry',scope});},async reviewReport(token){const wait=heldReport;heldReport=null;calls.push({kind:'reportReview',scope,token});if(wait)await wait.promise;return ranked.reportTarget?.row??null;},currentReport:token=>token===ranked.reportTarget?.token,clearReport:()=>{clearCount++;}};
 const overrides={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':native,'expo-router':{useIsFocused:()=>focused,useLocalSearchParams:()=>({token:routeToken}),router:{back(){},push(){}}},'../features/ranked/RankedPublicationScreen':{RankedPublicationScreen:'Publication'},'../features/ranked/RankedReportScreen':{RankedReportScreen:'Report'},'../features/ranked/publicationService':service,'../../lib/useScreenActivity':null,'../lib/i18n':{useI18n:()=>({t:key=>key})},'../state/AppState':{useApp:()=>({ready:appReady})},'../state/AuthState':{useAuth:()=>({scope,ready:true,session})},'../../state/AppState':{useApp:()=>({ready:appReady,storageError:null})},'../../state/AuthState':{useAuth:()=>({scope,ready:true,session}),isAccountCurrent:s=>s===scope},'../../state/RankedState':{useRanked:()=>({...ranked,clearReport:()=>{clearCount++;}})},'../../state/RideState':{useRide:()=>({movingLocked:moving})},'../components/ui':{Screen:'Screen',T:'T'}};
 delete overrides['../../lib/useScreenActivity'];
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith(`ranked-${kind}.tsx`))source+=`\nexport {Account${kind==='publication'?'Publication':'Report'} as __testHost};\n`;const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,TextEncoder,performance:{now:()=>now},require:key=>{if(key in overrides)return overrides[key];if(!key.startsWith('.'))return require(key);let next=resolve(dirname(path),key);if(!existsSync(next))for(const ext of ['.ts','.tsx'])if(existsSync(next+ext)){next+=ext;break;}return load(next);}});return module.exports;}
 const component=load(resolve(root,`app/ranked-${kind}.tsx`));
 const h={calls,ranked,route(value){routeToken=value;return h.render();},get port(){return h.tree.props.port;},get clearCount(){return clearCount;},render(){index=0;dirty=false;h.tree=component.__testHost();while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.port;},async settle(){for(let i=0;i<8;i++){await tick();if(dirty)h.render();}return h.render();},holdCandidates(){return heldCandidates=hold();},holdGetter(){return heldGetter=hold();},holdReport(){return heldReport=hold();},os(state){native.AppState.currentState=state;for(const fn of listeners)fn(state);},focus(value){focused=value;h.render();},move(value){moving=value;h.render();},switch(user){for(const c of cells){c?.cleanup?.();c?.remove?.();}cells=[];scope={userId:user,generation:scope.generation+1};session={user:{id:user},access_token:`${user}-${scope.generation}`};h.render();},close(){for(const c of cells){c?.cleanup?.();c?.remove?.();}},unread(){appReady=false;index=0;return component.default();}};return h;
}
test('actual owner host rejects held candidates after OS background/resume before React runs',async()=>{const h=harness(),wait=h.holdCandidates();h.render();await tick();assert.equal(h.calls.length,2);h.os('background');h.os('active');wait.resolve();await tick();assert.equal(h.port.state.candidates.length,0);await h.settle();assert.equal(h.port.state.candidatesRead.fresh,true);h.close();});
test('held fresh getter cannot authorize publication after batched lifecycle transition',async()=>{const h=harness();h.render();await h.settle();await h.port.select('sustained_speed',uuid(102));await h.settle();const wait=h.holdGetter(),pending=assert.rejects(h.port.reviewPublication(),/RANKED_CHANGED/);await tick();h.os('background');h.os('active');wait.resolve();await pending;await h.settle();assert.equal(h.calls.some(c=>c.kind==='write'),false);h.close();});
test('old owner ABA, blurred and moving publication callbacks make no service/write call',async()=>{const h=harness();h.render();await h.settle();const old=h.port;h.switch(peer);await h.settle();h.switch(owner);await h.settle();let before=h.calls.length;await assert.rejects(old.refresh(),/RANKED_CHANGED/);assert.equal(h.calls.length,before);const current=h.port;h.focus(false);before=h.calls.length;await assert.rejects(current.retry(),/RANKED_CHANGED/);assert.equal(h.calls.length,before);h.focus(true);await h.settle();const active=h.port;h.move(true);before=h.calls.length;await assert.rejects(active.select('sustained_speed',uuid(102)),/RANKED_MOVING/);assert.equal(h.calls.length,before);h.close();});
test('fresh publication revision is required at dispatch and getter failure never adopts receipt as authority',async()=>{const h=harness();h.render();await h.settle();await h.port.select('sustained_speed',uuid(102));await h.settle();await assert.rejects(h.port.publish({schema_version:1,action:'publication_set',metric:'sustained_speed',record_id:uuid(102),expected_revision:0,audience:'global'}),/RANKED_CHANGED/);const pub=await h.port.reviewPublication();await h.port.publish({schema_version:1,action:'publication_set',metric:pub.metric,record_id:pub.record_id,expected_revision:pub.revision,audience:'global'});assert.equal(h.calls.filter(c=>c.kind==='write').length,1);h.close();});
test('report cleanup is pinned to token/owner and normal unstable provider callbacks do not erase review',async()=>{const h=harness('report');h.render();h.render();h.render();assert.equal(h.clearCount,0);const wait=h.holdReport(),pending=assert.rejects(h.port.review('opaque-A'),/RANKED_CHANGED/);await tick();h.os('background');h.os('active');wait.resolve();await pending;h.render();assert.equal(h.clearCount,0);h.close();assert.equal(h.clearCount,1);});
test('outer publication host waits for unread private storage and sends no requests',()=>{const h=harness(),tree=h.unread();assert.equal(tree.type,'Screen');assert.equal(h.calls.length,0);h.close();});

test('report route rejects missing/mismatched/array tokens without adopting last in-memory target',async()=>{const h=harness('report');h.render();for(const value of [null,'foreign-token',['opaque-A']]){h.route(value);assert.equal(h.port.target,null);const before=h.calls.length;await assert.rejects(h.port.review('opaque-A'),/RANKED_CHANGED/);assert.equal(h.calls.length,before);}h.close();});
test('retired route token fences held report proof and stale callbacks under the same owner',async()=>{const h=harness('report');h.render();const previous=h.port,wait=h.holdReport(),pending=assert.rejects(previous.review('opaque-A'),/RANKED_CHANGED/);await tick();h.route('other-token');wait.resolve();await pending;assert.equal(h.port.target,null);const before=h.calls.length;await assert.rejects(previous.report({schema_version:1,action:'report_record',metric:'sustained_speed',record_id:uuid(102),reason:'other',detail:''}),/RANKED_CHANGED/);assert.equal(h.calls.length,before);h.close();});
