import test from 'node:test';import assert from 'node:assert/strict';import {createClient} from '@supabase/supabase-js';
import {rankedModule,owner,peer,uuid,stamp,hold,row} from './rankedFixtures.mjs';
const operation=()=>({owner_id:owner,operation_id:uuid(900),request:{schema_version:1,action:'publication_set',metric:'sustained_speed',record_id:uuid(102),expected_revision:0,audience:'friends'}});
const publication=()=>({owner_id:owner,metric:'sustained_speed',record_id:uuid(102),revision:1,audience:'friends',updated_at:stamp});
const receipt=()=>({owner_id:owner,operation_id:uuid(900),request:operation().request,applied_at:stamp,result:publication()});
function fixture(){let current={userId:owner,generation:1},response=receipt(),deferred=null;const scope=current,session={user:{id:owner},access_token:'captured-ranked-write-A'},requests=[];const service=rankedModule('publicationService',{'../../state/AuthState':{isAccountCurrent:s=>s===current,accountClient:(_s,auth)=>{const captured=auth.access_token;return createClient('https://configured.test','publishable-test',{accessToken:async()=>captured,global:{fetch:async(input,init)=>{requests.push({path:new URL(String(input)).pathname,body:JSON.parse(init.body),token:new Headers(init.headers).get('authorization')});return new Response(JSON.stringify(deferred?await deferred.promise:response),{headers:{'content-type':'application/json'}});}}});}}});return {scope,session,service,requests,response:v=>{response=v;},hold:()=>{deferred=hold();return deferred;},switchABA:()=>{current={userId:peer,generation:2};current={userId:owner,generation:3};session.access_token='later-account-token';}};}
test('installed SDK uses exact frozen publication write and exact operation receipt lookup',async()=>{const f=fixture(),op=operation();assert.equal((await f.service.sendRankedMutation(f.scope,f.session,op)).result.audience,'friends');assert.deepEqual(f.requests[0],{path:'/rest/v1/rpc/rs_ranked_mutate',body:{p_operation:op.operation_id,p_request:op.request},token:'Bearer captured-ranked-write-A'});assert.equal((await f.service.getRankedOperation(f.scope,f.session,op)).operation_id,op.operation_id);assert.deepEqual(f.requests[1].body,{p_operation:op.operation_id});f.response({...receipt(),request:{...op.request,audience:'global'}});await assert.rejects(f.service.getRankedOperation(f.scope,f.session,op),/RANKED_INVALID_RESPONSE/);});
test('owner selector and publication getter bind IDs and never request geometry or private paths',async()=>{const f=fixture(),{user_id,rank,position,tied,profile,...base}=row();f.response({owner_id:owner,server_now:stamp,items:[{...base,publication:{revision:0,audience:'private',updated_at:null}}],next_cursor:null});assert.equal((await f.service.getRankedOwnRecords(f.scope,f.session)).items.length,1);assert.deepEqual(f.requests[0].body,{p_cursor:null,p_limit:30});f.response(publication());assert.equal((await f.service.getRankedPublication(f.scope,f.session,'sustained_speed',uuid(102))).revision,1);assert.deepEqual(f.requests[1].body,{p_metric:'sustained_speed',p_record:uuid(102)});await assert.rejects(f.service.getRankedOwnRecords(f.scope,f.session,null,31),/RANKED_INVALID/);await assert.rejects(f.service.getRankedPublication(f.scope,f.session,'unknown',uuid(102)),/RANKED_INVALID/);assert.equal(f.requests.length,2);});
test('held write and receipt cannot cross account ABA or adopt a refreshed account token',async()=>{const f=fixture(),wait=f.hold(),pending=f.service.sendRankedMutation(f.scope,f.session,operation());await new Promise(r=>setTimeout(r,0));f.switchABA();wait.resolve(receipt());await assert.rejects(pending,/ACCOUNT_CHANGED/);await assert.rejects(f.service.getRankedOperation(f.scope,f.session,operation()),/ACCOUNT_CHANGED/);assert.equal(f.requests.length,1);assert.equal(f.requests[0].token,'Bearer captured-ranked-write-A');});
test('known rate/CAS write envelopes remain definitive typed results; malformed response cannot claim success',async()=>{const f=fixture();f.response({error:{code:'RANKED_PUBLICATION_CHANGED'}});assert.equal((await f.service.sendRankedMutation(f.scope,f.session,operation())).error.code,'RANKED_PUBLICATION_CHANGED');f.response({error:{code:'RANKED_RATE_LIMITED',retry_after_ms:500}});await assert.rejects(f.service.getRankedOperation(f.scope,f.session,operation()),e=>e.message==='RANKED_RATE_LIMITED'&&e.retryAfterMs===500);f.response({error:{code:'private SQL diagnostics'}});await assert.rejects(f.service.sendRankedMutation(f.scope,f.session,operation()),/RANKED_INVALID_RESPONSE/);});
test('installed SDK retained-settings read preserves exact cursor and captured owner JWT without qualification fields',async()=>{const f=fixture(),pub=publication(),cursor={updated_at:'2026-10-01T09:00:00.000001+00:00',record_id:uuid(105),metric:'sustained_speed'};f.response({owner_id:owner,server_now:stamp,items:[{...pub,updated_at:'2026-10-01T08:00:00.000Z'}],next_cursor:null});assert.equal((await f.service.getRankedPublications(f.scope,f.session,cursor,30)).items.length,1);assert.deepEqual(f.requests[0],{path:'/rest/v1/rpc/rs_ranked_publications',body:{p_cursor:cursor,p_limit:30},token:'Bearer captured-ranked-write-A'});const wait=f.hold(),pending=f.service.getRankedPublications(f.scope,f.session);await new Promise(r=>setTimeout(r,0));f.switchABA();wait.resolve({owner_id:owner,server_now:stamp,items:[pub],next_cursor:null});await assert.rejects(pending,/ACCOUNT_CHANGED/);await assert.rejects(f.service.getRankedPublications(f.scope,f.session),/ACCOUNT_CHANGED/);assert.equal(f.requests.length,2);});
