import test from 'node:test';import assert from 'node:assert/strict';import {rankedModule,owner,uuid,stamp,row,hold} from './rankedFixtures.mjs';
const plain=v=>JSON.parse(JSON.stringify(v)),tick=()=>new Promise(r=>setImmediate(r));
function candidate(n=102){const {user_id,rank,position,tied,profile,...base}=row();return {...base,record_id:uuid(n),publication:{revision:0,audience:'private',updated_at:null}};}
function pub(n=102,revision=1){return {owner_id:owner,record_id:uuid(n),metric:'sustained_speed',revision,audience:'private',updated_at:stamp};}
function fixture(){let current=true,now=1000,held=null,heldPublication=null,feed=null;const calls=[];const {RankedOwnerReader}=rankedModule('RankedOwnerReader');const reader=new RankedOwnerReader({ownerId:owner,guard(){if(!current)throw Error('ACCOUNT_CHANGED');},monotonicNow:()=>now,candidates:async cursor=>{calls.push(['candidates',cursor]);if(feed)return feed(cursor);if(held)return held.promise;return {owner_id:owner,server_now:stamp,items:[candidate()],next_cursor:null};},publications:async cursor=>{calls.push(['settings',cursor]);return {owner_id:owner,server_now:stamp,items:[pub()],next_cursor:null};},publication:async(metric,id)=>{calls.push(['get',id]);if(heldPublication)return heldPublication.promise;return pub(Number(id.slice(-12)));}});return {reader,calls,feed(fn){feed=fn;},hold(){return held=hold();},holdPublication(){return heldPublication=hold();},current(v){current=v;},advance(v){now+=v;}};}
test('owner lists distinguish unread/empty and qualification from retained settings',async()=>{const f=fixture();assert.equal(f.reader.getSnapshot().candidatesRead.loaded,false);await f.reader.refresh();assert.equal(f.reader.getSnapshot().candidates.length,1);assert.equal(f.reader.getSnapshot().settings.length,1);assert.equal(f.reader.getSnapshot().publication,null);await f.reader.select('sustained_speed',uuid(102));assert.equal(f.reader.getSnapshot().publication.revision,1);assert.equal(f.reader.currentPublication(f.reader.getSnapshot().publication),true);f.advance(15001);assert.equal(f.reader.currentPublication(f.reader.getSnapshot().publication),false);});
test('suspend before held reply invalidates a full background/foreground cycle without adoption',async()=>{const f=fixture(),wait=f.hold(),pending=f.reader.refresh();await tick();f.reader.suspend();wait.resolve({owner_id:owner,server_now:stamp,items:[candidate()],next_cursor:null});await pending;assert.equal(f.reader.getSnapshot().candidates.length,0);assert.equal(f.reader.getSnapshot().candidatesRead.fresh,false);});
test('latest selection wins held old getter; close/account guard prevents new request',async()=>{const f=fixture(),wait=f.holdPublication(),first=f.reader.select('sustained_speed',uuid(102));await tick();f.reader.suspend();wait.resolve(pub());await first;assert.equal(f.reader.getSnapshot().publication,null);f.current(false);const before=f.calls.length;await assert.rejects(f.reader.select('sustained_speed',uuid(103)),/ACCOUNT_CHANGED/);assert.equal(f.calls.length,before);f.current(true);f.reader.close();await assert.rejects(f.reader.refresh(),/RANKED_CHANGED/);});
test('same lane dispatch coalesces and selection re-read is actual getter, never candidate publication metadata',async()=>{const f=fixture();await f.reader.refresh();const state=f.reader.getSnapshot();assert.equal(state.candidates[0].publication.revision,0);await f.reader.select('sustained_speed',uuid(102));assert.equal(f.reader.getSnapshot().publication.revision,1);const wait=f.hold(),before=f.calls.length,a=f.reader.refresh(),b=f.reader.refresh();await tick();assert.equal(f.calls.length,before+2);wait.resolve({owner_id:owner,server_now:stamp,items:[],next_cursor:null});await Promise.all([a,b]);assert.deepEqual(plain(f.reader.getSnapshot().candidates),[]);assert.equal(f.reader.getSnapshot().candidatesRead.loaded,true);assert.equal(f.reader.getSnapshot().publicationRead.fresh,true);assert.ok(f.calls.slice(before).some(c=>c[0]==='get'));});

test('explicit first-page refresh retires held pagination instead of adopting stale append',async()=>{const f=fixture(),wait=hold();let first=0;f.feed(cursor=>cursor?wait.promise:Promise.resolve({owner_id:owner,server_now:stamp,items:[candidate(first++?105:102)],next_cursor:first===1?{completed_at:candidate().completed_at,record_id:uuid(102),metric:'sustained_speed'}:null}));await f.reader.refresh();const more=f.reader.loadMoreCandidates();await tick();const refreshing=f.reader.refresh();await tick();wait.resolve({owner_id:owner,server_now:stamp,items:[candidate(101)],next_cursor:null});await Promise.all([more,refreshing]);assert.deepEqual(plain(f.reader.getSnapshot().candidates.map(r=>r.record_id)),[uuid(105)]);assert.equal(f.reader.getSnapshot().candidatesRead.fresh,true);});
