import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {resolve,dirname} from 'node:path';import {fileURLToPath} from 'node:url';import {runInNewContext} from 'node:vm';import ts from 'typescript';
import {owner,peer,uuid,stamp,hold,page,row} from './rankedFixtures.mjs';
const root=fileURLToPath(new URL('../src/',import.meta.url)),require=createRequire(import.meta.url),tick=()=>new Promise(done=>setImmediate(done));
const request=()=>({schema_version:1,action:'publication_set',metric:'sustained_speed',record_id:uuid(102),expected_revision:0,audience:'friends'});
const ack=op=>({owner_id:op.owner_id,operation_id:op.operation_id,request:op.request,applied_at:stamp,result:{owner_id:op.owner_id,metric:op.request.metric,record_id:op.request.record_id,revision:op.request.expected_revision+1,audience:op.request.audience,updated_at:stamp}});
function harness(){
 let cells=[],index=0,dirty=false,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'fixture-A'},next=900,moving=false,error=null,failDisk=false,block=null,reportBlock=null,mono=0,social={pending:[],accountRevision:1,latest:null};
 const effects=[],layouts=[],listeners=new Set(),cache=new Map(),owned=new Map([[owner,{rankedOperations:[]}]]),events=[],receipts=new Map();
 const same=(a,b)=>!!a&&a.length===b.length&&a.every((v,i)=>v===b[i]);
 const memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;};
 const effect=(queue,fn,deps)=>{const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};queue.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}};
 const react={createContext(value){return{value,Provider:'Provider'};},useContext:c=>c.value,useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useRef:v=>{const n=index++;return cells[n]??={current:v};},useState:v=>{const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,value=>{cells[n].value=typeof value==='function'?value(cells[n].value):value;dirty=true;}];},useEffect:(fn,deps)=>effect(effects,fn,deps),useLayoutEffect:(fn,deps)=>effect(layouts,fn,deps),useSyncExternalStore:(subscribe,get)=>{const n=index++;if(cells[n]?.subscribe!==subscribe){cells[n]?.remove?.();cells[n]={subscribe,remove:subscribe(()=>dirty=true)};}return get();}};
 const native={currentState:'active',addEventListener(_name,fn){listeners.add(fn);return{remove:()=>listeners.delete(fn)};}};
 const jsx=(_type,props)=>({props});
 const app=()=>({ready:true,storageError:error,data:owned.get(scope.userId)??{rankedOperations:[]},getOwned:()=>owned.get(scope.userId),update(patch){if(error==='LOCAL_READ_FAILED')return false;owned.set(scope.userId,{...owned.get(scope.userId),...patch});events.push(['update',scope.userId]);dirty=true;return true;},flushStorage:async()=>{events.push(['flush',scope.userId]);if(failDisk)throw Error('LOCAL_WRITE_FAILED');},retryStorage:async()=>{}});
 const service={async getRankedOperation(s,_session,op){events.push(['status',s.userId,op.operation_id,native.currentState]);return receipts.get(op.operation_id)??null;},async sendRankedMutation(s,_session,op){events.push(['send',s.userId,op.operation_id,native.currentState]);const result=ack(op),held=block;block=null;if(held)await held.promise;receipts.set(op.operation_id,result);return result;}};
 const overrides={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':{AppState:native},'expo-crypto':{randomUUID:()=>uuid(next++)},'./AppState':{useApp:app},'./AuthState':{useAuth:()=>({scope,session,ready:true}),isAccountCurrent:s=>s===scope},'./RideState':{useRide:()=>({movingLocked:moving})},'./SocialState':{useSocial:()=>social},'../features/ranked/publicationService':service,'../features/ranked/service':{async getRankedPage(s){events.push(['report-read',s.userId]);const held=reportBlock;reportBlock=null;if(held)await held.promise;return{...page(),owner_id:s.userId};}}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);const code=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,TextEncoder,TextDecoder,performance:{now:()=>mono},require:name=>{if(name in overrides)return overrides[name];if(!name.startsWith('.'))return require(name);const base=resolve(dirname(path),name),file=['.ts','.tsx'].map(ext=>base+ext).find(existsSync)??base;return load(file);}});return module.exports;}
 const provider=load(resolve(root,'state/RankedState.tsx'));const h={events,owned,receipts,provider,get scope(){return scope;},get state(){return h.tree.props.value;},render(){index=0;dirty=false;h.tree=provider.RankedProvider({children:null});while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.state;},async settle(){for(let i=0;i<16;i++){await tick();if(dirty)h.render();}return h.render();},holdSend:()=>block=hold(),holdReport:()=>reportBlock=hold(),os(value){native.currentState=value;for(const fn of listeners)fn(value);},move(value){moving=value;return h.render();},social(value){social={...social,...value};return h.render();},storage(value,fail=false){error=value;failDisk=fail;return h.render();},switch(id){scope={userId:id,generation:scope.generation+1};session=id?{user:{id},access_token:'fixture-'+id}:null;if(!owned.has(id))owned.set(id,{rankedOperations:[]});return h.render();},close(){for(const cell of cells){cell?.cleanup?.();cell?.remove?.();}}};return h;
}
test('actual provider flushes owner-local intent before real coordinator status/write and does not publish stale ACK as a record',async()=>{const h=harness();h.render();await h.settle();h.events.length=0;await h.state.mutate(request());await h.settle();assert.deepEqual(h.events.slice(0,4).map(e=>e[0]),['update','flush','flush','flush']);assert.ok(h.events.findIndex(e=>e[0]==='flush')<h.events.findIndex(e=>e[0]==='status'));assert.equal(h.owned.get(owner).rankedOperations.length,0);assert.equal(h.state.appliedVersion,1);assert.equal(h.state.latest.status,'applied');assert.equal('record' in h.state,false);h.close();});
test('actual OS and moving guards reject retained mutation callbacks before storage or network',async()=>{const h=harness();h.render();await h.settle();const old=h.state;h.events.length=0;h.os('background');await assert.rejects(old.mutate(request()),/RANKED_INACTIVE/);assert.equal(h.events.length,0);h.os('active');h.move(true);await assert.rejects(old.mutate(request()),/RANKED_INACTIVE/);assert.equal(h.events.length,0);h.close();});
test('owner ABA retains unknown intent on its original owner and old callback cannot touch replacement storage',async()=>{const h=harness();h.render();await h.settle();const old=h.state,wait=h.holdSend(),task=old.mutate(request());await tick();h.switch(peer);await h.settle();h.switch(owner);wait.resolve();await task;await h.settle();assert.equal(h.owned.get(peer).rankedOperations.length,0);assert.equal(h.events.filter(e=>e[0]==='send').length,1);const before=h.events.length;await assert.rejects(old.mutate(request()),/ACCOUNT_CHANGED/);assert.equal(h.events.length,before);h.close();});
test('disk failure/unread owner cannot issue network and original intent stays available for recovery',async()=>{const h=harness();h.render();await h.settle();h.storage(null,true);h.events.length=0;assert.equal(await h.state.mutate(request()),null);await h.settle();assert.equal(h.events.some(e=>['send','status'].includes(e[0])),false);assert.equal(h.owned.get(owner).rankedOperations.length,1);h.storage('LOCAL_READ_FAILED');assert.equal(h.state.ready,false);await assert.rejects(h.state.retry(),/RANKED_INACTIVE/);h.close();});
test('report bridge clears immediately during an OS background/resume and rejects a held review without a React cleanup',async()=>{const h=harness();h.render();await h.settle();const token=h.state.armReport(page(),row().record_id,peer),wait=h.holdReport(),task=h.state.reviewReport(token);h.os('background');h.os('active');wait.resolve();await assert.rejects(task,/RANKED_CHANGED/);h.render();assert.equal(h.state.reportTarget,null);assert.equal(h.state.currentReport(token),false);h.close();});
test('pending block quarantines an armed peer and retires a held report before its ACK',async()=>{const h=harness();h.render();await h.settle();const old=h.state,token=old.armReport(page(),row().record_id,peer),wait=h.holdReport(),task=old.reviewReport(token);h.social({pending:[{request:{action:'friend_action',verb:'block'}}]});assert.equal(h.state.reportTarget,null);assert.equal(h.state.currentReport(token),false);wait.resolve();await assert.rejects(task,/RANKED_CHANGED/);await assert.rejects(old.reviewReport(token),/RANKED_CHANGED/);h.social({pending:[],accountRevision:2,latest:{operationId:uuid(999)}});assert.equal(h.state.reportTarget,null);assert.equal(h.state.currentReport(token),false);h.close();});
test('publication privacy change clears report authority while the private intent can still reconcile',async()=>{const h=harness();h.render();await h.settle();const token=h.state.armReport(page(),row().record_id,peer);h.owned.get(owner).rankedOperations.push({owner_id:owner,operation_id:uuid(950),request:{...request(),audience:'private'},queued_at:stamp,last_error:null});h.render();assert.equal(h.state.reportTarget,null);assert.equal(h.state.currentReport(token),false);h.close();});
