import test from 'node:test';import assert from 'node:assert/strict';import {rankedModule,owner,uuid,stamp,row,hold} from './rankedFixtures.mjs';
const tick=()=>new Promise(r=>setImmediate(r)),plain=v=>JSON.parse(JSON.stringify(v));
function fixture(kind='publication'){
 let index=0,cells=[],dirty=false,active=true,activityVersion=0,valid=true;const layouts=[],calls=[],same=(a,b)=>a&&a.length===b.length&&a.every((v,i)=>Object.is(v,b[i]));
 const memo=(fn,deps)=>{const n=index++;if(!cells[n]||!same(cells[n].deps,deps))cells[n]={deps,value:fn()};return cells[n].value;};
 const react={useState(v){const n=index++;cells[n]??={value:typeof v==='function'?v():v};return[cells[n].value,next=>{const value=typeof next==='function'?next(cells[n].value):next;if(!Object.is(value,cells[n].value)){cells[n].value=value;dirty=true;}}];},useRef(v){const n=index++;return cells[n]??={current:v};},useCallback:(fn,deps)=>memo(()=>fn,deps),useLayoutEffect(fn,deps){const n=index++,old=cells[n];if(!old||!same(old.deps,deps)){cells[n]={deps};layouts.push(()=>{old?.cleanup?.();cells[n].cleanup=fn();});}}};
 const activity={capture:()=>active?activityVersion:null,accepts:t=>t!==null&&active&&t===activityVersion,generation:0};
 const read={loaded:true,fresh:true,loading:false,hasMore:false,error:null},publication={owner_id:owner,metric:'sustained_speed',record_id:uuid(102),revision:7,audience:'friends',updated_at:stamp};const {user_id,rank,position,tied,profile,...base}=row();
 const port={generation:'A:1',current:g=>active&&valid&&g===port.generation,guard:g=>{if(!active||!valid||g!==port.generation)throw Error('RANKED_CHANGED');if(port.gate.moving)throw Error('RANKED_MOVING');},gate:{signedIn:true,active:true,moving:false,online:true},ready:true,pending:[],latest:null,error:null,state:{candidates:[{...base,publication:{revision:0,audience:'private',updated_at:null}}],settings:[publication],candidatesRead:read,settingsRead:read,selection:{metric:'sustained_speed',record_id:uuid(102)},publication,publicationRead:read},refresh:async()=>calls.push(['refresh']),loadMoreCandidates:async()=>{},loadMoreSettings:async()=>{},select:async()=>{},reviewPublication:async()=>{calls.push(['review']);return port.state.publication;},currentPublication:v=>valid&&active&&JSON.stringify(v)===JSON.stringify(port.state.publication),publish:async request=>{calls.push(['publish',plain(request)]);port.pending=[{operation_id:uuid(900),request}];return uuid(900);},retry:async()=>{calls.push(['retry']);},onBack(){},onSignIn(){},target:{token:'opaque-memory',row:row()},currentTarget:token=>active&&valid&&token===port.target?.token,review:async()=>{calls.push(['reportReview']);return port.target.row;},report:async request=>{calls.push(['report',plain(request)]);return uuid(901);}};
 const jsx=(type,props)=>({type,props}),ui=Object.fromEntries(['Button','Heading','Note','Panel','Screen','T','Field'].map(k=>[k,k]));
 const mod=rankedModule(kind==='publication'?'RankedPublicationScreen':'RankedReportScreen',{'react':react,'react/jsx-runtime':{jsx,jsxs:jsx},'../../components/ui':ui,'../../lib/useScreenActivity':{useScreenActivity:()=>activity}}),component=kind==='publication'?mod.RankedPublicationScreen:mod.RankedReportScreen;
 function flatten(node,out=[]){if(!node)return out;if(Array.isArray(node)){node.forEach(v=>flatten(v,out));return out;}if(typeof node!=='object'){out.push(node);return out;}if(typeof node.type==='function')return flatten(node.type(node.props),out);out.push(node);flatten(node.props?.children,out);flatten(node.props?.right,out);return out;}
 const h={port,calls,render(){index=0;dirty=false;h.tree=component({port,t:key=>key});while(layouts.length)layouts.shift()();return h;},async settle(){for(let i=0;i<8;i++){await tick();if(dirty)h.render();}return h;},nodes:()=>flatten(h.tree),button(label){const node=h.nodes().find(n=>n.type==='Button'&&n.props.label===label);assert.ok(node,`Missing ${label}`);return node.props;},click(label){const b=h.button(label);assert.equal(!!b.disabled,false,`${label} disabled`);b.onPress();return h.settle();},boundary(){active=false;++activityVersion;active=true;++activityVersion;activity.generation=activityVersion;},change(fn){fn(port);return h.render();},close(){valid=false;active=false;}};return h.render();
}
test('publication reviews fresh getter revision rather than embedded candidate metadata and pending is not success',async()=>{const h=fixture();await h.click('rankedPub.global');await h.click('rankedPub.review');await h.click('rankedPub.confirm');assert.deepEqual(h.calls.find(c=>c[0]==='publish')[1],{schema_version:1,action:'publication_set',metric:'sustained_speed',record_id:uuid(102),expected_revision:7,audience:'global'});assert.ok(h.nodes().includes('rankedPub.pending'));assert.equal(h.nodes().includes('rankedPub.applied'),false);});
test('retained expired setting can be made private but loaded qualification cannot be fabricated',async()=>{const h=fixture();h.change(p=>{p.state={...p.state,candidates:[]};});assert.equal(h.button('rankedPub.global').disabled,true);assert.equal(h.button('rankedPub.friends').disabled,true);await h.click('rankedPub.review');await h.click('rankedPub.confirm');assert.equal(h.calls.find(c=>c[0]==='publish')[1].audience,'private');});
test('canonical setting/candidate changes invalidate explicit review before another mutation',async()=>{const h=fixture();await h.click('rankedPub.review');assert.ok(h.button('rankedPub.confirm'));h.change(p=>{p.state={...p.state,publication:{...p.state.publication,revision:8}};});await h.settle();assert.equal(h.nodes().some(n=>n?.type==='Button'&&n.props.label==='rankedPub.confirm'),false);assert.equal(h.calls.some(c=>c[0]==='publish'),false);});
test('held review after full background/resume and later owner cannot expose confirmation or send',async()=>{const h=fixture(),wait=hold();h.port.reviewPublication=()=>wait.promise;const pending=h.click('rankedPub.review');h.boundary();wait.resolve(h.port.state.publication);await pending;h.render();await h.settle();assert.equal(h.nodes().some(n=>n?.type==='Button'&&n.props.label==='rankedPub.confirm'),false);const stale=h.button('rankedPub.review').onPress;h.close();stale();await h.settle();assert.equal(h.calls.some(c=>c[0]==='publish'),false);});
test('report requires opaque memory target and fresh visible proof, received never claims moderation',async()=>{const h=fixture('report');await h.click('rankedPub.reviewRecord');await h.click('rankedPub.sendReport');assert.deepEqual(h.calls.find(c=>c[0]==='report')[1],{schema_version:1,action:'report_record',metric:'sustained_speed',record_id:uuid(102),reason:'suspected_cheating',detail:''});h.change(p=>{p.latest={operation_id:uuid(901),status:'applied',error:null};});assert.ok(h.nodes().includes('rankedPub.received'));const no=fixture('report');no.change(p=>{p.target=null;});assert.ok(no.nodes().includes('rankedPub.reportUnavailable'));assert.equal(no.nodes().some(n=>n?.type==='Button'&&n.props.label==='rankedPub.sendReport'),false);});
test('held report proof and captured retry callback cannot egress after movement or focus exit',async()=>{const h=fixture('report'),wait=hold();h.port.review=()=>wait.promise;const pending=h.click('rankedPub.reviewRecord');h.boundary();wait.resolve(h.port.target.row);await pending;h.render();await h.settle();assert.equal(h.nodes().some(n=>n?.type==='Button'&&n.props.label==='rankedPub.sendReport'),false);h.change(p=>{p.pending=[{operation_id:uuid(900),request:{}}];});const callback=h.button('rankedPub.retry').onPress;h.close();callback();await h.settle();assert.equal(h.calls.some(c=>c[0]==='retry'),false);});
test('retained report editing callbacks cannot change text or reason under current movement policy',async()=>{const h=fixture('report');await h.click('rankedPub.reviewRecord');const field=h.nodes().find(n=>n?.type==='Field').props,reason=h.button('rankedPub.other').onPress;h.change(p=>{p.gate={...p.gate,moving:true};});field.onChangeText('retained edit');reason();await h.settle();h.change(p=>{p.gate={...p.gate,moving:false};});await h.click('rankedPub.reviewRecord');assert.equal(h.nodes().find(n=>n?.type==='Field').props.value,'');await h.click('rankedPub.sendReport');assert.equal(h.calls.find(c=>c[0]==='report')[1].reason,'suspected_cheating');});
test('retained local choices cannot change audience after background/resume or a later owner',async()=>{const h=fixture(),choice=h.button('rankedPub.global').onPress;h.boundary();h.render();choice();await h.settle();await h.click('rankedPub.review');await h.click('rankedPub.confirm');assert.equal(h.calls.find(c=>c[0]==='publish')[1].audience,'private');const other=fixture(),old=other.button('rankedPub.global').onPress;other.change(p=>{p.generation='B:1';});old();await other.settle();await other.click('rankedPub.review');await other.click('rankedPub.confirm');assert.equal(other.calls.find(c=>c[0]==='publish')[1].audience,'private');});
test('publication/report Thai and English resources have identical keys/placeholders and distinguish receipts from moderation',()=>{const {m6pEn,m6pTh}=rankedModule('../../lib/rankedPublicationI18n');assert.deepEqual(Object.keys(m6pEn).sort(),Object.keys(m6pTh).sort());for(const key of Object.keys(m6pEn)){assert.deepEqual(m6pEn[key].match(/\{[^}]+\}/g)??[],m6pTh[key].match(/\{[^}]+\}/g)??[]);assert.ok(m6pTh[key].trim());}assert.match(m6pEn['rankedPub.received'],/does not mean moderation/);assert.match(m6pTh['rankedPub.received'],/ยังไม่ได้หมายความ/);});
