import test from 'node:test';import assert from 'node:assert/strict';import {rankedModule,owner,filter,page,row,course,timeFilter,timeRow,hold} from './rankedFixtures.mjs';
function fixture(){
 const fibres=new Map(),calls=[],animations=[];let fibre,cursor,effects=[],screen,theme='dark';
 const hooks={useState(initial){const i=cursor++;if(!(i in fibre))fibre[i]=typeof initial==='function'?initial():initial;const selected=fibre;return [selected[i],next=>{selected[i]=typeof next==='function'?next(selected[i]):next;}];},useRef(initial){const i=cursor++;return fibre[i]??={current:initial};},useCallback(fn,deps){const i=cursor++,old=fibre[i];if(!old||deps?.some((v,j)=>v!==old.deps?.[j]))fibre[i]={value:fn,deps};return fibre[i].value;},useMemo(fn){cursor++;return fn();},useLayoutEffect(fn){cursor++;fn();},useEffect(fn,deps){const i=cursor++,selected=fibre,old=selected[i];if(!old||deps?.some((v,j)=>v!==old.deps?.[j]))effects.push(()=>{old?.cleanup?.();selected[i]={deps,cleanup:fn()};});}};
 const jsx=(type,props)=>({type,props}),deps={react:hooks,'react/jsx-runtime':{jsx,jsxs:jsx,Fragment:'Fragment'},'@shopify/flash-list':{FlashList:'FlashList'},'react-native':{View:'View',FlatList:'FlatList',Pressable:'Pressable',RefreshControl:'RefreshControl',ActivityIndicator:'ActivityIndicator',useWindowDimensions:()=>({width:428,height:926,fontScale:1}),StyleSheet:{absoluteFill:{},create:v=>v}},'react-native-safe-area-context':{useSafeAreaInsets:()=>({top:0,bottom:0})},'react-native-reanimated':{default:{View:'AnimatedView'},ReduceMotion:{System:'system',Always:'always'},useSharedValue:value=>hooks.useRef({value}).current,useAnimatedStyle:fn=>fn(),withTiming:(value,config)=>{animations.push(config);return value;},withSequence:(...values)=>values.at(-1),cancelAnimation:()=>{}},'../../components/ui':Object.fromEntries(['Button','Empty','Note','Panel','Row','T','Glass','Icon'].map(x=>[x,x])),'../../state/AppState':{useApp:()=>({dark:theme==='dark',motion:true,colors:{bg:theme==='dark'?'#000000':'#FAFAF8',surface:theme==='dark'?'#0A0A0A':'#FFF',raised:'#111',ink:'#FFF',muted:'#AAA',line:'#333',accent:'#FF5A1F',danger:'#FF3B5C'}})},'../motion':{AmbientLoop:'AmbientLoop'},'../motion/assets':{resolveAmbientAsset:(role,mode)=>`${role}-${mode}`},'../routes/RouteSheet':{RouteSheet:'RouteSheet'}};
 const port={ownerId:owner,generation:'A1',current:g=>g===port.generation,guard:g=>{if(g!==port.generation)throw Error('ACCOUNT_CHANGED');},gate:{signedIn:true,focused:true,foreground:true,moving:false,online:true},ready:true,filter:filter(),page:page(),rows:[row()],read:{loading:false,fresh:true,error:null,hasMore:false},courses:[course()],coursesRead:{loading:false,fresh:true,error:null,hasMore:false},units:'kmh',locale:'en',rankChanges:{},refresh:async()=>{calls.push('refresh');},loadMore:async()=>{calls.push('more');},loadMoreCourses:async()=>{calls.push('moreCourses');},setFilter:async selected=>{calls.push(['filter',selected]);port.filter=selected;port.page=null;port.rows=[];port.read.fresh=false;},onSignIn:()=>calls.push('signIn'),onManagePublication:()=>calls.push('publication'),onReport:binding=>calls.push(['report',binding])};
 function expand(value,path){if(!value||typeof value!=='object')return value;if(Array.isArray(value))return value.map((v,i)=>expand(v,path+':'+i));if(!('type' in value))return value;if(typeof value.type==='function'){const key=path+':'+value.type.name;fibre=fibres.get(key)??[];fibres.set(key,fibre);cursor=0;return expand(value.type(value.props),path+':render');}const result={...value,props:{...value.props}};for(const key of ['children','ListHeaderComponent','ListEmptyComponent','ListFooterComponent','refreshControl'])if(key in result.props&&!(value.type==='RouteSheet'&&!value.props.visible))result.props[key]=expand(result.props[key],path+':'+key);return result;}
 screen=rankedModule('RankedScreen',deps).RankedScreen;
 return {port,calls,animations,theme:value=>{theme=value;},render(){effects=[];const tree=expand(jsx(screen,{port,t:(key,values)=>values?key+':'+JSON.stringify(values):key}),'screen');effects.forEach(fn=>fn());return tree;},part(value){effects=[];const tree=expand(value,'part');effects.forEach(fn=>fn());return tree;}};
}
function all(tree,type){const found=[];function walk(v){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(walk);return;}if(v.type===type)found.push(v);if(v.type==='RouteSheet'&&!v.props.visible)return;for(const key of ['children','ListHeaderComponent','ListEmptyComponent','ListFooterComponent','refreshControl'])if(v.props&&key in v.props)walk(v.props[key]);}walk(tree);return found;}
function button(tree,label){const item=all(tree,'Button').find(x=>x.props.label===label);assert.ok(item,label);return item.props;}
test('a failed unread first page offers retry without claiming an empty board',()=>{const f=fixture();f.port.page=null;f.port.rows=[];f.port.read.fresh=false;f.port.read.error='RANKED_UNAVAILABLE';const tree=f.render();assert.equal(all(tree,'Empty').length,0);assert.ok(button(tree,'m6.refresh'));});
test('only a successful fresh supported read can show genuine empty records',()=>{const f=fixture();f.port.page.items=[];f.port.page.podium=[];f.port.rows=[];assert.equal(all(f.render(),'Empty').length,1);f.port.gate.online=false;assert.equal(all(f.render(),'Empty').length,0);});
test('actual 0–3 podium rows retain shared ranks and theme-resolved materials',()=>{for(let count=0;count<=3;count++){const f=fixture();f.port.page.podium=Array.from({length:count},(_,i)=>({...row(i+2,i+1),rank:1,tied:true}));let tree=f.render();assert.equal(all(tree,'AmbientLoop').filter(v=>v.props.asset.startsWith('podium-')).length,count);assert.equal(all(tree,'T').filter(v=>v.props.children==='m6.tied').length,count);f.theme('light');tree=f.render();assert.equal(all(tree,'AmbientLoop').every(v=>v.props.asset.endsWith('-light')),true);}});
test('sticky own-rank shows an authoritative off-page rank rather than scanning visible rows',()=>{const f=fixture();f.port.page.self=row(1,82);f.port.page.self_status='ranked';const tree=f.render();assert.ok(all(tree,'Glass').length);assert.ok(all(tree,'T').some(v=>v.props.children===82));assert.equal(f.port.rows.length,1);});
test('an old category/filter button cannot rewind a newer filter or account',async()=>{const f=fixture();let tree=f.render();await button(tree,'m6.filters').onPress();tree=f.render();const old=all(tree,'Pressable').find(v=>v.props.accessibilityLabel==='m6.car').props;f.port.generation='B1';f.render();await old.onPress();assert.deepEqual(f.calls,[]);});
test('movement disables list scrolling, reporting, filters and refresh at callback time',async()=>{const f=fixture(),tree=f.render(),refresh=button(tree,'m6.refresh'),filters=button(tree,'m6.filters');f.port.gate.moving=true;let moved=f.render();assert.equal(all(moved,'FlashList')[0].props.scrollEnabled,false);await refresh.onPress();await filters.onPress();assert.deepEqual(f.calls,[]);const rendered=f.part(all(moved,'FlashList')[0].props.renderItem({item:row()}));assert.equal(button(rendered,'m6.report').disabled,true);});
test('held page work invalidates on background and retry is usable on foreground return',async()=>{const f=fixture(),wait=hold();f.port.loadMore=()=>wait.promise;f.port.read.hasMore=true;let tree=f.render();const pending=button(tree,'m6.more').onPress();f.port.gate.foreground=false;f.render();f.port.gate.foreground=true;f.render();tree=f.render();assert.equal(button(tree,'m6.more').busy,false);wait.resolve();await pending;});
test('route-time labels retain outward interval bounds and original method while speed uses chosen units',()=>{const f=fixture();f.port.filter=timeFilter();f.port.page.filter=timeFilter();f.port.page.items=[timeRow()];f.port.page.podium=[timeRow()];f.port.rows=[timeRow()];let tree=f.render();assert.ok(all(tree,'T').some(v=>String(v.props.children).includes('10–11')));assert.ok(all(tree,'Note').some(v=>v.props.children==='m6.timeQuality'));const speed=fixture();speed.port.units='mph';tree=speed.render();assert.ok(all(tree,'T').some(v=>String(v.props.children).includes('mph')));});
test('courses expose further pages and a missing public discovery read never claims no boards',async()=>{const f=fixture();f.port.filter=timeFilter();f.port.filter.course=null;f.port.page=null;f.port.rows=[];f.port.coursesRead.hasMore=true;const tree=f.render();assert.ok(button(tree,'m6.moreCourses'));await button(tree,'m6.moreCourses').onPress();assert.deepEqual(f.calls,['moreCourses']);f.port.courses=[];f.port.coursesRead.fresh=false;f.port.coursesRead.error='RANKED_UNAVAILABLE';assert.equal(all(f.render(),'Note').some(v=>v.props.children==='m6.noCourses'),false);});
test('shared record report uses its exact current board binding and refuses stale revision',async()=>{const f=fixture();const list=all(f.render(),'FlashList')[0],item=f.part(list.props.renderItem({item:row()})),report=button(item,'m6.report');f.port.page.board_revision='c'.repeat(64);f.render();await report.onPress();assert.deepEqual(f.calls,[]);});
test('native View children contain elements, including unread/footer/podium branches',()=>{for(const variant of ['normal','unread','moving']){const f=fixture();if(variant==='unread'){f.port.page=null;f.port.rows=[];f.port.read.error='RANKED_UNAVAILABLE';}if(variant==='moving')f.port.gate.moving=true;const tree=f.render();for(const node of all(tree,'View'))assert.equal([node.props.children].flat(Infinity).some(v=>typeof v==='string'||typeof v==='number'),false,variant);}});
test('rank resource maps have Thai/English dotted-key parity without nested resources',()=>{const {m6En,m6Th}=rankedModule('../../lib/rankedI18n');assert.deepEqual(Object.keys(m6En).sort(),Object.keys(m6Th).sort());assert.equal(typeof m6Th['m6.class.scooter:gt125_le160'],'string');assert.equal('m6' in m6En,false);});
test('retired owner generations immediately hide cached rows and own-rank before provider clearing',()=>{const f=fixture();f.port.page.self=row(1,82);f.port.page.self_status='ranked';f.port.current=()=>false;const tree=f.render();assert.equal(all(tree,'FlashList')[0].props.data.length,0);assert.equal(all(tree,'Glass').length,0);});
test('ambient header/podium leave the playback budget after the measured content scrolls offscreen',()=>{const f=fixture();let tree=f.render();const list=all(tree,'FlashList')[0];list.props.onScroll({nativeEvent:{contentOffset:{y:1000}}});tree=f.render();assert.equal(all(tree,'AmbientLoop').every(v=>v.props.visible===false),true);});
