import test from 'node:test';import assert from 'node:assert/strict';
import {rankedModule,owner,uuid,stamp,hold} from './rankedFixtures.mjs';
const {RankedCoordinator}=rankedModule('RankedCoordinator');
const request=(audience='friends',expected_revision=0)=>({schema_version:1,action:'publication_set',metric:'sustained_speed',record_id:uuid(102),expected_revision,audience});
const stored=(n=900,input=request())=>({owner_id:owner,operation_id:uuid(n),request:input,queued_at:stamp,last_error:null});
const receipt=op=>({owner_id:owner,operation_id:op.operation_id,request:op.request,applied_at:stamp,result:{owner_id:owner,metric:op.request.metric,record_id:op.request.record_id,revision:op.request.expected_revision+1,audience:op.request.audience,updated_at:stamp}});
function fixture(initial=[]){let rows=initial,current=true,eligible=true,durable=false,writesFail=false,now=0;const calls=[],receipts=new Map();let sender=async op=>{const ack=receipt(op);receipts.set(op.operation_id,ack);return ack;};const f={coordinator:null,rows:()=>rows,calls,receipts,now:v=>{now=v;},closeOwner:()=>{current=false;},eligible:v=>{eligible=v;},failWrites:v=>{writesFail=v;},send:fn=>{sender=fn;}};
 f.coordinator=new RankedCoordinator({ownerId:owner,guard:()=>{if(!current)throw Error('ACCOUNT_CHANGED');},canSend:()=>eligible,read:()=>rows,update:async reduce=>{const next=reduce(rows);rows=next;durable=false;if(writesFail)throw Error('LOCAL_WRITE_FAILED');},flush:async()=>{if(writesFail)throw Error('LOCAL_WRITE_FAILED');durable=true;},operationId:()=>uuid(900+rows.length),nowISO:()=>stamp,monotonicNow:()=>now,status:async op=>{assert.equal(durable,true);calls.push(['status',op.operation_id]);return receipts.get(op.operation_id)??null;},send:async op=>{assert.equal(durable,true);calls.push(['send',op.operation_id]);return sender(op);},applied:async ack=>{calls.push(['applied',ack.operation_id]);}});return f;
}
test('persist and flush exact reviewed intent before any network; canonical ACK retires only that durable UUID',async()=>{const f=fixture();assert.equal(await f.coordinator.enqueue(request()),uuid(900));assert.deepEqual(f.calls.map(x=>x[0]),['status','send','applied']);assert.equal(f.rows().length,0);assert.equal(f.coordinator.getSnapshot().latest.status,'applied');});
test('lost ACK and restart reconciles exact receipt without a second mutation or new privacy intent',async()=>{const f=fixture();f.send(async op=>{f.receipts.set(op.operation_id,receipt(op));throw Error('RANKED_UNAVAILABLE');});await f.coordinator.enqueue(request('global'));assert.equal(f.rows().length,0);assert.equal(f.calls.filter(x=>x[0]==='send').length,1);
 const restart=fixture([stored()]);restart.receipts.set(uuid(900),receipt(stored()));await restart.coordinator.retry();assert.deepEqual(restart.calls.map(x=>x[0]),['status','applied']);assert.equal(restart.rows().length,0);});
test('unknown outcome stays durable; same-record successor cannot leap over it',async()=>{const f=fixture([stored(900),stored(901,request('private',1))]);f.send(async()=>{throw Error('RANKED_UNAVAILABLE');});await f.coordinator.retry();assert.equal(f.rows().length,2);assert.equal(f.calls.filter(x=>x[0]==='send').length,1);assert.equal(f.rows()[0].last_error,'RANKED_UNAVAILABLE');});
test('validated CAS rejection requires absent receipt; rate and transient replies preserve bounded recovery',async()=>{const f=fixture([stored()]);f.send(async()=>({error:{code:'RANKED_RATE_LIMITED',retry_after_ms:1000}}));await f.coordinator.retry();assert.equal(f.rows().length,1);const count=f.calls.length;await f.coordinator.retry();assert.equal(f.calls.length,count);f.now(1000);f.send(async()=>({error:{code:'RANKED_PUBLICATION_CHANGED'}}));await f.coordinator.retry();assert.equal(f.rows().length,0);assert.equal(f.coordinator.getSnapshot().latest.status,'rejected');});
test('failed persistence never sends and failed ACK removal restores unknown intent for status-only retry',async()=>{const f=fixture();f.failWrites(true);assert.equal(await f.coordinator.enqueue(request()),null);assert.equal(f.calls.length,0);f.failWrites(false);f.send(async op=>{f.receipts.set(op.operation_id,receipt(op));f.failWrites(true);return receipt(op);});await f.coordinator.retry();assert.equal(f.rows().length,1);f.failWrites(false);await f.coordinator.retry();assert.equal(f.rows().length,0);assert.equal(f.calls.filter(x=>x[0]==='send').length,1);});
test('held reply cannot settle owner ABA and background work does not issue transport',async()=>{const f=fixture([stored()]),wait=hold();f.send(()=>wait.promise);const pending=f.coordinator.retry();await new Promise(r=>setTimeout(r,0));f.closeOwner();wait.resolve(receipt(stored()));await pending;assert.equal(f.rows().length,1);assert.equal(f.calls.some(x=>x[0]==='applied'),false);
 const background=fixture([stored()]);background.eligible(false);await background.coordinator.retry();assert.equal(background.calls.length,0);});
