import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,existsSync} from 'node:fs';
import {createRequire} from 'node:module';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {runInNewContext} from 'node:vm';
import ts from 'typescript';
import {owner,peer,filter,page,row,coursePage,hold,rankedModule,stamp} from './rankedFixtures.mjs';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../src/',import.meta.url)),tick=()=>new Promise(done=>setImmediate(done));
const rankedModel=rankedModule('model'),{bangkokPeriodBounds}=rankedModule('presentationModel');

/** Actual account host, activity hook and reader. Only React/native OS events
 * and captured API replies are fixtures; no product gate or source is patched. */
function harness(){
 let cells=[],index=0,dirty=false,focused=true,scope={userId:owner,generation:1},session={user:{id:owner},access_token:'A-1'},moving=false,vehicle={category:'bigbike',engineCc:999,powertrain:'petrol'},appReady=true,now=1000,pageHold=null,courseHold=null;
 const layouts=[],effects=[],listeners=new Set(),cache=new Map(),calls=[],navigation=[]; let ranked={pending:[],appliedVersion:0,armReport:(p,id,user)=>{navigation.push({p,id,user});return 'opaque-token';}},social={pending:[],accountRevision:1,latest:null};
 const same=(a,b)=>!!a&&a.length===b.length&&a.every((value,i)=>Object.is(value,b[i]));
 const memo=(fn,deps)=>{const at=index++;if(!cells[at]||!same(cells[at].deps,deps))cells[at]={deps,value:fn()};return cells[at].value;};
 const enqueue=(queue,fn,deps)=>{const at=index++,old=cells[at];if(!old||!same(old.deps,deps)){cells[at]={deps};queue.push(()=>{old?.cleanup?.();cells[at].cleanup=fn();});}};
 const react={useRef:value=>{const at=index++;return cells[at]??={current:value};},useMemo:memo,useCallback:(fn,deps)=>memo(()=>fn,deps),useState:value=>{const at=index++;cells[at]??={value:typeof value==='function'?value():value};return[cells[at].value,next=>{cells[at].value=typeof next==='function'?next(cells[at].value):next;dirty=true;}];},useEffect:(fn,deps)=>enqueue(effects,fn,deps),useLayoutEffect:(fn,deps)=>enqueue(layouts,fn,deps),useSyncExternalStore:(subscribe,get)=>{const at=index++;if(cells[at]?.subscribe!==subscribe){cells[at]?.remove?.();cells[at]={subscribe,remove:subscribe(()=>dirty=true)};}return get();}};
 const native={Platform:{OS:'ios'},AppState:{currentState:'active',addEventListener(_name,fn){listeners.add(fn);return{remove(){listeners.delete(fn);}};}}},jsx=(type,props)=>({type,props});
 const auth=()=>({scope,ready:true,session}),app=()=>({ready:appReady,vehicle,storageError:null,data:{unit:'kmh'}});
 const service={async getRankedPage(requested,captured,value,cursor){const wait=pageHold;pageHold=null;calls.push({kind:'page',scope:requested,session:captured,filter:value,cursor});const record={...row(requested.userId===owner?2:3),category:value.category,class_key:`${value.category}:unknown`},items=value.class_key==='all'||value.class_key===record.class_key?[record]:[],base=page(),result=rankedModel.validateRankedPage({...base,owner_id:requested.userId,filter:value,period:{...base.period,...bangkokPeriodBounds(stamp,value.period)},items,podium:items},requested.userId,value,cursor);if(wait)await wait.promise;return result;},async getRankedCourses(requested,captured,cursor){const wait=courseHold;courseHold=null;calls.push({kind:'courses',scope:requested,session:captured,cursor});const result=rankedModel.validateRankedCourses({...coursePage(),owner_id:requested.userId},requested.userId,cursor);if(wait)await wait.promise;return result;}};
 const overrides={react,'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':native,'expo-router':{useIsFocused:()=>focused,router:{push(){}}},'../../features/ranked':{RankedScreen:'RankedScreen'},'../../features/ranked/service':service,'../../lib/i18n':{useI18n:()=>({language:'th',t:key=>key})},'../../state/AppState':{useApp:app},'../../state/AuthState':{useAuth:auth,isAccountCurrent:value=>value===scope},'../../state/RideState':{useRide:()=>({movingLocked:moving})},'../../state/RankedState':{useRanked:()=>ranked},'../../state/SocialState':{useSocial:()=>social},'../../components/ui':{Screen:'Screen',T:'T'}};
 function load(path){if(cache.has(path))return cache.get(path).exports;const module={exports:{}};cache.set(path,module);let source=readFileSync(path,'utf8');if(path.endsWith('rankings.tsx'))source+='\nexport {AccountRankings as __testAccountRankings};\n';const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;runInNewContext(code,{module,exports:module.exports,console,Date,Promise,Error,performance:{now:()=>now},require:name=>{if(name in overrides)return overrides[name];if(!name.startsWith('.'))return require(name);let target=resolve(dirname(path),name);if(!existsSync(target))for(const ext of ['.ts','.tsx'])if(existsSync(target+ext)){target+=ext;break;}return load(target);}});return module.exports;}
 const component=load(resolve(root,'app/(tabs)/rankings.tsx'));
 const h={calls,navigation,privacy(pending){ranked={...ranked,pending};return h.render();},settledPrivacy(){ranked={...ranked,pending:[],appliedVersion:ranked.appliedVersion+1};return h.render();},socialPrivacy(pending){social={...social,pending};return h.render();},get scope(){return scope;},get port(){return h.tree.props.port;},render(){index=0;dirty=false;h.tree=component.__testAccountRankings();while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return h.port;},async settle(){for(let i=0;i<8;i++){await tick();if(dirty)h.render();}return h.render();},holdPages(){return pageHold=hold();},holdCourses(){return courseHold=hold();},os(status){native.AppState.currentState=status;for(const listener of listeners)listener(status);},focus(value){focused=value;return h.render();},move(value){moving=value;return h.render();},changeVehicle(value){vehicle=value;return h.render();},switch(userId){for(const cell of cells){cell?.cleanup?.();cell?.remove?.();}cells=[];scope={userId,generation:scope.generation+1};session={user:{id:userId},access_token:`${userId}-${scope.generation}`};return h.render();},unread(){appReady=false;index=0;const result=component.default();while(layouts.length)layouts.shift()();while(effects.length)effects.shift()();return result;},close(){for(const cell of cells){cell?.cleanup?.();cell?.remove?.();}}};return h;
}

test('held board and course replies are retired by a complete OS background/resume before React renders',async()=>{
 const h=harness(),board=h.holdPages(),courses=h.holdCourses();h.render();assert.equal(h.calls.length,2);h.os('background');h.os('active');board.resolve();courses.resolve();await tick();
 // No lifecycle effect has run yet. The per-request activity ticket alone
 // must reject both replies; it must not rely on a later React cleanup.
 const port=h.render();assert.equal(port.page,null);assert.equal(port.rows.length,0);assert.equal(port.courses.length,0);assert.equal(port.read.fresh,false);assert.equal(port.coursesRead.fresh,false);await h.settle();assert.equal(h.port.read.fresh,true);h.close();
});
test('owner ABA cannot adopt an old reply or use an old callback to dispatch a later account request',async()=>{
 const h=harness(),blocked=h.holdPages();h.render();const old=h.port,oldScope=h.scope;h.switch(peer);await h.settle();h.switch(owner);await h.settle();const before=h.calls.length;await assert.rejects(old.refresh(),/RANKED_CHANGED/);assert.equal(h.calls.length,before);blocked.resolve();await h.settle();assert.notEqual(h.scope,oldScope);assert.equal(h.port.page.owner_id,owner);assert.equal(h.calls.at(-1).session.user.id,owner);h.close();
});
test('retired held filter response cannot replace the current filter and hidden/moving callbacks make no service call',async()=>{
 const h=harness();h.render();await h.settle();const blocked=h.holdPages(),refresh=assert.rejects(h.port.refresh(),/RANKED_CHANGED/);await tick();await h.port.setFilter({...h.port.filter,period:'week'});await h.settle();blocked.resolve();await refresh;await h.settle();assert.equal(h.port.page.filter.period,'week');const old=h.port,before=h.calls.length;h.os('background');await assert.rejects(old.refresh(),/RANKED_CHANGED/);assert.equal(h.calls.length,before);h.os('active');h.render();await h.settle();const current=h.port;h.move(true);const count=h.calls.length;await assert.rejects(current.refresh(),/RANKED_MOVING/);assert.equal(h.calls.length,count);h.close();
});
test('hydrated Garage big-bike class seeds once while later Garage changes preserve an explicit chosen filter',async()=>{
 const h=harness();h.render();await h.settle();assert.equal(h.port.filter.category,'motorcycle');assert.equal(h.port.filter.class_key,'motorcycle:gt900');await h.port.setFilter({...filter(),period:'month'});await h.settle();h.changeVehicle({category:'scooter',engineCc:160,powertrain:'petrol'});await h.settle();assert.equal(h.port.filter.period,'month');assert.equal(h.port.filter.category,'scooter');assert.equal(h.port.filter.class_key,'all');h.close();
});
test('outer host waits for unread Garage state and emits no ranked service request',()=>{const h=harness(),tree=h.unread();assert.equal(tree.type,'Screen');assert.equal(h.calls.length,0);h.close();});

test('pending unshare hides cached board immediately; confirmed outcome requires fresh canonical rows',async()=>{const h=harness();h.render();await h.settle();const source=h.port.page;assert.ok(source);const pending=h.holdPages(),task=h.port.refresh();await tick();h.privacy([{request:{action:'publication_set',audience:'private'}}]);assert.equal(h.port.page,null);assert.equal(h.port.rows.length,0);assert.equal(h.port.read.fresh,false);pending.resolve();await assert.rejects(task,/RANKED_CHANGED/);await h.settle();assert.equal(h.port.page,null);h.settledPrivacy();await h.settle();assert.equal(h.port.read.fresh,true);h.close();});

test('pending block/removal quarantines board and retired report callbacks dispatch nothing',async()=>{const h=harness();h.render();await h.settle();await h.port.setFilter({...filter(),period:'today'});await h.settle();const old=h.port,binding={record_id:old.rows[0].record_id,user_id:old.rows[0].user_id,metric:old.rows[0].metric,board_revision:old.page.board_revision};h.socialPrivacy([{request:{action:'friend_action',verb:'block',other_id:peer}}]);assert.equal(h.port.page,null);assert.throws(()=>h.port.onReport(binding),/RANKED_CHANGED/);assert.equal(h.navigation.length,0);h.close();});

test('report navigation hands off only an exact current server page and rejects changed record binding',async()=>{const h=harness();h.render();await h.settle();await h.port.setFilter({...filter(),period:'today'});await h.settle();const p=h.port,r=p.rows[0],binding={record_id:r.record_id,user_id:r.user_id,metric:r.metric,board_revision:p.page.board_revision};p.onReport(binding);assert.equal(h.navigation.length,1);assert.equal(h.navigation[0].p.items[0].record_id,r.record_id);assert.throws(()=>p.onReport({...binding,board_revision:'f'.repeat(64)}),/RANKED_CHANGED/);assert.equal(h.navigation.length,1);h.close();});
