import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {resolve,dirname} from 'node:path';
const require=createRequire(import.meta.url),ts=require('typescript'),cache=new Map();
function load(path){if(!existsSync(path))return {};if(cache.has(path))return cache.get(path).exports;const mod={exports:{}};cache.set(path,mod);new Function('require','module','exports',ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>name.startsWith('.')?load(resolve(dirname(path),`${name}.ts`)):require(name),mod,mod.exports);return mod.exports;}
const root=fileURLToPath(new URL('../src/features/routes/',import.meta.url)),model=load(resolve(root,'localModel.ts')),{RouteCoordinator}=load(resolve(root,'RouteCoordinator.ts')),copy=v=>JSON.parse(JSON.stringify(v));
const document=(title='Local')=>({schema_version:1,title,category:'scooter',visibility:'private',stops:[{lat:13,lng:100,label:'Start'},{lat:14,lng:101,label:'Finish'}],source:{kind:'draft'}});
const pause=()=>{let resolve;const promise=new Promise(done=>resolve=done);return {promise,resolve};};const tick=()=>new Promise(r=>setImmediate(r));
function fixture({records=[],session=true}={}){
 let owned={routeRecords:records},sequence=0,valid=true,failDisk=false,holdSend=null,holdFetch=null,holdWrite=null,sendError=null,loseResponse=false;
 const remote=new Map(),receipts=new Map(),calls=[],disk={owned:copy(owned)},port={guard(){if(!valid)throw Error('ACCOUNT_CHANGED');},hasSession:()=>session,read:()=>owned,flush:async()=>{if(failDisk)throw Error('LOCAL_WRITE_FAILED');disk.owned=copy(owned);},write:async patch=>{owned={...owned,...copy(patch)};if(holdWrite)await holdWrite.promise;if(failDisk)throw Error('LOCAL_WRITE_FAILED');disk.owned=copy(owned);},operation:()=>`aaaaaaaa-aaaa-4aaa-8aaa-${String(++sequence).padStart(12,'0')}`,
 async fetch(id){if(holdFetch)await holdFetch.promise;return copy(remote.get(id)??null);},async list(){return [...remote.values()].map(copy);},async save(draft){calls.push({action:'save',draft:copy(draft)});if(holdSend)await holdSend.promise;if(receipts.has(draft.operationId))return copy(receipts.get(draft.operationId));if(sendError)throw Error(sendError);const old=remote.get(draft.routeId);if((old?.revision??0)!==draft.expectedRevision)throw Error('ROUTE_REVISION_CONFLICT');const revision=draft.expectedRevision+1;remote.set(draft.routeId,{id:draft.routeId,owner_id:'owner',revision,document:copy(draft.document),segments:[],distanceMeters:null,durationSeconds:null,geometryHash:null,provider:'draft',calculatedAt:null,attribution:null,updated_at:'2026-10-01T00:00:00Z'});const ack={operation_id:draft.operationId,route_id:draft.routeId,action:'save',applied_revision:revision,current_revision:revision,document_sha256:'a'.repeat(64),synced_at:'2026-10-01T00:00:00Z'};receipts.set(draft.operationId,ack);if(loseResponse){loseResponse=false;throw Error('NETWORK_ERROR');}return ack;},async remove(draft){calls.push({action:'delete',draft:copy(draft)});if(receipts.has(draft.operationId))return copy(receipts.get(draft.operationId));const old=remote.get(draft.routeId);if(old?.revision!==draft.expectedRevision)throw Error('ROUTE_REVISION_CONFLICT');remote.delete(draft.routeId);const ack={operation_id:draft.operationId,route_id:draft.routeId,action:'delete',applied_revision:draft.expectedRevision,current_revision:null,document_sha256:null,synced_at:'2026-10-01T00:00:00Z'};receipts.set(draft.operationId,ack);return ack;}};
 const coordinator=new RouteCoordinator(port);return {coordinator,port,remote,calls,disk,get owned(){return owned;},restart(){owned={routeRecords:model.parseRouteRecords(copy(disk.owned.routeRecords))};coordinator.close();return new RouteCoordinator(port);},failDisk:v=>{failDisk=v;},invalidate:()=>{valid=false;},holdSend:()=>holdSend=pause(),holdFetch:()=>holdFetch=pause(),holdWrite:()=>holdWrite=pause(),sendError:v=>{sendError=v;},loseResponse:()=>{loseResponse=true;}};
}
const local=(title='Local')=>model.routeRecord({localId:'local',document:document(title)});
test('new route persists its cloud UUID and immutable operation before publication',async()=>{const h=fixture({records:[local()]});await h.coordinator.sync();assert.equal(h.calls.length,1);assert.equal(h.owned.routeRecords[0].sync.revision,1);assert.equal(h.owned.routeRecords[0].sync.pending,null);assert.equal(h.disk.owned.routeRecords[0].sync.cloudId,h.calls[0].draft.routeId);});
test('unknown response and restart replay identical operation before newer edit',async()=>{const h=fixture({records:[local()]});h.loseResponse();await h.coordinator.sync();const sent=copy(h.calls[0].draft),restarted=h.restart();await restarted.save({localId:'local',document:document('Newer')},{existingOnly:true});await restarted.sync();assert.deepEqual(h.calls[1].draft,sent);assert.equal(h.remote.get(sent.routeId).document.title,'Newer');});
test('delete while pending save hides route then settles old save before deleting',async()=>{const h=fixture({records:[local()]});h.sendError('NETWORK_ERROR');await h.coordinator.sync();const first=copy(h.calls[0].draft);await h.coordinator.remove('local');assert.deepEqual(model.compatibleRoutes(h.owned.routeRecords),[]);h.sendError(null);await h.coordinator.sync();assert.deepEqual(h.calls[1].draft,first);assert.equal(h.calls.at(-1).action,'delete');assert.equal(h.remote.size,0);assert.equal(h.owned.routeRecords[0].sync.serverDeleted,true);});
test('disk failure blocks egress; failed ACK restores pending while keeping newer edits',async()=>{const h=fixture({records:[local()]});h.failDisk(true);await h.coordinator.sync();assert.equal(h.calls.length,0);h.failDisk(false);const hold=h.holdSend(),work=h.coordinator.sync();await tick();await h.coordinator.save({localId:'local',document:document('Newer')});h.failDisk(true);hold.resolve();await work;assert.equal(h.owned.routeRecords[0].document.title,'Newer');assert.ok(h.owned.routeRecords[0].sync.pending);h.failDisk(false);await h.coordinator.sync();assert.deepEqual(h.calls[1].draft,h.calls[0].draft);assert.equal(h.remote.values().next().value.document.title,'Newer');});
test('closed/ABA owner scope fences delayed adoption and retained callbacks',async()=>{const h=fixture({records:[local()]});const hold=h.holdFetch(),work=h.coordinator.sync();h.invalidate();hold.resolve();await work;assert.equal(h.calls.length,0);assert.equal(await h.coordinator.save({localId:'late',document:document()}),false);h.coordinator.close();assert.equal(await h.coordinator.remove('local'),false);});
test('queued existingOnly edit cannot recreate removed route',async()=>{const h=fixture({records:[local()],session:false}),hold=h.holdWrite();const remove=h.coordinator.remove('local');await tick();const edit=h.coordinator.save({localId:'local',document:document('Stale')},{existingOnly:true});hold.resolve();await remove;assert.equal(await edit,false);assert.deepEqual(model.compatibleRoutes(h.owned.routeRecords),[]);});
test('dirty concurrent remote revision conflicts and cloud choice is explicit',async()=>{const h=fixture({records:[local()]});await h.coordinator.sync();const record=h.owned.routeRecords[0];await h.coordinator.save({localId:'local',document:document('Local edit')});h.remote.set(record.sync.cloudId,{...h.remote.get(record.sync.cloudId),revision:2,document:document('Other device')});await h.coordinator.sync();assert.equal(h.coordinator.getSnapshot().status,'conflict');assert.equal(h.owned.routeRecords[0].document.title,'Local edit');await h.coordinator.resolveConflict('local','cloud');assert.equal(h.owned.routeRecords[0].document.title,'Other device');assert.equal(h.calls.length,1);});
test('remote deletion keep-local creates new UUID copy and old tombstone blocks stale list adoption after reload',async()=>{const h=fixture({records:[local()]});await h.coordinator.sync();const old=copy(h.owned.routeRecords[0]),stale=copy(h.remote.get(old.sync.cloudId));await h.coordinator.save({localId:'local',document:document('Keep me')});h.remote.delete(old.sync.cloudId);await h.coordinator.sync();assert.equal(h.coordinator.getSnapshot().conflicts.local.reason,'deleted');await h.coordinator.resolveConflict('local','local');assert.ok(h.owned.routeRecords.find(r=>r.localId==='local').sync.serverDeleted);const visible=model.compatibleRoutes(h.owned.routeRecords);assert.equal(visible.length,1);assert.notEqual(visible[0].cloudId,old.sync.cloudId);h.remote.set(stale.id,stale);const restarted=new RouteCoordinator({...h.port,read:()=>({routeRecords:model.parseRouteRecords(h.owned.routeRecords)})});await restarted.sync();assert.equal(model.compatibleRoutes(h.owned.routeRecords).length,1);});
test('definitive expired source blocks same fingerprint durably; edited document clears fence',async()=>{const h=fixture({records:[local()]});h.sendError('ROUTE_SOURCE_EXPIRED');await h.coordinator.sync();assert.equal(h.owned.routeRecords[0].sync.pending,null);assert.equal(h.owned.routeRecords[0].sync.blocked.error,'ROUTE_SOURCE_EXPIRED');await h.coordinator.sync();assert.equal(h.calls.length,1);h.sendError(null);await h.coordinator.save({localId:'local',document:document('Recalculated')});await h.coordinator.sync();assert.equal(h.calls.length,2);});
test('local edits during conflict resolution fetch are preserved rather than silently overwritten',async()=>{const h=fixture({records:[local()]});await h.coordinator.sync();const id=h.owned.routeRecords[0].sync.cloudId;await h.coordinator.save({localId:'local',document:document('edit')});h.remote.set(id,{...h.remote.get(id),revision:2,document:document('remote')});await h.coordinator.sync();const hold=h.holdFetch(),work=h.coordinator.resolveConflict('local','cloud');await tick();await h.coordinator.save({localId:'local',document:document('Late edit')});hold.resolve();await work;assert.equal(h.owned.routeRecords[0].document.title,'Late edit');assert.equal(h.coordinator.getSnapshot().error,'ROUTE_CONFLICT_CHANGED');});
test('pin/category/source changes clear cached geometry; metadata-only edits preserve it',async()=>{
 const record=local();record.geometry={segments:[[{latitude:13,longitude:100},{latitude:14,longitude:101}]],distanceMeters:1,durationSeconds:null,geometryHash:null,provider:'recorded',calculatedAt:null,attribution:null};const h=fixture({records:[record],session:false});
 await h.coordinator.save({localId:'local',document:document('Renamed')});assert.ok(h.owned.routeRecords[0].geometry);
 await h.coordinator.save({localId:'local',document:{...document('Moved'),stops:[{lat:13.2,lng:100,label:'Start'},{lat:14,lng:101,label:'Finish'}]}});assert.equal(h.owned.routeRecords[0].geometry,null);
});
test('an uncertain operation on one route does not prevent another route syncing',async()=>{
 const second=model.routeRecord({localId:'second',document:document('Second')}),h=fixture({records:[local(),second]}),send=h.port.save;
 h.port.save=async draft=>{if(draft.document.title==='Local'){h.calls.push({action:'save',draft:copy(draft)});throw Error('NETWORK_ERROR');}return send(draft);};
 await h.coordinator.sync();assert.ok(h.owned.routeRecords.find(r=>r.localId==='local').sync.pending);assert.equal(h.owned.routeRecords.find(r=>r.localId==='second').sync.revision,1);
});
test('source rejection followed by local removal never emits invalid revision-zero delete',async()=>{
 const h=fixture({records:[local()]});h.sendError('ROUTE_SOURCE_EXPIRED');await h.coordinator.sync();await h.coordinator.remove('local');h.sendError(null);await h.coordinator.sync();assert.equal(h.calls.length,1);assert.equal(h.owned.routeRecords[0].sync.serverDeleted,true);assert.equal(h.coordinator.getSnapshot().status,'synced');
});
test('remote deletion of a clean route hides it, while partial empty lists do not prove deletion',async()=>{
 const h=fixture({records:[local()]});await h.coordinator.sync();const id=h.owned.routeRecords[0].sync.cloudId;h.port.list=async()=>[];await h.coordinator.sync();assert.equal(model.compatibleRoutes(h.owned.routeRecords).length,1);h.remote.delete(id);await h.coordinator.sync();assert.equal(model.compatibleRoutes(h.owned.routeRecords).length,0);assert.equal(h.owned.routeRecords[0].sync.serverDeleted,true);
});
test('lost deletion response survives disk reparse and exact receipt replay',async()=>{
 const h=fixture({records:[local()]});await h.coordinator.sync();await h.coordinator.remove('local');const remove=h.port.remove;let lost=true;h.port.remove=async draft=>{const ack=await remove(draft);if(lost){lost=false;throw Error('NETWORK_ERROR');}return ack;};await h.coordinator.sync();const pending=copy(h.disk.owned.routeRecords[0].sync.pending),restarted=h.restart();await restarted.sync();assert.deepEqual(h.calls.at(-1).draft,pending.draft);assert.equal(h.owned.routeRecords[0].sync.serverDeleted,true);assert.deepEqual(model.compatibleRoutes(h.owned.routeRecords),[]);
});
test('forged ACK cannot clear pending metadata and another route can continue',async()=>{
 const h=fixture({records:[local()]}),save=h.port.save;h.port.save=async draft=>({...await save(draft),operation_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb'});await h.coordinator.sync();assert.ok(h.owned.routeRecords[0].sync.pending);assert.equal(h.owned.routeRecords[0].sync.revision,0);assert.equal(h.coordinator.getSnapshot().error,'ROUTE_SYNC_INVALID_RESPONSE');h.port.save=save;await h.coordinator.sync();assert.equal(h.owned.routeRecords[0].sync.pending,null);assert.equal(h.calls.length,2);
});
test('late send response after owner change cannot acknowledge old pending in the new scope',async()=>{
 const h=fixture({records:[local()]}),hold=h.holdSend(),work=h.coordinator.sync();await tick();const old=copy(h.owned);h.invalidate();hold.resolve();await work;assert.deepEqual(h.owned,old);assert.ok(h.owned.routeRecords[0].sync.pending);
});
test('unknown legacy cloud binding adopts only exact equality and otherwise needs explicit conflict',async()=>{
 const h=fixture({records:[local()]});await h.coordinator.sync();const bound=copy(h.owned.routeRecords[0]);bound.sync.cleanFingerprint=null;const equal=fixture({records:[bound]});equal.remote.set(bound.sync.cloudId,copy(h.remote.get(bound.sync.cloudId)));await equal.coordinator.sync();assert.equal(equal.calls.length,0);assert.ok(equal.owned.routeRecords[0].sync.cleanFingerprint);
 const unequal=fixture({records:[{...bound,document:document('Legacy local differs')}]});unequal.remote.set(bound.sync.cloudId,copy(h.remote.get(bound.sync.cloudId)));await unequal.coordinator.sync();assert.equal(unequal.calls.length,0);assert.equal(unequal.coordinator.getSnapshot().status,'conflict');
});
test('cloud adoption capacity fails explicitly and does not silently claim synced',async()=>{
 const rows=Array.from({length:200},(_,i)=>model.routeRecord({localId:`local-${i}`,document:document()})),h=fixture({records:rows});h.remote.set('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',{id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',owner_id:'owner',revision:1,document:document('Cloud extra'),segments:[],distanceMeters:null,durationSeconds:null,geometryHash:null,provider:'draft',calculatedAt:null,attribution:null,updated_at:'2026-10-01T00:00:00Z'});await h.coordinator.sync();assert.equal(h.coordinator.getSnapshot().error,'ROUTE_TOO_LARGE');assert.equal(h.coordinator.getSnapshot().status,'error');assert.equal(h.owned.routeRecords.length,200);assert.equal(h.calls.length,0);
});
test('resumed editor baseline rejects a newer adopted cloud document and explicit missing baseline',async()=>{
 const h=fixture({records:[local()]});await h.coordinator.sync();const id=h.owned.routeRecords[0].sync.cloudId,baseline=model.fingerprintRoute(h.owned.routeRecords[0].document);h.remote.set(id,{...h.remote.get(id),revision:2,document:document('Changed remotely')});await h.coordinator.sync();
 assert.equal(await h.coordinator.save({localId:'local',document:document('Stale editor'),expectedFingerprint:baseline},{existingOnly:true}),false);assert.equal(h.owned.routeRecords[0].document.title,'Changed remotely');assert.equal(h.coordinator.getSnapshot().error,'ROUTE_LOCAL_CHANGED');
 assert.equal(await h.coordinator.save({localId:'local',document:document('Unknown baseline'),expectedFingerprint:null},{existingOnly:true}),false);
 const fresh=model.fingerprintRoute(h.owned.routeRecords[0].document);assert.equal(await h.coordinator.save({localId:'local',document:document('Current edit'),expectedFingerprint:fresh},{existingOnly:true}),true);
});
