import assert from 'node:assert/strict';import test from 'node:test';import {readFileSync} from 'node:fs';import {createRequire} from 'node:module';import vm from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript');const compile=(path,imports={})=>{const module={exports:{}};vm.compileFunction(ts.transpileModule(readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,['require','module','exports'])(name=>{if(name in imports)return imports[name];throw Error(name);},module,module.exports);return module.exports;};
const model=compile('../src/features/routes/syncModel.ts');const uuid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const doc=()=>({schema_version:1,title:'เส้นทางส่วนตัว',category:'scooter',visibility:'private',stops:[{lat:13.7,lng:100.5,label:'เริ่ม'},{lat:13.71,lng:100.5,label:'จบ'}],source:{kind:'road',routeToken:uuid(9)}});
const draft=()=>({operationId:uuid(2),routeId:uuid(3),expectedRevision:0,document:doc()});const ack=(d=draft(),action='save')=>({operation_id:d.operationId,route_id:d.routeId,action,applied_revision:action==='save'?d.expectedRevision+1:d.expectedRevision,current_revision:action==='save'?d.expectedRevision+1:null,document_sha256:action==='save'?'a'.repeat(64):null,synced_at:'2026-10-01T02:00:00.123456+00:00'});
test('freezer detaches exact route source/pin/visibility and rejects forged geometry or malformed segmented encodings',()=>{const d=draft(),copy=model.freezeRouteDraft(d);d.document.stops[0].label='changed';assert.equal(copy.document.stops[0].label,'เริ่ม');assert.equal(Object.isFrozen(copy.document.stops[0]),true);
for(const p of [{...doc(),owner_id:uuid(7)},{...doc(),category:['scooter']},{...doc(),source:{kind:'road',routeToken:uuid(9),geometry:[]}},{...doc(),source:{kind:'recorded',segments:['~']}},{...doc(),title:'x'.repeat(81)},{...doc(),stops:[{lat:999,lng:100,label:'x'},doc().stops[1]]}])assert.throws(()=>model.validateRouteDocument(p),/ROUTE_INVALID/);});
test('ACK replay remains exact after later edit or deletion and cannot bind a foreign operation/action',()=>{assert.deepEqual(model.validateRouteAck({...ack(),current_revision:null},draft(),'save'),{...ack(),current_revision:null});const deletion={operationId:uuid(5),routeId:uuid(3),expectedRevision:3};assert.deepEqual(model.validateRouteAck(ack(deletion,'delete'),deletion,'delete'),ack(deletion,'delete'));for(const patch of [{operation_id:uuid(8)},{route_id:uuid(8)},{action:'delete'},{applied_revision:4},{current_revision:0},{document_sha256:null},{rawGps:[]}])assert.throws(()=>model.validateRouteAck({...ack(),...patch},draft(),'save'),/ROUTE_SYNC_INVALID_RESPONSE/);});
test('unknown response recovers only exact receipt while conflicts and definite expired sources never rebase',async()=>{const d=draft(),calls=[];const result=await model.sendRouteOperation(d,'save',{async send(input){calls.push(input);d.document.title='edited';throw Error('lost');},async status(op){calls.push(op);return ack();}},()=>{});assert.equal(result.operation_id,uuid(2));assert.equal(calls[0].document.title,'เส้นทางส่วนตัว');assert.equal(calls[1],uuid(2));let statuses=0;for(const code of ['ROUTE_DELETED','ROUTE_REVISION_CONFLICT','ROUTE_SOURCE_EXPIRED','ACCOUNT_CHANGED'])await assert.rejects(model.sendRouteOperation(draft(),'save',{async send(){throw Error(code);},async status(){statuses++;return ack();}},()=>{}),new RegExp(code));assert.equal(statuses,0);});
function harness(respond){const sdk=require('@supabase/supabase-js'),requests=[],scope={userId:uuid(1),generation:1},session={user:{id:uuid(1)},access_token:'route-fixed-A'};let current=scope;const client=sdk.createClient('https://configured.test','publishable',{accessToken:async()=>session.access_token,global:{fetch:async(input,init)=>{const request={path:new URL(typeof input==='string'?input:input.url).pathname,token:new Headers(init.headers).get('Authorization'),body:JSON.parse(init.body)};requests.push(request);const r=await respond(request,requests.length);return new Response(JSON.stringify(r.body),{status:r.status??200,headers:{'Content-Type':'application/json'}});}}});const api=compile('../src/features/routes/syncService.ts',{'../../state/AuthState':{accountClient:()=>client,isAccountCurrent:value=>value===current},'./syncModel':model});return{api,scope,session,requests,switchAccount(){current={userId:uuid(1),generation:3};}};}
test('real SDK sends only bound v2 CAS parameters with captured JWT and scoped status recovery',async()=>{const h=harness((_,n)=>n===1?{status:503,body:{message:'private provider details'}}:{body:ack()});assert.deepEqual(await h.api.saveRoute(h.scope,h.session,draft()),ack());assert.deepEqual(h.requests.map(x=>x.path),['/rest/v1/rpc/rs_save_route_v2','/rest/v1/rpc/rs_get_route_operation']);assert.deepEqual(h.requests[0].body,{p_operation:uuid(2),p_id:uuid(3),p_expected_revision:0,p_document:doc()});assert.equal(h.requests[0].token,'Bearer route-fixed-A');assert.deepEqual(h.requests[1].body,{p_operation:uuid(2)});});
test('real SDK discards A→B→A read response and never sends invalid operation or exposes raw SQL error',async()=>{let enter,release;const ready=new Promise(r=>enter=r),held=new Promise(r=>release=r);const h=harness(async()=>{enter();return held;});const pending=h.api.getRouteOwner(h.scope,h.session,uuid(3));await ready;h.switchAccount();release({body:null});await assert.rejects(pending,/ACCOUNT_CHANGED/);assert.equal(h.requests.length,1);const c=harness(()=>({status:400,body:{code:'P0001',message:'ROUTE_SOURCE_EXPIRED'}}));await assert.rejects(c.api.saveRoute(c.scope,c.session,draft()),/ROUTE_SOURCE_EXPIRED/);assert.equal(c.requests.length,1);});
test('keyset ordering preserves server microseconds and handles equivalent timezone offsets',()=>{assert.equal(model.compareRouteTimestamps('2026-10-01T02:00:00.123456+00:00','2026-10-01T02:00:00.123455Z'),1);assert.equal(model.compareRouteTimestamps('2026-10-01T09:00:00.123456+07:00','2026-10-01T02:00:00.123456Z'),0);const snapshot=(id,date)=>({id,owner_id:uuid(1),revision:1,document:{...doc(),source:{kind:'draft'}},segments:[],distanceMeters:null,durationSeconds:null,geometryHash:null,provider:'draft',calculatedAt:null,attribution:null,updated_at:date});const items=[snapshot(uuid(3),'2026-10-01T02:00:00.123456Z'),snapshot(uuid(4),'2026-10-01T02:00:00.123455Z')];assert.deepEqual(model.validateRoutePage({items,next_cursor:null},uuid(1)).items,items);assert.throws(()=>model.validateRoutePage({items:items.toReversed(),next_cursor:null},uuid(1)),/ROUTE_SYNC_INVALID_RESPONSE/);});
test('last int32 revision can still be deleted while another save cannot overflow',()=>{assert.equal(model.freezeRouteDeleteDraft({operationId:uuid(2),routeId:uuid(3),expectedRevision:2147483647}).expectedRevision,2147483647);assert.throws(()=>model.freezeRouteDraft({...draft(),expectedRevision:2147483647}),/ROUTE_INVALID/);});
