import {randomUUID} from 'expo-crypto';
import * as ImagePicker from 'expo-image-picker';
import {router} from 'expo-router';
import {useCallback,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {Platform} from 'react-native';
import {AccountGate} from '../components/AccountGate';
import {Button,Heading,Note,Panel,Screen,T} from '../components/ui';
import {CommunityComposer} from '../features/community/CommunityComposer';
import {RouteSheet} from '../features/routes/RouteSheet';
import {CommunityDraftController} from '../features/community/CommunityDraftController';
import {prepareCommunityPhoto} from '../features/community/imagePreparation';
import {communityPhotoPreview} from '../features/community/photoPreview';
import {commitCommunityMedia,getCommunityAttachmentReview,reserveCommunityMedia,reserveCommunityPost} from '../features/community/service';
import type {CommunityComposerPort,CommunityDraftPhoto,CommunityRead,CommunityRideChoice,CommunityRouteChoice} from '../features/community/uiTypes';
import {listRideSummaries,type RideHistoryCursor} from '../features/rides/syncService';
import {listRoutesOwner,type RouteCursor} from '../features/routes/syncService';
import {communityErrorKey} from '../lib/communityI18n';
import {useI18n,type TranslationKey} from '../lib/i18n';
import {useScreenActivity} from '../lib/useScreenActivity';
import {useApp} from '../state/AppState';
import {isAccountCurrent,useAuth} from '../state/AuthState';
import {communityPhotos,uploadCommunityPhoto,useCommunity} from '../state/CommunityState';
import {useRide} from '../state/RideState';
import {useSocial} from '../state/SocialState';
const unread=():CommunityRead=>({loading:false,fresh:false,error:null,hasMore:false});
type Choices={rides:readonly CommunityRideChoice[];routes:readonly CommunityRouteChoice[];ridesRead:CommunityRead;routesRead:CommunityRead};
const blankChoices=():Choices=>({rides:[],routes:[],ridesRead:unread(),routesRead:unread()});
export default function ComposeRoute(){const auth=useAuth(),app=useApp(),{t}=useI18n();if(!auth.ready||!app.ready)return <Screen><T>{t('common.wait')}</T></Screen>;if(!auth.session)return <Screen><Heading eyebrow="" title={t('m7.compose')}/><AccountGate>{null}</AccountGate></Screen>;return <AccountComposer key={auth.scope.generation}/>;}
function AccountComposer(){
 const auth=useAuth(),app=useApp(),community=useCommunity(),ride=useRide(),social=useSocial(),activity=useScreenActivity(),{t,language}=useI18n(),{scope}=auth;
 const [discard,setDiscard]=useState<string|null>(null),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[choices,setChoices]=useState<Choices>(blankChoices),[previews,setPreviews]=useState<Record<string,string>>({});
 const choiceEpoch=useRef(0),choiceVersions=useRef({rides:0,routes:0}),cursors=useRef<{rides:RideHistoryCursor|null;routes:RouteCursor|null}>({rides:null,routes:null}),choiceRefs=useRef(choices),localEpoch=useRef(0),editLane=useRef<Promise<unknown>>(Promise.resolve()),libraryLock=useRef(false);
 const generation=JSON.stringify([scope.generation,activity.active,activity.generation,ride.movingLocked,community.privacyKey]),refs=useRef({auth,app,community,activity,moving:ride.movingLocked,generation,profileReady:social.profileReady});
 useLayoutEffect(()=>{if(refs.current.moving!==ride.movingLocked||refs.current.community.privacyKey!==community.privacyKey)++localEpoch.current;refs.current={auth,app,community,activity,moving:ride.movingLocked,generation,profileReady:social.profileReady};choiceRefs.current=choices;},[auth,app,community,activity,ride.movingLocked,generation,social.profileReady,choices]);
 const guard=useCallback((kind:'owner'|'edit'|'control')=>{const fresh=refs.current;fresh.community.guardOwner();if(!isAccountCurrent(scope)||fresh.auth.scope!==scope)throw Error('ACCOUNT_CHANGED');if(kind==='owner')return;if(!fresh.activity.current())throw Error('COMMUNITY_REVIEW_REQUIRED');if(fresh.moving)throw Error('COMMUNITY_MOVING');if(!fresh.community.ready)throw Error('LOCAL_READ_FAILED');if(kind==='control'){fresh.community.signed();if(!fresh.profileReady)throw Error('COMMUNITY_PROFILE_REQUIRED');}},[scope]);
 const version=useCallback(()=>JSON.stringify([refs.current.activity.capture(),localEpoch.current]),[]);
 const lease=useCallback((kind:'edit'|'control')=>{guard(kind);const value=version();return()=>{guard(kind);if(version()!==value)throw Error('COMMUNITY_REVIEW_REQUIRED');};},[guard,version]);
 const localTask=async<T,>(task:()=>Promise<T>,kind:'edit'|'control'='edit'):Promise<T>=>{const check=lease(kind),work=editLane.current.catch(()=>{}).then(async()=>{check();const result=await task();check();return result;});editLane.current=work.catch(()=>{});return work;};
 // Each finite request captures its initiating session.
 // eslint-disable-next-line react-hooks/refs
 const controller=useMemo(()=>new CommunityDraftController({ownerId:scope.userId!,guard,activityVersion:version,read:()=>refs.current.community.readDrafts(),update:reduce=>refs.current.community.updateDrafts(reduce),flush:()=>refs.current.app.flushStorage(),operationId:randomUUID,nowISO:()=>new Date().toISOString(),
  reservePost:async id=>{const check=lease('control'),session=refs.current.community.signed(),value=await reserveCommunityPost(scope,session,id);check();return value;},
  reserveMedia:async(post,media,descriptor)=>{const check=lease('control'),session=refs.current.community.signed(),value=await reserveCommunityMedia(scope,session,post,media,descriptor);check();return value;},
  readPhoto:(post_id,media_id,descriptor)=>communityPhotos.read(scope,{post_id,media_id},descriptor,lease('control')),
  upload:async(reservation,bytes)=>{const check=lease('control'),session=refs.current.community.signed();await uploadCommunityPhoto(scope,session,reservation,bytes,check);check();},
  commitMedia:async(post,media,descriptor)=>{const check=lease('control'),session=refs.current.community.signed(),value=await commitCommunityMedia(scope,session,post,media,descriptor);check();return value;},
  attachmentReview:async selection=>{const check=lease('control'),session=refs.current.community.signed(),value=await getCommunityAttachmentReview(scope,session,selection);check();return value;},
  enqueue:(request,id)=>refs.current.community.enqueuePublication(request,id,lease('control')),
 }),[scope,guard,version,lease]);
 useEffect(()=>()=>controller.close(),[controller]);
 const currentDraft=community.drafts.find(row=>row.draft_id===selected),photoKey=currentDraft?.photos.map(p=>p.media_id+':'+p.descriptor.sha256).join('|')??'';
 // Retire the foreground preview lease when its external activity changes.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{let alive=true;const disposers:(()=>void)[]=[];if(!activity.active||ride.movingLocked||!currentDraft){setPreviews({});return;}const ticket=activity.capture(),epoch=version(),post_id=currentDraft.post_id,photos=currentDraft.photos;const check=()=>{guard('edit');if(!alive||!activity.accepts(ticket)||version()!==epoch)throw Error('COMMUNITY_REVIEW_REQUIRED');};setPreviews({});void(async()=>{const values:Record<string,string>={};for(const photo of photos){try{const preview=await communityPhotoPreview(communityPhotos,scope,{post_id,media_id:photo.media_id},photo.descriptor,check);try{check();}catch(error){preview.dispose();throw error;}disposers.push(preview.dispose);values[photo.media_id]=preview.uri;}catch{check();}}check();setPreviews(values);})().catch(()=>{});return()=>{alive=false;disposers.forEach(dispose=>dispose());};
 // Caption edits do not reload private image bytes.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[scope,selected,photoKey,activity.active,activity.generation,ride.movingLocked,community.privacyKey,guard,version]);
 const readChoices=useCallback(async(kind:'rides'|'routes',append=false)=>{
  const check=lease('control'),ticket=refs.current.activity.capture(),epoch=choiceEpoch.current,sequence=++choiceVersions.current[kind],session=refs.current.community.signed(),cursor=append?cursors.current[kind]:null;
  if(append&&!cursor)return;const verify=()=>{check();if(!refs.current.activity.accepts(ticket)||epoch!==choiceEpoch.current||sequence!==choiceVersions.current[kind])throw Error('COMMUNITY_CHANGED');};
  const readKey=kind==='rides'?'ridesRead':'routesRead';
  setChoices(previous=>({...previous,[readKey]:{...previous[readKey],loading:true,fresh:false,error:null}}));
  try{if(kind==='rides'){
   const page=await listRideSummaries(scope,session,{limit:20,cursor:cursor as RideHistoryCursor|null});verify();const rows=page.items.map(row=>({binding:{ride_id:row.ride_id,ride_revision:row.revision},summary:{ride_id:row.ride_id,ride_revision:row.revision,started_at:row.payload.started_at,ended_at:row.payload.ended_at,active_duration_ms:row.payload.active_duration_ms,distance_m:row.payload.distance_m,max_speed_mps:row.payload.max_speed_mps,average_speed_mps:row.payload.average_speed_mps,speed_status:row.speed_status,vehicle:row.payload.vehicle}}));const existing=append?choiceRefs.current.rides:[],seen=new Set(existing.map(row=>row.binding.ride_id));if(rows.some(row=>seen.has(row.binding.ride_id))||existing.length+rows.length>300)throw Error('COMMUNITY_CAPACITY');cursors.current.rides=page.next_cursor;setChoices(previous=>({...previous,rides:[...existing,...rows],ridesRead:{loading:false,fresh:true,error:null,hasMore:!!page.next_cursor}}));
  }else{const page=await listRoutesOwner(scope,session,20,cursor as RouteCursor|null);verify();const rows=page.items.map(row=>({binding:{route_id:row.id,route_revision:row.revision},title:row.document.title,category:row.document.category})),existing=append?choiceRefs.current.routes:[],seen=new Set(existing.map(row=>row.binding.route_id));if(rows.some(row=>seen.has(row.binding.route_id))||existing.length+rows.length>300)throw Error('COMMUNITY_CAPACITY');cursors.current.routes=page.next_cursor;setChoices(previous=>({...previous,routes:[...existing,...rows],routesRead:{loading:false,fresh:true,error:null,hasMore:!!page.next_cursor}}));}
  }catch(value){try{verify();const code=value instanceof Error&&value.message==='COMMUNITY_CAPACITY'?'COMMUNITY_CAPACITY':'COMMUNITY_UNAVAILABLE';setChoices(previous=>({...previous,[readKey]:{...previous[readKey],loading:false,fresh:false,error:code}}));}catch{/* Retired choices are not adopted. */}}
 },[scope,lease]);
 const refreshChoices=useCallback(async()=>{lease('control')();await Promise.allSettled([readChoices('rides'),readChoices('routes')]);},[lease,readChoices]);
 // A new activity retires the external owner-source page cache and local action lease.
 // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
 useEffect(()=>{++choiceEpoch.current;libraryLock.current=false;setBusy(false);cursors.current={rides:null,routes:null};setChoices(blankChoices());if(selected&&activity.active&&!ride.movingLocked&&community.ready&&auth.session&&social.profileReady)void refreshChoices().catch(()=>{});return()=>{++choiceEpoch.current;};},[selected,activity.active,activity.generation,ride.movingLocked,community.ready,auth.session,social.profileReady,community.privacyKey,refreshChoices]);
 const freshDraft=()=>{guard('edit');const value=refs.current.community.readDrafts().find(d=>d.draft_id===selected);if(!value)throw Error('COMMUNITY_DRAFT_UNAVAILABLE');return value;};
 const run=async(task:()=>Promise<void>)=>{if(libraryLock.current)return;const check=lease('edit');libraryLock.current=true;setBusy(true);setError(null);try{await localTask(task);check();}catch(value){try{check();setError(communityErrorKey(value));}catch{/* Retired presentation. */}}finally{try{check();libraryLock.current=false;setBusy(false);}catch{}}};
 const close=()=>{guard('edit');void community.retirePublished().catch(()=>{});router.back();};
 if(!currentDraft)return <Screen><Heading eyebrow="" title={t('m7.compose')} right={<Button small secondary label={t('m7.close')} onPress={close}/>}/>{error&&<Note error>{t(error as TranslationKey)}</Note>}{community.drafts.filter(row=>row.status!=='published').map(row=><Panel key={row.draft_id}><T weight="semibold">{row.document.caption||t('m7.localDraft')}</T><T size={12} muted>{t(row.status==='pending'?'m7.pendingPublish':'m7.localDraft')}</T><Button secondary label={t('m7.resumeDraft')} disabled={busy||!activity.active||ride.movingLocked} onPress={()=>{guard('edit');setSelected(row.draft_id);}}/>{row.status!=='pending'&&<Button small secondary label={t('m7.discardDraft')} disabled={busy||!activity.active||ride.movingLocked} onPress={()=>{guard('edit');setDiscard(row.draft_id);}}/>}</Panel>)}<Button label={t('m7.newDraft')} icon="add-outline" busy={busy} disabled={!community.ready||!activity.active||ride.movingLocked||community.drafts.filter(d=>d.status!=='published').length>=4} onPress={()=>void run(async()=>{const check=lease('edit');await community.retirePublished();check();const draft=await controller.create();check();setSelected(draft.draft_id);})}/>{community.drafts.filter(d=>d.status!=='published').length>=4&&<Note>{t('m7.draftLimit')}</Note>}<RouteSheet visible={!!discard&&activity.active&&!ride.movingLocked} title={t('m7.discardDraft')} onClose={()=>setDiscard(null)}><T>{t('m7.discardDraftBody')}</T><Button label={t('m7.confirmDiscard')} busy={busy} onPress={()=>void run(async()=>{if(!discard)throw Error('COMMUNITY_CHANGED');await community.discardDraft(discard,lease('edit'));setDiscard(null);})}/></RouteSheet></Screen>;
 const photos:CommunityDraftPhoto[]=currentDraft.photos.map(p=>({media_id:p.media_id,previewUri:activity.active&&!ride.movingLocked?previews[p.media_id]??null:null,descriptor:p.commit?{...p.commit.descriptor,media_id:p.media_id,validation:'decoded_jpeg_v1'}:null,state:p.commit?'ready':currentDraft.status==='preparing'?'validating':'local',progress:null,error:null}));
 const port:CommunityComposerPort={ownerId:scope.userId,generation,current:value=>isAccountCurrent(scope)&&refs.current.generation===value,guard:(value,kind)=>{if(refs.current.generation!==value)throw Error('COMMUNITY_CHANGED');guard(kind==='control'?'control':'edit');},gate:{signedIn:!!auth.session,profileReady:social.profileReady,focused:activity.active,foreground:activity.active,moving:ride.movingLocked,online:Platform.OS!=='web'||typeof navigator==='undefined'||navigator.onLine},ready:community.ready,units:app.data.unit,locale:language,pending:community.pending,latest:community.latest,busy:community.busy,mutate:request=>community.mutate(request,lease('control')),retry:async()=>{const check=lease('control');await community.retry();check();await controller.retryPending(selected??undefined);check();},onSignIn:()=>router.push('/auth'),draft:{draft_id:currentDraft.draft_id,revision:currentDraft.revision,document:currentDraft.document,photos,status:currentDraft.status,operationId:currentDraft.operationId,error:currentDraft.error},...choices,
  changeDraft:patch=>localTask(async()=>{const draft=freshDraft();await controller.edit(draft.draft_id,{...draft.document,...patch});return true;}),
  choosePhotos:()=>localTask(async()=>{const check=lease('edit'),draft=freshDraft();if(draft.status!=='local'||draft.photos.length>=6)throw Error('COMMUNITY_CAPACITY');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:6-draft.photos.length,allowsEditing:false,quality:1,exif:false});check();if(result.canceled)return;for(const asset of result.assets){check();const current=freshDraft();if(current.photos.length>=6)throw Error('COMMUNITY_CAPACITY');const media_id=randomUUID(),key={post_id:current.post_id,media_id};let prepared:Awaited<ReturnType<typeof prepareCommunityPhoto>>|null=null;try{prepared=await prepareCommunityPhoto({uri:asset.uri,width:asset.width,height:asset.height,byteCount:asset.fileSize,webFile:asset.file},check);check();const descriptor=prepared.descriptor;await communityPhotos.putAndAdopt(scope,key,prepared.bytes,descriptor,async()=>{check();const fresh=freshDraft();await controller.setPhotos(fresh.draft_id,[...fresh.photos.map(p=>({media_id:p.media_id,descriptor:p.descriptor})),{media_id,descriptor}]);check();},check);check();}catch(value){try{guard('owner');if(!community.readDrafts().some(d=>d.photos.some(p=>p.media_id===media_id)))await communityPhotos.remove(scope,key,()=>guard('owner'));}catch{/* Only this unreferenced private candidate can be removed. */}throw value;}finally{await prepared?.dispose();}}}),
  removePhoto:id=>localTask(async()=>{const check=lease('edit'),draft=freshDraft();await controller.setPhotos(draft.draft_id,draft.photos.filter(p=>p.media_id!==id).map(p=>({media_id:p.media_id,descriptor:p.descriptor})));check();await communityPhotos.prune(scope,()=>community.readDrafts().flatMap(d=>d.photos.map(p=>({post_id:d.post_id,media_id:p.media_id}))),()=>guard('owner'));check();}),
  movePhoto:(id,direction)=>localTask(async()=>{const draft=freshDraft(),rows=[...draft.photos],index=rows.findIndex(p=>p.media_id===id),next=index+direction;if(index<0||next<0||next>=rows.length)throw Error('COMMUNITY_CHANGED');[rows[index],rows[next]]=[rows[next],rows[index]];await controller.setPhotos(draft.draft_id,rows.map(p=>({media_id:p.media_id,descriptor:p.descriptor})));}),
  refreshChoices,loadMoreRides:()=>readChoices('rides',true),loadMoreRoutes:()=>readChoices('routes',true),reviewPublish:()=>localTask(()=>controller.review(currentDraft.draft_id),'control'),publish:value=>localTask(()=>controller.publish(value),'control'),onClose:close,onOpenPublished:()=>{guard('edit');const row=freshDraft();if(row.status!=='published'||row.post_revision<1)throw Error('COMMUNITY_CHANGED');router.replace({pathname:'/community-post',params:{postId:row.post_id}});},
 };
 return <CommunityComposer port={port} t={(key,values)=>t(key as TranslationKey,values)}/>;
}
