import React,{useEffect,useRef,useState} from 'react';
import {router} from 'expo-router';
import {ActivityIndicator,FlatList,RefreshControl,Share,Switch,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Button,Empty,Field,Note,Panel,Row,Segments,T} from '../../components/ui';
import {useI18n,errorKey} from '../../lib/i18n';
import type {TranslationKey} from '../../lib/i18n/resources';
import {useNow} from '../../lib/useNow';
import {useApp} from '../../state/AppState';
import {RouteSheet} from '../routes/RouteSheet';
import SharedRouteSnapshot from '../routes/SharedRouteSnapshot';
import type {InvitationRoute} from '../social/invitationReviewService';
import {getConvoyRoutePage,reviewConvoyRoute,type ConvoyRouteCursor,type ConvoyRouteReview} from './convoyRouteService';
import {LiveHeader,LiveOutcome,LivePending,LiveReadState} from './LiveSurface';
import {normalizeConvoyCode} from './model';
import {assertLocationReview,convoyJoinRequest,convoyMemberRequest,convoyRoomRequest,locationReview} from './presentationModel';
import type {ConvoyMember,ConvoySnapshot,ConvoySummary,LiveRequest} from './types';
import type {ConvoyCodePreview,LocationGrantReview} from './uiTypes';
import {useLiveScreen} from './useLiveScreen';
const wallNow=()=>Date.now();
type Confirm={room:ConvoySnapshot;kind:'start'|'end'|'cancel'|'rotate'}|{room:ConvoySnapshot;kind:'member';member:ConvoyMember;verb:'remove'|'leave'};
export default function ConvoyScreen(){
 const screen=useLiveScreen(),{data}=screen,{colors}=useApp(),{t,locale}=useI18n(),insets=useSafeAreaInsets(),now=useNow(1000),room=data.room;
 const [sheet,setSheet]=useState<'create'|'join'|null>(null),[codeInput,setCodeInput]=useState(''),[codePreview,setCodePreview]=useState<ConvoyCodePreview|null>(null),[privateCode,setPrivateCode]=useState<{room:ConvoySnapshot;code:string|null}|null>(null);
 const [routes,setRoutes]=useState<readonly InvitationRoute[]>([]),[routeCursor,setRouteCursor]=useState<ConvoyRouteCursor|null>(null),[routesLoaded,setRoutesLoaded]=useState(false),[routeId,setRouteId]=useState<string|null>(null),[title,setTitle]=useState(''),[routeReview,setRouteReview]=useState<ConvoyRouteReview|null>(null);
 const [disclosure,setDisclosure]=useState<LocationGrantReview|null>(null),[duration,setDuration]=useState('900'),[confirm,setConfirm]=useState<Confirm|null>(null),[loading,setLoading]=useState(false),[paging,setPaging]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState<TranslationKey|null>(null),[operationId,setOperationId]=useState<string|null>(null);
 const epoch=useRef(0),pageLock=useRef<object|null>(null);
 const cancel=()=>{epoch.current++;pageLock.current=null;setSheet(null);setCodePreview(null);setPrivateCode(null);setRouteReview(null);setDisclosure(null);setConfirm(null);setLoading(false);setPaging(false);setBusy(false);};
 useEffect(()=>{if(screen.moving||!screen.focused||!screen.active){epoch.current++;pageLock.current=null;
  // External lifecycle cancellation disposes sensitive previews and async intent.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setSheet(null);setCodePreview(null);setPrivateCode(null);setRouteReview(null);setDisclosure(null);setConfirm(null);setLoading(false);setPaging(false);setBusy(false);
 }},[screen.moving,screen.focused,screen.active]);
 const fail=(value:unknown)=>{if(screen.current())setError(errorKey(value,'live'));};
 const begin=()=>{pageLock.current=null;setPaging(false);return ++epoch.current;};
 const time=(value:string)=>new Date(value).toLocaleString(locale,{dateStyle:'medium',timeStyle:'short'});
 const allowed=screen.enabled&&!busy,active=room?.state==='active'&&room.self_state==='accepted'&&Date.parse(room.expires_at)>now&&Date.parse(room.host_lease_until)>now;
 const send=async(build:()=>LiveRequest)=>{try{const id=await screen.run(async()=>{setBusy(true);setError(null);return screen.latestRef.current.data.mutate(build());});if(id&&screen.current()){setOperationId(id);cancel();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const memberAction=(captured:ConvoySnapshot,member:ConvoyMember,verb:'approve'|'decline'|'remove'|'leave')=>send(()=>convoyMemberRequest(captured,member,verb,screen.latestRef.current.data.room,screen.auth.scope.userId!,wallNow()));
 const openRoom=async(id:string)=>{try{await screen.run(()=>screen.latestRef.current.data.openRoom(id),false);}catch(value){fail(value);}};
 const loadRoutes=async()=>{const sequence=begin();try{screen.guard(false);const {auth}=screen.latestRef.current;if(!auth.session)throw Error('LIVE_AUTH_REQUIRED');setLoading(true);setError(null);const page=await getConvoyRoutePage(auth.scope,auth.session);screen.guard(false);if(sequence!==epoch.current)return;setRoutes(page.routes);setRouteCursor(page.nextCursor);setRoutesLoaded(true);}catch(value){if(sequence===epoch.current)fail(value);}finally{if(screen.current()&&sequence===epoch.current)setLoading(false);}};
 const moreRoutes=async()=>{const sequence=epoch.current,lease={};try{screen.guard(false);if(pageLock.current||!routeCursor)return;pageLock.current=lease;setPaging(true);const {auth}=screen.latestRef.current;if(!auth.session)throw Error('LIVE_AUTH_REQUIRED');const page=await getConvoyRoutePage(auth.scope,auth.session,routeCursor);screen.guard(false);if(sequence!==epoch.current)return;setRoutes(old=>[...new Map([...old,...page.routes].map(value=>[value.id,value])).values()]);setRouteCursor(page.nextCursor);}catch(value){if(sequence===epoch.current)fail(value);}finally{if(pageLock.current===lease)pageLock.current=null;if(screen.current()&&sequence===epoch.current)setPaging(false);}};
 const openCreate=()=>{try{screen.guard();setSheet('create');setRouteReview(null);setRouteId(null);setTitle('');setRoutesLoaded(false);setRoutes([]);setRouteCursor(null);void loadRoutes();}catch(value){fail(value);}};
 const reviewRoute=async()=>{const sequence=begin();try{screen.guard();const {auth}=screen.latestRef.current,route=routes.find(value=>value.id===routeId);if(!route||!auth.session)throw Error('CONVOY_CHANGED');setBusy(true);setError(null);const value=await reviewConvoyRoute(auth.scope,auth.session,route);screen.guard();if(sequence===epoch.current)setRouteReview(value);}catch(value){if(sequence===epoch.current)fail(value);}finally{if(sequence===epoch.current&&screen.current())setBusy(false);}};
 const create=async()=>{const captured=routeReview;if(!captured)return;try{const id=await screen.run(async()=>{setBusy(true);setError(null);return screen.latestRef.current.data.createConvoy({title:title.trim(),routeId:captured.route.id,routeRevision:captured.route.revision,geometryHash:captured.shared.geometryHash});});if(id&&screen.current()){setOperationId(id);cancel();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const reviewCode=async()=>{const sequence=begin();try{screen.guard();const code=normalizeConvoyCode(codeInput);setBusy(true);setError(null);const result=await screen.latestRef.current.data.resolveCode(code);screen.guard();if(sequence!==epoch.current)return;if('error' in result)throw Error(result.error.code);if(!result.preview)throw Error('CONVOY_UNAVAILABLE');setCodePreview(result.preview);}catch(value){if(sequence===epoch.current)fail(value);}finally{if(sequence===epoch.current&&screen.current())setBusy(false);}};
 const showCode=async(captured:ConvoySnapshot)=>{const sequence=begin();try{screen.guard();setBusy(true);const code=await screen.latestRef.current.data.getRoomCode(captured.id);screen.guard();const current=screen.latestRef.current.data.room;if(sequence!==epoch.current)return;if(!current||current.id!==captured.id||current.revision!==captured.revision||current.self_code?.hash!==captured.self_code?.hash)throw Error('CONVOY_CHANGED');setPrivateCode({room:captured,code});}catch(value){if(sequence===epoch.current)fail(value);}finally{if(sequence===epoch.current&&screen.current())setBusy(false);}};
 const openDisclosure=()=>{try{screen.guard();const current=screen.latestRef.current.data;if(!current.room)throw Error('CONVOY_UNAVAILABLE');if(!current.presenceReady)throw Error('LOCATION_CONSENT_REQUIRED');setDisclosure(locationReview(current.room,current.captureId,current.ghost,wallNow()));setDuration('900');setError(null);}catch(value){fail(value);}};
 const grant=async()=>{const proof=disclosure;if(!proof)return;try{const id=await screen.run(async()=>{const current=screen.latestRef.current.data;if(!current.presenceReady)throw Error('LOCATION_CONSENT_REQUIRED');assertLocationReview(proof,current.room,current.captureId,current.ghost,wallNow());setBusy(true);return current.grantLocation(duration==='3600'?3600:900,proof);});if(id&&screen.current()){setOperationId(id);cancel();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const stop=async()=>{if(!screen.current())return;try{await screen.latestRef.current.data.stopSharing();}catch(value){fail(value);}};
 const confirmAction=async()=>{const captured=confirm;if(!captured)return;if(captured.kind==='member')return memberAction(captured.room,captured.member,captured.verb);if(captured.kind!=='rotate'){const verb=captured.kind;return send(()=>convoyRoomRequest(captured.room,verb,screen.latestRef.current.data.room,screen.auth.scope.userId!,wallNow()));}try{const id=await screen.run(async()=>{const current=screen.latestRef.current.data.room;if(!current||current.id!==captured.room.id||current.revision!==captured.room.revision||current.viewer_role!=='host')throw Error('CONVOY_CHANGED');setBusy(true);return screen.latestRef.current.data.rotateCode(captured.room);});if(id&&screen.current()){setOperationId(id);cancel();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const openConfirm=(value:Confirm)=>{try{screen.guard();setConfirm(value);setError(null);}catch(error){fail(error);}};
 const rows:readonly (ConvoyMember|ConvoySummary)[]=room?room.members:data.summaries;
 const renderRow=(item:ConvoyMember|ConvoySummary)=>'user_id' in item?<View style={{gap:12,paddingVertical:18,borderBottomWidth:1,borderBottomColor:colors.line}}><Row style={{justifyContent:'space-between'}}><View style={{flex:1}}><T size={18} weight="semibold">{item.display_name}</T><T muted size={13}>@{item.handle}</T></View><T muted size={12}>{t(item.role==='host'?'m5b.host':item.state==='requested'?'m5b.requested':'m5b.accepted')}</T></Row>{room?.viewer_role==='host'&&item.user_id!==room.host_id&&(item.state==='requested'?<Row><Button small label={t('m5b.approve')} disabled={!allowed} onPress={()=>memberAction(room,item,'approve')}/><Button small secondary label={t('m5b.decline')} disabled={!allowed} onPress={()=>memberAction(room,item,'decline')}/></Row>:<Button small secondary label={t('m5b.remove')} disabled={!allowed} onPress={()=>openConfirm({room,kind:'member',member:item,verb:'remove'})}/>)}</View>:<View style={{paddingVertical:18,gap:12,borderBottomWidth:1,borderBottomColor:colors.line}}><T size={20} weight="semibold">{item.title}</T><T muted>{t(item.self_state==='requested'?'m5b.waitingApproval':item.state==='lobby'?'m5b.lobby':'m5b.active')}</T><Button secondary label={t('m5b.openTrip')} disabled={!allowed} onPress={()=>openRoom(item.id)}/></View>;
 return <View style={{flex:1,backgroundColor:colors.bg}}><FlatList data={rows} keyExtractor={item=>'user_id' in item?item.user_id:item.id} renderItem={({item})=>renderRow(item)} scrollEnabled={!screen.moving} contentContainerStyle={{paddingHorizontal:24,paddingTop:insets.top+18,paddingBottom:insets.bottom+124}} refreshControl={<RefreshControl refreshing={data.loading} tintColor={colors.accent} enabled={!screen.moving} onRefresh={()=>{if(screen.active&&screen.focused&&!screen.moving)void data.refresh().catch(fail);}}/>}
  ListHeaderComponent={<View style={{gap:18}}><LiveHeader title={t('m5b.convoy')} body={t('m5b.convoyBody')}/><LiveReadState/><LivePending/><LiveOutcome id={operationId}/>{(error||data.error)&&<Note error>{t(error??errorKey(data.error,'live'))}</Note>}{screen.moving&&<Note>{t('m5b.moving')}</Note>}{data.secretPersistence==='session'&&<Note>{t('m5b.sessionSecrets')}</Note>}{!room&&<Row style={{flexWrap:'wrap'}}><Button label={t('m5b.createTrip')} disabled={!allowed||data.summaries.length>0} onPress={openCreate}/><Button secondary label={t('m5b.joinTrip')} disabled={!allowed||data.summaries.length>0} onPress={()=>{try{screen.guard();setSheet('join');setCodePreview(null);setError(null);}catch(value){fail(value);}}}/></Row>}
   {room&&<><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><T size={28} weight="semibold">{room.title}</T><T muted size={12}>{t(`m5b.${room.state}`)}</T></Row><T muted size={12}>{t('m5b.expires',{time:time(room.expires_at)})}</T><SharedRouteSnapshot value={room.route_snapshot} invitation map={false}/>{room.viewer_role==='applicant'?<Note>{t('m5b.applicantBody')}</Note>:<><Note>{t('m5b.hostLease')}</Note>{active&&<Panel><Row><View style={{flex:1}}><T weight="semibold">{t('m5b.receive')}</T><T muted size={12}>{t('m5b.receiveBody')}</T></View><Switch accessibilityLabel={t('m5b.receive')} value={data.receiveEnabled} disabled={!allowed&&!data.receiveEnabled} onValueChange={enabled=>{try{if(!screen.current())return;if(enabled)screen.guard();screen.latestRef.current.data.setReceive(enabled);}catch(value){fail(value);}}} trackColor={{false:colors.line,true:colors.accent}}/></Row><T muted size={12}>{t('m5b.unverified')}</T><T>{t(data.share.pending?'m5b.sharingPending':data.share.armed&&data.share.expiresAt?'m5b.sharingActive':'m5b.sharingOff',{time:data.share.expiresAt?time(data.share.expiresAt):''})}</T>{data.share.error&&<Note error>{t(errorKey(data.share.error,'live'))}</Note>}{data.share.armed||data.share.pending?<Button secondary label={t('m5b.stopSharing')} onPress={stop}/>:data.ghost?<><Note>{t('m5b.ghost')}</Note><Button secondary label={t('m5b.privacy')} disabled={!allowed} onPress={()=>router.push('/profile')}/></>:!data.presenceReady?<><Note>{t('m5b.presenceRequired')}</Note><Button secondary label={t('m5b.presenceSettings')} disabled={!allowed} onPress={()=>{try{screen.guard();router.push('/friends');}catch(value){fail(value);}}}/></>:!data.captureReady?<><Note>{t('m5b.recordFirst')}</Note><Button secondary label={t('m5b.openMap')} disabled={!allowed} onPress={()=>router.replace('/')}/></>:<Button label={t('m5b.sharePosition')} disabled={!allowed} onPress={openDisclosure}/>}</Panel>}
    {room.viewer_role==='host'&&['lobby','active'].includes(room.state)&&<><Button small secondary label={t('m5b.groupCode')} disabled={!allowed} onPress={()=>showCode(room)}/>{room.state==='lobby'&&<Button label={t('m5b.startTrip')} disabled={!allowed||room.members.filter(value=>value.state==='accepted').length<2} onPress={()=>openConfirm({room,kind:'start'})}/>}<Button secondary label={t(room.state==='lobby'?'m5b.cancelTrip':'m5b.endTrip')} disabled={!allowed} onPress={()=>openConfirm({room,kind:room.state==='lobby'?'cancel':'end'})}/></>}
    {room.viewer_role==='member'&&['lobby','active'].includes(room.state)&&<Button small secondary label={t('m5b.leave')} disabled={!allowed} onPress={()=>{const self=room.members.find(value=>value.user_id===screen.auth.scope.userId);if(self)openConfirm({room,kind:'member',member:self,verb:'leave'});}}/>}</>}
    <T size={20} weight="semibold">{t('m5b.members',{count:room.members.filter(value=>value.state==='accepted').length})}</T></>}
  </View>}
  ListEmptyComponent={!room&&data.ready&&data.fresh&&!data.loading&&!data.error?<View style={{paddingTop:24}}><Empty icon="people-outline" title={t('m5b.noTrips')} body={t('m5b.noTripsBody')}/></View>:null}
  ListFooterComponent={<View style={{gap:12,paddingTop:18}}>{data.loading&&<ActivityIndicator color={colors.accent}/>}<Button small secondary label={t('m5b.refresh')} disabled={data.loading||screen.moving||!screen.active||!screen.focused} onPress={()=>data.refresh().catch(fail)}/></View>}/>
  <RouteSheet visible={sheet==='create'&&screen.focused&&screen.active&&!screen.moving} title={t(routeReview?'m5b.reviewTrip':'m5b.createTrip')} onClose={cancel}>{sheet==='create'&&(routeReview?<><T>{title}</T><SharedRouteSnapshot value={routeReview.shared} invitation/><Note>{t('m5b.routeReview')}</Note>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.createTrip')} disabled={!allowed||!title.trim()} busy={busy} onPress={create}/><Button secondary label={t('m5b.cancel')} onPress={()=>{begin();setRouteReview(null);}}/></>:<><Field label={t('m5b.title')} value={title} onChangeText={value=>{if(allowed)setTitle(Array.from(value).slice(0,48).join(''));}} editable={allowed}/><T weight="semibold">{t('m5b.chooseRoute')}</T>{loading?<ActivityIndicator color={colors.accent}/>:routesLoaded?routes.length?routes.map(value=><Button key={value.id} small secondary={routeId!==value.id} label={value.title} disabled={!allowed} onPress={()=>setRouteId(value.id)}/>):<Note>{t('m5b.noRoutes')}</Note>:<Note>{t('m5b.readUnavailable')}</Note>}{routeCursor&&<Button small secondary label={t('m5a.loadMoreRoutes')} disabled={!allowed||paging} busy={paging} onPress={moreRoutes}/>}<Button small secondary label={t('m5b.refresh')} disabled={loading||!allowed} onPress={loadRoutes}/>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.reviewTrip')} disabled={!allowed||!routeId||!title.trim()||loading} busy={busy} onPress={reviewRoute}/></>)}</RouteSheet>
  <RouteSheet visible={sheet==='join'&&screen.focused&&screen.active&&!screen.moving} title={t(codePreview?'m5b.joinReview':'m5b.joinTrip')} onClose={cancel}>{codePreview?<><T size={24} weight="semibold">{codePreview.title}</T><T>{codePreview.host_name}</T><T>{t('m5b.joinBody')}</T><T muted size={12}>{t('m5b.expires',{time:time(codePreview.expires_at)})}</T>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.requestJoin')} disabled={!allowed} busy={busy} onPress={()=>send(()=>convoyJoinRequest(codePreview,wallNow()))}/></>:<><Field label={t('m5b.code')} value={codeInput} onChangeText={value=>{if(allowed)setCodeInput(value);}} autoCapitalize="characters" autoCorrect={false} maxLength={32} editable={allowed}/><T>{t('m5b.joinBody')}</T>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.reviewCode')} disabled={!allowed||!codeInput.trim()} busy={busy} onPress={reviewCode}/></>}</RouteSheet>
  <RouteSheet visible={!!disclosure&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.disclosureTitle')} onClose={cancel}><T>{t('m5b.disclosure')}</T><Note>{t('m5b.retention')}</Note><Segments value={duration} items={[{value:'900',label:t('m5b.fifteenMinutes')},{value:'3600',label:t('m5b.sixtyMinutes')}]} onChange={value=>{if(allowed)setDuration(value);}}/>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.confirmShare')} disabled={!allowed} busy={busy} onPress={grant}/></RouteSheet>
  <RouteSheet visible={!!privateCode&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.groupCode')} onClose={cancel}>{privateCode&&(privateCode.code?<><T numeric selectable accessibilityLabel={privateCode.code} size={36} weight="semibold" style={{textAlign:'center'}}>{privateCode.code.slice(0,4)} {privateCode.code.slice(4)}</T><Button secondary label={t('m5b.shareCode')} disabled={!allowed} onPress={()=>{try{screen.guard();const current=screen.latestRef.current.data.room;if(!current||current.id!==privateCode.room.id||current.revision!==privateCode.room.revision||current.self_code?.hash!==privateCode.room.self_code?.hash)throw Error('CONVOY_CHANGED');void Share.share({message:t('m5b.codeShare',{code:privateCode.code??''})}).catch(fail);}catch(value){fail(value);}}}/><Button secondary label={t('m5b.rotateCode')} disabled={!allowed} onPress={()=>{setPrivateCode(null);openConfirm({room:privateCode.room,kind:'rotate'});}}/></>:<Note>{t('m5b.secretMissing')}</Note>)}</RouteSheet>
  <RouteSheet visible={!!confirm&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.confirm')} onClose={cancel}>{confirm&&<><T>{t(confirm.kind==='member'?(confirm.verb==='leave'?'m5b.leaveBody':'m5b.removeBody'):confirm.kind==='rotate'?'m5b.rotateBody':confirm.kind==='start'?'m5b.startBody':'m5b.endBody')}</T>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.confirm')} disabled={!allowed} busy={busy} onPress={confirmAction}/></>}</RouteSheet>
 </View>;
}
