import React,{useEffect,useRef,useState} from 'react';
import {CameraView,useCameraPermissions} from 'expo-camera';
import {ActivityIndicator,FlatList,RefreshControl,Share,View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Button,Empty,Field,Note,Row,Segments,T} from '../../components/ui';
import {useI18n,errorKey} from '../../lib/i18n';
import type {TranslationKey} from '../../lib/i18n/resources';
import {useApp} from '../../state/AppState';
import {RouteSheet} from '../routes/RouteSheet';
import {LiveHeader,LiveOutcome,LivePending,LiveReadState} from './LiveSurface';
import {encodedFriendLink,parseFriendLink} from './model';
import {friendLinkRequest} from './presentationModel';
import QrCode from './QrCode';
import type {FriendLinkRow,FriendLinkPreview,IncomingFriendIntent} from './uiTypes';
import {useLiveScreen} from './useLiveScreen';
const wallNow=()=>Date.now();
export default function FriendLinksScreen(){
 const screen=useLiveScreen(),{data}=screen,{colors}=useApp(),{t,locale}=useI18n(),insets=useSafeAreaInsets(),[permission,requestPermission]=useCameraPermissions();
 const [input,setInput]=useState(''),[preview,setPreview]=useState<FriendLinkPreview|null>(null),[scanner,setScanner]=useState<{stage:'rationale'|'camera';epoch:number}|null>(null),[scanned,setScanned]=useState(false),[ttl,setTtl]=useState('3600');
 const [selected,setSelected]=useState<{row:FriendLinkRow;url:string|null}|null>(null),[revoke,setRevoke]=useState<FriendLinkRow|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<TranslationKey|null>(null),[operationId,setOperationId]=useState<string|null>(null);
 const epoch=useRef(0),scanLock=useRef(false),incoming=useRef<IncomingFriendIntent|null>(null);
 useEffect(()=>{if(screen.moving||!screen.focused||!screen.active){epoch.current++;scanLock.current=true;
  // External lifecycle cancellation releases pending UI while fencing responses.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  setBusy(false);setScanner(null);setPreview(null);setSelected(null);setRevoke(null);
 }},[screen.moving,screen.focused,screen.active]);
 useEffect(()=>{if(!screen.auth.session||incoming.current===data.incomingFriendIntent||!data.incomingFriendIntent||!screen.focused||!screen.active||screen.moving)return;incoming.current=data.incomingFriendIntent;const intent=data.consumeIncomingFriendIntent();if(intent){
  // A captured installed-app link populates only local entry; no resolver runs.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  epoch.current++;scanLock.current=true;setBusy(false);setPreview(null);setSelected(null);setRevoke(null);setScanner(null);setScanned(false);setError(null);setInput(encodedFriendLink(intent.linkId,intent.token));
 }},[data,screen.auth.session,screen.focused,screen.active,screen.moving]);
 const fail=(value:unknown)=>{if(screen.current())setError(errorKey(value,'live'));};
 const time=(value:string)=>new Date(value).toLocaleString(locale,{dateStyle:'medium',timeStyle:'short'});
 const close=()=>{epoch.current++;setPreview(null);setSelected(null);setRevoke(null);setScanner(null);setBusy(false);};
 const review=async()=>{const sequence=++epoch.current;try{screen.guard();const intent=parseFriendLink(input.trim());if(!intent)throw Error('LIVE_INVALID');setBusy(true);setError(null);const value=await screen.latestRef.current.data.resolveFriendLink({linkId:intent.linkId,token:intent.token});screen.guard();if(sequence!==epoch.current)return;if('error' in value)throw Error(value.error.code);if(!value.preview)throw Error('FRIEND_LINK_UNAVAILABLE');setPreview(value.preview);}catch(value){if(sequence===epoch.current)fail(value);}finally{if(sequence===epoch.current&&screen.current())setBusy(false);}};
 const create=async()=>{try{const id=await screen.run(async()=>{setBusy(true);setError(null);return screen.latestRef.current.data.createFriendLink(ttl==='86400'?86400:3600);});if(id&&screen.current())setOperationId(id);}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const send=async()=>{const captured=preview;if(!captured)return;try{const id=await screen.run(async()=>{setBusy(true);return screen.latestRef.current.data.mutate(friendLinkRequest(captured,wallNow()));});if(id&&screen.current()){setOperationId(id);setInput('');close();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const show=async(row:FriendLinkRow)=>{const sequence=++epoch.current;try{screen.guard();setBusy(true);const url=await screen.latestRef.current.data.getFriendLinkUrl(row.id);screen.guard();if(sequence!==epoch.current)return;const fresh=screen.latestRef.current.data.links.find(value=>value.id===row.id);if(!fresh||fresh.revision!==row.revision||Date.parse(row.expires_at)<=wallNow())throw Error('FRIEND_LINK_UNAVAILABLE');if(url&&!parseFriendLink(url))throw Error('LIVE_INVALID_RESPONSE');setSelected({row,url});}catch(value){if(sequence===epoch.current)fail(value);}finally{if(sequence===epoch.current&&screen.current())setBusy(false);}};
 const revokeLink=async()=>{const row=revoke;if(!row)return;try{const id=await screen.run(async()=>{const fresh=screen.latestRef.current.data.links.find(value=>value.id===row.id);if(!fresh||fresh.revision!==row.revision)throw Error('FRIEND_LINK_UNAVAILABLE');setBusy(true);return screen.latestRef.current.data.mutate({schema_version:1,action:'friend_link_revoke',link_id:row.id,expected_revision:row.revision});});if(id&&screen.current()){setOperationId(id);close();}}catch(value){fail(value);}finally{if(screen.current())setBusy(false);}};
 const openCamera=async()=>{const sequence=++epoch.current;try{screen.localGuard();scanLock.current=false;setError(null);const allowed=permission?.granted?permission:await requestPermission();screen.localGuard();if(sequence!==epoch.current)return;if(!allowed.granted)throw Error('LIVE_CAMERA_UNAVAILABLE');setScanner({stage:'camera',epoch:sequence});}catch(value){if(sequence===epoch.current)fail(value);}};
 const onScan=({data:raw}:{data:string})=>{try{screen.localGuard();if(scanLock.current||scanner?.stage!=='camera'||scanner.epoch!==epoch.current)return;const parsed=parseFriendLink(raw);if(!parsed)throw Error('LIVE_INVALID');scanLock.current=true;setScanner(null);setInput(raw);setScanned(true);setError(null);}catch(value){fail(value);}};
 const allowed=screen.enabled&&!busy;
 return <View style={{flex:1,backgroundColor:colors.bg}}><FlatList data={data.links} keyExtractor={row=>row.id} scrollEnabled={!screen.moving} contentContainerStyle={{paddingHorizontal:24,paddingTop:insets.top+18,paddingBottom:insets.bottom+124}} refreshControl={<RefreshControl refreshing={data.loading} tintColor={colors.accent} enabled={!screen.moving} onRefresh={()=>{if(screen.active&&screen.focused&&!screen.moving)void data.refresh().catch(fail);}}/>}
  ListHeaderComponent={<View style={{gap:18}}><LiveHeader title={t('m5b.friends')} body={t('m5b.friendsBody')}/><LiveReadState/><LivePending/><LiveOutcome id={operationId}/>{(error||data.error)&&<Note error>{t(error??errorKey(data.error,'live'))}</Note>}{screen.moving&&<Note>{t('m5b.moving')}</Note>}{data.secretPersistence==='session'&&<Note>{t('m5b.sessionSecrets')}</Note>}<Button secondary icon="scan-outline" label={t('m5b.scan')} disabled={screen.moving||!screen.focused||!screen.active||busy} onPress={()=>{try{screen.localGuard();scanLock.current=false;setScanner({stage:'rationale',epoch:++epoch.current});setError(null);}catch(value){fail(value);}}}/><Field label={t('m5b.linkLabel')} value={input} onChangeText={value=>{try{screen.localGuard();epoch.current++;setBusy(false);setInput(value);setScanned(false);setPreview(null);setError(null);}catch(value){fail(value);}}} autoCorrect={false} autoCapitalize="none" maxLength={200} editable={!screen.moving}/>{scanned&&<Note>{t('m5b.scanned')}</Note>}<Button label={t('m5b.reviewLink')} disabled={!allowed||!input.trim()} busy={busy} onPress={review}/><T size={20} weight="semibold">{t('m5b.myQr')}</T><Segments value={ttl} items={[{value:'3600',label:t('m5b.oneHour')},{value:'86400',label:t('m5b.oneDay')}]} onChange={value=>{if(allowed)setTtl(value);}}/><Button secondary label={t('m5b.createLink')} disabled={!allowed||data.links.length>=8} onPress={create}/></View>}
  ListEmptyComponent={data.ready&&data.fresh&&!data.loading&&!data.error?<View style={{paddingTop:24}}><Empty icon="qr-code-outline" title={t('m5b.noLinks')} body={t('m5b.noLinksBody')}/></View>:null}
  ListFooterComponent={<View style={{gap:12,paddingTop:18}}>{data.loading&&<ActivityIndicator color={colors.accent}/>}<Button small secondary label={t('m5b.refresh')} disabled={screen.moving||data.loading||!screen.active||!screen.focused} onPress={()=>data.refresh().catch(fail)}/></View>}
  renderItem={({item})=><View style={{gap:12,paddingVertical:18,borderBottomWidth:1,borderBottomColor:colors.line}}><T>{t('m5b.expires',{time:time(item.expires_at)})}</T><Row><Button small secondary label={t('m5b.myQr')} disabled={!allowed} onPress={()=>show(item)}/><Button small secondary label={t('m5b.revokeLink')} disabled={!allowed} onPress={()=>{try{screen.guard();setRevoke(item);setError(null);}catch(value){fail(value);}}}/></Row></View>}/>
  <RouteSheet visible={scanner!==null&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.scan')} onClose={()=>{epoch.current++;scanLock.current=true;setScanner(null);}}>{scanner?.stage==='rationale'?<><T>{t('m5b.cameraRationale')}</T>{permission&&!permission.granted&&!permission.canAskAgain&&<Note>{t('m5b.cameraDenied')}</Note>}<Button label={t('m5b.openCamera')} onPress={openCamera}/></>:scanner?.stage==='camera'&&screen.focused&&screen.active&&!screen.moving?<><T>{t('m5b.scanHint')}</T><View style={{height:300,borderRadius:24,overflow:'hidden'}}><CameraView style={{flex:1}} facing="back" barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={onScan} onMountError={()=>{if(!screen.current()||scanner?.epoch!==epoch.current)return;scanLock.current=true;setScanner(null);setError('m5b.cameraError');}}/></View></>:null}</RouteSheet>
  <RouteSheet visible={!!preview&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.friendPreview')} onClose={close}>{preview&&<><T size={24} weight="semibold">{preview.display_name}</T><T muted>@{preview.handle}</T><T>{t('m5b.friendProof')}</T><T muted size={12}>{t('m5b.expires',{time:time(preview.expires_at)})}</T>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.friendRequest')} disabled={!allowed} busy={busy} onPress={send}/></>}</RouteSheet>
  <RouteSheet visible={!!selected&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.myQr')} onClose={close}>{selected&&(selected.url?<><QrCode url={selected.url} label={t('m5b.qrA11y',{time:time(selected.row.expires_at)})}/><T>{t('m5b.expires',{time:time(selected.row.expires_at)})}</T><Button secondary label={t('m5b.shareLink')} disabled={!allowed} onPress={()=>{try{screen.guard();const fresh=screen.latestRef.current.data.links.find(value=>value.id===selected.row.id);if(!fresh||fresh.revision!==selected.row.revision||Date.parse(fresh.expires_at)<=wallNow())throw Error('FRIEND_LINK_UNAVAILABLE');void Share.share({message:selected.url!}).catch(fail);}catch(value){fail(value);}}}/></>:<Note>{t('m5b.secretMissing')}</Note>)}</RouteSheet>
  <RouteSheet visible={!!revoke&&screen.focused&&screen.active&&!screen.moving} title={t('m5b.revokeLink')} onClose={close}><T>{t('m5b.revokeBody')}</T>{error&&<Note error>{t(error)}</Note>}<Button label={t('m5b.confirm')} disabled={!allowed} busy={busy} onPress={revokeLink}/></RouteSheet>
 </View>;
}
