import {isSocialInstant} from '../social/model';
import {validateRouteProjection} from '../routes/syncModel';
import type {ConvoyCodeResolution,ConvoyEvent,ConvoyHeartbeat,ConvoyHeartbeatMutation,ConvoyList,ConvoyPositions,ConvoyPositionMutation,ConvoySnapshot,FriendLinkResolution,FriendLinks,LiveErrorCode,LiveErrorEnvelope,LiveGrantCancellationMutation,LiveMutation,LiveOperation,LivePublishAck,LivePublishMutation,LiveReceipt,LiveRequest,LiveSample,StoredLiveOperation} from './types';
export const liveErrors=['LIVE_INVALID','LIVE_TOO_LARGE','LIVE_OPERATION_CONFLICT','LIVE_OPERATION_CANCELLED','LIVE_UNAVAILABLE','LIVE_RATE_LIMITED','LIVE_AUTH_REQUIRED','LIVE_DISABLED','LIVE_CAPACITY','PROFILE_REQUIRED','FRIEND_CHANGED','FRIEND_LINK_UNAVAILABLE','CONVOY_UNAVAILABLE','CONVOY_CHANGED','CONVOY_FULL','LOCATION_CONSENT_REQUIRED','LOCATION_CONSENT_CHANGED','LOCATION_STALE','LOCATION_QUALITY','POSITION_SEQUENCE','ACCOUNT_DELETION_PENDING'] as const;
const storedErrors=new Set<string>([...liveErrors,'LIVE_INVALID_RESPONSE','LIVE_CLOCK_UNCERTAIN','LIVE_REVIEW_REQUIRED','ACCOUNT_CHANGED','LOCAL_READ_FAILED','LOCAL_WRITE_FAILED']);
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
const hash=/^[a-f0-9]{64}$/;
const token=/^[A-Za-z0-9_-]{42}[AEIMQUYcgkosw048]$/;
export const isLiveId=(v:unknown):v is string=>typeof v==='string'&&uuid.test(v);
export const isLiveInstant=isSocialInstant;
export const liveObject=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
export const liveKeys=(v:Record<string,unknown>,ks:readonly string[])=>Object.keys(v).length===ks.length&&ks.every(k=>Object.hasOwn(v,k));
const int=(v:unknown,min=0):v is number=>typeof v==='number'&&Number.isInteger(v)&&v>=min&&v<=2147483647;
const str=(v:unknown,max:number):v is string=>typeof v==='string'&&!!v.trim()&&[...v].length<=max&&!/[\u0000-\u001f\u007f]/.test(v)&&!/[\uD800-\uDFFF]/u.test(v);
const handle=(v:unknown)=>typeof v==='string'&&/^[a-z0-9_]{3,24}$/.test(v);
const digest=(v:unknown)=>typeof v==='string'&&hash.test(v);
const memberState=(v:unknown)=>v==='requested'||v==='accepted';
const finite=(v:unknown,min:number,max:number):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
function fail(code='LIVE_INVALID'):never{throw Error(code);}
function freeze<T>(v:T):T{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;}
function detached<T>(v:T):T{return freeze(JSON.parse(JSON.stringify(v)));}
const bytes=(v:unknown)=>new TextEncoder().encode(JSON.stringify(v)).byteLength;
export function canonicalLive(v:unknown):string{if(Array.isArray(v))return '['+v.map(canonicalLive).join(',')+']';if(liveObject(v))return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonicalLive(v[k])).join(',')+'}';return JSON.stringify(v);}
export function freezeLiveRequest(v:unknown):LiveRequest{
 if(!liveObject(v)||v.schema_version!==1)fail();let fields:string[];
 switch(v.action){
 case 'friend_link_create':fields=['link_id','token_hash','ttl_seconds'];if(!isLiveId(v.link_id)||!digest(v.token_hash)||v.ttl_seconds!==3600&&v.ttl_seconds!==86400)fail();break;
 case 'friend_link_revoke':fields=['link_id','expected_revision'];if(!isLiveId(v.link_id)||!int(v.expected_revision,1))fail();break;
 case 'friend_link_request':fields=['proof_id','issuer_id'];if(!isLiveId(v.proof_id)||!isLiveId(v.issuer_id))fail();break;
 case 'convoy_create':fields=['convoy_id','title','route_id','route_revision','reviewed_geometry_hash','code_hash','ttl_seconds'];if(!isLiveId(v.convoy_id)||!str(v.title,48)||!isLiveId(v.route_id)||!int(v.route_revision,1)||v.reviewed_geometry_hash!==null&&!digest(v.reviewed_geometry_hash)||!digest(v.code_hash)||v.ttl_seconds!==3600)fail();break;
 case 'convoy_join':fields=['convoy_id','proof_id','expected_room_revision','host_friendship_generation'];if(!isLiveId(v.convoy_id)||!isLiveId(v.proof_id)||!int(v.expected_room_revision,1)||!int(v.host_friendship_generation,1))fail();break;
 case 'convoy_member':fields=['convoy_id','other_id','verb','expected_room_revision','expected_member_generation','expected_member_state'];if(!isLiveId(v.convoy_id)||!isLiveId(v.other_id)||!['approve','decline','remove','leave'].includes(String(v.verb))||!int(v.expected_room_revision,1)||!int(v.expected_member_generation,1)||!memberState(v.expected_member_state)||v.verb==='approve'&&v.expected_member_state!=='requested'||v.verb==='decline'&&v.expected_member_state!=='requested'||v.verb==='remove'&&v.expected_member_state!=='accepted')fail();break;
 case 'convoy_start':fields=['convoy_id','expected_room_revision'];if(!isLiveId(v.convoy_id)||!int(v.expected_room_revision,1))fail();break;
 case 'convoy_end':fields=['convoy_id','expected_room_revision','verb'];if(!isLiveId(v.convoy_id)||!int(v.expected_room_revision,1)||v.verb!=='end'&&v.verb!=='cancel')fail();break;
 case 'convoy_code_rotate':fields=['convoy_id','expected_room_revision','code_hash'];if(!isLiveId(v.convoy_id)||!int(v.expected_room_revision,1)||!digest(v.code_hash))fail();break;
 case 'location_grant':fields=['convoy_id','expected_room_revision','expected_member_generation','expected_consent_revision','capture_id','duration_seconds','precision'];if(!isLiveId(v.convoy_id)||!int(v.expected_room_revision,1)||!int(v.expected_member_generation,1)||!int(v.expected_consent_revision)||!isLiveId(v.capture_id)||v.duration_seconds!==900&&v.duration_seconds!==3600||v.precision!=='precise')fail();break;
 case 'location_revoke':fields=['convoy_id','expected_member_generation','expected_consent_revision','expected_lease_id'];if(!isLiveId(v.convoy_id)||!int(v.expected_member_generation,1)||!int(v.expected_consent_revision)||v.expected_lease_id!==null&&!isLiveId(v.expected_lease_id))fail();break;
 default:fail();
 }
 if(!liveKeys(v,['schema_version','action',...fields]))fail();if(bytes(v)>16384)fail('LIVE_TOO_LARGE');return detached(v) as LiveRequest;
}
export function freezeLiveOperation(v:unknown):LiveOperation{if(!liveObject(v)||!liveKeys(v,['operationId','request'])||!isLiveId(v.operationId))fail();return freeze({operationId:v.operationId,request:freezeLiveRequest(v.request)});}
export function parseLiveOperations(v:unknown,stripCloud=false):StoredLiveOperation[]{
 if(stripCloud||v===undefined)return [];if(!Array.isArray(v))fail();if(v.length>32||bytes(v)>131072)fail('LIVE_TOO_LARGE');const seen=new Set<string>();
 return freeze(v.map(row=>{if(!liveObject(row)||!liveKeys(row,['operationId','request','queuedAt','lastError'])||!isLiveInstant(row.queuedAt)||row.lastError!==null&&(typeof row.lastError!=='string'||!storedErrors.has(row.lastError)))fail();const op=freezeLiveOperation({operationId:row.operationId,request:row.request});if(seen.has(op.operationId)||canonicalLive(op.request)!==canonicalLive(row.request))fail();seen.add(op.operationId);return {...op,queuedAt:row.queuedAt,lastError:row.lastError as StoredLiveOperation['lastError']};}));
}
export function validateLiveError(v:unknown):LiveErrorEnvelope|null{
 if(!liveObject(v)||!Object.hasOwn(v,'error'))return null;if(!liveKeys(v,['error'])||!liveObject(v.error)||!liveKeys(v.error,['code'])||typeof v.error.code!=='string'||!liveErrors.includes(v.error.code as LiveErrorCode))fail('LIVE_INVALID_RESPONSE');return detached(v) as LiveErrorEnvelope;
}
export function validateLiveOperation(v:unknown,owner:string,operationId:string):LiveReceipt|null{
 if(!isLiveId(owner)||!isLiveId(operationId))fail();if(v===null)return null;
 try{
  if(!liveObject(v)||!liveKeys(v,['owner_id','operation_id','request','applied_at','result'])||v.owner_id!==owner||v.operation_id!==operationId||!isLiveInstant(v.applied_at)||!liveObject(v.result))fail();const q=freezeLiveRequest(v.request),r=v.result;if(canonicalLive(q)!==canonicalLive(v.request))fail();
  switch(q.action){
  case 'friend_link_create':case 'friend_link_revoke':if(!liveKeys(r,['kind','link_id','revision','state','expires_at'])||r.kind!=='friend_link'||r.link_id!==q.link_id||!int(r.revision,1)||!isLiveInstant(r.expires_at)||q.action==='friend_link_create'&&(r.state!=='active'||r.revision!==1)||q.action==='friend_link_revoke'&&(r.state!=='revoked'||r.revision<q.expected_revision||r.revision>q.expected_revision+1))fail();break;
  case 'friend_link_request':if(!liveKeys(r,['kind','user_id','state','generation'])||r.kind!=='friend'||r.user_id!==q.issuer_id||r.user_id===owner||!['incoming','outgoing','accepted'].includes(String(r.state))||!int(r.generation,1))fail();break;
  case 'convoy_create':case 'convoy_start':case 'convoy_end':case 'convoy_code_rotate':if(!liveKeys(r,['kind','convoy_id','revision','state'])||r.kind!=='convoy'||r.convoy_id!==q.convoy_id||!int(r.revision,1))fail();if(q.action==='convoy_create'?(r.revision!==1||r.state!=='lobby'):r.revision<q.expected_room_revision||r.revision>q.expected_room_revision+1)fail();if(q.action==='convoy_start'&&r.state!=='active'||q.action==='convoy_end'&&r.state!==(q.verb==='end'?'ended':'cancelled')||q.action==='convoy_code_rotate'&&!['lobby','active'].includes(String(r.state)))fail();break;
  case 'convoy_join':case 'convoy_member':{
   if(!liveKeys(r,['kind','convoy_id','user_id','room_revision','state','generation'])||r.kind!=='member'||r.convoy_id!==q.convoy_id||r.user_id!==(q.action==='convoy_join'?owner:q.other_id)||!int(r.room_revision,1)||r.room_revision<q.expected_room_revision||r.room_revision>q.expected_room_revision+1||!int(r.generation,1))fail();const state=q.action==='convoy_join'?'requested':{approve:'accepted',decline:'declined',remove:'removed',leave:'left'}[q.verb];if(r.state!==state||q.action==='convoy_member'&&(r.generation<q.expected_member_generation||r.generation>q.expected_member_generation+1))fail();break;}
  case 'location_grant':case 'location_revoke':{
   if(!liveKeys(r,['kind','convoy_id','revision','precision','lease_id','capture_id','expires_at'])||r.kind!=='consent'||r.convoy_id!==q.convoy_id||!int(r.revision,q.action==='location_grant'?1:0))fail();
   if(q.action==='location_grant'){if(r.revision!==q.expected_consent_revision+1||r.precision!=='precise'||!isLiveId(r.lease_id)||r.capture_id!==q.capture_id||!isLiveInstant(r.expires_at)||Date.parse(r.expires_at)<=Date.parse(v.applied_at)||Date.parse(r.expires_at)-Date.parse(v.applied_at)>q.duration_seconds*1000+1)fail();}
   else if(r.revision<q.expected_consent_revision||r.revision>q.expected_consent_revision+1||r.precision!=='none'||r.lease_id!==null||r.capture_id!==null||r.expires_at!==null)fail();break;}
  }
  return detached({...v,request:q}) as LiveReceipt;
 }catch{return fail('LIVE_INVALID_RESPONSE');}
}
export function validateLiveReceipt(v:unknown,owner:string,op:LiveOperation):LiveReceipt{const frozen=freezeLiveOperation({operationId:op.operationId,request:op.request}),r=validateLiveOperation(v,owner,frozen.operationId);if(!r||canonicalLive(r.request)!==canonicalLive(frozen.request))fail('LIVE_INVALID_RESPONSE');return r;}
export function validateLiveMutation(v:unknown,owner:string,op:LiveOperation):LiveMutation{return validateLiveError(v)??validateLiveReceipt(v,owner,op);}
export function validateLiveGrantCancellation(v:unknown,owner:string,input:LiveOperation):LiveGrantCancellationMutation{
 const op=freezeLiveOperation({operationId:input.operationId,request:input.request});if(op.request.action!=='location_grant')fail();const error=validateLiveError(v);if(error)return error;
 if(liveObject(v)&&Object.hasOwn(v,'state')){if(!liveKeys(v,['owner_id','operation_id','request','state','cancelled_at'])||v.owner_id!==owner||v.operation_id!==op.operationId||v.state!=='cancelled'||!isLiveInstant(v.cancelled_at)||canonicalLive(v.request)!==canonicalLive(op.request))fail('LIVE_INVALID_RESPONSE');return detached(v) as LiveGrantCancellationMutation;}
 return validateLiveReceipt(v,owner,op);
}
function owned(v:unknown,owner:string,ks:readonly string[]):Record<string,unknown>{if(!isLiveId(owner)||!liveObject(v)||!liveKeys(v,['owner_id','server_now',...ks])||v.owner_id!==owner||!isLiveInstant(v.server_now))fail();return v;}
function safeRoute(v:unknown,owner:string){if(!liveObject(v)||!liveKeys(v,['route_id','revision','title','category','segments','geometryStatus','privacyTrimMeters','geometryHash','provider','attribution'])||!isLiveId(v.route_id))fail();validateRouteProjection({id:v.route_id,owner_id:owner,revision:v.revision,title:v.title,category:v.category,visibility:'private',segments:v.segments,geometryStatus:v.geometryStatus,privacyTrimMeters:v.privacyTrimMeters,geometryHash:v.geometryHash,provider:v.provider,attribution:v.attribution});}
export function validateConvoySnapshot(v:unknown,owner:string,roomId:string):ConvoySnapshot|null{
 if(!isLiveId(owner)||!isLiveId(roomId))fail();if(v===null)return null;
 try{
  const r=owned(v,owner,['id','host_id','title','revision','state','expires_at','host_lease_until','route_snapshot','viewer_role','self_state','self_generation','members','topic','topic_generation','change_revision','self_consent','self_code']);
  if(r.id!==roomId||!isLiveId(r.host_id)||!str(r.title,48)||!int(r.revision,1)||!['lobby','active','ended','cancelled'].includes(String(r.state))||!isLiveInstant(r.expires_at)||!isLiveInstant(r.host_lease_until)||!['host','member','applicant'].includes(String(r.viewer_role))||!memberState(r.self_state)||!int(r.self_generation,1)||!int(r.topic_generation,1)||!int(r.change_revision,1)||!Array.isArray(r.members)||r.members.length<1||r.members.length>16)fail();safeRoute(r.route_snapshot,r.host_id);
  const seen=new Map<string,Record<string,unknown>>();let accepted=0,requested=0;
  for(const m of r.members){if(!liveObject(m)||!liveKeys(m,['user_id','handle','display_name','role','state','generation','host_friendship_generation'])||!isLiveId(m.user_id)||seen.has(m.user_id)||!handle(m.handle)||!str(m.display_name,40)||!['host','member'].includes(String(m.role))||!memberState(m.state)||!int(m.generation,1)||m.role==='host'&&(m.user_id!==r.host_id||m.state!=='accepted'||m.host_friendship_generation!==null)||m.role==='member'&&(m.user_id===r.host_id||!int(m.host_friendship_generation,1)))fail();seen.set(m.user_id,m);if(m.state==='accepted')accepted++;else requested++;}
  const self=seen.get(owner),host=seen.get(r.host_id);if(!self||!host||self.state!==r.self_state||self.generation!==r.self_generation||accepted>4||requested>12||r.viewer_role==='host'&&(owner!==r.host_id||self.role!=='host')||r.viewer_role!=='host'&&(owner===r.host_id||self.role!=='member')||r.viewer_role==='member'&&r.self_state!=='accepted'||r.viewer_role==='applicant'&&r.self_state!=='requested')fail();
  const terminal=r.state==='ended'||r.state==='cancelled';if(terminal?(r.viewer_role==='applicant'||r.topic!==null||r.members.length!==(owner===r.host_id?1:2)):Date.parse(r.expires_at)<=Date.parse(r.server_now as string)||Date.parse(r.host_lease_until)<=Date.parse(r.server_now as string))fail();
  if(r.viewer_role==='applicant'){if(r.members.length!==2||r.topic!==null)fail();}else if(!terminal&&(typeof r.topic!=='string'||!r.topic.startsWith('rs-convoy:')||!isLiveId(r.topic.slice(10))))fail();
  if(r.viewer_role!=='host'&&r.viewer_role!=='applicant'&&requested)fail();
  const c=r.self_consent;if(!liveObject(c)||!liveKeys(c,['revision','precision','lease_id','capture_id','expires_at','last_sequence'])||!int(c.revision)||!int(c.last_sequence)||!['none','precise'].includes(String(c.precision)))fail();
  if(c.precision==='none'?(c.lease_id!==null||c.capture_id!==null||c.expires_at!==null||c.last_sequence!==0):r.state!=='active'||r.self_state!=='accepted'||!isLiveId(c.lease_id)||!isLiveId(c.capture_id)||!isLiveInstant(c.expires_at)||Date.parse(c.expires_at)<=Date.parse(r.server_now as string)||Date.parse(c.expires_at)>Date.parse(r.expires_at))fail();
  if(r.viewer_role==='applicant'&&(c.revision!==0||c.precision!=='none'))fail();
  const code=r.self_code;if(r.viewer_role==='host'&&!terminal){if(!liveObject(code)||!liveKeys(code,['generation','hash','expires_at'])||!int(code.generation,1)||!digest(code.hash)||!isLiveInstant(code.expires_at)||Date.parse(code.expires_at)>Date.parse(r.expires_at))fail();}else if(code!==null)fail();return detached(r) as ConvoySnapshot;
 }catch{return fail('LIVE_INVALID_RESPONSE');}
}
export function freezeLiveSample(v:unknown):LiveSample{
 if(!liveObject(v)||!liveKeys(v,['schema_version','convoy_id','topic_generation','member_generation','consent_revision','lease_id','capture_id','sequence','latitude','longitude','accuracy_m','heading_deg','captured_at','source'])||v.schema_version!==1||!isLiveId(v.convoy_id)||!int(v.topic_generation,1)||!int(v.member_generation,1)||!int(v.consent_revision,1)||!isLiveId(v.lease_id)||!isLiveId(v.capture_id)||!int(v.sequence,1)||!finite(v.latitude,-90,90)||!finite(v.longitude,-180,180)||!finite(v.accuracy_m,Number.MIN_VALUE,20)||v.heading_deg!==null&&!finite(v.heading_deg,0,359.99999999999994)||!isLiveInstant(v.captured_at)||!liveObject(v.source)||!liveKeys(v.source,['platform','mocked','simulated'])||!['ios','android','web'].includes(String(v.source.platform))||v.source.mocked!==null&&v.source.mocked!==false||v.source.simulated!==null&&v.source.simulated!==false)fail();return detached(v) as LiveSample;
}
export function validateConvoyPositions(v:unknown,owner:string,room:ConvoySnapshot):ConvoyPositions{
 try{
  const r=owned(v,owner,['convoy_id','topic_generation','change_revision','items']);if(r.convoy_id!==room.id||room.owner_id!==owner||room.state!=='active'||room.self_state!=='accepted'||r.topic_generation!==room.topic_generation||!int(r.change_revision,1)||r.change_revision<room.change_revision||!Array.isArray(r.items)||r.items.length>3)fail();const seen=new Set<string>();
  for(const p of r.items){if(!liveObject(p)||!liveKeys(p,['user_id','display_name','latitude','longitude','accuracy_m','heading_deg','captured_at','received_at','expires_at','member_generation','consent_revision','sequence','authority'])||!isLiveId(p.user_id)||p.user_id===owner||seen.has(p.user_id)||!str(p.display_name,40)||!finite(p.latitude,-90,90)||!finite(p.longitude,-180,180)||!finite(p.accuracy_m,Number.MIN_VALUE,20)||p.heading_deg!==null&&!finite(p.heading_deg,0,359.99999999999994)||!isLiveInstant(p.captured_at)||!isLiveInstant(p.received_at)||!isLiveInstant(p.expires_at)||!int(p.member_generation,1)||!int(p.consent_revision,1)||!int(p.sequence,1)||p.authority!=='unverified_live')fail();const m=room.members.find(m=>m.user_id===p.user_id);if(!m||m.state!=='accepted'||m.generation!==p.member_generation)fail();const expiry=Date.parse(p.expires_at),received=Date.parse(p.received_at),captured=Date.parse(p.captured_at);if(expiry<=received||expiry-received>15001||expiry<=Date.parse(r.server_now as string)||expiry>Date.parse(room.expires_at)||expiry>Date.parse(room.host_lease_until)||received>Date.parse(r.server_now as string)+1||captured<received-3001||captured>received+2001)fail();seen.add(p.user_id);}
  return detached(r) as ConvoyPositions;
 }catch{return fail('LIVE_INVALID_RESPONSE');}
}
export function validateConvoyPositionMutation(v:unknown,owner:string,room:ConvoySnapshot):ConvoyPositionMutation{return validateLiveError(v)??validateConvoyPositions(v,owner,room);}
export function validateLivePublishAck(v:unknown,owner:string,sample:LiveSample):LivePublishAck{
 try{if(!liveObject(v)||!liveKeys(v,['owner_id','convoy_id','lease_id','sequence','received_at','expires_at'])||v.owner_id!==owner||v.convoy_id!==sample.convoy_id||v.lease_id!==sample.lease_id||v.sequence!==sample.sequence||!isLiveInstant(v.received_at)||!isLiveInstant(v.expires_at)||Date.parse(v.expires_at)<=Date.parse(v.received_at)||Date.parse(v.expires_at)-Date.parse(v.received_at)>15001||Date.parse(sample.captured_at)<Date.parse(v.received_at)-3001||Date.parse(sample.captured_at)>Date.parse(v.received_at)+2001)fail();return detached(v) as LivePublishAck;}catch{return fail('LIVE_INVALID_RESPONSE');}
}
export function validateLivePublishMutation(v:unknown,owner:string,sample:LiveSample):LivePublishMutation{return validateLiveError(v)??validateLivePublishAck(v,owner,sample);}
export function validateConvoyEvent(v:unknown,room:ConvoySnapshot):ConvoyEvent|null{if(!liveObject(v)||!liveKeys(v,['schema_version','convoy_id','topic_generation','change_revision','kind'])||v.schema_version!==1||v.convoy_id!==room.id||v.topic_generation!==room.topic_generation||!int(v.change_revision,1)||v.change_revision<room.change_revision||v.kind!=='positions_changed'&&v.kind!=='room_changed')return null;return detached(v) as ConvoyEvent;}
export function validateConvoyHeartbeat(v:unknown,owner:string,room:ConvoySnapshot):ConvoyHeartbeat{try{const r=owned(v,owner,['convoy_id','host_lease_until']);if(owner!==room.host_id||room.viewer_role!=='host'||room.self_state!=='accepted'||r.convoy_id!==room.id||!isLiveInstant(r.host_lease_until)||Date.parse(r.host_lease_until)<=Date.parse(r.server_now as string)||Date.parse(r.host_lease_until)-Date.parse(r.server_now as string)>45001)fail();return detached(r) as ConvoyHeartbeat;}catch{return fail('LIVE_INVALID_RESPONSE');}}
export function validateConvoyHeartbeatMutation(v:unknown,owner:string,room:ConvoySnapshot):ConvoyHeartbeatMutation{return validateLiveError(v)??validateConvoyHeartbeat(v,owner,room);}
export function validateFriendLinks(v:unknown,owner:string):FriendLinks{try{const r=owned(v,owner,['items']);if(!Array.isArray(r.items)||r.items.length>8)fail();const seen=new Set<string>();for(const l of r.items){if(!liveObject(l)||!liveKeys(l,['id','revision','state','expires_at'])||!isLiveId(l.id)||seen.has(l.id)||!int(l.revision,1)||l.state!=='active'||!isLiveInstant(l.expires_at)||Date.parse(l.expires_at)<=Date.parse(r.server_now as string))fail();seen.add(l.id);}return detached(r) as FriendLinks;}catch{return fail('LIVE_INVALID_RESPONSE');}}
export function validateFriendLinkResolution(v:unknown,owner:string,linkId:string):FriendLinkResolution{try{const r=owned(v,owner,['preview']),p=r.preview;if(p!==null&&(!liveObject(p)||!liveKeys(p,['proof_id','link_id','issuer_id','handle','display_name','expires_at'])||!isLiveId(p.proof_id)||p.link_id!==linkId||!isLiveId(p.issuer_id)||!handle(p.handle)||!str(p.display_name,40)||!isLiveInstant(p.expires_at)||Date.parse(p.expires_at)<=Date.parse(r.server_now as string)||Date.parse(p.expires_at)-Date.parse(r.server_now as string)>300001))fail();return detached(r) as FriendLinkResolution;}catch{return fail('LIVE_INVALID_RESPONSE');}}
export function validateConvoyCodeResolution(v:unknown,owner:string):ConvoyCodeResolution{try{const r=owned(v,owner,['preview']),p=r.preview;if(p!==null&&(!liveObject(p)||!liveKeys(p,['proof_id','convoy_id','host_id','host_name','title','room_revision','host_friendship_generation','expires_at'])||!isLiveId(p.proof_id)||!isLiveId(p.convoy_id)||!isLiveId(p.host_id)||!str(p.host_name,40)||!str(p.title,48)||!int(p.room_revision,1)||!int(p.host_friendship_generation,1)||!isLiveInstant(p.expires_at)||Date.parse(p.expires_at)<=Date.parse(r.server_now as string)||Date.parse(p.expires_at)-Date.parse(r.server_now as string)>300001))fail();return detached(r) as ConvoyCodeResolution;}catch{return fail('LIVE_INVALID_RESPONSE');}}
export function validateConvoyList(v:unknown,owner:string):ConvoyList{try{const r=owned(v,owner,['items']);if(!Array.isArray(r.items)||r.items.length>1)fail();for(const row of r.items){if(!liveObject(row)||!liveKeys(row,['id','host_id','title','revision','state','self_state','expires_at'])||!isLiveId(row.id)||!isLiveId(row.host_id)||!str(row.title,48)||!int(row.revision,1)||row.state!=='lobby'&&row.state!=='active'||!memberState(row.self_state)||!isLiveInstant(row.expires_at)||Date.parse(row.expires_at)<=Date.parse(r.server_now as string))fail();}return detached(r) as ConvoyList;}catch{return fail('LIVE_INVALID_RESPONSE');}}
export type ParsedFriendLink={linkId:string;token:string;scheme:'ridespeed'|'ridespeed-dev'};
export function parseFriendLink(value:unknown):ParsedFriendLink|null{if(typeof value!=='string'||value.length>200)return null;const match=/^(ridespeed|ridespeed-dev):\/\/friend\/v1\/([a-f0-9-]{36})#token=([A-Za-z0-9_-]{43})$/.exec(value);if(!match||!isLiveId(match[2])||!token.test(match[3]))return null;return {scheme:match[1] as ParsedFriendLink['scheme'],linkId:match[2],token:match[3]};}
export function encodedFriendLink(linkId:string,value:string,scheme:ParsedFriendLink['scheme']='ridespeed'):string{if(!isLiveId(linkId)||!token.test(value)||scheme!=='ridespeed'&&scheme!=='ridespeed-dev')fail();return `${scheme}://friend/v1/${linkId}#token=${value}`;}
export function normalizeConvoyCode(value:unknown):string{if(typeof value!=='string'||value.length>32)fail();const normalized=value.replace(/[ -]/g,'').toUpperCase();if(!/^[0-9A-HJKMNP-TV-Z]{8}$/.test(normalized))fail();return normalized;}
export function friendTokenHashInput(value:string):string{if(!token.test(value))fail();return 'ride-speed:friend-link:v1:'+value;}
export function convoyCodeHashInput(value:string):string{return 'ride-speed:convoy-code:v1:'+normalizeConvoyCode(value);}
