import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {freezeLiveOperation,freezeLiveSample,friendTokenHashInput,isLiveId,normalizeConvoyCode,validateConvoyCodeResolution,validateConvoyHeartbeatMutation,validateConvoyList,validateConvoyPositionMutation,validateConvoySnapshot,validateFriendLinkResolution,validateFriendLinks,validateLiveError,validateLiveGrantCancellation,validateLiveMutation,validateLiveOperation,validateLivePublishMutation} from './model';
import type {ConvoyCodeResolutionResponse,ConvoyHeartbeatMutation,ConvoyList,ConvoyPositionMutation,ConvoySnapshot,FriendLinkResolutionResponse,FriendLinks,LiveGrantCancellationMutation,LiveMutation,LiveOperation,LivePublishMutation,LiveReceipt,LiveSample} from './types';
export type {ConvoyCodeResolutionResponse,ConvoyHeartbeatMutation,ConvoyList,ConvoyPositionMutation,ConvoySnapshot,FriendLinkResolutionResponse,FriendLinks,LiveGrantCancellation,LiveGrantCancellationMutation,LiveMutation,LiveOperation,LivePublishMutation,LiveReceipt,LiveSample} from './types';
function current(scope:AuthScope,session:Session){if(!scope.userId||session.user.id!==scope.userId||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>):Promise<unknown>=>{current(scope,session);let response;try{response=await client.rpc(name,args);}catch{current(scope,session);throw Error('LIVE_UNAVAILABLE');}current(scope,session);if(response.error){if(response.error.code==='PGRST301'||response.error.code==='PGRST302')throw Error('LIVE_AUTH_REQUIRED');if(response.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('LIVE_UNAVAILABLE');}return response.data;};}
function requiredId(id:string){if(!isLiveId(id))throw Error('LIVE_INVALID');}
function readError(value:unknown){const error=validateLiveError(value);if(error)throw Error(error.error.code);return value;}
/** Transport has no retry/outbox, mutable global token or Realtime GPS channel. */
export async function mutateLive(scope:AuthScope,session:Session,value:LiveOperation):Promise<LiveMutation>{const op=freezeLiveOperation({operationId:value.operationId,request:value.request}),rpc=transport(scope,session);return validateLiveMutation(await rpc('rs_live_mutate',{p_operation:op.operationId,p_request:op.request}),scope.userId!,op);}
export async function cancelLiveGrant(scope:AuthScope,session:Session,value:LiveOperation):Promise<LiveGrantCancellationMutation>{const op=freezeLiveOperation({operationId:value.operationId,request:value.request});if(op.request.action!=='location_grant')throw Error('LIVE_INVALID');const rpc=transport(scope,session);return validateLiveGrantCancellation(await rpc('rs_cancel_live_grant',{p_operation:op.operationId,p_request:op.request}),scope.userId!,op);}
export async function getLiveOperation(scope:AuthScope,session:Session,operationId:string):Promise<LiveReceipt|null>{requiredId(operationId);const rpc=transport(scope,session);return validateLiveOperation(readError(await rpc('rs_live_operation',{p_operation:operationId})),scope.userId!,operationId);}
export async function getFriendLinks(scope:AuthScope,session:Session):Promise<FriendLinks>{const rpc=transport(scope,session);return validateFriendLinks(readError(await rpc('rs_friend_links',{})),scope.userId!);}
export async function resolveFriendLink(scope:AuthScope,session:Session,linkId:string,token:string):Promise<FriendLinkResolutionResponse>{requiredId(linkId);friendTokenHashInput(token);const rpc=transport(scope,session),value=await rpc('rs_resolve_friend_link',{p_link:linkId,p_token:token});return validateLiveError(value)??validateFriendLinkResolution(value,scope.userId!,linkId);}
export async function resolveConvoyCode(scope:AuthScope,session:Session,code:string):Promise<ConvoyCodeResolutionResponse>{const normalized=normalizeConvoyCode(code),rpc=transport(scope,session),value=await rpc('rs_resolve_convoy_code',{p_code:normalized});return validateLiveError(value)??validateConvoyCodeResolution(value,scope.userId!);}
export async function getConvoy(scope:AuthScope,session:Session,convoyId:string):Promise<ConvoySnapshot|null>{requiredId(convoyId);const rpc=transport(scope,session);return validateConvoySnapshot(readError(await rpc('rs_get_convoy',{p_convoy:convoyId})),scope.userId!,convoyId);}
export async function listConvoys(scope:AuthScope,session:Session):Promise<ConvoyList>{const rpc=transport(scope,session);return validateConvoyList(readError(await rpc('rs_list_convoys',{})),scope.userId!);}
export async function heartbeatConvoy(scope:AuthScope,session:Session,room:ConvoySnapshot):Promise<ConvoyHeartbeatMutation>{if(room.owner_id!==scope.userId||room.host_id!==scope.userId||room.viewer_role!=='host'||room.self_state!=='accepted'||room.state!=='lobby'&&room.state!=='active')throw Error('CONVOY_UNAVAILABLE');const rpc=transport(scope,session);return validateConvoyHeartbeatMutation(await rpc('rs_convoy_heartbeat',{p_convoy:room.id,p_member_generation:room.self_generation}),scope.userId!,room);}
export async function publishLivePosition(scope:AuthScope,session:Session,value:LiveSample):Promise<LivePublishMutation>{const sample=freezeLiveSample(value),rpc=transport(scope,session);return validateLivePublishMutation(await rpc('rs_publish_live_position',{p_sample:sample}),scope.userId!,sample);}
export async function getConvoyPositions(scope:AuthScope,session:Session,room:ConvoySnapshot):Promise<ConvoyPositionMutation>{if(room.owner_id!==scope.userId||room.state!=='active'||room.self_state!=='accepted'||room.viewer_role==='applicant'||room.topic===null)throw Error('CONVOY_UNAVAILABLE');const rpc=transport(scope,session);return validateConvoyPositionMutation(await rpc('rs_convoy_positions',{p_convoy:room.id,p_topic_generation:room.topic_generation}),scope.userId!,room);}
