import type {DirectedGate,RaceCoordinate,RaceCourseConfiguration} from './types';
export type RaceGateFix=Readonly<{sequence:number;latitude:number;longitude:number;accuracyM:number;timestampMs:number;receivedMonotonicMs?:number;receivedWallMs?:number}>;
export type RaceGateCrossing=Readonly<{index:number;kind:DirectedGate['kind'];before:RaceGateFix;after:RaceGateFix}>;
export type RaceGateProgress=Readonly<{state:'progress'|'start'|'checkpoint'|'finish'|'invalid';nextGate:number;crossing:RaceGateCrossing|null;reason:string|null}>;
type Point={x:number;y:number};
type PreviewCourse=Pick<RaceCourseConfiguration,'origin'|'gates'|'geometry_error_margin_m'|'maximum_accuracy_m'|'maximum_gap_ms'|'maximum_crossing_span_ms'>;
function xyz(p:RaceCoordinate){const lat=p.latitude*Math.PI/180,lon=p.longitude*Math.PI/180,e2=(1/298.257223563)*(2-1/298.257223563),n=6378137/Math.sqrt(1-e2*Math.sin(lat)**2);return[n*Math.cos(lat)*Math.cos(lon),n*Math.cos(lat)*Math.sin(lon),n*(1-e2)*Math.sin(lat)];}
function projector(origin:RaceCoordinate){const base=xyz(origin),lat=origin.latitude*Math.PI/180,lon=origin.longitude*Math.PI/180;return(p:RaceCoordinate):Point=>{const q=xyz(p).map((v,i)=>v-base[i]);return{x:-Math.sin(lon)*q[0]+Math.cos(lon)*q[1],y:-Math.sin(lat)*Math.cos(lon)*q[0]-Math.sin(lat)*Math.sin(lon)*q[1]+Math.cos(lat)*q[2]};};}
const cross=(a:Point,b:Point)=>a.x*b.y-a.y*b.x;
/** Bounded local gate hints. It does not prove corridor, elapsed time or a result. */
export class RaceGatePreview{
 private next=0;private last:RaceGateFix|null=null;private before:RaceGateFix|null=null;private invalid:string|null=null;
 private readonly project:(p:RaceCoordinate)=>Point;
 constructor(private course:PreviewCourse){if(course.gates.length<2||course.gates.length>16)throw Error('RACE_INVALID');this.project=projector(course.origin);}
 private state(state:RaceGateProgress['state']='progress',crossing:RaceGateCrossing|null=null):RaceGateProgress{return Object.freeze({state:this.invalid?'invalid':state,nextGate:this.next,crossing,reason:this.invalid});}
 private reject(reason:string){this.invalid=reason;return this.state();}
 private side(fix:RaceGateFix,gate:DirectedGate){const a=this.project(gate.a),b=this.project(gate.b),forward=this.project(gate.forward_point),p=this.project(fix),mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2},length=Math.hypot(b.x-a.x,b.y-a.y),sign=Math.sign(cross({x:b.x-a.x,y:b.y-a.y},{x:forward.x-mid.x,y:forward.y-mid.y}));if(!length||!sign)return NaN;return sign*cross({x:b.x-a.x,y:b.y-a.y},{x:p.x-mid.x,y:p.y-mid.y})/length;}
 private intersects(before:RaceGateFix,after:RaceGateFix,gate:DirectedGate){const p=this.project(before),q=this.project(after),a=this.project(gate.a),b=this.project(gate.b),r={x:q.x-p.x,y:q.y-p.y},s={x:b.x-a.x,y:b.y-a.y},d=cross(r,s);if(Math.abs(d)<1e-10)return false;const ap={x:a.x-p.x,y:a.y-p.y},t=cross(ap,s)/d,u=cross(ap,r)/d,margin=(Math.max(before.accuracyM,after.accuracyM)+this.course.geometry_error_margin_m)/Math.hypot(s.x,s.y);return t>=0&&t<=1&&u>=margin&&u<=1-margin;}
 accept(input:RaceGateFix):RaceGateProgress{if(this.invalid)return this.state();if(this.next>=this.course.gates.length)return this.state('finish');const fix=Object.freeze({...input});if(!Number.isSafeInteger(fix.sequence)||fix.sequence<0||![fix.latitude,fix.longitude,fix.timestampMs,fix.accuracyM].every(Number.isFinite)||Math.abs(fix.latitude)>80||Math.abs(fix.longitude)>180||fix.accuracyM<=0||fix.accuracyM>this.course.maximum_accuracy_m)return this.reject('quality');if(this.last&&(fix.sequence!==this.last.sequence+1||fix.timestampMs<=this.last.timestampMs||fix.timestampMs-this.last.timestampMs>this.course.maximum_gap_ms))return this.reject('continuity');const gate=this.course.gates[this.next],side=this.side(fix,gate),margin=fix.accuracyM+this.course.geometry_error_margin_m;if(!Number.isFinite(side))return this.reject('gate');this.last=fix;if(side< -margin){this.before=fix;return this.state();}if(side<=margin)return this.state();if(!this.before)return this.reject('start_side');if(fix.timestampMs-this.before.timestampMs>this.course.maximum_crossing_span_ms)return this.reject('crossing_span');if(!this.intersects(this.before,fix,gate))return this.reject('gate_width');const crossing=Object.freeze({index:this.next,kind:gate.kind,before:this.before,after:fix});this.next++;this.before=null;if(this.next<this.course.gates.length){const next=this.course.gates[this.next],s=this.side(fix,next);if(s>fix.accuracyM+this.course.geometry_error_margin_m)return this.reject('multiple_gates');if(s< -fix.accuracyM-this.course.geometry_error_margin_m)this.before=fix;}return this.state(gate.kind,crossing);}
}
