import {parseRaceClockInstant} from './raceClock';
import {parseShareSnapshot} from '../routes/compatibilityModel';
import type * as T from './types';
export const raceLimits=Object.freeze({operations:32,outboxBytes:131072,controlBytes:16384,evidenceBytes:2097152,samples:8000,revision:2147483647});
export const raceErrors=['RACE_INVALID','RACE_TOO_LARGE','RACE_AUTH_REQUIRED','RACE_PROFILE_REQUIRED','RACE_DISABLED','RACE_RATE_LIMITED','RACE_UNAVAILABLE','RACE_OPERATION_CONFLICT','RACE_OPERATION_CANCELLED','RACE_CHANGED','RACE_MEMBER_CHANGED','RACE_FRIEND_CHANGED','RACE_BLOCKED','RACE_APPROVAL_UNAVAILABLE','RACE_SESSION_UNAVAILABLE','RACE_CAPACITY','RACE_ATTEMPT_ACTIVE','RACE_ATTEMPT_LIMIT','RACE_ATTEMPT_CHANGED','RACE_CAPTURE_MISMATCH','RACE_STAGE_UNAVAILABLE','RACE_CLOCK_UNAVAILABLE','RACE_READY_CHANGED','RACE_NOT_READY','RACE_TOO_LATE','RACE_EVIDENCE_BOUND','RACE_EVIDENCE_UNAVAILABLE','RACE_UPLOAD_EXPIRED','ACCOUNT_DELETION_PENDING'] as const;
const terminal=['host_cancelled','host_expired','membership_changed','blocked','approval_revoked','session_ended','account_deleted','deadline'];
const abort=['user_stop','background','capture_changed','quality','storage_error','clock_invalid','late_start'];
const evidence=['EVIDENCE_SCHEMA','EVIDENCE_DIGEST','EVIDENCE_SIZE','EVIDENCE_SOURCE','EVIDENCE_MOCKED','EVIDENCE_ACCURACY','EVIDENCE_TIMESTAMP','EVIDENCE_CLOCK','EVIDENCE_CLOCK_PRECISION','EVIDENCE_CLOCK_STALE','EVIDENCE_GAP','EVIDENCE_TRUNCATED','EVIDENCE_CAPTURE','EVIDENCE_FOREGROUND','EVIDENCE_TELEPORT','EVIDENCE_ACCELERATION','EVIDENCE_BOUNDARY','EVIDENCE_CORRIDOR','EVIDENCE_PROGRESS','EVIDENCE_GATE_DIRECTION','EVIDENCE_GATE_ORDER','EVIDENCE_GATE_AMBIGUOUS','EVIDENCE_STAGING','EVIDENCE_LATE_START','EVIDENCE_WINDOW','EVIDENCE_DURATION','APPROVAL_REVOKED','MEMBERSHIP_CHANGED','ACCOUNT_DELETION'];
const category=['scooter','motorcycle','car'],activeRace=['open','lobby','countdown','running'],clientErrors=['RACE_INVALID_RESPONSE','RACE_REVIEW_REQUIRED','ACCOUNT_CHANGED','LOCAL_READ_FAILED','LOCAL_WRITE_FAILED'];
function fail():never{throw Error('RACE_INVALID_RESPONSE');}
function obj(value:unknown,keys?:string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))fail();const v=value as Record<string,unknown>;if(keys&&(Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k))))fail();return v;}
function arr(value:unknown,min:number,max:number):unknown[]{if(!Array.isArray(value)||value.length<min||value.length>max)fail();return value;}
function num(value:unknown,min=0,max=Number.MAX_SAFE_INTEGER):number{if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)fail();return value;}
function int(value:unknown,min:number=0,max:number=raceLimits.revision):number{const n=num(value,min,max);if(!Number.isInteger(n))fail();return n;}
function text(value:unknown,max=100):string{if(typeof value!=='string'||!value.trim()||[...value].length>max||/[\u0000-\u001f\u007f]/u.test(value))fail();return value;}
export const isRaceId=(value:unknown):value is string=>typeof value==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(value);
function id(value:unknown):string{if(!isRaceId(value))fail();return value;}
function hash(value:unknown):string{if(typeof value!=='string'||!/^[a-f0-9]{64}$/.test(value))fail();return value;}
function utc(value:unknown):string{if(parseRaceClockInstant(value)===null)fail();return value as string;}
// Timestamp floats are adequate for the 100ms clock bound, but not DB keysets.
function utcKey(value:unknown):string{const s=utc(value),match=/^(.*?)(?:\.(\d{1,6}))?(?:Z|\+00:00)$/.exec(s)!;return `${match[1]}.${(match[2]??'').padEnd(6,'0')}`;}
function choice(value:unknown,values:readonly unknown[]){if(!values.includes(value))fail();return value;}
function literal(value:unknown,wanted:unknown){if(value!==wanted)fail();}
function nullable(value:unknown,validate:(value:unknown)=>unknown){if(value!==null)validate(value);}
function boolean(value:unknown){if(typeof value!=='boolean')fail();}
function unique(values:unknown[],get:(v:unknown)=>string){const keys=values.map(get);if(new Set(keys).size!==keys.length)fail();}
function probes(value:unknown){unique(arr(value,3,5),id);}
function native(platform:unknown,provider:unknown){choice(platform,['ios','android']);choice(provider,['ios_core_location','expo_location']);if(platform==='android'&&provider!=='expo_location')fail();}
function window(start:unknown,end:unknown,max=86400000){utc(start);utc(end);const gap=parseRaceClockInstant(end)!-parseRaceClockInstant(start)!;if(gap<=0||gap>max)fail();}
function freezeDeep<V>(value:V):V{if(value&&typeof value==='object'){for(const next of Object.values(value))freezeDeep(next);Object.freeze(value);}return value;}
function detached<V>(value:unknown):V{return freezeDeep(JSON.parse(JSON.stringify(value))) as V;}
export function canonicalRace(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonicalRace).join(',')}]`;const v=value as Record<string,unknown>;return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalRace(v[k])}`).join(',')}}`;}
function bytes(value:unknown){return new TextEncoder().encode(JSON.stringify(value)).length;}
function readyBinding(value:unknown){const v=obj(value,['user_id','member_generation','ready_revision','ready_lease_id','attempt_id']);id(v.user_id);int(v.member_generation,1);int(v.ready_revision,1);id(v.ready_lease_id);id(v.attempt_id);return v;}
const requestKeys:Record<string,string[]>={
 race_create:['race_id','mode','approval_id','route_id','route_revision','reviewed_projection_hash','starts_at','ends_at','friends','acknowledgement_version','evidence_consent_version'],
 member_action:['race_id','expected_revision','expected_member_generation','expected_friendship_generation','decision'],
 attempt_reserve:['race_id','expected_revision','expected_member_generation','attempt_id','ride_id','capture_id','platform','provider','vehicle_local_id'],
 attempt_arm:['attempt_id','expected_revision','stage_proof_id','capture_id','clock_probe_ids'],
 attempt_abort:['attempt_id','expected_revision','reason'],
 race_ready:['race_id','expected_revision','expected_member_generation','expected_ready_revision','lobby_epoch','attempt_id','capture_id','stage_proof_id','clock_probe_ids'],
 race_unready:['race_id','expected_member_generation','expected_ready_revision','expected_ready_lease_id'],
 race_schedule:['race_id','expected_revision','lobby_epoch','ready'],race_cancel:['race_id','expected_revision','reason'],
 evidence_bind:['attempt_id','expected_revision','capture_id','first_sequence','last_sequence','sample_count','byte_length','sha256'],evidence_queue:['attempt_id','expected_revision','sha256']};
function request(value:unknown):T.RaceRequest{
 const first=obj(value),action=text(first.action,30),keys=requestKeys[action];if(!keys)fail();const consent=action==='member_action'&&first.decision==='accept'?['acknowledgement_version','evidence_consent_version']:[];
 const v=obj(value,['schema_version','action',...keys,...consent]);literal(v.schema_version,1);
 for(const key of ['race_id','approval_id','route_id','attempt_id','ride_id','capture_id','stage_proof_id','lobby_epoch','expected_ready_lease_id'])if(key in v)id(v[key]);
 for(const key of ['route_revision','expected_revision','expected_member_generation','expected_friendship_generation'])if(key in v)int(v[key],1,key==='expected_revision'&&action!=='attempt_abort'&&action!=='race_cancel'?raceLimits.revision-1:raceLimits.revision);
 if('expected_ready_revision'in v)int(v.expected_ready_revision,action==='race_unready'?1:0,raceLimits.revision-1);
 if('clock_probe_ids'in v)probes(v.clock_probe_ids);
 if(action==='race_create'){choice(v.mode,['async','live']);hash(v.reviewed_projection_hash);window(v.starts_at,v.ends_at);literal(v.acknowledgement_version,1);literal(v.evidence_consent_version,1);const list=arr(v.friends,1,3);unique(list,x=>{const f=obj(x,['user_id','friendship_generation']);int(f.friendship_generation,1);return id(f.user_id);});if(list.some((x,i)=>i>0&&id(obj(list[i-1]).user_id)>=id(obj(x).user_id)))fail();}
 if(action==='member_action'){choice(v.decision,['accept','decline','withdraw']);if(v.decision==='accept'){literal(v.acknowledgement_version,1);literal(v.evidence_consent_version,1);}}
 if(action==='attempt_reserve'){native(v.platform,v.provider);nullable(v.vehicle_local_id,x=>text(x,100));}
 if(action==='attempt_abort')choice(v.reason,abort);
 if(action==='race_cancel')literal(v.reason,'user_cancel');
 if(action==='race_schedule'){const list=arr(v.ready,2,4);unique(list,x=>id(readyBinding(x).user_id));}
 if(action==='evidence_bind'){int(v.first_sequence,0,Number.MAX_SAFE_INTEGER);int(v.last_sequence,0,Number.MAX_SAFE_INTEGER);int(v.sample_count,4,8000);int(v.byte_length,1,raceLimits.evidenceBytes);hash(v.sha256);if((v.last_sequence as number)-(v.first_sequence as number)+1!==v.sample_count)fail();}
 if(action==='evidence_queue')hash(v.sha256);
 return detached<T.RaceRequest>(v);
}
export function freezeRaceRequest(value:unknown):T.RaceRequest{try{if(bytes(value)>raceLimits.controlBytes)throw Error('RACE_TOO_LARGE');return request(value);}catch(e){if(e instanceof Error&&e.message==='RACE_TOO_LARGE')throw e;throw Error('RACE_INVALID');}}
export function freezeRaceOperation(value:unknown):T.RaceOperation{try{const v=obj(value,['operation_id','request']);return freezeDeep({operation_id:id(v.operation_id),request:freezeRaceRequest(v.request)});}catch(e){if(e instanceof Error&&e.message==='RACE_TOO_LARGE')throw e;throw Error('RACE_INVALID');}}
export function parseRaceOperations(value:unknown):T.StoredRaceOperation[]{if(value===undefined)return [];try{if(bytes(value)>raceLimits.outboxBytes)throw Error('RACE_TOO_LARGE');const list=arr(value,0,raceLimits.operations),rows=list.map(x=>{const v=obj(x,['operation_id','request','queued_at','last_error']),op=freezeRaceOperation({operation_id:v.operation_id,request:v.request});utc(v.queued_at);nullable(v.last_error,x=>choice(x,[...raceErrors,...clientErrors]));return detached<T.StoredRaceOperation>({...op,queued_at:v.queued_at,last_error:v.last_error});});unique(rows,x=>id(obj(x).operation_id));return rows;}catch{throw Error('RACE_INVALID');}}
export function validateRaceError(value:unknown):T.RaceErrorEnvelope|null{if(!value||typeof value!=='object'||!Object.hasOwn(value,'error'))return null;const v=obj(value,['error']),error=obj(v.error);choice(error.code,raceErrors);if(error.code==='RACE_RATE_LIMITED'){obj(error,['code','retry_after_ms']);int(error.retry_after_ms,1,86400000);}else obj(error,['code']);return detached<T.RaceErrorEnvelope>(v);}
function approval(value:unknown){const v=obj(value,['id','route_id','route_revision','route_geometry_hash','config_hash','course_id','session_id','method','category','starts_at','ends_at','distance_m','maximum_duration_s']);for(const k of ['id','route_id','course_id','session_id'])id(v[k]);int(v.route_revision,1);hash(v.route_geometry_hash);hash(v.config_hash);literal(v.method,'route_time_v1');choice(v.category,category);window(v.starts_at,v.ends_at,Number.MAX_SAFE_INTEGER);num(v.distance_m,100,15000);num(v.maximum_duration_s,10,1800);return v;}
function member(value:unknown){const v=obj(value,['user_id','role','state','member_generation','friendship_generation','profile','evidence_consent_version','consented_at','ready_revision','ready','ready_until']);id(v.user_id);choice(v.role,['host','member']);choice(v.state,['invited','accepted','declined','withdrawn']);int(v.member_generation,1);nullable(v.friendship_generation,x=>int(x,1));if((v.role==='host')!==(v.friendship_generation===null))fail();const p=obj(v.profile,['name','handle','avatar_id']);text(p.name,80);if(typeof p.handle!=='string'||!/^[a-z0-9_]{3,24}$/.test(p.handle))fail();nullable(p.avatar_id,id);nullable(v.evidence_consent_version,x=>literal(x,1));nullable(v.consented_at,utc);if((v.evidence_consent_version===null)!==(v.consented_at===null)||v.state==='accepted'&&v.evidence_consent_version!==1)fail();int(v.ready_revision);boolean(v.ready);nullable(v.ready_until,utc);if(v.ready!==(v.ready_until!==null)||v.ready&&(v.state!=='accepted'||v.ready_revision===0))fail();return v;}
function safeRoute(value:unknown){const v=obj(value,['route_id','revision','title','category','segments','geometryStatus','privacyTrimMeters','geometryHash','provider','attribution']);id(v.route_id);int(v.revision,1);text(v.title,80);choice(v.category,category);const parsed=parseShareSnapshot(v);if(!parsed?.geometry)fail();return v;}
export function validateRaceSnapshot(value:unknown,ownerId:string,expectedId?:string):T.RaceSnapshot|null{
 if(value===null)return null;const v=obj(value,['id','creator_id','revision','mode','metric','method','state','approval','route_summary','route_snapshot','starts_at','ends_at','lobby_epoch','common_start_at','schedule_epoch','topic','topic_generation','host_lease_until','self_member','members','self_ready','schedule_ready','updated_at','terminal_reason']);id(v.id);if(expectedId&&v.id!==expectedId)fail();id(v.creator_id);int(v.revision,1);choice(v.mode,['async','live']);literal(v.metric,'route_time');literal(v.method,'route_time_v1');choice(v.state,[...activeRace,'finished','cancelled','expired']);const a=approval(v.approval),s=obj(v.route_summary,['title','revision','category']),r=safeRoute(v.route_snapshot);text(s.title,80);int(s.revision,1);choice(s.category,category);if(s.title!==r.title||s.revision!==r.revision||s.category!==r.category||r.route_id!==a.route_id||r.revision!==a.route_revision||r.category!==a.category)fail();window(v.starts_at,v.ends_at);if(parseRaceClockInstant(v.starts_at)!<parseRaceClockInstant(a.starts_at)!||parseRaceClockInstant(v.ends_at)!>parseRaceClockInstant(a.ends_at)!)fail();id(v.lobby_epoch);nullable(v.common_start_at,utc);nullable(v.schedule_epoch,id);if((v.common_start_at===null)!==(v.schedule_epoch===null)||v.mode==='async'&&v.schedule_epoch!==null)fail();nullable(v.topic,x=>{if(typeof x!=='string'||!x.startsWith('rs-race:'))fail();id(x.slice(8));});int(v.topic_generation,1);nullable(v.host_lease_until,utc);const self=member(v.self_member),members=arr(v.members,1,4).map(member);unique(members,x=>id(obj(x).user_id));if(self.user_id!==ownerId||!members.some(m=>canonicalRace(m)===canonicalRace(self)))fail();const live=activeRace.includes(v.state as string);if(live&&!members.some(m=>m.user_id===v.creator_id&&m.role==='host'))fail();if(!live||self.state!=='accepted'){if(v.topic!==null||v.self_ready!==null||v.schedule_ready!==null)fail();}nullable(v.self_ready,x=>{const b=obj(x,['revision','lease_id','attempt_id','until']);int(b.revision,1);id(b.lease_id);id(b.attempt_id);utc(b.until);if(b.revision!==self.ready_revision||b.until!==self.ready_until||!self.ready)fail();});nullable(v.schedule_ready,x=>{if(v.creator_id!==ownerId||self.role!=='host'||!['lobby','countdown'].includes(v.state as string))fail();const rows=arr(x,0,4);unique(rows,y=>id(readyBinding(y).user_id));for(const row of rows){const b=readyBinding(row),m=members.find(m=>m.user_id===b.user_id);if(!m||!m.ready||m.member_generation!==b.member_generation||m.ready_revision!==b.ready_revision)fail();}});utc(v.updated_at);nullable(v.terminal_reason,x=>choice(x,terminal));if(live&&v.terminal_reason!==null)fail();return detached<T.RaceSnapshot>(v);
}
function reservation(value:unknown,ownerId:string,attemptId:string){const v=obj(value,['bucket','path','attempt_id','capture_id','sha256','byte_length','first_sequence','last_sequence','sample_count','upload_deadline']);literal(v.bucket,'ride-race-evidence');id(v.attempt_id);id(v.capture_id);if(v.attempt_id!==attemptId||v.path!==`${ownerId}/${attemptId}/route-time-v1.json`)fail();hash(v.sha256);int(v.byte_length,1,raceLimits.evidenceBytes);int(v.first_sequence,0,Number.MAX_SAFE_INTEGER);int(v.last_sequence,0,Number.MAX_SAFE_INTEGER);int(v.sample_count,4,8000);if((v.last_sequence as number)-(v.first_sequence as number)+1!==v.sample_count)fail();utc(v.upload_deadline);return v;}
function vehicle(value:unknown){const v=obj(value,['local_id','catalog_id','category','brand','model','variant','year','powertrain','engine_cc','motor_kw']);nullable(v.local_id,x=>text(x,100));nullable(v.catalog_id,x=>text(x,120));choice(v.category,category);text(v.brand,80);text(v.model,120);nullable(v.variant,x=>text(x,120));nullable(v.year,x=>text(x,20));choice(v.powertrain,['petrol','diesel','hybrid','electric','unknown']);nullable(v.engine_cc,x=>num(x,0,30000));nullable(v.motor_kw,x=>num(x,0,5000));}
export function validateRaceAttempt(value:unknown,ownerId:string,expectedId?:string):T.AttemptSnapshot|null{if(value===null)return null;const v=obj(value,['id','owner_id','race_id','revision','ordinal','member_generation','approval_id','config_hash','platform','provider','ride_id','capture_id','state','armed_at','schedule_epoch','common_start_at','vehicle','evidence','rejection_code','terminal_reason','terminal_at','updated_at']);for(const k of ['id','owner_id','race_id','approval_id','ride_id','capture_id'])id(v[k]);if(v.owner_id!==ownerId||expectedId&&v.id!==expectedId)fail();int(v.revision,1);int(v.ordinal,1,3);int(v.member_generation,1);hash(v.config_hash);native(v.platform,v.provider);choice(v.state,['reserved','armed','upload_pending','queued','verifying','verified','rejected','aborted','dnf']);nullable(v.armed_at,utc);nullable(v.schedule_epoch,id);nullable(v.common_start_at,utc);if((v.schedule_epoch===null)!==(v.common_start_at===null))fail();nullable(v.vehicle,vehicle);nullable(v.evidence,x=>{if(reservation(x,ownerId,v.id as string).capture_id!==v.capture_id)fail();});nullable(v.rejection_code,x=>choice(x,evidence));nullable(v.terminal_reason,x=>choice(x,[...terminal,...abort]));nullable(v.terminal_at,utc);utc(v.updated_at);if(!['verified','rejected','aborted','dnf'].includes(v.state as string)&&(v.terminal_at!==null||v.terminal_reason!==null||v.rejection_code!==null))fail();return detached<T.AttemptSnapshot>(v);}
export function validateRaceAttemptPage(value:unknown,ownerId:string,raceId:string):T.RaceAttemptPage{const v=obj(value,['owner_id','race_id','items']);literal(v.owner_id,ownerId);literal(v.race_id,raceId);id(v.owner_id);id(v.race_id);const rows=arr(v.items,0,3).map(x=>validateRaceAttempt(x,ownerId));if(rows.some(x=>x===null||x.race_id!==raceId))fail();unique(rows,x=>id(obj(x).id));for(let i=1;i<rows.length;i++)if(rows[i-1]!.ordinal>=rows[i]!.ordinal)fail();return detached<T.RaceAttemptPage>(v);}
function result(value:unknown,ownerId:string,request:T.RaceRequest):T.RaceControlResult{
 const v=obj(value);if(v.action!==request.action)fail();
 if(['race_create','member_action','race_cancel'].includes(request.action)){obj(v,['action','race']);const race=validateRaceSnapshot(v.race,ownerId,(request as T.RaceCreate).race_id);if(!race)fail();if(request.action==='race_create'&&(race.creator_id!==ownerId||race.approval.id!==request.approval_id||race.approval.route_id!==request.route_id||race.approval.route_revision!==request.route_revision||race.mode!==request.mode||utcKey(race.starts_at)!==utcKey(request.starts_at)||utcKey(race.ends_at)!==utcKey(request.ends_at)))fail();}
 else if(['attempt_reserve','attempt_arm','attempt_abort','evidence_bind','evidence_queue'].includes(request.action)){obj(v,request.action==='evidence_bind'?['action','attempt','reservation']:['action','attempt']);const input=request as T.AttemptReserve|T.AttemptArm|T.AttemptAbort|T.EvidenceBind|T.EvidenceQueue,attempt=validateRaceAttempt(v.attempt,ownerId,input.attempt_id);if(!attempt)fail();if('capture_id'in input&&attempt.capture_id!==input.capture_id)fail();if(request.action==='attempt_reserve'&&(attempt.race_id!==request.race_id||attempt.ride_id!==request.ride_id||attempt.platform!==request.platform||attempt.provider!==request.provider))fail();if(request.action==='evidence_bind'){const b=reservation(v.reservation,ownerId,request.attempt_id);for(const k of ['capture_id','sha256','byte_length','first_sequence','last_sequence','sample_count'] as const)if(b[k]!==request[k])fail();if(canonicalRace(attempt.evidence)!==canonicalRace(b))fail();}if(request.action==='evidence_queue'&&attempt.evidence?.sha256!==request.sha256)fail();}
 else if(request.action==='race_ready'||request.action==='race_unready'){obj(v,['action','race_id','member_generation','ready_revision','ready_lease_id','ready_until','lobby_epoch','attempt_id']);id(v.race_id);id(v.lobby_epoch);int(v.member_generation,1);int(v.ready_revision);nullable(v.ready_lease_id,id);nullable(v.ready_until,utc);nullable(v.attempt_id,id);if(v.race_id!==request.race_id||v.member_generation!==request.expected_member_generation||(v.ready_lease_id===null)!==(v.ready_until===null)||(v.ready_lease_id===null)!==(v.attempt_id===null))fail();if(request.action==='race_ready'&&(v.attempt_id!==request.attempt_id||v.lobby_epoch!==request.lobby_epoch||v.ready_lease_id===null))fail();if(request.action==='race_unready'&&v.ready_lease_id!==null)fail();}
 else if(request.action==='race_schedule'){obj(v,['action','race','common_start_at','schedule_epoch','scheduled_members']);const race=validateRaceSnapshot(v.race,ownerId,request.race_id);utc(v.common_start_at);id(v.schedule_epoch);if(!race||race.creator_id!==ownerId||race.common_start_at!==v.common_start_at||race.schedule_epoch!==v.schedule_epoch||race.lobby_epoch!==request.lobby_epoch)fail();const rows=arr(v.scheduled_members,2,4);unique(rows,x=>id(readyBinding(x).user_id));if(canonicalRace(rows)!==canonicalRace(request.ready))fail();}
 else fail();return detached<T.RaceControlResult>(v);
}
export function validateRaceReceipt(value:unknown,ownerId:string,expected?:T.RaceOperation):T.RaceReceipt{const v=obj(value,['owner_id','operation_id','request','applied_at','result']);id(v.owner_id);id(v.operation_id);if(v.owner_id!==ownerId)fail();const r=request(v.request);if(expected&&(v.operation_id!==expected.operation_id||canonicalRace(r)!==canonicalRace(expected.request)))fail();utc(v.applied_at);result(v.result,ownerId,r);return detached<T.RaceReceipt>(v);}
export function validateRaceMutation(value:unknown,ownerId:string,op:T.RaceOperation):T.RaceMutation{return validateRaceError(value)??validateRaceReceipt(value,ownerId,op);}
export function validateRaceOperation(value:unknown,ownerId:string,operationId:string):T.RaceReceipt|null{if(value===null)return null;const receipt=validateRaceReceipt(value,ownerId);if(receipt.operation_id!==operationId)fail();return receipt;}
export function isRaceActivation(request:T.RaceRequest):request is T.RaceActivation{return ['attempt_arm','race_ready','race_schedule'].includes(request.action);}
export function validateRaceCancellation(value:unknown,ownerId:string,op:T.RaceOperation):T.RaceCancellationMutation{if(!isRaceActivation(op.request))fail();const error=validateRaceError(value);if(error)return error;const v=obj(value);if('result'in v)return validateRaceReceipt(v,ownerId,op);obj(v,['kind','owner_id','operation_id','request','cancelled_at']);literal(v.kind,'cancelled');id(v.owner_id);id(v.operation_id);if(v.owner_id!==ownerId||v.operation_id!==op.operation_id||canonicalRace(request(v.request))!==canonicalRace(op.request))fail();utc(v.cancelled_at);return detached<T.RaceActivationCancellation>(v);}
export function validateRaceCursor(value:unknown):T.RaceCursor|null{if(value===null)return null;const v=obj(value,['before','before_id']);utc(v.before);id(v.before_id);return detached<T.RaceCursor>(v);}
export function validateRacePage(value:unknown,ownerId:string):T.RacePage{const v=obj(value,['owner_id','server_now','items','next_cursor']);literal(v.owner_id,ownerId);utc(v.server_now);const rows=arr(v.items,0,30).map(x=>validateRaceSnapshot(x,ownerId));if(rows.some(x=>x===null))fail();unique(rows,x=>id(obj(x).id));for(let i=1;i<rows.length;i++){const prev=rows[i-1]!,next=rows[i]!,a=utcKey(prev.updated_at),b=utcKey(next.updated_at);if(a<b||a===b&&prev.id<=next.id)fail();}const c=validateRaceCursor(v.next_cursor);if(c&&(!rows.length||c.before!==rows.at(-1)!.updated_at||c.before_id!==rows.at(-1)!.id))fail();return detached<T.RacePage>(v);}
export function validateApprovalPage(value:unknown,ownerId:string,routeId:string,revision:number):T.ApprovalPage{const v=obj(value,['owner_id','server_now','items']);literal(v.owner_id,ownerId);utc(v.server_now);const rows=arr(v.items,0,20).map(approval);unique(rows,x=>id(obj(x).id));if(rows.some(x=>x.route_id!==routeId||x.route_revision!==revision))fail();return detached<T.ApprovalPage>(v);}
export function validateRaceClockProbe(value:unknown,ownerId:string,binding:T.RaceClockBinding):T.RaceClockProbe{const v=obj(value,['owner_id','probe_id','race_id','capture_id','clock_generation','server_received_at','server_sent_at']);literal(v.owner_id,ownerId);for(const k of ['probe_id','race_id','capture_id','clock_generation'] as const){id(v[k]);literal(v[k],binding[k]);}utc(v.server_received_at);utc(v.server_sent_at);if(parseRaceClockInstant(v.server_received_at)!>parseRaceClockInstant(v.server_sent_at)!)fail();return detached<T.RaceClockProbe>(v);}
export function freezeRaceStage(value:unknown):T.StageSample{try{const v=obj(value,['schema_version','race_id','member_generation','attempt_id','capture_id','lobby_epoch','sequence','platform','provider','timestamp_ms','received_wall_ms','received_monotonic_ms','latitude','longitude','horizontal_accuracy_m','is_simulated_by_software','is_produced_by_accessory','mocked']);literal(v.schema_version,1);for(const k of ['race_id','attempt_id','capture_id','lobby_epoch'])id(v[k]);int(v.member_generation,1);int(v.sequence,0,Number.MAX_SAFE_INTEGER);native(v.platform,v.provider);num(v.timestamp_ms);num(v.received_wall_ms);num(v.received_monotonic_ms);num(v.latitude,-80,80);num(v.longitude,-180,180);if(num(v.horizontal_accuracy_m,0,15)===0)fail();for(const k of ['is_simulated_by_software','is_produced_by_accessory','mocked']){nullable(v[k],boolean);if(v[k]===true&&k!=='is_produced_by_accessory')fail();}const age=(v.received_wall_ms as number)-(v.timestamp_ms as number);if(age< -500||age>3000)fail();return detached<T.StageSample>(v);}catch{throw Error('RACE_INVALID');}}
export function validateRaceStageProof(value:unknown,ownerId:string,sample:T.StageSample):T.StageProof{const v=obj(value,['owner_id','race_id','attempt_id','capture_id','lobby_epoch','member_generation','sequence','proof_id','received_at','expires_at']);literal(v.owner_id,ownerId);for(const k of ['race_id','attempt_id','capture_id','lobby_epoch','member_generation','sequence'] as const)literal(v[k],sample[k]);id(v.proof_id);window(v.received_at,v.expires_at,3000);return detached<T.StageProof>(v);}
export function validateRaceHeartbeat(value:unknown,ownerId:string,input:T.RaceHeartbeatInput):T.RaceHeartbeat{const v=obj(value,['owner_id','race_id','member_generation','server_received_at','server_sent_at','host_lease_until','ready_revision','ready_lease_id','ready_until']);literal(v.owner_id,ownerId);literal(v.race_id,input.race_id);literal(v.member_generation,input.member_generation);utc(v.server_received_at);utc(v.server_sent_at);if(parseRaceClockInstant(v.server_received_at)!>parseRaceClockInstant(v.server_sent_at)!)fail();nullable(v.host_lease_until,utc);int(v.ready_revision);nullable(v.ready_lease_id,id);nullable(v.ready_until,utc);if((v.ready_lease_id===null)!==(v.ready_until===null)||input.ready_lease_id!==null&&v.ready_lease_id!==input.ready_lease_id)fail();return detached<T.RaceHeartbeat>(v);}
export function freezeRaceClockBinding(value:unknown):T.RaceClockBinding{try{const v=obj(value,['probe_id','race_id','capture_id','clock_generation']);for(const k of Object.keys(v))id(v[k]);return detached<T.RaceClockBinding>(v);}catch{throw Error('RACE_INVALID');}}
export function freezeRaceHeartbeat(value:unknown):T.RaceHeartbeatInput{try{const v=obj(value,['race_id','member_generation','ready_lease_id','attempt_id','stage_proof_id','clock_probe_ids']);id(v.race_id);int(v.member_generation,1);for(const k of ['ready_lease_id','attempt_id','stage_proof_id'])nullable(v[k],id);nullable(v.clock_probe_ids,probes);const ready=v.ready_lease_id!==null;if(['attempt_id','stage_proof_id','clock_probe_ids'].some(k=>(v[k]!==null)!==ready))fail();return detached<T.RaceHeartbeatInput>(v);}catch{throw Error('RACE_INVALID');}}
function coordinate(value:unknown):T.RaceCoordinate{const v=obj(value,['latitude','longitude']);num(v.latitude,-80,80);num(v.longitude,-180,180);return v as T.RaceCoordinate;}
function chord(a:T.RaceCoordinate,b:T.RaceCoordinate){const e2=(1/298.257223563)*(2-1/298.257223563),ecef=(p:T.RaceCoordinate)=>{const lat=p.latitude*Math.PI/180,lon=p.longitude*Math.PI/180,n=6378137/Math.sqrt(1-e2*Math.sin(lat)**2);return[n*Math.cos(lat)*Math.cos(lon),n*Math.cos(lat)*Math.sin(lon),n*(1-e2)*Math.sin(lat)];},x=ecef(a),y=ecef(b);return Math.hypot(...x.map((v,i)=>v-y[i]));}
const constants={schema_version:1,method:'route_time_v1',projection:'wgs84_ecef_enu_v1',geometry_error_margin_m:0.25,maximum_accuracy_m:15,maximum_gap_ms:1500,maximum_crossing_span_ms:3000,maximum_duration_ms:1800000,minimum_duration_ms:10000,maximum_acceleration_mps2:15,maximum_backtrack_m:5,whole_capture_residual_ms:250,server_time_drift_allowance_ms:250,live_start_gate_window_ms:10000};
export function validateRaceCourse(value:unknown,raceId:string):T.RaceCourseSnapshot{const v=obj(value,['race_id','approval_id','config_hash','route_geometry_hash','configuration']);literal(id(v.race_id),raceId);id(v.approval_id);hash(v.config_hash);hash(v.route_geometry_hash);const c=obj(v.configuration,[...Object.keys(constants),'origin','route_geometry','boundary_polygon','staging_polygon','gates','corridor_half_width_m','maximum_speed_mps']);if(bytes(c)>131072)fail();for(const [key,wanted] of Object.entries(constants))literal(c[key],wanted);const origin=coordinate(c.origin),route=arr(c.route_geometry,2,512).map(coordinate),boundary=arr(c.boundary_polygon,3,128).map(coordinate),staging=arr(c.staging_polygon,3,32).map(coordinate);if(canonicalRace(origin)!==canonicalRace(route[0]))fail();num(c.corridor_half_width_m,10,30);if(num(c.maximum_speed_mps,0,138.888889)===0)fail();const gates=arr(c.gates,2,16).map((x,index,list)=>{const g=obj(x,['index','kind','a','b','forward_point','progress_min_m','progress_max_m']);literal(g.index,index);literal(g.kind,index===0?'start':index===list.length-1?'finish':'checkpoint');const a=coordinate(g.a),b=coordinate(g.b),forward=coordinate(g.forward_point);if(canonicalRace(a)===canonicalRace(b)||canonicalRace(a)===canonicalRace(forward)||canonicalRace(b)===canonicalRace(forward))fail();num(g.progress_min_m,0,15000);num(g.progress_max_m,0,15000);if((g.progress_min_m as number)>=(g.progress_max_m as number))fail();return {g,a,b,forward};});for(let i=1;i<gates.length;i++)if((gates[i].g.progress_min_m as number)<=(gates[i-1].g.progress_max_m as number))fail();const points=[...route,...boundary,...staging,...gates.flatMap(g=>[g.a,g.b,g.forward])];for(const p of points){if(Math.abs(p.longitude-origin.longitude)>180)fail();if(chord(origin,p)>15000.25)fail();}return detached<T.RaceCourseSnapshot>(v);}
function interval(value:unknown,withIndex=false){const v=obj(value,withIndex?['index','lower_ms','upper_ms']:['lower_ms','upper_ms']);num(v.lower_ms);num(v.upper_ms);if((v.lower_ms as number)>(v.upper_ms as number))fail();if(withIndex)int(v.index,0,15);return v;}
export function validateRaceResults(value:unknown,ownerId:string,raceId:string):T.RaceResults{const v=obj(value,['owner_id','race_id','server_now','items','statuses']);literal(v.owner_id,ownerId);literal(id(v.race_id),raceId);utc(v.server_now);const rows=arr(v.items,0,12);unique(rows,x=>id(obj(x).attempt_id));for(const row of rows){const r=obj(row,['attempt_id','owner_id','race_id','approval_id','config_hash','method','quality','platform','provenance_unknown','elapsed_lower_ms','elapsed_upper_ms','start_interval','finish_interval','gate_intervals','distance_m','maximum_speed_mps','average_speed_mps','sample_count','max_gap_ms','evidence_sha256','verified_at']);for(const k of ['attempt_id','owner_id','approval_id'])id(r[k]);literal(r.race_id,raceId);hash(r.config_hash);hash(r.evidence_sha256);literal(r.method,'route_time_v1');literal(r.quality,'native_evidence_consistency');choice(r.platform,['ios','android']);boolean(r.provenance_unknown);num(r.elapsed_lower_ms,10000,1800000);num(r.elapsed_upper_ms,10000,1800000);if((r.elapsed_lower_ms as number)>(r.elapsed_upper_ms as number))fail();const start=interval(r.start_interval),finish=interval(r.finish_interval),gates=arr(r.gate_intervals,2,16).map(x=>interval(x,true));for(let i=0;i<gates.length;i++){literal(gates[i].index,i);if(i>0&&(gates[i-1].upper_ms as number)>(gates[i].lower_ms as number))fail();}if(canonicalRace({lower_ms:gates[0].lower_ms,upper_ms:gates[0].upper_ms})!==canonicalRace(start)||canonicalRace({lower_ms:gates.at(-1)!.lower_ms,upper_ms:gates.at(-1)!.upper_ms})!==canonicalRace(finish))fail();num(r.distance_m,100,20000);nullable(r.maximum_speed_mps,x=>num(x,0,138.888889));num(r.average_speed_mps,0,138.888889);int(r.sample_count,4,8000);num(r.max_gap_ms,0,1500);utc(r.verified_at);}const statuses=arr(v.statuses,1,4);unique(statuses,x=>id(obj(x).user_id));for(const row of statuses){const s=obj(row,['user_id','state','terminal_reason']);id(s.user_id);choice(s.state,['not_started','in_progress','processing','verified','rejected','dnf']);nullable(s.terminal_reason,x=>choice(x,[...terminal,...abort]));if(!['rejected','dnf'].includes(s.state as string)&&s.terminal_reason!==null)fail();}if(rows.some(row=>!statuses.some(s=>obj(s).user_id===obj(row).owner_id)))fail();return detached<T.RaceResults>(v);}
