import type {OriginalCaptureBinding,OriginalCaptureEvent,OriginalCapturePort,OriginalCaptureReceipt} from './OriginalCaptureBus';
import {CompetitiveRaceClock,armRaceSchedule,raceScheduleDecision,type RaceArmTicket,type RaceClockEstimate} from './raceClock';
import {RaceGatePreview,type RaceGateCrossing} from './gatePreview';
import {freezeRaceOperation,freezeRaceStage,validateRaceReceipt} from './model';
import type {AttemptAbort,AttemptSnapshot,RaceClockBinding,RaceClockProbe,RaceCourseSnapshot,RaceErrorEnvelope,RaceHeartbeat,RaceHeartbeatInput,RaceMode,RaceReceipt,RaceRequest,RaceSnapshot,StageProof,StageSample} from './types';
export type AttemptClockReference=Readonly<{probe_id:string;clock_generation:string;request_started_monotonic_ms:number;request_started_wall_ms:number;received_monotonic_ms:number;received_wall_ms:number}>;
export type AttemptLifecycle=Readonly<{kind:'armed'|'finish_observed';received_monotonic_ms:number;received_wall_ms:number}>;
export type RaceAttemptContext={race:RaceSnapshot;attempt:AttemptSnapshot;course:RaceCourseSnapshot;binding:OriginalCaptureBinding;foreground:boolean;fresh:boolean};
export type FrozenRaceCandidate=Readonly<{binding:OriginalCaptureBinding;firstSequence:number;lastSequence:number;sampleCount:number;clockGeneration:string;armClockProbeIds:readonly string[];clockProbes:readonly AttemptClockReference[];lifecycle:readonly AttemptLifecycle[];race:RaceSnapshot;attempt:AttemptSnapshot}>;
export type RaceAttemptPhase='idle'|'preparing'|'pending'|'armed'|'ready'|'countdown'|'running'|'candidate'|'invalid';
export type RaceAttemptPresentation=Readonly<{phase:RaceAttemptPhase;error:string|null;pendingOperationId:string|null;firstSequence:number|null;lastSequence:number|null;sampleCount:number;nextGate:number;stageReady:boolean;clockReady:boolean;probeCount:number;secondsRemaining:number|null;uncertaintyMs:number|null;retryAfterMs:number|null;observedMonotonicMs:number|null}>;
export interface RaceAttemptPort{
 ownerId:string;current:(binding:OriginalCaptureBinding)=>boolean;getCurrent:()=>RaceAttemptContext|null;originalCapture:OriginalCapturePort;
 monotonicNow:()=>number;wallNow:()=>number;uuid:()=>string;
 probe:(binding:RaceClockBinding)=>Promise<RaceClockProbe|RaceErrorEnvelope>;
 stage:(sample:StageSample)=>Promise<StageProof|RaceErrorEnvelope>;
 heartbeat:(input:RaceHeartbeatInput)=>Promise<RaceHeartbeat|RaceErrorEnvelope>;
 enqueue:(request:RaceRequest)=>Promise<string|null>;receipt:(operationId:string)=>RaceReceipt|null;
 cancelActivation:(operationId:string)=>Promise<boolean>;abort:(reason:AttemptAbort['reason'],binding:OriginalCaptureBinding)=>Promise<void>;
 onFrozenCandidate:(candidate:FrozenRaceCandidate)=>Promise<void>;
}
const initial=():RaceAttemptPresentation=>({phase:'idle',error:null,pendingOperationId:null,firstSequence:null,lastSequence:null,sampleCount:0,nextGate:0,stageReady:false,clockReady:false,probeCount:0,secondsRemaining:null,uncertaintyMs:null,retryAfterMs:null,observedMonotonicMs:null});
type Pending={request:RaceRequest;id:string|null;generation:number};
const frozenCopy=<T>(value:T):T=>{const copy=JSON.parse(JSON.stringify(value));const freeze=(v:unknown)=>{if(v&&typeof v==='object'){for(const child of Object.values(v))freeze(child);Object.freeze(v);}};freeze(copy);return copy;};
/** A passive original-receipt consumer. No watcher, private GPS store, verification
 * claim, autonomous schedule or background network timer is created here. */
export class RaceAttemptCoordinator{
 private state=initial();private listeners=new Set<()=>void>();private unsubscribe:()=>void;
 private generation=0;private closed=false;private clock=new CompetitiveRaceClock();private binding:OriginalCaptureBinding|null=null;private attemptId:string|null=null;private context:RaceAttemptContext|null=null;
 private latest:OriginalCaptureReceipt|null=null;private pending:Pending|null=null;private clockGeneration:string|null=null;private references:AttemptClockReference[]=[];private issued=0;private armIds:string[]=[];private sealed:RaceClockEstimate|null=null;
 private armed:AttemptLifecycle|null=null;private finish:AttemptLifecycle|null=null;private preview:RaceGatePreview|null=null;private expectedFirst:number|null=null;private first:number|null=null;private last:number|null=null;private count=0;private previous:OriginalCaptureReceipt|null=null;private start:RaceGateCrossing|null=null;
 private ticket:RaceArmTicket|null=null;private epoch:string|null=null;private readyLease:{id:string;revision:number;until:string}|null=null;private hostUntil:string|null=null;private due=false;private begun=false;private lastMono=0;private retryAt=0;private lastStage=-Infinity;private lastProbe=-Infinity;private lastHeartbeat=-Infinity;private ticking=false;private candidate:FrozenRaceCandidate|null=null;private saving:Promise<void>|null=null;private cancelled=new Set<string>();
 constructor(private port:RaceAttemptPort){this.unsubscribe=port.originalCapture.subscribe(event=>this.accept(event));}
 getSnapshot=()=>this.state;
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};
 private publish(patch:Partial<RaceAttemptPresentation>){
  if(this.closed||Object.entries(patch).every(([key,value])=>Object.is(this.state[key as keyof RaceAttemptPresentation],value)))return;
  const phase=patch.phase??this.state.phase;
  const changed=phase!==this.state.phase||patch.secondsRemaining!==undefined&&patch.secondsRemaining!==this.state.secondsRemaining;
  let observedMonotonicMs=this.state.observedMonotonicMs;
  if(changed){const now=this.port.monotonicNow();observedMonotonicMs=['countdown','running'].includes(phase)&&Number.isFinite(now)&&now>=0?now:null;}
  // The source bin's age must survive held renders; unrelated/no-op ticks cannot refresh it.
  this.state=Object.freeze({...this.state,...patch,observedMonotonicMs});
  for(const listener of this.listeners){try{listener();}catch{/* Rendering cannot restore attempt authority. */}}
 }
 private times(){const mono=this.port.monotonicNow(),wall=this.port.wallNow();if(!Number.isFinite(mono)||mono<0||mono<this.lastMono||!Number.isFinite(wall)||wall<0)throw Error('RACE_CLOCK_UNAVAILABLE');this.lastMono=mono;return{mono,wall};}
 private valid(binding:OriginalCaptureBinding){return !this.closed&&binding.scope.userId===this.port.ownerId&&binding.platform!=='web'&&this.port.current(binding);}
 private same(a:OriginalCaptureBinding,b:OriginalCaptureBinding){return a.scope===b.scope&&a.generation===b.generation&&a.captureId===b.captureId&&a.rideId===b.rideId&&a.segmentId===b.segmentId&&a.startedMonotonicMs===b.startedMonotonicMs;}
 private read(fresh=true):RaceAttemptContext{const c=this.port.getCurrent();if(!c||!this.valid(c.binding)||!c.foreground||fresh&&!c.fresh||c.binding.startedMonotonicMs===null||c.attempt.owner_id!==this.port.ownerId||c.attempt.capture_id!==c.binding.captureId||c.attempt.ride_id!==c.binding.rideId||c.attempt.platform!==c.binding.platform||c.attempt.provider!==c.binding.provider||c.race.id!==c.attempt.race_id||c.race.self_member.user_id!==this.port.ownerId||c.race.self_member.state!=='accepted'||c.race.self_member.member_generation!==c.attempt.member_generation||c.course.race_id!==c.race.id||c.course.approval_id!==c.attempt.approval_id||c.course.config_hash!==c.attempt.config_hash||c.race.approval.config_hash!==c.attempt.config_hash)throw Error('RACE_CAPTURE_MISMATCH');if(c.race.mode==='live'&&(c.race.common_start_at!==null||c.race.schedule_epoch!==null)&&(c.attempt.common_start_at!==c.race.common_start_at||c.attempt.schedule_epoch!==c.race.schedule_epoch))throw Error('RACE_ATTEMPT_CHANGED');if(!['reserved','armed'].includes(c.attempt.state))throw Error('RACE_ATTEMPT_CHANGED');if(this.binding&&!this.same(c.binding,this.binding)||this.attemptId&&c.attempt.id!==this.attemptId)throw Error('RACE_CAPTURE_MISMATCH');if(['cancelled','finished','expired'].includes(c.race.state)&&!(this.begun&&c.race.terminal_reason==='host_expired'))throw Error('RACE_CHANGED');return c;}
 private guard(generation:number,fresh=true){if(generation!==this.generation)throw Error('RACE_CAPTURE_MISMATCH');return this.read(fresh);}
 private error(value:unknown){return value instanceof Error?value.message:'RACE_UNAVAILABLE';}
 private response<V>(value:V|RaceErrorEnvelope):V{if(value&&typeof value==='object'&&'error'in value){const error=(value as RaceErrorEnvelope).error;if(error.code==='RACE_RATE_LIMITED'){const {mono}=this.times();this.retryAt=mono+error.retry_after_ms;this.publish({retryAfterMs:error.retry_after_ms});}throw Error(error.code);}return value as V;}
 // Terminal callbacks own the initiating account fence. A recorder invalidation
 // has already cleared its active binding; that must not suppress its abort.
 private cancelPending(pending=this.pending){if(!pending?.id||this.cancelled.has(pending.id)||!this.binding)return;this.cancelled.add(pending.id);void this.port.cancelActivation(pending.id).catch(()=>{/* Durable control queue retains unresolved identity. */});}
 suspend(reason:AttemptAbort['reason']='background'){
  if(this.closed||this.state.phase==='idle'||this.state.phase==='candidate'||this.state.phase==='invalid')return;const b=this.binding,had=this.attemptId!==null;this.generation++;this.clock.invalidate('suspended',Math.max(this.lastMono,this.port.monotonicNow()));this.ticket=null;this.due=false;this.cancelPending();this.publish({phase:'invalid',clockReady:false,stageReady:false,error:reason==='clock_invalid'?'RACE_CLOCK_UNAVAILABLE':reason==='quality'?'RACE_STAGE_UNAVAILABLE':'RACE_CAPTURE_MISMATCH'});if(had&&b)void this.port.abort(reason,b).catch(()=>{/* Root persists/reconciles terminal intent. */});
 }
 close(){if(this.closed)return;this.suspend('capture_changed');this.closed=true;this.unsubscribe();this.listeners.clear();this.latest=null;}
 private quality(receipt:OriginalCaptureReceipt){const s=receipt.sample,age=receipt.receivedAtMs-s.timestampMs;return Number.isSafeInteger(receipt.seq)&&receipt.seq>=0&&receipt.receivedMonotonicMs!==null&&receipt.receivedMonotonicMs!==undefined&&Number.isFinite(receipt.receivedMonotonicMs)&&Number.isFinite(receipt.receivedAtMs)&&Number.isFinite(s.timestampMs)&&Number.isFinite(s.latitude)&&Math.abs(s.latitude)<=80&&Number.isFinite(s.longitude)&&Math.abs(s.longitude)<=180&&s.horizontalAccuracyM!==null&&Number.isFinite(s.horizontalAccuracyM)&&s.horizontalAccuracyM>0&&s.horizontalAccuracyM<=15&&s.mocked!==true&&s.isSimulatedBySoftware!==true&&age>=-500&&age<=3000;}
 private accept(event:OriginalCaptureEvent){if(this.closed)return;if(event.kind==='invalidated'){this.latest=null;this.suspend(event.reason==='background'?'background':event.reason==='storage_error'?'storage_error':event.reason==='stop'?'user_stop':'capture_changed');return;}if(event.kind==='active'){if(this.binding&&!this.same(this.binding,event.binding))this.suspend('capture_changed');return;}const r=event.receipt;if(!this.valid(event.binding))return;if(this.binding&&!this.same(this.binding,event.binding)){this.suspend('capture_changed');return;}if(!this.quality(r)){this.latest=null;if(this.armed||this.pending)this.suspend('quality');return;}this.latest=r;if(!this.armed||['invalid','candidate','idle','preparing'].includes(this.state.phase))return;
  try{const c=this.read(false),mono=r.receivedMonotonicMs!;if(mono<this.armed.received_monotonic_ms){if(this.first===null)this.expectedFirst=r.seq+1;return;}const now=this.times();if(mono>now.mono||this.first===null&&this.expectedFirst!==null&&r.seq!==this.expectedFirst)throw Error('RACE_STAGE_UNAVAILABLE');if(Math.abs((r.receivedAtMs-this.armed.received_wall_ms)-(mono-this.armed.received_monotonic_ms))>250)throw Error('RACE_CLOCK_UNAVAILABLE');if(this.previous&&(r.seq!==this.previous.seq+1||sGap(r,this.previous)>1500||sGap(r,this.previous)<=0||mono<this.previous.receivedMonotonicMs!))throw Error('RACE_STAGE_UNAVAILABLE');if(this.count>=8000)throw Error('RACE_TOO_LARGE');if(this.first===null)this.first=r.seq;this.last=r.seq;this.count++;this.previous=r;const g=this.preview!.accept({sequence:r.seq,latitude:r.sample.latitude,longitude:r.sample.longitude,accuracyM:r.sample.horizontalAccuracyM!,timestampMs:r.sample.timestampMs,receivedMonotonicMs:mono,receivedWallMs:r.receivedAtMs});this.publish({firstSequence:this.first,lastSequence:this.last,sampleCount:this.count,nextGate:g.nextGate});if(g.state==='invalid')throw Error('RACE_STAGE_UNAVAILABLE');if(g.crossing?.kind==='start'){if(c.race.mode==='live'){if(!this.epoch||!this.begun)throw Error('RACE_TOO_LATE');const before=this.serverInterval(g.crossing.before),after=this.serverInterval(g.crossing.after);const e=Date.parse(this.epoch);if(before.lower<e||after.upper>e+10000)throw Error('RACE_TOO_LATE');}this.start=g.crossing;}if(g.state==='finish')this.freezeCandidate(c);}
  catch(error){this.suspend(this.error(error)==='RACE_CLOCK_UNAVAILABLE'?'clock_invalid':'quality');this.publish({error:this.error(error)});}
 }
 private serverInterval(fix:RaceGateCrossing['before']){if(!this.sealed||fix.receivedMonotonicMs===undefined||fix.receivedWallMs===undefined)throw Error('RACE_CLOCK_UNAVAILABLE');const delta=fix.receivedMonotonicMs-this.sealed.observedMono,age=fix.receivedWallMs-fix.timestampMs;return{lower:this.sealed.lowerServerMs!+delta-age-250,upper:this.sealed.upperServerMs!+delta-age+250};}
 private async collect(generation:number){const c=this.guard(generation),{mono:started,wall:startedWall}=this.times();if(this.issued>=24)throw Error('RACE_CLOCK_UNAVAILABLE');if(started<this.retryAt)throw Error('RACE_RATE_LIMITED');const ticket=this.clock.beginProbe(started);if(!ticket)throw Error('RACE_CLOCK_UNAVAILABLE');const binding:RaceClockBinding={probe_id:this.port.uuid(),race_id:c.race.id,capture_id:c.binding.captureId,clock_generation:this.clockGeneration!};this.issued++;this.lastProbe=started;this.publish({probeCount:this.issued});const value=this.response(await this.port.probe(binding));this.guard(generation);const {mono:received,wall:receivedWall}=this.times();if(value.owner_id!==this.port.ownerId||value.probe_id!==binding.probe_id||value.race_id!==binding.race_id||value.capture_id!==binding.capture_id||value.clock_generation!==binding.clock_generation)throw Error('RACE_INVALID_RESPONSE');if(Math.abs((receivedWall-startedWall)-(received-started))>250)throw Error('RACE_CLOCK_UNAVAILABLE');const observation=this.clock.observe(ticket,{serverNow:value.server_sent_at,requestStartedMono:started,receivedMono:received});if(!observation.accepted)throw Error('RACE_CLOCK_UNAVAILABLE');this.references.push(Object.freeze({probe_id:binding.probe_id,clock_generation:binding.clock_generation,request_started_monotonic_ms:started,request_started_wall_ms:startedWall,received_monotonic_ms:received,received_wall_ms:receivedWall}));this.publish({clockReady:observation.canArm,uncertaintyMs:observation.halfWidthMs});}
 private recent(){const {mono}=this.times();return this.references.filter(p=>mono-p.request_started_monotonic_ms<5000).slice(-5).map(p=>p.probe_id);}
 private async burst(generation:number){while(this.recent().length<3){await this.collect(generation);}const estimate=this.clock.read(this.times().mono);if(!estimate.canArm)throw Error('RACE_CLOCK_UNAVAILABLE');return estimate;}
 private async stage(generation:number){const c=this.guard(generation),{mono}=this.times(),r=this.latest;if(!r||!this.quality(r)||mono-r.receivedMonotonicMs!>=3000||mono<r.receivedMonotonicMs!)throw Error('RACE_STAGE_UNAVAILABLE');if(mono-this.lastStage<1000)throw Error('RACE_STAGE_UNAVAILABLE');this.lastStage=mono;const sample=freezeRaceStage({schema_version:1,race_id:c.race.id,member_generation:c.attempt.member_generation,attempt_id:c.attempt.id,capture_id:c.binding.captureId,lobby_epoch:c.race.lobby_epoch,sequence:r.seq,platform:c.binding.platform,provider:c.binding.provider,timestamp_ms:r.sample.timestampMs,received_wall_ms:r.receivedAtMs,received_monotonic_ms:r.receivedMonotonicMs!,latitude:r.sample.latitude,longitude:r.sample.longitude,horizontal_accuracy_m:r.sample.horizontalAccuracyM!,is_simulated_by_software:r.sample.isSimulatedBySoftware??null,is_produced_by_accessory:r.sample.isProducedByAccessory??null,mocked:r.sample.mocked??null});const proof=this.response(await this.port.stage(sample));this.guard(generation);const estimate=this.clock.read(this.times().mono);if(!estimate.canArm||this.times().mono-mono>=3000||estimate.upperServerMs!>=Date.parse(proof.expires_at))throw Error('RACE_STAGE_UNAVAILABLE');if(proof.owner_id!==this.port.ownerId||proof.race_id!==c.race.id||proof.attempt_id!==c.attempt.id||proof.capture_id!==c.binding.captureId||proof.lobby_epoch!==c.race.lobby_epoch||proof.sequence!==r.seq)throw Error('RACE_INVALID_RESPONSE');this.publish({stageReady:true});return proof;}
 async prepare(mode:RaceMode):Promise<string|null>{let pending:Pending|null=null;try{if(this.closed||this.state.phase!=='idle')throw Error('RACE_ATTEMPT_CHANGED');const c=this.read();if(c.race.mode!==mode||c.attempt.state!=='reserved')throw Error('RACE_ATTEMPT_CHANGED');this.binding=c.binding;this.attemptId=c.attempt.id;this.context=c;this.clockGeneration=this.port.uuid();const {mono}=this.times();this.clock.reset(mono);const generation=++this.generation;this.publish({phase:'preparing',error:null});await this.burst(generation);const proof=await this.stage(generation),fresh=this.guard(generation);const request:RaceRequest={schema_version:1,action:'attempt_arm',attempt_id:fresh.attempt.id,expected_revision:fresh.attempt.revision,stage_proof_id:proof.proof_id,capture_id:fresh.binding.captureId,clock_probe_ids:this.recent()};pending={request,id:null,generation};this.pending=pending;this.publish({phase:'pending'});const id=await this.port.enqueue(request);pending.id=id;if(!id)throw Error('RACE_UNAVAILABLE');this.publish({pendingOperationId:id});if(generation!==this.generation){this.cancelPending(pending);return id;}const receipt=this.port.receipt(id);if(receipt)this.acceptReceipt(receipt);return id;}catch(error){if(this.state.phase!=='invalid'){this.suspend(this.error(error)==='RACE_CLOCK_UNAVAILABLE'?'clock_invalid':'capture_changed');this.publish({error:this.error(error)});}if(pending)this.cancelPending(pending);return null;}}
 acceptReceipt(value:RaceReceipt){const pending=this.pending;if(!pending?.id||value.operation_id!==pending.id)return;try{const receipt=validateRaceReceipt(value,this.port.ownerId,freezeRaceOperation({operation_id:pending.id,request:pending.request}));const c=this.guard(pending.generation);const {mono,wall}=this.times(),estimate=this.clock.read(mono);if(!estimate.canArm)throw Error('RACE_CLOCK_UNAVAILABLE');if(receipt.result.action==='attempt_arm'){if(c.attempt.state!=='armed'||receipt.result.attempt.id!==c.attempt.id)throw Error('RACE_ATTEMPT_CHANGED');this.armIds=[...(pending.request as {clock_probe_ids:string[]}).clock_probe_ids];this.armed=Object.freeze({kind:'armed',received_monotonic_ms:mono,received_wall_ms:wall});this.expectedFirst=this.latest?this.latest.seq+1:null;this.sealed=estimate;this.preview=new RaceGatePreview(c.course.configuration);this.context=c;this.pending=null;this.publish({phase:'armed',pendingOperationId:null,clockReady:true});}else if(receipt.result.action==='race_ready'){if(!this.armed||!c.race.self_ready||c.race.self_ready.lease_id!==receipt.result.ready_lease_id)throw Error('RACE_READY_CHANGED');this.pending=null;this.lastHeartbeat=mono;this.readyLease={id:receipt.result.ready_lease_id!,revision:receipt.result.ready_revision,until:receipt.result.ready_until!};this.hostUntil=c.race.host_lease_until;this.publish({phase:'ready',pendingOperationId:null,error:null});this.reconcile();}}catch(error){this.suspend(this.error(error)==='RACE_CLOCK_UNAVAILABLE'?'clock_invalid':'capture_changed');this.publish({error:this.error(error)});this.cancelPending(pending);}}
 async ready():Promise<string|null>{try{if(this.state.phase!=='armed'||!this.armed)throw Error('RACE_ATTEMPT_CHANGED');const generation=this.generation,c=this.read();if(c.race.mode!=='live'||c.race.state!=='lobby'||c.attempt.state!=='armed')throw Error('RACE_CHANGED');await this.burst(generation);const proof=await this.stage(generation),fresh=this.guard(generation),request:RaceRequest={schema_version:1,action:'race_ready',race_id:fresh.race.id,expected_revision:fresh.race.revision,expected_member_generation:fresh.attempt.member_generation,expected_ready_revision:fresh.race.self_member.ready_revision,lobby_epoch:fresh.race.lobby_epoch,attempt_id:fresh.attempt.id,capture_id:fresh.binding.captureId,stage_proof_id:proof.proof_id,clock_probe_ids:this.recent()};const pending={request,id:null as string|null,generation};this.pending=pending;this.publish({phase:'pending'});const id=await this.port.enqueue(request);pending.id=id;if(!id)throw Error('RACE_UNAVAILABLE');this.publish({pendingOperationId:id});if(generation!==this.generation){this.cancelPending(pending);return id;}const receipt=this.port.receipt(id);if(receipt)this.acceptReceipt(receipt);return id;}catch(error){this.suspend('clock_invalid');this.publish({error:this.error(error)});return null;}}
 reconcile(){if(this.closed||!this.armed||['invalid','candidate'].includes(this.state.phase))return;try{const c=this.read(!this.begun);if(c.race.mode!=='live')return;if(c.race.common_start_at!==null){if(this.epoch&&this.epoch!==c.race.common_start_at)throw Error('RACE_CHANGED');if(!this.ticket){const estimate=this.clock.read(this.times().mono),ticket=armRaceSchedule(estimate,c.race.common_start_at);if(!ticket)throw Error('RACE_TOO_LATE');this.ticket=ticket;this.epoch=c.race.common_start_at;this.publish({phase:'countdown'});}}else if(this.epoch)throw Error('RACE_CHANGED');}catch(error){this.suspend('clock_invalid');this.publish({error:this.error(error)});}}
 tick(){if(this.closed||['idle','invalid','candidate','preparing','pending'].includes(this.state.phase))return;try{this.reconcile();if(this.state.phase==='invalid')return;const c=this.read(!this.begun),{mono}=this.times();if(this.armed&&mono-this.armed.received_monotonic_ms>1800000)throw Error('RACE_TOO_LATE');if(c.race.mode!=='live'||this.begun)return;const estimate=this.clock.read(mono);if(!estimate.canArm)throw Error('RACE_CLOCK_UNAVAILABLE');if(this.readyLease&&(!c.race.self_ready||c.race.self_ready.lease_id!==this.readyLease.id||c.race.self_ready.revision!==this.readyLease.revision||estimate.upperServerMs!>=Date.parse(this.readyLease.until)))throw Error('RACE_READY_CHANGED');const hostUntil=c.race.creator_id===this.port.ownerId?(this.hostUntil??c.race.host_lease_until):c.race.host_lease_until;if(['ready','countdown'].includes(this.state.phase)&&(!hostUntil||estimate.upperServerMs!>=Date.parse(hostUntil)))throw Error('RACE_CHANGED');if(this.ticket){const d=raceScheduleDecision(estimate,this.epoch!,this.ticket);this.publish({secondsRemaining:d.displayRemainingMs===null?null:Math.max(0,Math.ceil(d.displayRemainingMs/1000)),uncertaintyMs:estimate.halfWidthMs});if(d.state==='due'){this.due=true;this.begun=true;this.publish({phase:'running'});}else if(['missed','invalidated','unarmed','uncertain'].includes(d.state))throw Error('RACE_TOO_LATE');}if(!this.begun&&['ready','countdown'].includes(this.state.phase)&&!this.ticking){this.ticking=true;void this.renew(c,this.generation).catch(error=>{if(this.begun)return;this.suspend('clock_invalid');this.publish({error:this.error(error)});}).finally(()=>{this.ticking=false;});}}catch(error){this.suspend('clock_invalid');this.publish({error:this.error(error)});}}
 private async renew(context:RaceAttemptContext,generation:number){const {mono}=this.times();if(mono-this.lastProbe>=1000)await this.collect(generation);if(this.begun)return;if(mono-this.lastHeartbeat<3000)return;const proof=await this.stage(generation),c=this.guard(generation),ready=c.race.self_ready;if(!ready||c.race.lobby_epoch!==context.race.lobby_epoch)throw Error('RACE_READY_CHANGED');this.lastHeartbeat=this.times().mono;const result=this.response(await this.port.heartbeat({race_id:c.race.id,member_generation:c.attempt.member_generation,ready_lease_id:ready.lease_id,attempt_id:c.attempt.id,stage_proof_id:proof.proof_id,clock_probe_ids:this.recent()}));this.guard(generation);if(result.ready_lease_id!==ready.lease_id||result.ready_revision!==ready.revision||result.ready_until===null)throw Error('RACE_READY_CHANGED');this.readyLease={id:result.ready_lease_id,revision:result.ready_revision,until:result.ready_until};if(result.host_lease_until!==null&&c.race.creator_id===this.port.ownerId)this.hostUntil=result.host_lease_until;}
 private freezeCandidate(c:RaceAttemptContext){if(this.first===null||this.last===null||!this.armed||!this.start||!this.clockGeneration)throw Error('RACE_STAGE_UNAVAILABLE');const {mono,wall}=this.times();this.finish=Object.freeze({kind:'finish_observed',received_monotonic_ms:mono,received_wall_ms:wall});this.candidate=Object.freeze({binding:this.binding!,firstSequence:this.first,lastSequence:this.last,sampleCount:this.count,clockGeneration:this.clockGeneration,armClockProbeIds:Object.freeze([...this.armIds]),clockProbes:Object.freeze([...this.references]),lifecycle:Object.freeze([this.armed,this.finish]),race:frozenCopy(c.race),attempt:frozenCopy(c.attempt)});this.publish({phase:'candidate',error:null});void this.retryCandidate();}
 retryCandidate():Promise<void>{if(this.saving)return this.saving;const candidate=this.candidate;if(!candidate||this.closed||!this.valid(candidate.binding))return Promise.resolve();const generation=this.generation,task=Promise.resolve().then(async()=>{try{await this.port.onFrozenCandidate(candidate);if(!this.closed&&generation===this.generation&&this.valid(candidate.binding))this.publish({error:null});}catch(error){if(!this.closed&&generation===this.generation&&this.valid(candidate.binding))this.publish({error:this.error(error)});}});this.saving=task;void task.finally(()=>{if(this.saving===task)this.saving=null;});return task;}
}
function sGap(a:OriginalCaptureReceipt,b:OriginalCaptureReceipt){return a.sample.timestampMs-b.sample.timestampMs;}
