import {canonicalRace,freezeRaceOperation,freezeRaceRequest,isRaceActivation,parseRaceOperations,raceErrors,validateRaceCancellation,validateRaceMutation,validateRaceReceipt} from './model';
import type {RaceClientErrorCode,RaceControlPort,RaceCoordinatorSnapshot,RaceErrorCode,RaceOperation,RaceOwned,RaceRequest,StoredRaceOperation} from './types';
export type {RaceControlPort,RaceCoordinatorSnapshot,RaceOwned,RaceLatest,StoredRaceOperation} from './types';
const safe=new Set<string>([...raceErrors,'RACE_INVALID_RESPONSE','RACE_REVIEW_REQUIRED','ACCOUNT_CHANGED','LOCAL_READ_FAILED','LOCAL_WRITE_FAILED']);
function code(value:unknown):RaceErrorCode|RaceClientErrorCode{return value instanceof Error&&safe.has(value.message)?value.message as RaceErrorCode|RaceClientErrorCode:'RACE_UNAVAILABLE';}
const operation=(row:RaceOperation)=>freezeRaceOperation({operation_id:row.operation_id,request:row.request});
const identity=(row:RaceOperation)=>canonicalRace(operation(row));
/** One owner control lane keeps unknown arm/ready/schedule dependencies ordered.
 * GPS and runtime capture/clock/review authority never enter durable storage. */
export class RaceCoordinator{
 private state:RaceCoordinatorSnapshot={busy:false,pending:[],error:null,latest:null,reviewRequired:[],retryAfterMs:null};
 private listeners=new Set<()=>void>();private reviewed=new Set<string>();private unattempted=new Set<string>();
 private writes=Promise.resolve();private running:Promise<void>|null=null;private again=false;private closed=false;
 private cancelling=new Set<string>();private cancellations=new Map<string,Promise<boolean>>();private settled=new Map<string,string>();private settlements=new Map<string,Promise<void>>();
 private lastMono=0;private retryAt=0;
 constructor(private port:RaceControlPort){}
 getSnapshot=()=>this.state;
 subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};
 suspend(){this.reviewed.clear();this.unattempted.clear();try{this.publish({reviewRequired:this.reviewIds(this.rows())});}catch{/* An unread owner remains unread. */}}
 close(){this.closed=true;this.suspend();this.listeners.clear();}
 private guard(){if(this.closed||!this.port.current())throw Error('ACCOUNT_CHANGED');}
 private network(){this.guard();return this.port.eligible();}
 private rows(){this.guard();return parseRaceOperations(this.port.read().operations);}
 private remaining(){const now=this.port.monotonicNow();if(!Number.isFinite(now)||now<0)throw Error('RACE_CLOCK_UNAVAILABLE');this.lastMono=Math.max(this.lastMono,now);const wait=Math.max(0,Math.ceil(this.retryAt-this.lastMono));return wait||null;}
 private limited(delay:number){this.remaining();this.retryAt=Math.max(this.retryAt,this.lastMono+delay);this.publish({retryAfterMs:this.remaining()});}
 private reviewIds(rows:StoredRaceOperation[]){return rows.filter(row=>isRaceActivation(row.request)&&!this.reviewed.has(row.operation_id)).map(row=>row.operation_id);}
 private publish(patch:Partial<RaceCoordinatorSnapshot>){if(this.closed||!this.port.current())return;this.state={...this.state,...patch};for(const listener of this.listeners){try{listener();}catch{/* A UI subscriber cannot undo a durable receipt. */}}}
 private fail(error:unknown){try{this.guard();this.publish({error:code(error)});}catch{/* Owner closed. */}}
 private commit(reducer:(fresh:RaceOwned)=>RaceOwned){const task=this.writes.catch(()=>{}).then(async()=>{this.guard();this.rows();await this.port.update(fresh=>{this.guard();return reducer({operations:parseRaceOperations(fresh.operations)});});this.guard();await this.port.flush();this.guard();});this.writes=task.catch(()=>{});return task;}
 async enqueue(input:RaceRequest):Promise<string|null>{try{this.guard();const request=freezeRaceRequest(input);if(request.action!=='attempt_abort'&&!this.network())throw Error('RACE_AUTH_REQUIRED');const op=freezeRaceOperation({operation_id:this.port.operationId(),request}),row:StoredRaceOperation={...op,queued_at:this.port.nowISO(),last_error:null};parseRaceOperations([row]);if(this.settled.has(op.operation_id))throw Error('RACE_OPERATION_CONFLICT');this.reviewed.add(op.operation_id);this.unattempted.add(op.operation_id);await this.commit(old=>({operations:parseRaceOperations([...old.operations,row])}));this.publish({pending:this.rows(),error:null});await this.retry();this.guard();return op.operation_id;}catch(error){this.fail(error);try{this.publish({pending:this.rows()});}catch{/* No corrupt-read overwrite. */}return null;}}
 retry(reviewedOperationId?:string):Promise<void>{if(reviewedOperationId!==undefined){try{this.guard();if(!this.network())throw Error('RACE_AUTH_REQUIRED');const row=this.rows().find(r=>r.operation_id===reviewedOperationId);if(!row||!isRaceActivation(row.request))throw Error('RACE_INVALID');if(this.cancelling.has(reviewedOperationId))throw Error('RACE_REVIEW_REQUIRED');this.reviewed.add(reviewedOperationId);}catch(error){this.fail(error);return Promise.resolve();}}if(this.running){this.again=true;return this.running;}const task=this.runPasses();this.running=task;void task.then(()=>{if(this.running===task)this.running=null;},()=>{if(this.running===task)this.running=null;});return task;}
 private async remove(row:StoredRaceOperation){let removed:StoredRaceOperation|null=null,index=0;try{await this.commit(old=>{index=old.operations.findIndex(v=>v.operation_id===row.operation_id);const present=old.operations[index];if(!present||identity(present)!==identity(row))throw Error('RACE_INVALID_RESPONSE');removed=present;return {operations:old.operations.filter(v=>v.operation_id!==row.operation_id)};});}catch(error){if(removed){const previous=removed;try{await this.commit(old=>{if(old.operations.some(v=>v.operation_id===row.operation_id))return old;const rows=[...old.operations];rows.splice(Math.min(index,rows.length),0,previous);return {operations:parseRaceOperations(rows)};});}catch{/* Exact restored dirty row must flush before later egress. */}}throw error;}this.reviewed.delete(row.operation_id);this.unattempted.delete(row.operation_id);}
 private noteSettled(row:StoredRaceOperation){this.settled.set(row.operation_id,identity(row));this.cancelling.delete(row.operation_id);while(this.settled.size>64)this.settled.delete(this.settled.keys().next().value!);}
 private async settleDurably(row:StoredRaceOperation,publish:()=>void):Promise<boolean>{const running=this.settlements.get(row.operation_id);if(running){await running;if(this.settled.get(row.operation_id)!==identity(row))throw Error('RACE_INVALID_RESPONSE');return false;}if(this.settled.has(row.operation_id)){if(this.settled.get(row.operation_id)!==identity(row))throw Error('RACE_INVALID_RESPONSE');return false;}const task=Promise.resolve().then(async()=>{this.guard();await this.remove(row);this.noteSettled(row);this.guard();publish();});this.settlements.set(row.operation_id,task);try{await task;return true;}finally{if(this.settlements.get(row.operation_id)===task)this.settlements.delete(row.operation_id);}}
 private async acknowledge(row:StoredRaceOperation,value:unknown){const receipt=validateRaceReceipt(value,this.port.ownerId,operation(row)),won=await this.settleDurably(row,()=>this.publish({pending:this.rows(),latest:{operation_id:row.operation_id,status:'applied',error:null,receipt},error:null}));if(won&&this.network()){try{await this.port.refresh(receipt);this.guard();}catch(error){this.fail(error);}}}
 private async status(row:StoredRaceOperation){if(!this.network())return undefined;const value=await this.port.status(row.operation_id);this.guard();return value===null?null:validateRaceReceipt(value,this.port.ownerId,operation(row));}
 private async remember(row:StoredRaceOperation,error:unknown){const last_error=code(error);await this.commit(old=>({operations:old.operations.map(v=>v.operation_id===row.operation_id&&identity(v)===identity(row)?{...v,last_error}:v)}));this.fail(error);}
 private async settle(row:StoredRaceOperation):Promise<boolean>{if(this.settled.has(row.operation_id))return true;if(!this.network())return false;
  if(!this.unattempted.has(row.operation_id)){const previous=await this.status(row);if(previous){await this.acknowledge(row,previous);return true;}if(previous===undefined||!this.network())return false;}
  if(isRaceActivation(row.request)&&(!this.reviewed.has(row.operation_id)||this.cancelling.has(row.operation_id))){this.publish({reviewRequired:[...new Set([...this.state.reviewRequired,row.operation_id])]});return false;}
  if(this.remaining()!==null){this.publish({error:'RACE_RATE_LIMITED',retryAfterMs:this.remaining()});return false;}if(!this.network())return false;this.unattempted.delete(row.operation_id);let response;
  try{const op=operation(row);response=validateRaceMutation(await this.port.send(op),this.port.ownerId,op);this.guard();}catch(error){this.guard();const previous=await this.status(row);if(previous){await this.acknowledge(row,previous);return true;}await this.remember(row,error);return false;}
  if('error'in response){if(response.error.code==='RACE_RATE_LIMITED')this.limited(response.error.retry_after_ms);const previous=await this.status(row);if(previous){await this.acknowledge(row,previous);return true;}if(previous===undefined||!this.network()){await this.remember(row,Error(response.error.code));return false;}await this.settleDurably(row,()=>this.publish({pending:this.rows(),latest:{operation_id:row.operation_id,status:'rejected',error:response.error.code,receipt:null},error:response.error.code}));return true;}
  await this.acknowledge(row,response);return true;
 }
 cancelActivation(operationId:string):Promise<boolean>{const running=this.cancellations.get(operationId);if(running)return running;const task=this.cancel(operationId);this.cancellations.set(operationId,task);void task.then(()=>{if(this.cancellations.get(operationId)===task)this.cancellations.delete(operationId);});return task;}
 private async cancel(operationId:string):Promise<boolean>{let row:StoredRaceOperation|undefined;try{this.guard();row=this.rows().find(v=>v.operation_id===operationId);if(!row){if(this.settled.has(operationId))return true;throw Error('RACE_INVALID');}if(!isRaceActivation(row.request))throw Error('RACE_INVALID');this.cancelling.add(operationId);this.reviewed.delete(operationId);this.unattempted.delete(operationId);await this.writes;this.guard();await this.port.flush();this.guard();if(!this.network())throw Error('RACE_AUTH_REQUIRED');const previous=await this.status(row);if(previous){await this.acknowledge(row,previous);return true;}if(!this.network())throw Error('RACE_AUTH_REQUIRED');if(this.remaining()!==null)throw Error('RACE_RATE_LIMITED');const result=validateRaceCancellation(await this.port.cancelActivation(operation(row)),this.port.ownerId,operation(row));this.guard();if(this.settled.has(operationId))return true;if('error'in result){if(result.error.code==='RACE_RATE_LIMITED')this.limited(result.error.retry_after_ms);const applied=await this.status(row);if(applied){await this.acknowledge(row,applied);return true;}throw Error(result.error.code);}if('result'in result){await this.acknowledge(row,result);return true;}await this.settleDurably(row,()=>this.publish({pending:this.rows(),latest:{operation_id:operationId,status:'rejected',error:'RACE_OPERATION_CANCELLED',receipt:null},error:'RACE_OPERATION_CANCELLED'}));return true;}catch(error){if(this.settled.has(operationId)){try{this.guard();return true;}catch{return false;}}if(row){try{await this.remember(row,error);}catch(writeError){this.fail(writeError);}}else this.fail(error);return false;}}
 private async runPasses(){do{this.again=false;await this.run();}while(this.again&&!this.closed&&this.port.current()&&this.port.eligible());}
 private async run(){try{this.guard();await this.writes;this.guard();await this.port.flush();this.guard();const rows=this.rows();this.publish({busy:true,pending:rows,reviewRequired:this.reviewIds(rows),retryAfterMs:this.remaining()});if(!this.network())return;let processed=0;for(const row of rows){if(!this.network()||processed++>=4)break;try{if(!await this.settle(row))break;}catch(error){this.guard();this.fail(error);break;}}}catch(error){this.fail(error);}finally{try{this.guard();const rows=this.rows();this.publish({busy:false,pending:rows,reviewRequired:this.reviewIds(rows),retryAfterMs:this.remaining()});}catch(error){this.fail(error);}}}
}
