import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {freezeRaceClockBinding,freezeRaceHeartbeat,freezeRaceOperation,freezeRaceStage,isRaceActivation,isRaceId,validateApprovalPage,validateRaceAttempt,validateRaceAttemptPage,validateRaceCancellation,validateRaceClockProbe,validateRaceCourse,validateRaceCursor,validateRaceError,validateRaceHeartbeat,validateRaceMutation,validateRaceOperation,validateRacePage,validateRaceResults,validateRaceSnapshot,validateRaceStageProof} from './model';
import type {ApprovalPage,AttemptSnapshot,RaceAttemptPage,RaceCancellationMutation,RaceClockBinding,RaceClockProbe,RaceCourseSnapshot,RaceCursor,RaceErrorCode,RaceErrorEnvelope,RaceHeartbeat,RaceHeartbeatInput,RaceMutation,RaceOperation,RacePage,RaceReceipt,RaceResults,RaceSnapshot,StageProof,StageSample} from './types';
export type {ApprovalPage,AttemptSnapshot,RaceAttemptPage,RaceCancellationMutation,RaceClockBinding,RaceClockProbe,RaceCourseSnapshot,RaceCursor,RaceHeartbeat,RaceHeartbeatInput,RaceMutation,RaceOperation,RacePage,RaceReceipt,RaceResults,RaceSnapshot,StageProof,StageSample} from './types';
export class RaceServiceError extends Error{readonly retryAfterMs:number|null;constructor(envelope:RaceErrorEnvelope){super(envelope.error.code);this.name='RaceServiceError';this.retryAfterMs=envelope.error.code==='RACE_RATE_LIMITED'?envelope.error.retry_after_ms:null;}}
function current(scope:AuthScope,session:Session){if(!scope.userId||session.user.id!==scope.userId||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>):Promise<unknown>=>{current(scope,session);let response;try{response=await client.rpc(name,args);}catch{current(scope,session);throw Error('RACE_UNAVAILABLE');}current(scope,session);if(response.error){if(response.error.code==='PGRST301'||response.error.code==='PGRST302')throw Error('RACE_AUTH_REQUIRED');if(response.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('RACE_UNAVAILABLE');}return response.data;};}
function requiredId(value:string){if(!isRaceId(value))throw Error('RACE_INVALID');}
function readError(value:unknown){const error=validateRaceError(value);if(error)throw new RaceServiceError(error);return value;}
function revision(value:number){if(!Number.isInteger(value)||value<1||value>2147483647)throw Error('RACE_INVALID');}
/** Each call captures an owner scope and JWT; no retry, GPS queue or global token. */
export async function mutateRace(scope:AuthScope,session:Session,value:RaceOperation):Promise<RaceMutation>{const op=freezeRaceOperation(value),rpc=transport(scope,session);return validateRaceMutation(await rpc('rs_race_mutate',{p_operation:op.operation_id,p_request:op.request}),scope.userId!,op);}
export async function cancelRaceActivation(scope:AuthScope,session:Session,value:RaceOperation):Promise<RaceCancellationMutation>{const op=freezeRaceOperation(value);if(!isRaceActivation(op.request))throw Error('RACE_INVALID');const rpc=transport(scope,session);return validateRaceCancellation(await rpc('rs_cancel_race_activation',{p_operation:op.operation_id,p_request:op.request}),scope.userId!,op);}
export async function getRaceOperation(scope:AuthScope,session:Session,operationId:string):Promise<RaceReceipt|null>{requiredId(operationId);const rpc=transport(scope,session);return validateRaceOperation(readError(await rpc('rs_race_operation',{p_operation:operationId})),scope.userId!,operationId);}
export async function getRace(scope:AuthScope,session:Session,raceId:string):Promise<RaceSnapshot|null>{requiredId(raceId);const rpc=transport(scope,session);return validateRaceSnapshot(readError(await rpc('rs_get_race',{p_race:raceId})),scope.userId!,raceId);}
export async function listRaces(scope:AuthScope,session:Session,cursor:RaceCursor|null=null):Promise<RacePage>{const c=validateRaceCursor(cursor),rpc=transport(scope,session);return validateRacePage(readError(await rpc('rs_list_races',{p_limit:30,p_before:c?.before??null,p_before_id:c?.before_id??null})),scope.userId!);}
export async function listRaceApprovals(scope:AuthScope,session:Session,routeId:string,routeRevision:number):Promise<ApprovalPage>{requiredId(routeId);revision(routeRevision);const rpc=transport(scope,session);return validateApprovalPage(readError(await rpc('rs_list_race_approvals',{p_route:routeId,p_revision:routeRevision})),scope.userId!,routeId,routeRevision);}
export async function getRaceCourse(scope:AuthScope,session:Session,raceId:string):Promise<RaceCourseSnapshot>{requiredId(raceId);const rpc=transport(scope,session);return validateRaceCourse(readError(await rpc('rs_get_race_course',{p_race:raceId})),raceId);}
export async function getRaceAttempt(scope:AuthScope,session:Session,attemptId:string):Promise<AttemptSnapshot|null>{requiredId(attemptId);const rpc=transport(scope,session);return validateRaceAttempt(readError(await rpc('rs_get_race_attempt',{p_attempt:attemptId})),scope.userId!,attemptId);}
export async function listRaceAttempts(scope:AuthScope,session:Session,raceId:string):Promise<RaceAttemptPage>{requiredId(raceId);const rpc=transport(scope,session);return validateRaceAttemptPage(readError(await rpc('rs_list_race_attempts',{p_race:raceId})),scope.userId!,raceId);}
export async function getRaceResults(scope:AuthScope,session:Session,raceId:string):Promise<RaceResults>{requiredId(raceId);const rpc=transport(scope,session);return validateRaceResults(readError(await rpc('rs_race_results',{p_race:raceId})),scope.userId!,raceId);}
export async function probeRaceClock(scope:AuthScope,session:Session,value:RaceClockBinding):Promise<RaceClockProbe|RaceErrorEnvelope>{const binding=freezeRaceClockBinding(value),rpc=transport(scope,session),result=await rpc('rs_race_clock',{p_probe:binding.probe_id,p_race:binding.race_id,p_capture:binding.capture_id,p_generation:binding.clock_generation});return validateRaceError(result)??validateRaceClockProbe(result,scope.userId!,binding);}
export async function publishRaceStage(scope:AuthScope,session:Session,value:StageSample):Promise<StageProof|RaceErrorEnvelope>{const sample=freezeRaceStage(value),rpc=transport(scope,session),result=await rpc('rs_race_stage',{p_sample:sample});return validateRaceError(result)??validateRaceStageProof(result,scope.userId!,sample);}
export async function heartbeatRace(scope:AuthScope,session:Session,value:RaceHeartbeatInput):Promise<RaceHeartbeat|RaceErrorEnvelope>{const input=freezeRaceHeartbeat(value),rpc=transport(scope,session),result=await rpc('rs_race_heartbeat',{p_race:input.race_id,p_member_generation:input.member_generation,p_ready_lease:input.ready_lease_id,p_attempt:input.attempt_id,p_stage_proof:input.stage_proof_id,p_clock_probe_ids:input.clock_probe_ids});return validateRaceError(result)??validateRaceHeartbeat(result,scope.userId!,input);}
export function raceServiceCode(error:unknown):RaceErrorCode|'RACE_INVALID_RESPONSE'|'ACCOUNT_CHANGED'{if(error instanceof RaceServiceError)return error.message as RaceErrorCode;return error instanceof Error&&['ACCOUNT_CHANGED','RACE_INVALID_RESPONSE','RACE_AUTH_REQUIRED','ACCOUNT_DELETION_PENDING','RACE_INVALID'].includes(error.message)?error.message as RaceErrorCode|'RACE_INVALID_RESPONSE'|'ACCOUNT_CHANGED':'RACE_UNAVAILABLE';}
