import React,{useEffect,useRef,useState} from 'react';
import {ActivityIndicator,View} from 'react-native';
import {Button,Empty,Field,Note,Segments,T} from '../../../components/ui';
import {raceErrorKey} from '../../../lib/raceI18n';
import {useApp} from '../../../state/AppState';
import {RouteSheet} from '../../routes/RouteSheet';
import SharedRouteSnapshot from '../../routes/SharedRouteSnapshot';
import type {FriendBinding,RaceMode} from '../types';
import type {RaceCreateSelection,RaceRouteOption,RaceScreenProps,ReviewedRaceCreation} from '../uiTypes';
import {assertReview,assertSelection,displayInstant,selectionMatches} from './presentationModel';
import {ConsentChecks,RaceOutcome} from './RaceSurface';
import {useRaceUI} from './useRaceUI';

export default function RaceCreate({port,t,visible,onClose}:RaceScreenProps&{visible:boolean;onClose:()=>void}){
 const ui=useRaceUI(port),{colors}=useApp(),epoch=useRef(0),[mode,setMode]=useState<RaceMode>('async'),[route,setRoute]=useState<RaceRouteOption|null>(null),[approvalId,setApprovalId]=useState<string|null>(null),[friends,setFriends]=useState<FriendBinding[]>([]),[start,setStart]=useState(''),[end,setEnd]=useState(''),[routeQuery,setRouteQuery]=useState(''),[friendQuery,setFriendQuery]=useState(''),[review,setReview]=useState<ReviewedRaceCreation|null>(null),[safety,setSafety]=useState(false),[evidence,setEvidence]=useState(false);
 const invalidateRun=ui.invalidate;
 // Revoke a displayed consent/review on lifecycle loss; never restore its held response.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{epoch.current++;invalidateRun();setReview(null);setSafety(false);setEvidence(false);},[visible,port.generation,port.gate.focused,port.gate.foreground,port.gate.moving,invalidateRun]);
 // Local form selections belong to one account generation, including A→B→A.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setMode('async');setRoute(null);setApprovalId(null);setFriends([]);setStart('');setEnd('');setRouteQuery('');setFriendQuery('');},[port.generation]);
 const invalidate=()=>{epoch.current++;setReview(null);setSafety(false);setEvidence(false);};
 const chooseRoute=(selected:RaceRouteOption)=>{try{const p=ui.guard('read');if(!p.routes.some(r=>r.id===selected.id&&r.revision===selected.revision))throw Error('RACE_CHANGED');invalidate();setRoute(selected);setApprovalId(null);setStart('');setEnd('');void ui.run(p=>p.loadApprovals(selected),'read');}catch(value){ui.setError(raceErrorKey(value));}};
 const selection=():RaceCreateSelection=>{if(!route||!approvalId)throw Error('RACE_APPROVAL_UNAVAILABLE');return {mode,route_id:route.id,route_revision:route.revision,approval_id:approvalId,starts_at:start,ends_at:end,friends:[...friends].sort((a,b)=>a.user_id.localeCompare(b.user_id))};};
 const prepare=()=>ui.run(async p=>{const chosen=selection();assertSelection(p,chosen);const sequence=++epoch.current,result=await p.reviewCreate(chosen);if(!ui.current()||sequence!==epoch.current)return;const fresh=ui.guard('read');assertReview(fresh,result);if(!selectionMatches(result,chosen))throw Error('RACE_CHANGED');setReview(result);setSafety(false);setEvidence(false);},'read');
 const send=()=>ui.run(async p=>{if(!review||!safety||!evidence)throw Error('RACE_CONSENT');assertReview(p,review);if(!p.pilotEnabled)throw Error('RACE_DISABLED');return p.create(review,{acknowledgement_version:1,evidence_consent_version:1});});
 const routes=port.routes.filter(r=>r.title.toLocaleLowerCase().includes(routeQuery.trim().toLocaleLowerCase()));
 const peers=port.friends.filter(f=>(f.name+' '+f.handle).toLocaleLowerCase().includes(friendQuery.trim().toLocaleLowerCase()));
 const matchingApprovals=route&&port.approvals.route_id===route.id&&port.approvals.route_revision===route.revision;
 const disabled=!ui.enabled||ui.busy||port.busy;
 return <RouteSheet visible={visible&&port.gate.focused&&port.gate.foreground&&!port.gate.moving} title={t(review?'m5c.reviewTitle':'m5c.newTrial')} onClose={()=>{invalidate();onClose();}}>{review?<><T size={20} weight="semibold">{review.projection.title}</T><T>{t(`m5c.${review.mode}`)}</T><T muted size={13}>{displayInstant(review.starts_at)}{'\n'}{displayInstant(review.ends_at)}</T><SharedRouteSnapshot value={review.projection} invitation map={false}/><Note>{t('m5c.routePrivate')}</Note>{review.friends.map(binding=>{const person=port.friends.find(f=>f.user_id===binding.user_id);return <T key={binding.user_id}>{person?.name??t('m5c.errors.changed')}</T>;})}<ConsentChecks t={t} safety={safety} evidence={evidence} onSafety={setSafety} onEvidence={setEvidence} disabled={disabled||!!ui.operation}/>{!port.pilotEnabled&&<Note>{t('m5c.disabled')}</Note>}<Button label={t('m5c.create')} disabled={disabled||!safety||!evidence||!port.pilotEnabled||!!ui.operation} busy={ui.busy} onPress={send}/><RaceOutcome port={port} t={t} id={ui.operation}/><Button secondary label={t('m5c.cancelReview')} disabled={ui.busy} onPress={invalidate}/></>:<>
  <Segments items={[{value:'async',label:t('m5c.async')},{value:'live',label:t('m5c.live')}]} value={mode} onChange={value=>{if(disabled)return;invalidate();setMode(value);}}/><T size={13} muted>{t('m5c.modeHelp')}</T>
  <Field label={t('m5c.route')} value={routeQuery} onChangeText={setRouteQuery} editable={!disabled}/>
  {port.routesPage.loading&&<ActivityIndicator color={colors.accent}/>}<View style={{gap:8}}>{routes.map(option=><Button key={option.id} secondary small label={option.title} disabled={disabled||!port.routesPage.fresh} icon={route?.id===option.id?'checkmark-circle-outline':undefined} onPress={()=>chooseRoute(option)}/>)}</View>
  {port.routesPage.fresh&&!port.routesPage.error&&!port.routes.length&&<Empty icon="map-outline" title={t('m5c.routesEmpty')} body={t('m5c.routesBody')}/>}{port.routesPage.error&&<Note error>{t('m5c.unavailable')}</Note>}
  {port.routesPage.hasMore&&<Button small secondary label={t('m5c.routesMore')} disabled={disabled} onPress={()=>ui.run(p=>p.loadMoreRoutes(),'read')}/>}
  {route&&<><T size={13} muted>{t('m5c.routeRevision',{revision:route.revision})}</T><T weight="semibold">{t('m5c.approval')}</T>{port.approvals.loading?<T>{t('m5c.approvalsLoading')}</T>:matchingApprovals&&port.approvals.fresh&&!port.approvals.error&&!port.approvals.items.length?<View style={{gap:8}}><T>{t('m5c.approvalEmpty')}</T><Note>{t('m5c.approvalBody')}</Note></View>:null}{matchingApprovals&&port.approvals.items.map(a=><Button key={a.id} small secondary label={displayInstant(a.starts_at)+' – '+displayInstant(a.ends_at)} disabled={disabled||!port.approvals.fresh} icon={approvalId===a.id?'checkmark-circle-outline':undefined} onPress={()=>{try{ui.guard('read');invalidate();setApprovalId(a.id);setStart(a.starts_at);setEnd(a.ends_at);}catch(value){ui.setError(raceErrorKey(value));}}}/>)}{port.approvals.error&&<Note error>{t(raceErrorKey(port.approvals.error))}</Note>}<Button small secondary label={t('m5c.approvalRetry')} disabled={disabled} onPress={()=>ui.run(p=>p.loadApprovals(route),'read')}/></>}
  <Field label={t('m5c.friends')} value={friendQuery} onChangeText={setFriendQuery} editable={!disabled}/><T size={13} muted>{t('m5c.friendsBody')}</T><View style={{gap:8}}>{peers.map(person=>{const selected=friends.some(f=>f.user_id===person.user_id);return <Button key={person.user_id} small secondary label={person.name+' · @'+person.handle} icon={selected?'checkbox-outline':'square-outline'} disabled={disabled||!port.friendsPage.fresh||(!selected&&friends.length>=3)} onPress={()=>{try{const p=ui.guard('read');if(!p.friends.some(f=>f.user_id===person.user_id&&f.friendship_generation===person.friendship_generation))throw Error('RACE_FRIEND_CHANGED');invalidate();setFriends(current=>selected?current.filter(f=>f.user_id!==person.user_id):[...current,{user_id:person.user_id,friendship_generation:person.friendship_generation}]);}catch(value){ui.setError(raceErrorKey(value));}}}/>;})}</View>{port.friendsPage.fresh&&!port.friendsPage.error&&!port.friends.length&&<Note>{t('m5c.friendsEmpty')}</Note>}{port.friendsPage.error&&<Note error>{t('m5c.unavailable')}</Note>}{port.friendsPage.hasMore&&<Button small secondary label={t('m5c.friendsMore')} disabled={disabled} onPress={()=>ui.run(p=>p.loadMoreFriends(),'read')}/>}
  {approvalId&&<><Field label={t('m5c.startsAt')} value={start} autoCapitalize="none" editable={!disabled} onChangeText={value=>{invalidate();setStart(value);}}/><Field label={t('m5c.endsAt')} value={end} autoCapitalize="none" editable={!disabled} onChangeText={value=>{invalidate();setEnd(value);}}/><Note>{t('m5c.windowHelp')}</Note></>}
  <Button label={t('m5c.review')} disabled={disabled||!approvalId||!friends.length} busy={ui.busy} onPress={prepare}/>
 </>}{ui.error&&<Note error>{t(ui.error)}</Note>}</RouteSheet>;
}
