import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {isRankedId} from './model';
import {validateRankedOperation,validateRankedOwnCursor,validateRankedOwnPage,validateRankedPublicationCursor,validateRankedPublicationPage,validateRankedPublication,validateRankedMutationError,validateRankedMutation,validateRankedReceipt,type RankedOperation} from './publicationModel';
import type {RankedMetric,RankedOwnCursor,RankedPublicationCursor,RankedPublication,RankedMutationError} from './types';
export class RankedMutationServiceError extends Error{readonly retryAfterMs:number|null;constructor(value:RankedMutationError){super(value.error.code);this.name='RankedMutationServiceError';this.retryAfterMs=value.error.code==='RANKED_RATE_LIMITED'?value.error.retry_after_ms:null;}}
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>)=>{current(scope,session);let result;try{result=await client.rpc(name,args);}catch{current(scope,session);throw Error('RANKED_UNAVAILABLE');}current(scope,session);if(result.error){if(['PGRST301','PGRST302'].includes(result.error.code))throw Error('RANKED_AUTH_REQUIRED');if(result.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('RANKED_UNAVAILABLE');}return result.data;};}
function binding(metric:RankedMetric,recordId:string){if(!['sustained_speed','route_time'].includes(metric)||!isRankedId(recordId))throw Error('RANKED_INVALID');}
function error(value:unknown){const e=validateRankedMutationError(value);if(e)throw new RankedMutationServiceError(e);return value;}
export async function getRankedOwnRecords(scope:AuthScope,session:Session,cursor:RankedOwnCursor|null=null,limit=30){current(scope,session);if(!Number.isInteger(limit)||limit<1||limit>30)throw Error('RANKED_INVALID');const frozen=validateRankedOwnCursor(cursor);return validateRankedOwnPage(error(await transport(scope,session)('rs_ranked_own_records',{p_cursor:frozen,p_limit:limit})),scope.userId!,frozen);}
export async function getRankedPublications(scope:AuthScope,session:Session,cursor:RankedPublicationCursor|null=null,limit=30){current(scope,session);if(!Number.isInteger(limit)||limit<1||limit>30)throw Error('RANKED_INVALID');const frozen=validateRankedPublicationCursor(cursor);return validateRankedPublicationPage(error(await transport(scope,session)('rs_ranked_publications',{p_cursor:frozen,p_limit:limit})),scope.userId!,frozen);}
export async function getRankedPublication(scope:AuthScope,session:Session,metric:RankedMetric,recordId:string):Promise<RankedPublication>{current(scope,session);binding(metric,recordId);return validateRankedPublication(error(await transport(scope,session)('rs_get_result_publication',{p_metric:metric,p_record:recordId})),scope.userId!,metric,recordId);}
export async function sendRankedMutation(scope:AuthScope,session:Session,input:RankedOperation){current(scope,session);const op=validateRankedOperation(input,scope.userId!);return validateRankedMutation(await transport(scope,session)('rs_ranked_mutate',{p_operation:op.operation_id,p_request:op.request}),scope.userId!,op);}
/** Receipt lookup stays bound to the exact persisted request, including after restart. */
export async function getRankedOperation(scope:AuthScope,session:Session,input:RankedOperation){current(scope,session);const op=validateRankedOperation(input,scope.userId!),result=error(await transport(scope,session)('rs_ranked_operation',{p_operation:op.operation_id}));return result===null?null:validateRankedReceipt(result,scope.userId!,op);}
