import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,RefreshControl,StyleSheet,View,useWindowDimensions,type LayoutChangeEvent,type NativeScrollEvent,type NativeSyntheticEvent} from 'react-native';
import {FlashList} from '@shopify/flash-list';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Button,Empty,Note,Row,T} from '../../components/ui';
import {rankedErrorKey} from '../../lib/rankedI18n';
import {theme} from '../../lib/theme';
import {useApp} from '../../state/AppState';
import {AmbientLoop} from '../motion';
import {resolveAmbientAsset} from '../motion/assets';
import {RouteSheet} from '../routes/RouteSheet';
import {rankedFilterKey} from './model';
import {classesForCategory} from './presentationModel';
import {OwnRank,RankedListRow,RankedPodium,RankedSignIn} from './RankedParts';
import type {RankedCategory,RankedFilter,RankedRow} from './types';
import type {RankedScreenProps} from './uiTypes';
import {useRankedUI} from './useRankedUI';

function Choices<TValue extends string>({items,value,onChange,disabled}:{items:readonly {value:TValue;label:string}[];value:TValue;onChange:(value:TValue)=>void;disabled:boolean}){
 const {colors}=useApp();
 return <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{items.map(item=><Pressable key={item.value} accessibilityRole="tab" accessibilityLabel={item.label} accessibilityState={{selected:item.value===value,disabled}} disabled={disabled} onPress={()=>onChange(item.value)} style={{minHeight:theme.material.minTarget,minWidth:theme.material.minTarget,paddingHorizontal:14,paddingVertical:10,borderRadius:theme.radius.pill,borderWidth:StyleSheet.hairlineWidth,borderColor:item.value===value?colors.accent:colors.line,backgroundColor:item.value===value?colors.raised:colors.surface,justifyContent:'center',opacity:disabled?.5:1}}><T size={13} weight={item.value===value?'semibold':'regular'}>{item.label}</T></Pressable>)}</View>;
}
function instantLabel(instant:string,locale:'th'|'en'){return new Intl.DateTimeFormat(locale==='th'?'th-TH':'en-GB',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(instant));}

export function RankedScreen({port,t}:RankedScreenProps){
 const ui=useRankedUI(port),{colors,dark}=useApp(),insets=useSafeAreaInsets(),{height}=useWindowDimensions(),[filters,setFilters]=useState(false),[visibility,setVisibility]=useState({hero:true,podium:true});
 const rectangles=useRef({hero:{top:0,bottom:220},podium:{top:350,bottom:650}}),scrollY=useRef(0),visibilityRef=useRef(visibility);
 const reconcileVisibility=useCallback(()=>{const y=scrollY.current,viewport=height-insets.top-insets.bottom,next={hero:rectangles.current.hero.bottom>y&&rectangles.current.hero.top<y+viewport,podium:rectangles.current.podium.bottom>y&&rectangles.current.podium.top<y+viewport};if(next.hero!==visibilityRef.current.hero||next.podium!==visibilityRef.current.podium){visibilityRef.current=next;setVisibility(next);}},[height,insets.top,insets.bottom]);
 const measure=useCallback((kind:'hero'|'podium',event:LayoutChangeEvent)=>{const {y,height:measured}=event.nativeEvent.layout;rectangles.current[kind]={top:y+insets.top+16,bottom:y+measured+insets.top+16};reconcileVisibility();},[insets.top,reconcileVisibility]);
 const scrolled=useCallback((event:NativeSyntheticEvent<NativeScrollEvent>)=>{scrollY.current=event.nativeEvent.contentOffset.y;reconcileVisibility();},[reconcileVisibility]);
 // A sheet cannot remain interactive after account/screen/movement policy invalidation.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setFilters(false);},[port.generation,port.gate.focused,port.gate.foreground,port.gate.moving]);
 const filter=port.filter,anchor=rankedFilterKey(filter),identityCurrent=port.current(port.generation),matching=identityCurrent&&port.ready&&port.gate.signedIn&&port.page?.owner_id===port.ownerId&&rankedFilterKey(port.page.filter)===anchor,page=matching?port.page:null;
 const supported=page?(filter.metric==='sustained_speed'?page.capabilities.speed:page.capabilities.route_time):true;
 const loaded=!!page&&port.read.fresh&&!port.read.error&&!port.read.loading&&port.gate.online&&supported;
 const choose=useCallback((patch:Partial<RankedFilter>)=>ui.run(async p=>{if(rankedFilterKey(p.filter)!==anchor)throw Error('RANKED_CHANGED');await p.setFilter({...p.filter,...patch});},'filter'),[ui,anchor]);
 const category=(value:RankedCategory)=>void choose({category:value,class_key:`${value}:unknown`,course:null});
 const publication=()=>void ui.run(p=>{if(!p.read.fresh||p.read.error||!p.page?.capabilities.publication)throw Error('RANKED_CHANGED');p.onManagePublication?.();},'publication');
 const boardRevision=page?.board_revision??'';
 const report=(record:RankedRow)=>{
  const binding={record_id:record.record_id,user_id:record.user_id,metric:record.metric,board_revision:boardRevision};
  void ui.run(p=>{if(!p.read.fresh||p.read.error||p.page?.board_revision!==binding.board_revision||rankedFilterKey(p.filter)!==anchor||!p.rows.some(r=>r.record_id===binding.record_id&&r.user_id===binding.user_id&&r.metric===binding.metric))throw Error('RANKED_CHANGED');p.onReport?.(binding);},'publication');
 };
 const header=<View style={{gap:22}}><View onLayout={event=>measure('hero',event)} style={{borderRadius:theme.radius.card,overflow:'hidden',backgroundColor:colors.surface}}><AmbientLoop asset={resolveAmbientAsset(`ranked-${filter.period}`,dark?'dark':'light')} visible={visibility.hero&&port.gate.focused&&port.gate.foreground&&!port.gate.moving} style={StyleSheet.absoluteFill}/><View style={{padding:24,gap:12}}><T accessibilityRole="header" size={32} weight="semibold">{t('m6.title')}</T><T muted>{t('m6.body')}</T></View></View>
 <Choices items={(['today','week','month'] as const).map(value=>({value,label:t(`m6.${value}`)}))} value={filter.period} disabled={!ui.enabled} onChange={value=>void choose({period:value})}/>
 <Choices items={(['sustained_speed','route_time'] as const).map(value=>({value,label:t(`m6.${value}`)}))} value={filter.metric} disabled={!ui.enabled} onChange={value=>void choose({metric:value,course:null})}/>
 <Row style={{flexWrap:'wrap',justifyContent:'space-between'}}><Button small secondary icon="options-outline" label={t('m6.filters')} disabled={!ui.enabled} onPress={()=>void ui.run(()=>setFilters(true),'filter')}/><Button small secondary icon="refresh-outline" label={t('m6.refresh')} disabled={!ui.active||!port.gate.signedIn} busy={ui.busy||port.read.loading} onPress={()=>void ui.run(p=>p.refresh())}/></Row>
 <T size={13} muted>{t(`m6.${filter.category}`)} · {filter.class_key==='all'?t('m6.allClasses'):t(`m6.class.${filter.class_key}`)} · {t(`m6.${filter.scope}`)}</T>
 {!port.gate.signedIn&&<RankedSignIn t={t} disabled={!ui.active} onSignIn={()=>void ui.run(p=>p.onSignIn(),'navigation')}/>}
 {port.gate.moving&&<Note>{t('m6.moving')}</Note>}{!port.gate.online&&<Note>{t('m6.offline')}</Note>}{port.gate.signedIn&&!port.read.fresh&&!!page&&<Note>{t('m6.stale')}</Note>}{port.read.error&&<Note error>{t(rankedErrorKey(port.read.error))}</Note>}{ui.error&&<Note error>{t(ui.error)}</Note>}
 {filter.metric==='route_time'&&<View style={{gap:12}}><T accessibilityRole="header" weight="semibold">{t('m6.chooseCourse')}</T><Note>{t('m6.courseBody')}</Note>{port.courses.filter(c=>c.category===filter.category).map(c=><Button key={`${c.approval_id}:${c.mode}`} small secondary label={`${c.title} · ${t(`m6.${c.mode}`)}`} disabled={!ui.enabled||!port.coursesRead.fresh||!!port.coursesRead.error} onPress={()=>void ui.run(async p=>{if(rankedFilterKey(p.filter)!==anchor||!p.coursesRead.fresh||p.coursesRead.error||!p.courses.some(current=>current.approval_id===c.approval_id&&current.config_hash===c.config_hash&&current.mode===c.mode&&current.category===p.filter.category))throw Error('RANKED_COURSE_UNAVAILABLE');await p.setFilter({...p.filter,course:{approval_id:c.approval_id,config_hash:c.config_hash,mode:c.mode}});},'filter')}/>)}{port.coursesRead.loading&&<ActivityIndicator color={colors.accent}/>}<View style={{gap:10}}>{port.coursesRead.error&&<Note error>{t(rankedErrorKey(port.coursesRead.error))}</Note>}{port.coursesRead.hasMore&&<Button small secondary label={t('m6.moreCourses')} disabled={!ui.enabled||ui.busy} busy={port.coursesRead.loading} onPress={()=>void ui.run(p=>p.loadMoreCourses())}/>}</View>{port.coursesRead.fresh&&!port.coursesRead.loading&&!port.coursesRead.error&&!port.coursesRead.hasMore&&!port.courses.some(c=>c.category===filter.category)&&port.gate.online&&<Note>{t('m6.noCourses')}</Note>}</View>}
 {page&&!supported&&<Note>{t('m6.unsupported')}</Note>}<T weight="semibold">{t(filter.metric==='sustained_speed'?'m6.speedMethod':'m6.timeMethod')}</T><Note>{t(filter.metric==='sustained_speed'?'m6.speedQuality':'m6.timeQuality')}</Note>{filter.metric==='sustained_speed'?<Note>{t('m6.legacy')}</Note>:<Note>{t('m6.metadata')}</Note>}{filter.class_key==='all'&&<Note>{t('m6.allBody')}</Note>}<Note>{t('m6.periodBody')}</Note>{page&&<T size={12} muted>{t('m6.asOf',{time:instantLabel(page.period.as_of,port.locale)})}</T>}
 {page&&supported&&<View onLayout={event=>measure('podium',event)}><RankedPodium rows={page.podium} port={port} t={t} visible={visibility.podium}/></View>}{matching&&port.rows.length>0&&<T accessibilityRole="header" size={20} weight="semibold">{t('m6.listTitle')}</T>}</View>;
 return <View style={{flex:1,backgroundColor:colors.bg}}><FlashList key={`${port.generation}:${anchor}`} drawDistance={400} maintainVisibleContentPosition={{disabled:true}} data={matching&&supported?port.rows:[]} keyExtractor={record=>record.record_id} scrollEnabled={!port.gate.moving} onScroll={scrolled} scrollEventThrottle={100} contentContainerStyle={{paddingHorizontal:24,paddingTop:insets.top+16,paddingBottom:page?insets.bottom+280:insets.bottom+120}} refreshControl={<RefreshControl refreshing={port.read.loading} tintColor={colors.accent} enabled={ui.active&&port.gate.signedIn} onRefresh={()=>void ui.run(p=>p.refresh())}/>} ListHeaderComponent={header} renderItem={({item})=><RankedListRow record={item} port={port} t={t} report={()=>report(item)}/>} ListEmptyComponent={port.read.loading?<Row><ActivityIndicator color={colors.accent}/><T>{t('m6.loading')}</T></Row>:loaded&&!(filter.metric==='route_time'&&!filter.course)?<Empty icon="podium-outline" title={t('m6.emptyTitle')} body={t('m6.emptyBody')}/>:null} ListFooterComponent={<View style={{gap:12,paddingTop:18}}>{port.read.hasMore&&<Button secondary label={t('m6.more')} disabled={!ui.enabled||ui.busy} busy={port.read.loading} onPress={()=>void ui.run(async p=>{if(!p.read.fresh||p.read.error||p.page?.board_revision!==page?.board_revision||rankedFilterKey(p.filter)!==anchor)throw Error('RANKED_CHANGED');await p.loadMore();})}/>}</View>}/>
 {page&&<View style={{position:'absolute',left:24,right:24,bottom:insets.bottom+96}}><OwnRank port={{...port,page}} t={t} publication={publication} stale={!loaded}/></View>}
 <RouteSheet visible={filters} title={t('m6.filters')} onClose={()=>setFilters(false)}><Choices items={(['scooter','motorcycle','car'] as const).map(value=>({value,label:t(`m6.${value}`)}))} value={filter.category} disabled={!ui.enabled} onChange={category}/><T weight="semibold">{t('m6.vehicleClass')}</T><Choices items={(['all',...classesForCategory(filter.category)] as const).map(value=>({value,label:value==='all'?t('m6.allClasses'):t(`m6.class.${value}`)}))} value={filter.class_key} disabled={!ui.enabled} onChange={value=>void choose({class_key:value})}/><Choices items={(['global','friends'] as const).map(value=>({value,label:t(`m6.${value}`)}))} value={filter.scope} disabled={!ui.enabled} onChange={value=>void choose({scope:value})}/>{port.onManagePublication&&<><Note>{t('m6.publicationBody')}</Note><Button secondary label={t('m6.managePublication')} disabled={!ui.enabled||!page?.capabilities.publication} onPress={publication}/></>}</RouteSheet></View>;
}
export default RankedScreen;
