import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {freezeRankedFilter,validateRankedCourseCursor,validateRankedCourses,validateRankedCursor,validateRankedError,validateRankedPage} from './model';
import type {RankedCourseCursor,RankedCoursePage,RankedCursor,RankedErrorEnvelope,RankedFilter,RankedPage} from './types';
export class RankedServiceError extends Error{readonly retryAfterMs:number|null;constructor(value:RankedErrorEnvelope){super(value.error.code);this.name='RankedServiceError';this.retryAfterMs=value.error.code==='RANKED_RATE_LIMITED'?value.error.retry_after_ms:null;}}
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>)=>{current(scope,session);let result;try{result=await client.rpc(name,args);}catch{current(scope,session);throw Error('RANKED_UNAVAILABLE');}current(scope,session);if(result.error){if(['PGRST301','PGRST302'].includes(result.error.code))throw Error('RANKED_AUTH_REQUIRED');if(result.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('RANKED_UNAVAILABLE');}const error=validateRankedError(result.data);if(error)throw new RankedServiceError(error);return result.data;};}
function limit(value:number){if(!Number.isInteger(value)||value<1||value>30)throw Error('RANKED_INVALID');}
/** Owner JWT/filter/cursor are captured once. Root controls retry/invalidation, never a hidden polling loop. */
export async function getRankedPage(scope:AuthScope,session:Session,selected:RankedFilter,cursor:RankedCursor|null=null,pageSize=30):Promise<RankedPage>{current(scope,session);limit(pageSize);const filter=freezeRankedFilter(selected);if(filter.metric==='route_time'&&!filter.course)throw Error('RANKED_COURSE_UNAVAILABLE');const frozenCursor=validateRankedCursor(cursor,scope.userId!),rpc=transport(scope,session);return validateRankedPage(await rpc('rs_ranked_page',{p_filter:filter,p_cursor:frozenCursor,p_limit:pageSize}),scope.userId!,filter,frozenCursor);}
export async function getRankedCourses(scope:AuthScope,session:Session,cursor:RankedCourseCursor|null=null,pageSize=30):Promise<RankedCoursePage>{current(scope,session);limit(pageSize);const frozen=validateRankedCourseCursor(cursor),rpc=transport(scope,session);return validateRankedCourses(await rpc('rs_ranked_courses',{p_cursor:frozen,p_limit:pageSize}),scope.userId!,frozen);}
