import React,{useCallback,useLayoutEffect,useRef,useState} from 'react';
import {ActivityIndicator,RefreshControl,View,type ViewToken} from 'react-native';
import {FlashList} from '@shopify/flash-list';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {Button,Empty,Glass,Note,Panel,Row,T} from '../../components/ui';
import {communityErrorKey} from '../../lib/communityI18n';
import {useApp} from '../../state/AppState';
import {CommunityChoices,CommunityStatus} from './CommunityParts';
import {communityFilterKey} from './model';
import {PostCard} from './PostCard';
import type {CommunityPost} from './types';
import {communityPostBinding,type CommunityFeedProps} from './uiTypes';
import {useCommunityUI} from './useCommunityUI';
const feedViewability={itemVisiblePercentThreshold:10,minimumViewTime:250};
const noVisiblePosts:ReadonlySet<string>=new Set();
export function CommunityFeed({port,t,headerAccessory}:CommunityFeedProps){
 const {colors}=useApp(),insets=useSafeAreaInsets(),ui=useCommunityUI(port),anchor=communityFilterKey(port.filter),listKey=`${port.generation}:${anchor}`,[visibility,setVisibility]=useState<{key:string;ids:ReadonlySet<string>}>({key:'',ids:noVisiblePosts}),visibleRef=useRef(visibility),activeList=useRef(listKey);
 useLayoutEffect(()=>{activeList.current=listKey;},[listKey]);
 const onViewable=useCallback(({viewableItems}:{viewableItems:ViewToken<CommunityPost>[]})=>{if(activeList.current!==listKey)return;const ids=new Set(viewableItems.filter(v=>v.isViewable).map(v=>v.item.post_id)),prior=visibleRef.current;if(prior.key!==listKey||ids.size!==prior.ids.size||[...ids].some(id=>!prior.ids.has(id))){const next={key:listKey,ids};visibleRef.current=next;setVisibility(next);}},[listKey]);
 const visible=visibility.key===listKey?visibility.ids:noVisiblePosts,identity=port.current(port.generation),matching=identity&&port.ready&&port.gate.signedIn&&port.page?.owner_id===port.ownerId&&communityFilterKey(port.page.filter)===anchor,rows=matching?port.rows.filter(p=>port.postCurrent(communityPostBinding(p))):[];
 const loaded=matching&&port.read.fresh&&!port.read.error&&!port.read.loading&&port.gate.online,revision=matching?port.page?.feed_revision:null;
 const act=(post:CommunityPost,action:'like'|'save'|'open'|'route'|'share')=>{const binding=communityPostBinding(post);return ui.run(async p=>{if(communityFilterKey(p.filter)!==anchor||!p.postCurrent(binding))throw Error('COMMUNITY_CHANGED');if(action==='open'){p.onOpenPost(binding);return;}if(action==='route'){p.onOpenRoute(binding);return;}if(!p.read.fresh||p.read.error)throw Error('COMMUNITY_CHANGED');if(action==='share'){await p.onShare(binding);return;}const intents=p.pending.filter(op=>op.request.post_id===post.post_id&&op.request.expected_revision===post.content_revision&&op.request.action===action).at(-1)?.request;
  return p.mutate(action==='like'?{schema_version:1,action:'like',post_id:binding.post_id,expected_revision:binding.content_revision,liked:!(intents?.action==='like'?intents.liked:post.engagement.liked)}:{schema_version:1,action:'save',post_id:binding.post_id,expected_revision:binding.content_revision,saved:!(intents?.action==='save'?intents.saved:post.engagement.saved)});
 },action==='open'||action==='route'?'navigation':'control');};
 const header=<View style={{gap:18,marginBottom:20}}><Row style={{justifyContent:'space-between',flexWrap:'wrap'}}><View style={{flex:1,minWidth:160,gap:4}}><T size={30} weight="semibold" accessibilityRole="header">{t('m7.title')}</T><T size={14} muted>{t('m7.subtitle')}</T></View><Button small icon="add-outline" label={t('m7.compose')} disabled={!ui.canEdit} onPress={()=>ui.run(p=>p.onCompose(),'navigation')}/></Row>{headerAccessory}<Glass style={{padding:8}}><CommunityChoices values={(['latest','top_week','friends'] as const).map(value=>({value,label:t(value==='top_week'?'m7.topWeek':`m7.${value}`)}))} selected={port.filter.mode} disabled={!ui.enabled||ui.busy} onChange={mode=>void ui.run(async p=>{if(communityFilterKey(p.filter)!==anchor)throw Error('COMMUNITY_CHANGED');await p.setFilter({schema_version:1,mode});})}/></Glass>{port.filter.mode==='top_week'&&<T size={12} muted>{t('m7.topCriterion')}</T>}{!port.gate.signedIn&&<Panel><T>{t('m7.signInBody')}</T><Button label={t('m7.signIn')} disabled={!ui.canNavigate} onPress={()=>ui.run(p=>p.onSignIn(),'navigation')}/></Panel>}{port.gate.moving&&<Note>{t('m7.moving')}</Note>}{!port.gate.online&&<Note>{t('m7.offline')}</Note>}{matching&&!port.read.fresh&&<Note>{t('m7.stale')}</Note>}{port.read.error&&<Note error>{t(communityErrorKey(port.read.error))}</Note>}<CommunityStatus port={port} t={t} operation={ui.operation} error={ui.error} retry={()=>void ui.run(p=>p.retry())}/>{port.gate.signedIn&&<Button small secondary icon="refresh-outline" label={t('m7.refresh')} disabled={!ui.enabled} busy={port.read.loading||ui.busy} onPress={()=>ui.run(p=>p.refresh(),'read')}/>}</View>;
 return <View style={{flex:1,backgroundColor:colors.bg}}><FlashList key={`${port.generation}:${anchor}`} data={rows} keyExtractor={p=>p.post_id} drawDistance={400} maintainVisibleContentPosition={{disabled:true}} scrollEnabled={!port.gate.moving} viewabilityConfig={feedViewability} onViewableItemsChanged={onViewable} contentContainerStyle={{paddingHorizontal:24,paddingTop:insets.top+16,paddingBottom:insets.bottom+124}} ListHeaderComponent={header} renderItem={({item})=><PostCard post={item} port={port} t={t} visible={visible.has(item.post_id)} act={(post,action)=>void act(post,action)}/>} refreshControl={<RefreshControl refreshing={port.read.loading} tintColor={colors.accent} enabled={ui.enabled} onRefresh={()=>void ui.run(p=>p.refresh(),'read')}/>} ListEmptyComponent={port.read.loading?<Row><ActivityIndicator color={colors.accent}/><T>{t('m7.loading')}</T></Row>:loaded?<Empty icon="trail-sign-outline" title={t('m7.emptyTitle')} body={t('m7.emptyBody')}/>:null} ListFooterComponent={<View style={{gap:12}}>{port.read.hasMore&&<Button secondary label={t('m7.more')} disabled={!ui.enabled||ui.busy} busy={ui.busy||port.read.loading} onPress={()=>ui.run(async p=>{if(communityFilterKey(p.filter)!==anchor||p.page?.feed_revision!==revision||!p.read.fresh||p.read.error)throw Error('COMMUNITY_CHANGED');await p.loadMore();},'read')}/>}</View>}/></View>;
}
export default CommunityFeed;
