import {isCommunityId} from './model';
import type {CommunityAudience} from './types';
export type CommunityOwnerPost=Readonly<{post_id:string;content_revision:number;visibility:CommunityAudience;state:'draft'|'published'|'hidden'|'deleted';updated_at:string}>;
export type CommunityOwnerCursor=Readonly<{owner_id:string;updated_at:string;post_id:string}>;
export type CommunityOwnerPage=Readonly<{owner_id:string;server_now:string;items:readonly CommunityOwnerPost[];next_cursor:CommunityOwnerCursor|null}>;
export type CommunityOwnerDetail=Readonly<{owner_id:string;server_now:string;post:CommunityOwnerPost}>;
function fail():never{throw Error('COMMUNITY_INVALID_RESPONSE');}
function object(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value)||Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))fail();return value as Record<string,unknown>;}
function id(value:unknown):string{if(!isCommunityId(value))fail();return value;}
/** Canonical instant key retains all six Postgres fractional digits. */
export function communityOwnerUtcKey(value:unknown):string{if(typeof value!=='string')fail();const match=/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,6}))?(?:Z|\+00:00)$/.exec(value);if(!match||!Number.isFinite(Date.parse(match[1]+'Z'))||new Date(match[1]+'Z').toISOString().slice(0,19)!==match[1])fail();return match[1]+'.'+(match[2]??'').padEnd(6,'0');}
function freeze<T>(value:T):T{const copy=JSON.parse(JSON.stringify(value));function visit(item:unknown){if(item&&typeof item==='object'){Object.values(item).forEach(visit);Object.freeze(item);}}visit(copy);return copy;}
export function communityOwnerKey(value:CommunityOwnerPost){return JSON.stringify([value.post_id,value.content_revision,value.visibility,value.state,communityOwnerUtcKey(value.updated_at)]);}
export function validateCommunityOwnerPost(value:unknown,allowDraft=false):CommunityOwnerPost{const p=object(value,['post_id','content_revision','visibility','state','updated_at']);id(p.post_id);if(!Number.isSafeInteger(p.content_revision)||Number(p.content_revision)<(p.state==='draft'&&allowDraft?0:1)||Number(p.content_revision)>2147483647)fail();if(!['private','friends','public'].includes(String(p.visibility))||!['published','hidden','deleted',...(allowDraft?['draft']:[])].includes(String(p.state))||p.state==='draft'&&p.content_revision!==0)fail();communityOwnerUtcKey(p.updated_at);return freeze(value as CommunityOwnerPost);}
export function validateCommunityOwnerCursor(value:unknown,ownerId:string):CommunityOwnerCursor|null{if(value===null)return null;const c=object(value,['owner_id','updated_at','post_id']);if(id(c.owner_id)!==ownerId)fail();id(c.post_id);communityOwnerUtcKey(c.updated_at);return freeze(value as CommunityOwnerCursor);}
export function validateCommunityOwnerPage(value:unknown,ownerId:string,after:CommunityOwnerCursor|null=null):CommunityOwnerPage{const p=object(value,['owner_id','server_now','items','next_cursor']);if(id(p.owner_id)!==ownerId)fail();const now=communityOwnerUtcKey(p.server_now);if(!Array.isArray(p.items)||p.items.length>30)fail();const cursor=validateCommunityOwnerCursor(after,ownerId);let last=cursor?communityOwnerUtcKey(cursor.updated_at)+':'+cursor.post_id:null;const seen=new Set<string>();for(const raw of p.items){const row=validateCommunityOwnerPost(raw),instant=communityOwnerUtcKey(row.updated_at),key=instant+':'+row.post_id;if(instant>now||seen.has(row.post_id)||last!==null&&key>=last)fail();seen.add(row.post_id);last=key;}const next=validateCommunityOwnerCursor(p.next_cursor,ownerId);if(next){const row=p.items.at(-1) as CommunityOwnerPost|undefined;if(!row||next.post_id!==row.post_id||communityOwnerUtcKey(next.updated_at)!==communityOwnerUtcKey(row.updated_at))fail();}return freeze(value as CommunityOwnerPage);}
export function validateCommunityOwnerDetail(value:unknown,ownerId:string,postId:string):CommunityOwnerDetail{const p=object(value,['owner_id','server_now','post']);if(id(p.owner_id)!==ownerId)fail();const now=communityOwnerUtcKey(p.server_now),post=validateCommunityOwnerPost(p.post,true);if(post.post_id!==postId||communityOwnerUtcKey(post.updated_at)>now)fail();return freeze(value as CommunityOwnerDetail);}
