import React from 'react';
import {Platform,Pressable,StyleSheet,View} from 'react-native';
import Svg,{Path} from 'react-native-svg';
import {Button,Icon,Note,Row,T} from '../../components/ui';
import {communityErrorKey} from '../../lib/communityI18n';
import {theme} from '../../lib/theme';
import {useApp} from '../../state/AppState';
import {distanceLabel,durationLabel,routeOutline,speedLabel} from './presentationModel';
import type {CommunityRideSnapshot,CommunityRouteSnapshot} from './types';
import type {CommunityBasePort,CommunityTranslator} from './uiTypes';
export function CommunityChoices<TValue extends string>({values,selected,disabled,onChange}:{values:readonly {value:TValue;label:string}[];selected:TValue;disabled:boolean;onChange:(value:TValue)=>void}){const {colors}=useApp();return <View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{values.map(v=><Pressable key={v.value} accessibilityRole="tab" accessibilityLabel={v.label} accessibilityState={{selected:selected===v.value,disabled}} disabled={disabled} onPress={()=>onChange(v.value)} style={{minHeight:theme.material.minTarget,minWidth:theme.material.minTarget,paddingHorizontal:14,paddingVertical:10,borderRadius:theme.radius.pill,borderWidth:StyleSheet.hairlineWidth,borderColor:selected===v.value?colors.accent:colors.line,backgroundColor:colors.surface}}><T size={13} weight={selected===v.value?'semibold':'regular'}>{v.label}</T></Pressable>)}</View>;}
export function RideStatistics({ride,units,t}:{ride:Omit<CommunityRideSnapshot,'summary_hash'>;units:'kmh'|'mph';t:CommunityTranslator}){const {colors}=useApp(),values=[['m7.maxSpeed',speedLabel(ride.max_speed_mps,units)],['m7.averageSpeed',speedLabel(ride.average_speed_mps,units)],['m7.distance',distanceLabel(ride.distance_m,units)],['m7.duration',durationLabel(ride.active_duration_ms)]];return <View style={{gap:12}}><T size={12} muted>{t('m7.selfReported')}</T><View style={{flexDirection:'row',flexWrap:'wrap',gap:12}}>{values.map(([key,value])=><View key={key} style={{width:'46%',gap:3}}><T size={12} muted>{t(key)}</T><T numeric size={21} accessibilityLabel={`${t(key)} ${value==='—'?t('m7.unavailableValue'):value}`}>{value}</T></View>)}</View>{ride.vehicle&&<View style={{borderTopColor:colors.line,borderTopWidth:StyleSheet.hairlineWidth,paddingTop:10,gap:4}}><T size={12} muted>{t('m7.vehicle')}</T><T size={13}>{`${ride.vehicle.brand} ${ride.vehicle.model}${ride.vehicle.variant?' · '+ride.vehicle.variant:''}`}</T></View>}</View>;}
export function RouteOutline({route,t}:{route:CommunityRouteSnapshot;t:CommunityTranslator}){const {colors}=useApp(),paths=routeOutline(route);return <View style={{gap:8}}>{route.title&&<T weight="semibold">{route.title}</T>}{paths.length?<View accessible accessibilityLabel={t('m7.routeOutline')} style={{backgroundColor:colors.raised,borderRadius:theme.radius.small,overflow:'hidden'}}><Svg viewBox="0 0 320 144" width="100%" height={144} {...(Platform.OS==='web'?{'aria-hidden':true}:{accessible:false})}>{paths.map((d,i)=><Path key={i} d={d} fill="none" stroke={colors.accent} strokeWidth={3} strokeLinecap="round" strokeLinejoin="round"/>)}</Svg></View>:<T size={13} muted>{t(route.source==='legacy'?'m7.legacyRoute':'m7.routeHidden')}</T>}{route.geometryStatus==='trimmed'&&<T size={12} muted>{t('m7.privacyTrim')}</T>}</View>;}
export function CommunityStatus({port,t,operation,error,retry}:{port:CommunityBasePort;t:CommunityTranslator;operation?:string|null;error?:string|null;retry?:()=>void}){const latest=operation&&port.latest?.operationId===operation?port.latest:null;return <View style={{gap:10}}>{error&&<Note error>{t(error)}</Note>}{latest?.status==='applied'?<Note>{t('m7.applied')}</Note>:latest?.status==='rejected'?<><Note error>{t('m7.rejected')}</Note>{latest.error&&<Note error>{t(communityErrorKey(latest.error))}</Note>}</>:operation?<Note>{t('m7.queued')}</Note>:null}{port.pending.length>0&&<Row style={{flexWrap:'wrap',justifyContent:'space-between'}}><T size={12} muted>{t('m7.pendingCount',{count:port.pending.length})}</T>{retry&&<Button small secondary label={t('m7.retry')} disabled={!port.gate.focused||!port.gate.foreground||port.gate.moving||!port.gate.online} onPress={retry}/>}</Row>}</View>;}
export function CommunityMonogram({name}:{name:string}){const {colors}=useApp();return <View style={{width:44,height:44,borderRadius:22,backgroundColor:colors.raised,borderWidth:StyleSheet.hairlineWidth,borderColor:colors.line,alignItems:'center',justifyContent:'center'}}><T size={18} weight="semibold">{Array.from(name.trim())[0]??''}</T></View>;}
export function PhotoPlaceholder({label}:{label:string}){const {colors}=useApp();return <View style={{flex:1,minHeight:144,alignItems:'center',justifyContent:'center',gap:8,backgroundColor:colors.raised}}><Icon name="image-outline"/><T size={12} muted>{label}</T></View>;}
