import {communityOwnerKey,validateCommunityOwnerDetail,validateCommunityOwnerPage,type CommunityOwnerCursor,type CommunityOwnerDetail,type CommunityOwnerPage,type CommunityOwnerPost} from './communityOwnerModel';
import {isCommunityId} from './model';
export type CommunityOwnerRead=Readonly<{loaded:boolean;loading:boolean;fresh:boolean;error:string|null;hasMore:boolean}>;
export type CommunityOwnerSnapshot=Readonly<{loaded:boolean;rows:readonly CommunityOwnerPost[];read:CommunityOwnerRead;selectedId:string|null;detail:CommunityOwnerDetail|null;detailRead:CommunityOwnerRead;retryAfterMs:number|null}>;
export type CommunityOwnerPort=Readonly<{ownerId:string;guard:()=>void;monotonicNow:()=>number;page:(cursor:CommunityOwnerCursor|null)=>Promise<CommunityOwnerPage>;detail:(postId:string)=>Promise<CommunityOwnerDetail>}>;
const unread=():CommunityOwnerRead=>({loaded:false,loading:false,fresh:false,error:null,hasMore:false});
function code(value:unknown){const message=(value as {message?:unknown}|null)?.message;return typeof message==='string'&&['ACCOUNT_CHANGED','ACCOUNT_DELETION_PENDING','COMMUNITY_CHANGED','COMMUNITY_INVALID_RESPONSE','COMMUNITY_RATE_LIMITED','COMMUNITY_CAPACITY','COMMUNITY_UNAVAILABLE','COMMUNITY_AUTH_REQUIRED','COMMUNITY_MOVING','LOCAL_READ_FAILED'].includes(message)?message:'COMMUNITY_UNAVAILABLE';}
/** Metadata has no content/signing authority. Only a freshly selected getter
 * can supply the CAS reviewed by the current owner. Receipts never adopt it. */
export class CommunityOwnerReader{
 private state:CommunityOwnerSnapshot={loaded:false,rows:[],read:unread(),selectedId:null,detail:null,detailRead:unread(),retryAfterMs:null};private listeners=new Set<()=>void>();private version=0;private pageVersion=0;private detailVersion=0;private closed=false;private cursor:CommunityOwnerCursor|null=null;private pending:Promise<void>|null=null;private pendingMore=false;private detailPending:Promise<void>|null=null;private detailAt:number|null=null;private retryAt=0;
 constructor(private port:CommunityOwnerPort){if(!isCommunityId(port.ownerId))throw Error('COMMUNITY_INVALID');}
 getSnapshot=()=>this.state;subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 private publish(value:Partial<CommunityOwnerSnapshot>){this.state={...this.state,...value};for(const fn of this.listeners)fn();}
 private guard(version=this.version){if(this.closed||version!==this.version)throw Error('COMMUNITY_CHANGED');this.port.guard();}
 private now(){const value=this.port.monotonicNow();if(!Number.isFinite(value)||value<0)throw Error('COMMUNITY_CHANGED');return value;}
 private allowed(){const remaining=this.retryAt-this.now();if(remaining>0){this.publish({retryAfterMs:remaining});return false;}return true;}
 private failure(error:unknown){const typed=error as {name?:string;message?:string;retryAfterMs?:number};if(typed?.name==='CommunityServiceError'&&typed.message==='COMMUNITY_RATE_LIMITED'&&Number.isSafeInteger(typed.retryAfterMs)&&typed.retryAfterMs!>=1&&typed.retryAfterMs!<=86400000)this.retryAt=Math.max(this.retryAt,this.now()+typed.retryAfterMs!);return code(error);}
 invalidate(){if(this.closed)return;++this.version;++this.pageVersion;++this.detailVersion;this.pending=null;this.detailPending=null;this.cursor=null;this.detailAt=null;this.publish({loaded:false,rows:[],read:unread(),detail:null,detailRead:unread()});}
 suspend(){this.invalidate();}close(){this.invalidate();this.closed=true;this.listeners.clear();}
 current(post:CommunityOwnerPost){try{this.guard();const now=this.now();return this.state.detailRead.fresh&&!this.state.detailRead.error&&this.detailAt!==null&&now>=this.detailAt&&now-this.detailAt<=15000&&this.state.detail!==null&&communityOwnerKey(post)===communityOwnerKey(this.state.detail.post);}catch{return false;}}
 refresh=()=>{try{this.guard();}catch(e){return Promise.reject(e);}++this.detailVersion;this.detailPending=null;this.detailAt=null;this.publish({detail:null,detailRead:unread()});return this.read(false);};loadMore=()=>this.read(true);
 private read(more:boolean):Promise<void>{try{this.guard();}catch(e){return Promise.reject(e);}if(this.pending&&(more||!this.pendingMore))return this.pending;if(!this.allowed()||more&&(!this.state.read.fresh||!this.cursor))return Promise.resolve();const version=this.version,request=++this.pageVersion,cursor=more?this.cursor:null;this.publish({read:{...this.state.read,loading:true,error:null,...(!more?{fresh:false}:{})}});
  const check=()=>{this.guard(version);if(request!==this.pageVersion)throw Error('COMMUNITY_CHANGED');};const run=async()=>{try{check();const raw=await this.port.page(cursor);check();const page=validateCommunityOwnerPage(raw,this.port.ownerId,cursor),prior=more?this.state.rows:[],seen=new Set(prior.map(p=>p.post_id));if(page.items.some(p=>seen.has(p.post_id)))throw Error('COMMUNITY_CHANGED');if(prior.length+page.items.length>300)throw Error('COMMUNITY_CAPACITY');this.cursor=page.next_cursor;this.publish({loaded:true,rows:Object.freeze([...prior,...page.items]),read:{loaded:true,loading:false,fresh:true,error:null,hasMore:!!this.cursor},retryAfterMs:null});}catch(e){try{check();const error=this.failure(e);this.publish({read:{...this.state.read,loading:false,fresh:false,error},retryAfterMs:this.retryAt>this.now()?this.retryAt-this.now():null});}catch{/* Retired metadata is not adopted. */}}finally{if(this.pending===promise)this.pending=null;}};const promise=Promise.resolve().then(run);this.pending=promise;this.pendingMore=more;return promise;}
 select(postId:string):Promise<void>{try{this.guard();if(!isCommunityId(postId))throw Error('COMMUNITY_INVALID');}catch(e){return Promise.reject(e);}if(this.detailPending&&this.state.selectedId===postId)return this.detailPending;if(!this.allowed())return Promise.resolve();const version=this.version,request=++this.detailVersion,started=this.now();this.detailAt=null;this.publish({selectedId:postId,detail:null,detailRead:{...unread(),loading:true}});const check=()=>{this.guard(version);if(request!==this.detailVersion||this.state.selectedId!==postId)throw Error('COMMUNITY_CHANGED');};const run=async()=>{try{check();const raw=await this.port.detail(postId);check();const detail=validateCommunityOwnerDetail(raw,this.port.ownerId,postId);this.detailAt=started;this.publish({detail,detailRead:{loaded:true,loading:false,fresh:true,error:null,hasMore:false},retryAfterMs:null});}catch(e){try{check();const error=this.failure(e);this.publish({detail:null,detailRead:{...unread(),loaded:true,error},retryAfterMs:this.retryAt>this.now()?this.retryAt-this.now():null});}catch{/* Retired getter cannot supply a CAS. */}}finally{if(this.detailPending===promise)this.detailPending=null;}};const promise=Promise.resolve().then(run);this.detailPending=promise;return promise;}
}
