import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {isCommunityId,validateCommunityError} from './model';
import {CommunityServiceError} from './service';
import {validateCommunityOwnerCursor,validateCommunityOwnerDetail,validateCommunityOwnerPage,type CommunityOwnerCursor,type CommunityOwnerDetail,type CommunityOwnerPage} from './communityOwnerModel';
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
async function rpc(scope:AuthScope,session:Session,name:string,args:Record<string,unknown>){current(scope,session);const client=accountClient(scope,session);let result;try{result=await client.rpc(name,args);}catch{current(scope,session);throw Error('COMMUNITY_UNAVAILABLE');}current(scope,session);if(result.error){if(['PGRST301','PGRST302'].includes(result.error.code))throw Error('COMMUNITY_AUTH_REQUIRED');if(result.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('COMMUNITY_UNAVAILABLE');}const error=validateCommunityError(result.data);if(error)throw new CommunityServiceError(error);return result.data;}
export async function getCommunityOwnerPosts(scope:AuthScope,session:Session,cursor:CommunityOwnerCursor|null=null,pageSize=20):Promise<CommunityOwnerPage>{current(scope,session);if(!Number.isInteger(pageSize)||pageSize<1||pageSize>30)throw Error('COMMUNITY_INVALID');const frozen=validateCommunityOwnerCursor(cursor,scope.userId!);return validateCommunityOwnerPage(await rpc(scope,session,'rs_community_owner_posts',{p_cursor:frozen,p_limit:pageSize}),scope.userId!,frozen);}
export async function getCommunityOwnerPost(scope:AuthScope,session:Session,postId:string):Promise<CommunityOwnerDetail>{current(scope,session);if(!isCommunityId(postId))throw Error('COMMUNITY_INVALID');return validateCommunityOwnerDetail(await rpc(scope,session,'rs_community_owner_post',{p_post_id:postId}),scope.userId!,postId);}
