import {communityLimits,validPhotoDescriptor,validateCaption,validateDescription,type CommunityPhotoDescriptor} from './content';
import {communityErrors,freezeCommunityRequest,isCommunityId,validateCommunityReceipt} from './model';
import type {CommunityOperation,CommunityPublicationDocument,CommunityStoredOperation,CommunityMediaCommit,CommunityMediaReservation,CommunityReceipt} from './types';
export type OwnedCommunityOperation=CommunityStoredOperation&Readonly<{owner_id:string}>;
export type CommunityLocalPhoto=Readonly<{media_id:string;descriptor:CommunityPhotoDescriptor;reservation:CommunityMediaReservation|null;commit:CommunityMediaCommit|null}>;
export type CommunityDraftRecord=Readonly<{owner_id:string;draft_id:string;post_id:string;revision:number;document:CommunityPublicationDocument;photos:readonly CommunityLocalPhoto[];post_revision:number;status:'local'|'preparing'|'pending'|'published';operationId:string|null;error:string|null;created_at:string;updated_at:string}>;
export const communityLocalErrors=[...communityErrors,'COMMUNITY_INVALID_RESPONSE','COMMUNITY_INACTIVE','COMMUNITY_MOVING','LOCAL_READ_FAILED','LOCAL_WRITE_FAILED','ACCOUNT_CHANGED','COMMUNITY_PHOTO_INVALID','COMMUNITY_PHOTO_TOO_LARGE'] as const;
function fail():never{throw Error('COMMUNITY_LOCAL_INVALID');}
function object(value:unknown,keys:readonly string[]){if(!value||typeof value!=='object'||Array.isArray(value))fail();const v=value as Record<string,unknown>;if(Object.keys(v).length!==keys.length||keys.some(k=>!Object.hasOwn(v,k)))fail();return v;}
function id(value:unknown){if(!isCommunityId(value))fail();return value;}
function integer(value:unknown,min=0){if(typeof value!=='number'||!Number.isSafeInteger(value)||value<min||value>2147483647)fail();return value;}
function utc(value:unknown){if(typeof value!=='string'||!/^20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|\+00:00)$/.test(value)||!Number.isFinite(Date.parse(value))||new Date(Date.parse(value)).toISOString().slice(0,19)!==value.slice(0,19))fail();return value;}
function error(value:unknown){if(value!==null&&!communityLocalErrors.includes(value as typeof communityLocalErrors[number]))fail();}
export function communityCanonical(value:unknown):string{if(Array.isArray(value))return `[${value.map(communityCanonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${communityCanonical((value as Record<string,unknown>)[k])}`).join(',')}}`;return JSON.stringify(value);}
export function freezeCommunityLocal<T>(value:T):T{const copy=JSON.parse(JSON.stringify(value));function freeze(v:unknown){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}}freeze(copy);return copy;}
export const communityWire=(op:OwnedCommunityOperation):CommunityOperation=>({operationId:op.operationId,request:op.request});
export function parseCommunityOperations(value:unknown,owner?:string|null):OwnedCommunityOperation[]{if(value===undefined)return [];if(!Array.isArray(value))fail();if(value.length>32||new TextEncoder().encode(JSON.stringify(value)).byteLength>131072)throw Error('COMMUNITY_CAPACITY');const ids=new Set<string>();return value.map(candidate=>{const v=object(candidate,['owner_id','operationId','request','queuedAt','lastError']);id(v.owner_id);if(owner!==undefined&&v.owner_id!==owner)fail();const operationId=id(v.operationId);if(ids.has(operationId))fail();ids.add(operationId);freezeCommunityRequest(v.request as OwnedCommunityOperation['request']);utc(v.queuedAt);error(v.lastError);return freezeCommunityLocal(candidate as OwnedCommunityOperation);});}
export function validateOwnedCommunityReceipt(value:unknown,owner:string,op:OwnedCommunityOperation):CommunityReceipt{parseCommunityOperations([op],owner);return validateCommunityReceipt(value,owner,communityWire(op));}
/** Incomplete drafts may be blank. They never pass the publication validator. */
export function freezeCommunityDraftDocument(value:CommunityPublicationDocument){const v=object(value,['schema_version','caption','description','visibility','ride','route','include_ride_route','media_ids']);if(v.schema_version!==1||!validateCaption(v.caption)||!validateDescription(v.description)||!['private','friends','public'].includes(String(v.visibility))||typeof v.include_ride_route!=='boolean'||v.include_ride_route&&!v.ride||!Array.isArray(v.media_ids)||v.media_ids.length>communityLimits.photos||new Set(v.media_ids).size!==v.media_ids.length)fail();for(const media of v.media_ids)id(media);for(const kind of ['ride','route'] as const){if(v[kind]===null)continue;const b=object(v[kind],[`${kind}_id`,`${kind}_revision`]);id(b[`${kind}_id`]);integer(b[`${kind}_revision`],1);}return freezeCommunityLocal(value);}
export function parseCommunityDrafts(value:unknown,owner?:string|null):CommunityDraftRecord[]{if(value===undefined)return [];if(!Array.isArray(value))fail();if(value.length>4||new TextEncoder().encode(JSON.stringify(value)).byteLength>262144)throw Error('COMMUNITY_CAPACITY');const drafts=new Set<string>(),posts=new Set<string>(),mediaIds=new Set<string>();return value.map(candidate=>{
 const v=object(candidate,['owner_id','draft_id','post_id','revision','document','photos','post_revision','status','operationId','error','created_at','updated_at']);id(v.owner_id);if(owner!==undefined&&v.owner_id!==owner)fail();const draft=id(v.draft_id),post=id(v.post_id);if(drafts.has(draft)||posts.has(post))fail();drafts.add(draft);posts.add(post);integer(v.revision,1);integer(v.post_revision);const document=freezeCommunityDraftDocument(v.document as CommunityPublicationDocument);if(!['local','preparing','pending','published'].includes(String(v.status)))fail();if(v.operationId!==null)id(v.operationId);if(['pending','published'].includes(String(v.status))&&v.operationId===null)fail();error(v.error);utc(v.created_at);utc(v.updated_at);if(Date.parse(v.updated_at as string)<Date.parse(v.created_at as string))fail();
 if(!Array.isArray(v.photos)||v.photos.length>communityLimits.photos)fail();const photoOrder:string[]=[];for(const candidatePhoto of v.photos){const p=object(candidatePhoto,['media_id','descriptor','reservation','commit']),media=id(p.media_id);if(mediaIds.has(media))fail();mediaIds.add(media);photoOrder.push(media);object(p.descriptor,['mime','sha256','byte_count','width','height','blurhash']);if(!validPhotoDescriptor(p.descriptor))fail();
  if(p.reservation!==null){const r=object(p.reservation,['post_id','media_id','bucket','path','expires_at','state']);if(r.post_id!==post||r.media_id!==media||r.bucket!=='ride-post-media'||r.path!==`${v.owner_id}/${post}/${media}.jpg`||!['reserved','committed'].includes(String(r.state)))fail();utc(r.expires_at);}
  if(p.commit!==null){const c=object(p.commit,['post_id','media_id','descriptor']);object(c.descriptor,['mime','sha256','byte_count','width','height','blurhash']);if(c.post_id!==post||c.media_id!==media||!validPhotoDescriptor(c.descriptor))fail();const original=p.descriptor as CommunityPhotoDescriptor,committed=c.descriptor as CommunityPhotoDescriptor;for(const key of ['mime','sha256','byte_count','width','height'] as const)if(original[key]!==committed[key])fail();}
 }if(communityCanonical(photoOrder)!==communityCanonical(document.media_ids))fail();return freezeCommunityLocal(candidate as CommunityDraftRecord);
 });}
