import {bangkokPeriodBounds} from '../ranked/presentationModel';
import {hasPublicationContent,readableCaption,validMediaIds,validPhotoDescriptor,validateCaption,validateComment,validateDescription,validateReportDetail} from './content';
import type * as C from './types';
export const communityErrors=['COMMUNITY_INVALID','COMMUNITY_AUTH_REQUIRED','COMMUNITY_PROFILE_REQUIRED','COMMUNITY_UNAVAILABLE','COMMUNITY_CHANGED','COMMUNITY_REVISION_CONFLICT','COMMUNITY_OPERATION_CONFLICT','COMMUNITY_SOURCE_CHANGED','COMMUNITY_MEDIA_UNAVAILABLE','COMMUNITY_MEDIA_INVALID','COMMUNITY_MEDIA_EXPIRED','COMMUNITY_DRAFT_UNAVAILABLE','COMMUNITY_RATE_LIMITED','COMMUNITY_CAPACITY','ACCOUNT_DELETION_PENDING'] as const;
function fail():never{throw Error('COMMUNITY_INVALID_RESPONSE');}
function obj(value:unknown,keys:readonly string[]):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))fail();const v=value as Record<string,unknown>;if(Object.keys(v).length!==keys.length||keys.some(key=>!Object.hasOwn(v,key)))fail();return v;}
function choice(value:unknown,values:readonly unknown[]){if(!values.includes(value))fail();}
function num(value:unknown,min=0,max=2147483647){if(typeof value!=='number'||!Number.isFinite(value)||value<min||value>max)fail();return value;}
function int(value:unknown,min=1,max=2147483647){const n=num(value,min,max);if(!Number.isSafeInteger(n))fail();return n;}
function bool(value:unknown){if(typeof value!=='boolean')fail();}
export const isCommunityId=(value:unknown):value is string=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(value);
function id(value:unknown){if(!isCommunityId(value))fail();return value;}
function hash(value:unknown){if(typeof value!=='string'||!/^[0-9a-f]{64}$/.test(value))fail();}
function text(value:unknown,max:number,empty=false){if(typeof value!=='string'||(!empty&&!value.trim())||[...value].length>max||/[\u0000-\u001F\u007F]/u.test(value))fail();for(const point of value){const n=point.codePointAt(0)!;if(n>=0xD800&&n<=0xDFFF)fail();}return value;}
function utc(value:unknown){if(typeof value!=='string'||!/^20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,6})?(?:Z|\+00:00)$/.test(value))fail();const time=Date.parse(value);if(!Number.isFinite(time)||new Date(time).toISOString().slice(0,19)!==value.slice(0,19))fail();return value;}
function instant(value:string){const m=/^(.*?)(?:\.(\d{1,6}))?(?:Z|\+00:00)$/.exec(value)!;return `${m[1]}.${(m[2]??'').padEnd(6,'0')}`;}
function arr(value:unknown,max:number):unknown[]{if(!Array.isArray(value)||value.length>max)fail();return value;}
function clone<T>(value:T):T{const copy=JSON.parse(JSON.stringify(value));function freeze(v:unknown){if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}}freeze(copy);return copy;}
function canonical(value:unknown):string{if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${canonical((value as Record<string,unknown>)[k])}`).join(',')}}`;return JSON.stringify(value);}
export function communityFilterKey(value:C.CommunityFilter){return canonical(value);}
export function freezeCommunityFilter(value:C.CommunityFilter):C.CommunityFilter{try{const f=obj(value,['schema_version','mode']);choice(f.schema_version,[1]);choice(f.mode,['latest','top_week','friends']);return clone(value);}catch{throw Error('COMMUNITY_INVALID');}}
function profile(value:unknown){const p=obj(value,['name','handle']);text(p.name,80);if(!/^[a-z0-9_]{3,24}$/.test(text(p.handle,24)))fail();}
function sourceBinding(value:unknown,kind:'ride'|'route'){if(value===null)return;const b=obj(value,[`${kind}_id`,`${kind}_revision`]);id(b[`${kind}_id`]);int(b[`${kind}_revision`]);}
function vehicle(value:unknown){if(value===null)return;const v=obj(value,['local_id','catalog_id','category','brand','model','variant','year','powertrain','engine_cc','motor_kw']);choice(v.category,['scooter','motorcycle','car']);text(v.brand,80);text(v.model,100);for(const key of ['local_id','catalog_id','variant'])if(v[key]!==null)text(v[key],100);if(v.year!==null)text(v.year,30);choice(v.powertrain,['petrol','diesel','hybrid','electric','unknown']);if(v.engine_cc!==null)num(v.engine_cc,.01,10000);if(v.motor_kw!==null)num(v.motor_kw,.01,2000);if(v.powertrain==='electric'&&v.engine_cc!==null)fail();}
function ride(value:unknown){if(value===null)return;const r=obj(value,['ride_id','ride_revision','summary_hash','started_at','ended_at','active_duration_ms','distance_m','max_speed_mps','average_speed_mps','speed_status','vehicle']);id(r.ride_id);int(r.ride_revision);hash(r.summary_hash);const start=utc(r.started_at),end=utc(r.ended_at);if(instant(end)<instant(start))fail();int(r.active_duration_ms,0,604800000);if(r.distance_m!==null)num(r.distance_m,0,10000000);for(const k of ['max_speed_mps','average_speed_mps'])if(r[k]!==null)num(r[k],0,500/3.6);choice(r.speed_status,['self_reported']);vehicle(r.vehicle);}
function route(value:unknown,attached:C.CommunityRideSnapshot|null,version:0|1){if(value===null)return;const r=obj(value,['source','source_id','source_revision','title','category','segments','geometryStatus','privacyTrimMeters','geometryHash','provider','attribution']);choice(r.source,['ride','route','legacy']);int(r.source_revision);if(r.title!==null)text(r.title,120);choice(r.category,r.source==='ride'?['scooter','motorcycle','car','bicycle',null]:['scooter','motorcycle','car','bicycle']);
 if(r.source==='legacy'){if(version!==0||r.source_id!==null||r.title===null||r.geometryStatus!=='unavailable'||r.privacyTrimMeters!==null||r.geometryHash!==null||r.provider!=='unknown'||r.attribution!==null||arr(r.segments,0).length)fail();return;}
 id(r.source_id);choice(r.geometryStatus,['trimmed','hidden']);choice(r.privacyTrimMeters,[200]);choice(r.provider,['geoapify','recorded','draft']);if(r.attribution!==null)text(r.attribution,400);
 if(r.source==='ride'&&(!attached||r.source_id!==attached.ride_id||r.source_revision!==attached.ride_revision||r.provider!=='recorded'))fail();
 const parts=arr(r.segments,32);let total=0;for(const part of parts){const points=arr(part,4096);if(points.length<2)fail();for(const point of points){const c=obj(point,['latitude','longitude']);num(c.latitude,-85.05112878,85.05112878);num(c.longitude,-180,180);}total+=points.length;}if(total>10000)fail();if(r.geometryStatus==='hidden'){if(parts.length||r.geometryHash!==null)fail();}else{if(!parts.length)fail();hash(r.geometryHash);}
}
export function validateCommunityMedia(value:unknown,version:0|1):C.CommunityMedia{
 const m=obj(value,['media_id','validation','mime','sha256','byte_count','width','height','blurhash']);id(m.media_id);choice(m.validation,['decoded_jpeg_v1','legacy_unverified']);
 if(m.validation==='legacy_unverified'){if(version!==0)fail();choice(m.mime,['image/jpeg','image/png','image/webp']);for(const k of ['sha256','byte_count','width','height','blurhash'])if(m[k]!==null)fail();}
 else if(!validPhotoDescriptor(m))fail();return value as C.CommunityMedia;
}
function post(value:unknown,viewer:string,asOf:string,mode:C.CommunityMode|'detail'):C.CommunityPost{
 const p=obj(value,['post_id','owner_id','profile','content_version','content_revision','engagement_revision','caption','description','visibility','created_at','updated_at','ride','route','legacy_claimed_speed_kmh','media','engagement','week_score']);id(p.post_id);id(p.owner_id);profile(p.profile);choice(p.content_version,[0,1]);int(p.content_revision);int(p.engagement_revision);if(!readableCaption(p.caption,p.content_version as 0|1)||!validateDescription(p.description))fail();choice(p.visibility,['private','friends','public']);if(p.visibility==='private'&&(p.owner_id!==viewer||mode==='top_week'))fail();const created=utc(p.created_at),updated=utc(p.updated_at);if(instant(created)>instant(asOf)||instant(updated)<instant(created))fail();ride(p.ride);route(p.route,p.ride as C.CommunityRideSnapshot|null,p.content_version as 0|1);
 if(p.legacy_claimed_speed_kmh!==null){if(p.content_version!==0)fail();num(p.legacy_claimed_speed_kmh,0,500);}const media=arr(p.media,6).map(v=>validateCommunityMedia(v,p.content_version as 0|1));if(new Set(media.map(v=>v.media_id)).size!==media.length)fail();
 const e=obj(p.engagement,['likes','comments','liked','saved']);int(e.likes,0);int(e.comments,0);bool(e.liked);bool(e.saved);if(p.week_score!==null)int(p.week_score,0);if(mode==='top_week'&&p.week_score===null||mode!=='top_week'&&mode!=='detail'&&p.week_score!==null)fail();if(p.week_score!==null&&(p.week_score as number)>(e.likes as number))fail();return value as C.CommunityPost;
}
export function validateCommunityCursor(value:unknown,owner:string):C.CommunityCursor|null{if(value===null)return null;const c=obj(value,['owner_id','mode','feed_revision','starts_at','ends_at','as_of','after']);if(id(c.owner_id)!==owner)fail();choice(c.mode,['latest','top_week','friends']);hash(c.feed_revision);utc(c.as_of);for(const k of ['starts_at','ends_at'])if(c[k]!==null)utc(c[k]);if(c.mode==='top_week'){if(c.starts_at===null||c.ends_at===null)fail();}else if(c.starts_at!==null||c.ends_at!==null)fail();const a=obj(c.after,['created_at','post_id','week_score']);utc(a.created_at);id(a.post_id);if(c.mode==='top_week')int(a.week_score,0);else if(a.week_score!==null)fail();return clone(value as C.CommunityCursor);}
function rowOrder(a:Pick<C.CommunityPost,'created_at'|'post_id'|'week_score'>,b:Pick<C.CommunityPost,'created_at'|'post_id'|'week_score'>,mode:C.CommunityMode){if(mode==='top_week'&&a.week_score!==b.week_score)return (b.week_score??0)-(a.week_score??0);const at=instant(a.created_at),bt=instant(b.created_at);return bt>at?1:bt<at?-1:b.post_id>a.post_id?1:b.post_id<a.post_id?-1:0;}
export function validateCommunityPage(value:unknown,owner:string,expected:C.CommunityFilter,previous:C.CommunityCursor|null=null):C.CommunityPage{
 const p=obj(value,['owner_id','server_now','filter','window','feed_revision','items','next_cursor']);if(id(p.owner_id)!==owner)fail();const now=utc(p.server_now);let inbound:C.CommunityFilter;try{inbound=freezeCommunityFilter(p.filter as C.CommunityFilter);}catch{fail();}if(canonical(inbound)!==canonical(expected))fail();hash(p.feed_revision);const w=obj(p.window,['timezone','starts_at','ends_at','as_of']);choice(w.timezone,['Asia/Bangkok']);const asOf=utc(w.as_of);if(instant(asOf)>instant(now))fail();if(expected.mode==='top_week'){utc(w.starts_at);utc(w.ends_at);const bounds=bangkokPeriodBounds(asOf.replace(/\+00:00$/, 'Z'),'week');if(Date.parse(w.starts_at as string)!==Date.parse(bounds.starts_at)||Date.parse(w.ends_at as string)!==Date.parse(bounds.ends_at))fail();}else if(w.starts_at!==null||w.ends_at!==null)fail();
 if(previous){validateCommunityCursor(previous,owner);if(previous.mode!==expected.mode||previous.feed_revision!==p.feed_revision||canonical([previous.starts_at,previous.ends_at,previous.as_of])!==canonical([w.starts_at,w.ends_at,w.as_of]))fail();}
 const items=arr(p.items,30).map(v=>post(v,owner,asOf,expected.mode));let last=previous?.after??null;const ids=new Set<string>();for(const item of items){if(ids.has(item.post_id)||last&&rowOrder(last,item,expected.mode)>=0)fail();ids.add(item.post_id);last=item;if(expected.mode==='top_week'&&(instant(item.created_at)<instant(w.starts_at as string)||instant(item.created_at)>=instant(w.ends_at as string)))fail();if(instant(item.updated_at)>instant(now))fail();}
 const next=validateCommunityCursor(p.next_cursor,owner);if(next&&(!items.length||!last||next.mode!==expected.mode||next.feed_revision!==p.feed_revision||canonical([next.starts_at,next.ends_at,next.as_of])!==canonical([w.starts_at,w.ends_at,w.as_of])||canonical(next.after)!==canonical({created_at:last.created_at,post_id:last.post_id,week_score:last.week_score})))fail();return clone(value as C.CommunityPage);
}
export function validateCommunityDetail(value:unknown,owner:string,postId:string):C.CommunityDetail{const p=obj(value,['owner_id','server_now','post']);if(id(p.owner_id)!==owner)fail();const now=utc(p.server_now),row=post(p.post,owner,now,'detail');if(row.post_id!==postId||instant(row.updated_at)>instant(now))fail();return clone(value as C.CommunityDetail);}
export function validateCommunityCommentCursor(value:unknown):C.CommunityCommentCursor|null{if(value===null)return null;const c=obj(value,['created_at','id']);utc(c.created_at);id(c.id);return clone(value as C.CommunityCommentCursor);}
export function validateCommunityComments(value:unknown,owner:string,postId:string,previous:C.CommunityCommentCursor|null=null):C.CommunityCommentPage{
 const p=obj(value,['owner_id','server_now','post_id','content_revision','items','next_cursor']);if(id(p.owner_id)!==owner||id(p.post_id)!==postId)fail();const now=utc(p.server_now);int(p.content_revision);const comments=arr(p.items,30);let last=previous?`${instant(utc(previous.created_at))}:${id(previous.id)}`:'';
 for(const value of comments){const c=obj(value,['comment_id','post_id','owner_id','profile','body','created_at','can_delete']);id(c.comment_id);if(id(c.post_id)!==postId)fail();id(c.owner_id);profile(c.profile);if(!validateComment(c.body))fail();const stamp=utc(c.created_at),key=`${instant(stamp)}:${c.comment_id}`;if(key<=last||instant(stamp)>instant(now))fail();last=key;bool(c.can_delete);if(c.can_delete!==(c.owner_id===owner))fail();}
 const next=validateCommunityCommentCursor(p.next_cursor);if(next&&(!comments.length||`${instant(next.created_at)}:${next.id}`!==last))fail();return clone(value as C.CommunityCommentPage);
}
export function freezePublicationDocument(value:C.CommunityPublicationDocument):C.CommunityPublicationDocument{
 try{const d=obj(value,['schema_version','caption','description','visibility','ride','route','include_ride_route','media_ids']);choice(d.schema_version,[1]);if(!validateCaption(d.caption)||!validateDescription(d.description)||!validMediaIds(d.media_ids))fail();choice(d.visibility,['private','friends','public']);sourceBinding(d.ride,'ride');sourceBinding(d.route,'route');bool(d.include_ride_route);if(d.include_ride_route&&!d.ride||!hasPublicationContent(value))fail();return clone(value);}catch{throw Error('COMMUNITY_INVALID');}
}
export function freezeAttachmentSelection(value:C.CommunityAttachmentSelection):C.CommunityAttachmentSelection{
 try{const s=obj(value,['ride','route','include_ride_route']);sourceBinding(s.ride,'ride');sourceBinding(s.route,'route');bool(s.include_ride_route);if(s.include_ride_route&&!s.ride)fail();return clone(value);}catch{throw Error('COMMUNITY_INVALID');}
}
/** The canonical review uses the same sanitized projection as publication. A separate chosen route wins. */
export function validateAttachmentReview(value:unknown,owner:string,selection:C.CommunityAttachmentSelection):C.CommunityAttachmentReview{
 const p=obj(value,['owner_id','server_now','ride','route']);if(id(p.owner_id)!==owner)fail();utc(p.server_now);ride(p.ride);route(p.route,p.ride as C.CommunityRideSnapshot|null,1);
 const actualRide=p.ride as C.CommunityRideSnapshot|null,actualRoute=p.route as C.CommunityRouteSnapshot|null;
 if(selection.ride){if(!actualRide||actualRide.ride_id!==selection.ride.ride_id||actualRide.ride_revision!==selection.ride.ride_revision)fail();}else if(actualRide!==null)fail();
 const selected=selection.route??(selection.include_ride_route?selection.ride:null);
 if(!selected){if(actualRoute!==null)fail();}else if(!actualRoute||actualRoute.source==='legacy')fail();
 else if(selection.route){if(actualRoute.source!=='route'||actualRoute.source_id!==selection.route.route_id||actualRoute.source_revision!==selection.route.route_revision)fail();}
 else if(!selection.ride||actualRoute.source!=='ride'||actualRoute.source_id!==selection.ride.ride_id||actualRoute.source_revision!==selection.ride.ride_revision)fail();
 return clone(value as C.CommunityAttachmentReview);
}
export function freezeCommunityRequest(value:C.CommunityRequest):C.CommunityRequest{
 try{if(!value||typeof value!=='object')fail();const action=value.action,extras:Record<C.CommunityRequest['action'],readonly string[]>={publish:['document'],audience:['visibility'],delete_post:[],like:['liked'],save:['saved'],comment:['comment_id','body'],delete_comment:['comment_id'],report:['comment_id','reason','detail']};if(!Object.hasOwn(extras,action))fail();const r=obj(value,['schema_version','action','post_id','expected_revision',...extras[action]]);choice(r.schema_version,[1]);id(r.post_id);int(r.expected_revision,action==='publish'?0:1);switch(action){case'publish':freezePublicationDocument(r.document as C.CommunityPublicationDocument);break;case'audience':choice(r.visibility,['private','friends','public']);break;case'like':bool(r.liked);break;case'save':bool(r.saved);break;case'comment':id(r.comment_id);if(!validateComment(r.body))fail();break;case'delete_comment':id(r.comment_id);break;case'report':if(r.comment_id!==null)id(r.comment_id);choice(r.reason,['spam','harassment','privacy','dangerous','other']);if(!validateReportDetail(r.detail))fail();break;}return clone(value);}catch{throw Error('COMMUNITY_INVALID');}
}
export function validateCommunityError(value:unknown):C.CommunityErrorEnvelope|null{if(!value||typeof value!=='object'||Array.isArray(value)||!Object.hasOwn(value,'error'))return null;const e=obj(value,['error']).error;if(!e||typeof e!=='object'||Array.isArray(e))fail();const data=e as Record<string,unknown>;obj(data,data.code==='COMMUNITY_RATE_LIMITED'?['code','retry_after_ms']:['code']);choice(data.code,communityErrors);if(data.code==='COMMUNITY_RATE_LIMITED')int(data.retry_after_ms,1,86400000);return clone(value as C.CommunityErrorEnvelope);}
export function validateCommunityReceipt(value:unknown,owner:string,operation?:C.CommunityOperation):C.CommunityReceipt{
 const p=obj(value,['owner_id','operation_id','request','applied_at','result']);if(id(p.owner_id)!==owner)fail();id(p.operation_id);utc(p.applied_at);let request:C.CommunityRequest;try{request=freezeCommunityRequest(p.request as C.CommunityRequest);}catch{fail();}if(operation&&(p.operation_id!==operation.operationId||canonical(request)!==canonical(operation.request)))fail();
 const action=request.action,result=p.result as Record<string,unknown>|null;if(!result)fail();const keys=action==='publish'||action==='audience'||action==='delete_post'?['kind','post_id','content_revision','engagement_revision','state','visibility']:action==='like'?['kind','post_id','content_revision','engagement_revision','liked','like_count']:action==='save'?['kind','post_id','content_revision','saved']:action==='comment'||action==='delete_comment'?['kind','post_id','content_revision','engagement_revision','comment_id','state','comment_count']:['kind','post_id','comment_id','reported'];obj(result,keys);if(id(result.post_id)!==request.post_id)fail();
 switch(action){case'publish':case'audience':case'delete_post':choice(result.kind,['post']);int(result.content_revision,Math.max(1,request.expected_revision),request.expected_revision+1);int(result.engagement_revision);choice(result.state,[action==='delete_post'?'deleted':'published']);choice(result.visibility,['private','friends','public']);if(result.visibility!==(action==='publish'?request.document.visibility:action==='audience'?request.visibility:'private'))fail();break;case'like':choice(result.kind,['like']);if(result.content_revision!==request.expected_revision||result.liked!==request.liked)fail();int(result.engagement_revision);int(result.like_count,0);break;case'save':choice(result.kind,['save']);if(result.content_revision!==request.expected_revision||result.saved!==request.saved)fail();break;case'comment':case'delete_comment':choice(result.kind,['comment']);if(result.content_revision!==request.expected_revision||id(result.comment_id)!==request.comment_id)fail();int(result.engagement_revision);int(result.comment_count,0);choice(result.state,[action==='comment'?'published':'deleted']);break;case'report':choice(result.kind,['report']);if(result.comment_id!==request.comment_id||result.reported!==true)fail();}
 return clone(value as C.CommunityReceipt);
}
export function validatePostReservation(value:unknown,owner:string,postId:string):C.CommunityPostReservation{const p=obj(value,['owner_id','post_id','revision','state']);if(id(p.owner_id)!==owner||id(p.post_id)!==postId)fail();choice(p.state,['draft','published']);int(p.revision,p.state==='draft'?0:1);return clone(value as C.CommunityPostReservation);}
export function validateMediaReservation(value:unknown,owner:string,postId:string,mediaId:string):C.CommunityMediaReservation{const p=obj(value,['post_id','media_id','bucket','path','expires_at','state']);if(id(p.post_id)!==postId||id(p.media_id)!==mediaId||p.bucket!=='ride-post-media'||p.path!==`${owner}/${postId}/${mediaId}.jpg`)fail();utc(p.expires_at);choice(p.state,['reserved','committed']);return clone(value as C.CommunityMediaReservation);}
export function validateMediaCommit(value:unknown,postId:string,mediaId:string,expected:Omit<C.CommunityVerifiedMedia,'media_id'|'validation'>):C.CommunityMediaCommit{const p=obj(value,['post_id','media_id','descriptor']);if(id(p.post_id)!==postId||id(p.media_id)!==mediaId)fail();const d=obj(p.descriptor,['mime','sha256','byte_count','width','height','blurhash']),keys=['mime','sha256','byte_count','width','height'] as const;if(!validPhotoDescriptor(d)||keys.some(k=>d[k]!==expected[k]))fail();return clone(value as C.CommunityMediaCommit);}
/** Signed URLs are request-bound, project-local and never persisted by this module. */
export function validateCommunityMediaURL(value:unknown,projectUrl:string,p:C.CommunityPost,m:C.CommunityMedia):C.CommunityMediaURL{
 const r=obj(value,['postId','mediaId','sha256','url','expiresIn']);if(r.postId!==p.post_id||r.mediaId!==m.media_id||r.sha256!==m.sha256||r.expiresIn!==60||typeof r.url!=='string'||!p.media.some(asset=>asset.media_id===m.media_id&&canonical(asset)===canonical(m)))fail();
 try{const u=new URL(r.url),project=new URL(projectUrl),base=`/storage/v1/object/sign/`,extensions=m.mime==='image/jpeg'?['jpg','jpeg']:m.mime==='image/png'?['png']:['webp'],legacyPrefix=`${base}ride-community/${p.owner_id}/${p.post_id}/`,legacyName=u.pathname.startsWith(legacyPrefix)?u.pathname.slice(legacyPrefix.length).split('.'):[],path=m.validation==='decoded_jpeg_v1'?u.pathname===`${base}ride-post-media/${p.owner_id}/${p.post_id}/${m.media_id}.jpg`:legacyName.length===2&&isCommunityId(legacyName[0])&&extensions.includes(legacyName[1]);if(u.protocol!=='https:'||u.origin!==project.origin||u.username||u.password||u.hash||!path||u.searchParams.getAll('token').length!==1||!u.searchParams.get('token')||[...u.searchParams.keys()].some(k=>k!=='token'))fail();}catch{fail();}return clone(value as C.CommunityMediaURL);
}
