import {isCommunityId} from './model';
import type {CommunityPhotoDisk,CommunityPhotoKey} from './CommunityPhotoStore';
let database:Promise<IDBDatabase>|null=null;
function guard(owner:string,key?:CommunityPhotoKey){if(!isCommunityId(owner))throw Error('ACCOUNT_CHANGED');if(key&&(!isCommunityId(key.post_id)||!isCommunityId(key.media_id)))throw Error('COMMUNITY_PHOTO_INVALID');}
const open=()=>database??=new Promise<IDBDatabase>((resolve,reject)=>{if(typeof indexedDB==='undefined'){reject(Error('LOCAL_READ_FAILED'));return;}const request=indexedDB.open('ride-community-photos-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('photos',{keyPath:['owner','post','media']}).createIndex('owner','owner');request.onsuccess=()=>resolve(request.result);request.onerror=()=>{database=null;reject(Error('LOCAL_READ_FAILED'));};});
const done=(tx:IDBTransaction)=>new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(Error('LOCAL_WRITE_FAILED'));});
export const communityPhotoDisk:CommunityPhotoDisk={
 async read(owner,key){guard(owner,key);const tx=(await open()).transaction('photos','readonly');return new Promise((resolve,reject)=>{const request=tx.objectStore('photos').get([owner,key.post_id,key.media_id]);request.onsuccess=()=>{const bytes=request.result?.bytes;if(bytes===undefined){resolve(null);return;}if(!(bytes instanceof Uint8Array)||bytes.byteLength<1||bytes.byteLength>1048576){reject(Error('COMMUNITY_PHOTO_INVALID'));return;}resolve(Uint8Array.from(bytes));};request.onerror=()=>reject(Error('LOCAL_READ_FAILED'));});},
 async list(owner){guard(owner);const tx=(await open()).transaction('photos','readonly');return new Promise((resolve,reject)=>{const request=tx.objectStore('photos').index('owner').getAllKeys(owner);request.onsuccess=()=>{try{const keys=request.result.map(key=>{if(!Array.isArray(key)||key.length!==3||key[0]!==owner||!isCommunityId(key[1])||!isCommunityId(key[2]))throw Error('LOCAL_READ_FAILED');return {post_id:key[1],media_id:key[2]};});resolve(keys);}catch{reject(Error('LOCAL_READ_FAILED'));}};request.onerror=()=>reject(Error('LOCAL_READ_FAILED'));});},
 async writeNew(owner,key,bytes){guard(owner,key);const tx=(await open()).transaction('photos','readwrite'),completion=done(tx);tx.objectStore('photos').add({owner,post:key.post_id,media:key.media_id,bytes:Uint8Array.from(bytes)});await completion;},
 async remove(owner,key){guard(owner,key);const tx=(await open()).transaction('photos','readwrite'),completion=done(tx);tx.objectStore('photos').delete([owner,key.post_id,key.media_id]);await completion;},
 async removeOwner(owner){guard(owner);const tx=(await open()).transaction('photos','readwrite'),completion=done(tx),request=tx.objectStore('photos').index('owner').openCursor(owner);request.onsuccess=()=>{const cursor=request.result;if(cursor){cursor.delete();cursor.continue();}};await completion;},
};
