import React from 'react';
import {Pressable,StyleSheet,View} from 'react-native';
import {Button,Note,Row,T} from '../../components/ui';
import {theme} from '../../lib/theme';
import {useApp} from '../../state/AppState';
import {CommunityMediaView} from './CommunityMedia';
import {CommunityMonogram,RideStatistics,RouteOutline} from './CommunityParts';
import type {CommunityPost} from './types';
import {communityPostBinding,type CommunityPostActions,type CommunityTranslator} from './uiTypes';
export function PostCard({post,port,t,visible,act,detail=false,showMedia=true}:{post:CommunityPost;port:CommunityPostActions;t:CommunityTranslator;visible:boolean;detail?:boolean;showMedia?:boolean;act:(post:CommunityPost,action:'like'|'save'|'open'|'route'|'share')=>void}){
 const {colors}=useApp(),enabled=port.gate.focused&&port.gate.foreground&&!port.gate.moving,mutating=enabled&&port.ready&&port.read.fresh&&!port.read.error&&port.gate.online;
 const pending=port.pending.filter(op=>op.request.post_id===post.post_id&&op.request.expected_revision===post.content_revision),like=pending.filter(op=>op.request.action==='like').at(-1)?.request,save=pending.filter(op=>op.request.action==='save').at(-1)?.request,liked=like?.action==='like'?like.liked:post.engagement.liked,saved=save?.action==='save'?save.saved:post.engagement.saved;
 if(!port.current(port.generation)||!port.postCurrent(communityPostBinding(post)))return null;
 return <View style={{borderRadius:theme.radius.card,borderWidth:StyleSheet.hairlineWidth,borderColor:colors.line,backgroundColor:colors.surface,padding:18,gap:16,marginBottom:16}}><Pressable accessibilityRole="button" accessibilityLabel={t('m7.openPost',{name:post.profile.name})} disabled={!enabled} onPress={()=>act(post,'open')} style={{minHeight:44}}><Row style={{alignItems:'flex-start'}}><CommunityMonogram name={post.profile.name}/><View style={{flex:1,gap:2}}><T weight="semibold">{post.profile.name}</T><T size={12} muted>{`@${post.profile.handle}`}</T><T size={12} muted>{t(`m7.audience.${post.visibility}`)}</T></View></Row></Pressable>{post.caption&&<T size={detail?20:17} weight="medium" numberOfLines={detail?undefined:3}>{post.caption}</T>}{showMedia&&post.media.length>0&&<View style={{gap:8}}><CommunityMediaView post={post} media={post.media[0]} port={port} t={t} visible={visible}/>{post.media.length>1&&<T size={12} muted>{t('m7.photo',{index:1,count:post.media.length})}</T>}{post.media[0].validation==='legacy_unverified'&&<T size={12} muted>{t('m7.legacyPhoto')}</T>}</View>}{post.ride&&<RideStatistics ride={post.ride} units={port.units} t={t}/>}{post.legacy_claimed_speed_kmh!==null&&<View style={{gap:5}}><T numeric size={24}>{`${(post.legacy_claimed_speed_kmh*(port.units==='mph'?1/1.609344:1)).toFixed(1)} ${port.units==='mph'?'mph':'km/h'}`}</T><T muted size={12}>{t('m7.legacyReported')}</T></View>}{post.route&&<View style={{gap:10}}>{(!post.media.length||detail)&&<RouteOutline route={post.route} t={t}/>}<Button small secondary icon="map-outline" label={t('m7.openRoute')} disabled={!enabled||post.route.geometryStatus!=='trimmed'} onPress={()=>act(post,'route')}/></View>}{detail&&post.description&&<T>{post.description}</T>}<Row style={{flexWrap:'wrap',gap:8}}><Button small secondary icon={liked?'heart':'heart-outline'} label={t(liked?'m7.unlike':'m7.like')} disabled={!mutating} onPress={()=>act(post,'like')}/><Button small secondary icon="chatbubble-outline" label={t('m7.comments',{count:post.engagement.comments})} disabled={!enabled} onPress={()=>act(post,'open')}/><Button small secondary icon={saved?'bookmark':'bookmark-outline'} label={t(saved?'m7.unsave':'m7.save')} disabled={!mutating} onPress={()=>act(post,'save')}/><Button small secondary icon="share-outline" label={t('m7.share')} disabled={!mutating} onPress={()=>act(post,'share')}/></Row><T size={12} muted>{t('m7.likes',{count:post.engagement.likes})}</T>{pending.length>0&&<Note>{t('m7.queued')}</Note>}</View>;
}
