import type {Session} from '@supabase/supabase-js';
import {accountClient,isAccountCurrent,type AuthScope} from '../../state/AuthState';
import {publicService} from '../../lib/publicService';
import {validPhotoDescriptor,type CommunityPhotoDescriptor} from './content';
import {freezeAttachmentSelection,freezeCommunityFilter,freezeCommunityRequest,isCommunityId,validateAttachmentReview,validateCommunityCommentCursor,validateCommunityComments,validateCommunityCursor,validateCommunityDetail,validateCommunityError,validateCommunityMediaURL,validateCommunityPage,validateCommunityReceipt,validateMediaCommit,validateMediaReservation,validatePostReservation} from './model';
import type * as C from './types';
export class CommunityServiceError extends Error{readonly retryAfterMs:number|null;constructor(value:C.CommunityErrorEnvelope){super(value.error.code);this.name='CommunityServiceError';this.retryAfterMs=value.error.code==='COMMUNITY_RATE_LIMITED'?value.error.retry_after_ms:null;}}
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function inputId(value:string){if(!isCommunityId(value))throw Error('COMMUNITY_INVALID');}
function limit(value:number){if(!Number.isInteger(value)||value<1||value>30)throw Error('COMMUNITY_INVALID');}
function descriptor(value:CommunityPhotoDescriptor){const keys=['mime','sha256','byte_count','width','height','blurhash'];if(!validPhotoDescriptor(value)||Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))throw Error('COMMUNITY_INVALID');return Object.freeze({...value});}
function transport(scope:AuthScope,session:Session){
 current(scope,session);const client=accountClient(scope,session);
 return {rpc:async(name:string,args:Record<string,unknown>,write=false):Promise<unknown>=>{
  current(scope,session);let result;try{result=await client.rpc(name,args);}catch{current(scope,session);throw Error('COMMUNITY_UNAVAILABLE');}current(scope,session);
  if(result.error){if(['PGRST301','PGRST302'].includes(result.error.code))throw Error('COMMUNITY_AUTH_REQUIRED');if(result.error.message==='ACCOUNT_DELETION_PENDING')throw Error('ACCOUNT_DELETION_PENDING');throw Error('COMMUNITY_UNAVAILABLE');}
  const error=validateCommunityError(result.data);if(error&&!write)throw new CommunityServiceError(error);return result.data;
 },edge:async(name:string,body:Record<string,unknown>):Promise<unknown>=>{
  current(scope,session);let result;try{result=await client.functions.invoke(name,{body});}catch{current(scope,session);throw Error('COMMUNITY_UNAVAILABLE');}current(scope,session);
  let data:unknown=result.data;if(result.error){const response=result.error as {context?:unknown};if(response.context instanceof Response){try{data=await response.context.json();}catch{data=null;}current(scope,session);}const known=validateCommunityError(data);if(known)throw new CommunityServiceError(known);throw Error('COMMUNITY_UNAVAILABLE');}
  const error=validateCommunityError(data);if(error)throw new CommunityServiceError(error);return data;
 }};
}
export async function getCommunityFeed(scope:AuthScope,session:Session,selected:C.CommunityFilter,cursor:C.CommunityCursor|null=null,pageSize=20):Promise<C.CommunityPage>{current(scope,session);limit(pageSize);const filter=freezeCommunityFilter(selected),frozen=validateCommunityCursor(cursor,scope.userId!);if(frozen&&frozen.mode!==filter.mode)throw Error('COMMUNITY_INVALID');return validateCommunityPage(await transport(scope,session).rpc('rs_community_feed',{p_filter:filter,p_cursor:frozen,p_limit:pageSize}),scope.userId!,filter,frozen);}
export async function getCommunityPost(scope:AuthScope,session:Session,postId:string):Promise<C.CommunityDetail>{current(scope,session);inputId(postId);return validateCommunityDetail(await transport(scope,session).rpc('rs_community_post',{p_post_id:postId}),scope.userId!,postId);}
export async function getCommunityAttachmentReview(scope:AuthScope,session:Session,selection:C.CommunityAttachmentSelection):Promise<C.CommunityAttachmentReview>{current(scope,session);const frozen=freezeAttachmentSelection(selection),value=await transport(scope,session).rpc('rs_community_attachment_review',{p_ride:frozen.ride,p_route:frozen.route,p_include_ride_route:frozen.include_ride_route});return validateAttachmentReview(value,scope.userId!,frozen);}
export async function getCommunityComments(scope:AuthScope,session:Session,postId:string,cursor:C.CommunityCommentCursor|null=null,pageSize=30):Promise<C.CommunityCommentPage>{current(scope,session);inputId(postId);limit(pageSize);const frozen=validateCommunityCommentCursor(cursor);return validateCommunityComments(await transport(scope,session).rpc('rs_community_comments',{p_post_id:postId,p_cursor:frozen,p_limit:pageSize}),scope.userId!,postId,frozen);}
export async function mutateCommunity(scope:AuthScope,session:Session,operation:C.CommunityOperation):Promise<C.CommunityMutationResponse>{current(scope,session);inputId(operation.operationId);const frozen=Object.freeze({operationId:operation.operationId,request:freezeCommunityRequest(operation.request)}),value=await transport(scope,session).rpc('rs_community_mutate',{p_operation_id:frozen.operationId,p_request:frozen.request},true);return validateCommunityError(value)??validateCommunityReceipt(value,scope.userId!,frozen);}
export async function getCommunityOperation(scope:AuthScope,session:Session,operationId:string):Promise<C.CommunityReceipt|null>{current(scope,session);inputId(operationId);const value=await transport(scope,session).rpc('rs_community_operation',{p_operation_id:operationId});if(value===null)return null;const receipt=validateCommunityReceipt(value,scope.userId!);if(receipt.operation_id!==operationId)throw Error('COMMUNITY_INVALID_RESPONSE');return receipt;}
export async function reserveCommunityPost(scope:AuthScope,session:Session,postId:string):Promise<C.CommunityPostReservation>{current(scope,session);inputId(postId);return validatePostReservation(await transport(scope,session).rpc('rs_community_reserve_post',{p_post_id:postId}),scope.userId!,postId);}
export async function reserveCommunityMedia(scope:AuthScope,session:Session,postId:string,mediaId:string,value:CommunityPhotoDescriptor):Promise<C.CommunityMediaReservation>{current(scope,session);inputId(postId);inputId(mediaId);const frozen=descriptor(value);return validateMediaReservation(await transport(scope,session).rpc('rs_community_reserve_media',{p_post_id:postId,p_media_id:mediaId,p_descriptor:frozen}),scope.userId!,postId,mediaId);}
export async function commitCommunityMedia(scope:AuthScope,session:Session,postId:string,mediaId:string,value:CommunityPhotoDescriptor):Promise<C.CommunityMediaCommit>{current(scope,session);inputId(postId);inputId(mediaId);const frozen=descriptor(value);return validateMediaCommit(await transport(scope,session).edge('community-media-commit',{postId,mediaId}),postId,mediaId,frozen);}
/** Root owns the short-lived scope cache and revocation. This function does not save a URL. */
export async function getCommunityMediaURL(scope:AuthScope,session:Session,post:C.CommunityPost,media:C.CommunityMedia):Promise<C.CommunityMediaURL>{current(scope,session);inputId(post.post_id);inputId(media.media_id);const binding=JSON.parse(JSON.stringify({post,media})) as {post:C.CommunityPost;media:C.CommunityMedia},result=await transport(scope,session).edge('community-media-url',{postId:post.post_id,mediaId:media.media_id});return validateCommunityMediaURL(result,process.env.EXPO_PUBLIC_SUPABASE_URL??publicService.url,binding.post,binding.media);}
