import type {ApprovalPage,ApprovalSummary,AttemptSnapshot,RaceCourseSnapshot,RaceCursor,RacePage,RaceResults,RaceSnapshot} from '../features/races/types';
import type {RacePageState,RaceRouteOption} from '../features/races/uiTypes';
import type {RouteCursor,RoutePage} from '../features/routes/syncTypes';
export type RaceReadSnapshot={loaded:boolean;fresh:boolean;error:string|null;races:RaceSnapshot[];racesPage:RacePageState;routes:RaceRouteOption[];routesPage:RacePageState;
 race:RaceSnapshot|null;selectedId:string|null;detailLoading:boolean;detailFresh:boolean;detailError:string|null;course:RaceCourseSnapshot|null;courseLoading:boolean;courseError:string|null;
 attempt:AttemptSnapshot|null;attemptId:string|null;results:RaceResults|null;resultsLoading:boolean;resultsFresh:boolean;resultsError:string|null;
 approvals:{route_id:string|null;route_revision:number|null;items:ApprovalSummary[];loading:boolean;fresh:boolean;error:string|null}};
export interface RaceReadPort{guard:()=>void;list:(cursor:RaceCursor|null)=>Promise<RacePage>;routes:(cursor:RouteCursor|null)=>Promise<RoutePage>;race:(id:string)=>Promise<RaceSnapshot|null>;course:(id:string)=>Promise<RaceCourseSnapshot>;attempt:(id:string)=>Promise<AttemptSnapshot|null>;attempts:(raceId:string)=>Promise<AttemptSnapshot[]>;results:(id:string)=>Promise<RaceResults>;approvals:(id:string,revision:number)=>Promise<ApprovalPage>}
const page=():RacePageState=>({loading:false,fresh:false,error:null,hasMore:false});
const blank=():RaceReadSnapshot=>({loaded:false,fresh:false,error:null,races:[],racesPage:page(),routes:[],routesPage:page(),race:null,selectedId:null,detailLoading:false,detailFresh:false,detailError:null,course:null,courseLoading:false,courseError:null,attempt:null,attemptId:null,results:null,resultsLoading:false,resultsFresh:false,resultsError:null,approvals:{route_id:null,route_revision:null,items:[],loading:false,fresh:false,error:null}});
/** Read authority is lost synchronously on suspension. Held replies cannot
 * restore an earlier owner, selected race, course or reviewed approval. */
export class RaceReader{
 private state=blank();private version=0;private selection=0;private bundleVersion=0;private approvalsVersion=0;private resultsVersion=0;private closed=false;private listeners=new Set<()=>void>();private cursor:RaceCursor|null=null;private routeCursor:RouteCursor|null=null;
 constructor(private port:RaceReadPort){}
 getSnapshot=()=>this.state;subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};
 private guard(version=this.version){this.port.guard();if(this.closed||version!==this.version)throw Error('RACE_CHANGED');}
 private publish(patch:Partial<RaceReadSnapshot>){if(this.closed)return;this.state={...this.state,...patch};for(const listener of this.listeners)listener();}
 private code(error:unknown){return error instanceof Error&&['ACCOUNT_CHANGED','RACE_CHANGED','RACE_RATE_LIMITED','RACE_AUTH_REQUIRED','RACE_DISABLED','RACE_PROFILE_REQUIRED','LOCAL_READ_FAILED'].includes(error.message)?error.message:'RACE_UNAVAILABLE';}
 suspend(){this.version++;this.selection++;this.approvalsVersion++;this.resultsVersion++;this.publish({fresh:false,detailFresh:false,resultsFresh:false,racesPage:{...this.state.racesPage,loading:false,fresh:false},routesPage:{...this.state.routesPage,loading:false,fresh:false},detailLoading:false,courseLoading:false,resultsLoading:false,approvals:{...this.state.approvals,loading:false,fresh:false}});}
 close(){this.suspend();this.closed=true;this.listeners.clear();}
 async list(more=false){const v=this.version;try{this.guard(v);if(this.state.racesPage.loading||more&&(!this.state.racesPage.fresh||!this.cursor))return;this.publish({racesPage:{...this.state.racesPage,loading:true,error:null}});const result=await this.port.list(more?this.cursor:null);this.guard(v);const items=more?[...this.state.races,...result.items]:result.items;if(items.length>300||new Set(items.map(r=>r.id)).size!==items.length)throw Error('RACE_CHANGED');this.cursor=result.next_cursor;this.publish({loaded:true,fresh:true,error:null,races:items,racesPage:{loading:false,fresh:true,error:null,hasMore:!!this.cursor}});}catch(error){try{this.guard(v);const code=this.code(error);this.publish({fresh:false,error:code,racesPage:{...this.state.racesPage,loading:false,fresh:false,error:code}});}catch{/* Old read cannot publish. */}}}
 async routes(more=false){const v=this.version;try{this.guard(v);if(this.state.routesPage.loading||more&&(!this.state.routesPage.fresh||!this.routeCursor))return;this.publish({routesPage:{...this.state.routesPage,loading:true,error:null}});const result=await this.port.routes(more?this.routeCursor:null);this.guard(v);const mapped=result.items.flatMap(r=>r.document.category==='bicycle'?[]:[{id:r.id,revision:r.revision,title:r.document.title,category:r.document.category} as RaceRouteOption]);const items=more?[...this.state.routes,...mapped]:mapped;if(items.length>300||new Set(items.map(r=>r.id)).size!==items.length)throw Error('RACE_CHANGED');this.routeCursor=result.next_cursor;this.publish({routes:items,routesPage:{loading:false,fresh:true,error:null,hasMore:!!this.routeCursor}});}catch(error){try{this.guard(v);this.publish({routesPage:{...this.state.routesPage,loading:false,fresh:false,error:this.code(error)}});}catch{/* Old route page cannot publish. */}}}
 async open(id:string){this.guard();++this.selection;++this.resultsVersion;this.publish({race:null,selectedId:id,detailLoading:true,detailFresh:false,detailError:null,course:null,courseError:null,courseLoading:false,attempt:null,attemptId:null,results:null,resultsLoading:false,resultsFresh:false,resultsError:null});await this.refreshDetail();}
 async refreshDetail(){const id=this.state.selectedId,v=this.version,s=this.selection,b=++this.bundleVersion;if(!id)return;try{this.guard(v);let race:RaceSnapshot|null=null,own:AttemptSnapshot|null=null;
  for(let pass=0;pass<2;pass++){race=await this.port.race(id);this.guard(v);if(s!==this.selection||b!==this.bundleVersion)return;if(!race)break;const items=await this.port.attempts(id);this.guard(v);if(s!==this.selection||b!==this.bundleVersion)return;own=items.find(a=>['reserved','armed','upload_pending','queued','verifying'].includes(a.state))??items.at(-1)??null;
   const historical=!!own&&['verified','rejected','aborted','dnf'].includes(own.state);
   if(own&&(own.race_id!==race.id||own.approval_id!==race.approval.id||own.config_hash!==race.approval.config_hash||own.member_generation>race.self_member.member_generation||!historical&&(own.member_generation!==race.self_member.member_generation||race.self_member.state!=='accepted')))throw Error('RACE_CHANGED');if(!own||historical||own.schedule_epoch===race.schedule_epoch&&own.common_start_at===race.common_start_at)break;if(pass===1)throw Error('RACE_CHANGED');
  }
  const old=this.state.race,prior=this.state.attempt;if(race&&old&&race.id===old.id&&race.revision<old.revision||own&&prior&&own.id===prior.id&&own.revision<prior.revision)throw Error('RACE_CHANGED');const changed=!race||!old||race.approval.id!==old.approval.id||race.approval.config_hash!==old.approval.config_hash||race.self_member.member_generation!==old.self_member.member_generation;
  const resultsChanged=changed||race?.revision!==old?.revision||race?.self_member.state!==old?.self_member.state||own?.id!==prior?.id||own?.revision!==prior?.revision||own?.state!==prior?.state;
  if(resultsChanged)++this.resultsVersion;
  this.publish({race,attempt:own,attemptId:own?.id??null,detailLoading:false,detailFresh:!!race,detailError:race?null:'RACE_CHANGED',...(changed?{course:null}:{}),...(resultsChanged?{results:null,resultsLoading:false,resultsError:null,resultsFresh:false}:{})});
 }catch(error){try{this.guard(v);if(s===this.selection&&b===this.bundleVersion)this.publish({detailLoading:false,detailFresh:false,detailError:this.code(error)});}catch{/* Closed selection. */}}}
 async loadCourse(){const race=this.state.race,v=this.version,s=this.selection;if(!race||!this.state.detailFresh||race.self_member.state!=='accepted')return;try{this.guard(v);this.publish({courseLoading:true,courseError:null});const course=await this.port.course(race.id);this.guard(v);if(s!==this.selection)return;if(this.state.race?.approval.config_hash!==course.config_hash||this.state.race.approval.id!==course.approval_id||this.state.race.self_member.state!=='accepted'||this.state.race.self_member.member_generation!==race.self_member.member_generation)throw Error('RACE_CHANGED');this.publish({course,courseLoading:false});}catch(error){try{this.guard(v);if(s===this.selection)this.publish({courseLoading:false,courseError:this.code(error)});}catch{/* Closed course. */}}}
 async loadAttempt(id:string){const v=this.version,s=this.selection,b=this.bundleVersion,raceId=this.state.selectedId;try{this.guard(v);const attempt=await this.port.attempt(id);this.guard(v);if(s!==this.selection||b!==this.bundleVersion||attempt&&attempt.race_id!==raceId)return;const prior=this.state.attempt,race=this.state.race;if(attempt&&prior&&attempt.id===prior.id&&attempt.revision<prior.revision||attempt&&race&&(attempt.schedule_epoch!==race.schedule_epoch||attempt.common_start_at!==race.common_start_at||attempt.config_hash!==race.approval.config_hash||attempt.member_generation!==race.self_member.member_generation))throw Error('RACE_CHANGED');this.publish({attempt,attemptId:id});}catch(error){try{this.guard(v);if(s===this.selection&&b===this.bundleVersion)this.publish({detailFresh:false,detailError:this.code(error)});}catch{/* Closed attempt. */}}}
 async loadResults(){const id=this.state.selectedId,v=this.version,s=this.selection,r=++this.resultsVersion;if(!id)return;try{this.guard(v);this.publish({resultsLoading:true,resultsFresh:false,resultsError:null});const results=await this.port.results(id);this.guard(v);if(s!==this.selection||r!==this.resultsVersion)return;this.publish({results,resultsLoading:false,resultsFresh:true});}catch(error){try{this.guard(v);if(s===this.selection&&r===this.resultsVersion)this.publish({resultsLoading:false,resultsFresh:false,resultsError:this.code(error)});}catch{/* Closed results. */}}}
 async loadApprovals(route:RaceRouteOption){const v=this.version,a=++this.approvalsVersion;try{this.guard(v);this.publish({approvals:{route_id:route.id,route_revision:route.revision,items:[],loading:true,fresh:false,error:null}});const result=await this.port.approvals(route.id,route.revision);this.guard(v);if(a!==this.approvalsVersion)return;this.publish({approvals:{route_id:route.id,route_revision:route.revision,items:result.items,loading:false,fresh:true,error:null}});}catch(error){try{this.guard(v);if(a===this.approvalsVersion)this.publish({approvals:{...this.state.approvals,loading:false,fresh:false,error:this.code(error)}});}catch{/* Old approval selection. */}}}
 async refresh(){await Promise.allSettled([this.list(),this.routes(),this.refreshDetail()]);}
}
