#!/usr/bin/env bash
# Run only on a disposable macOS CI checkout. Native projects are generated by Expo.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
APP="$ROOT/ExpoRideSpeed"
VARIANT="${APP_VARIANT:?Set APP_VARIANT}"
case "$VARIANT" in
  release) CONFIGURATION=Release ;;
  development) CONFIGURATION=Debug ;;
  *) echo 'APP_VARIANT must be release or development' >&2; exit 1 ;;
esac
[[ "$(uname -s)" == Darwin ]] || { echo 'Native iOS builds require the macOS runner.' >&2; exit 1; }
[[ "${IOS_BUILD_NUMBER:-}" =~ ^[1-9][0-9]{0,3}\.[0-9]{1,2}\.[0-9]{1,2}$ ]] || exit 1
OUT="$ROOT/build/$VARIANT"
mkdir -p "$OUT"
cd "$APP"
if [[ "$VARIANT" == release ]]; then
  npm ci --omit=dev
  # Fail closed if a dependency later reintroduces development-native code.
  for name in expo-dev-client expo-dev-launcher expo-dev-menu; do
    [[ ! -d "node_modules/$name" ]] || { echo "Release contains $name" >&2; exit 1; }
  done
else
  npm ci --include=dev
fi
# Do not set NODE_ENV=production for Debug; dependencies differ via npm omit only.
CI=1 npx --no-install expo prebuild --platform ios --clean --no-install
pod install --project-directory=ios | tee "$OUT/pods.log"
WORKSPACE="$(find "$APP/ios" -maxdepth 1 -name '*.xcworkspace' -print)"
[[ -n "$WORKSPACE" && "$(printf '%s\n' "$WORKSPACE" | wc -l | tr -d ' ')" == 1 ]] || { echo 'Expected one generated workspace' >&2; exit 1; }
xcodebuild -list -json -workspace "$WORKSPACE" > "$OUT/workspace.json"
SCHEME="$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); s=d["workspace"]["schemes"]; expected=sys.argv[2]; assert expected in s, s; print(expected)' "$OUT/workspace.json" "$(basename "$WORKSPACE" .xcworkspace)")"
xcodebuild -showBuildSettings -json -workspace "$WORKSPACE" -scheme "$SCHEME" \
  -configuration "$CONFIGURATION" -sdk iphoneos -destination 'generic/platform=iOS' \
  CODE_SIGNING_ALLOWED=NO > "$OUT/build-settings.json"
python3 "$ROOT/scripts/verify-generated-ios.py" "$APP/ios" "$VARIANT" "$OUT/build-settings.json"
xcodebuild archive \
  -workspace "$WORKSPACE" -scheme "$SCHEME" \
  -configuration "$CONFIGURATION" -sdk iphoneos \
  -destination 'generic/platform=iOS' \
  -archivePath "$OUT/RideSpeed.xcarchive" \
  -derivedDataPath "$OUT/DerivedData" \
  CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' \
  ARCHS=arm64 ONLY_ACTIVE_ARCH=NO \
  | tee "$OUT/xcodebuild.log"
python3 "$ROOT/scripts/package-ipa.py" \
  --archive "$OUT/RideSpeed.xcarchive" --output "$OUT/artifacts" \
  --variant "$VARIANT" --build-number "$IOS_BUILD_NUMBER" \
  --version "$(node -p "require('./package.json').version")"
# Symbols stay in a short-lived diagnostic artifact, separate from friend downloads.
if [[ -d "$OUT/RideSpeed.xcarchive/dSYMs" ]]; then
  ditto -c -k --keepParent "$OUT/RideSpeed.xcarchive/dSYMs" "$OUT/dSYMs.zip"
fi
