export const m4En={
 'm4.cachedRoad':'Cached road preview · calculate again to save',
 'm4.providerCredit':'Powered by Geoapify',
 'm4.searchCoverage':'Place search is limited to Thailand in this free pilot.',
 'm4.error.distanceLimit':'This free pilot supports route pins within 200 km and road routes up to 450 km. Choose a shorter route.',
 'm4.hiddenGeometry':'This route is too short to show safely. Its exact location is hidden.','m4.sharedGeometry':'Shared view · the first and last 200 m are hidden.','m4.synced':'Saved to your account','m4.localSaved':'Saved on this device · waiting to sync','m4.deleteConfirm':'Delete “{{name}}” from your saved routes?',
 'm4.title':'Plan a route','m4.search':'Search a place','m4.searchHint':'Type at least 3 characters','m4.searchEmpty':'No places found. Try another name.','m4.searching':'Searching…',
 'm4.start':'Start','m4.via':'Stop {{number}}','m4.finish':'Finish','m4.tapStart':'Tap the map to choose your start.','m4.tapFinish':'Choose a finish, or search for a place.','m4.tapNext':'Tap to add the next stop. Drag the selected pin to adjust it.',
 'm4.stops':'Stops','m4.stopCount':'{{count}} / 12 stops','m4.undo':'Undo last pin change','m4.reverse':'Reverse direction','m4.roundTrip':'Return to start','m4.overview':'Show the whole route','m4.recenter':'Your location','m4.snap':'Find a road route','m4.calculating':'Finding a road route…','m4.unsnapped':'Pins only · road route not calculated','m4.road':'Road route','m4.recorded':'Recorded route','m4.freeFlow':'Estimated time · no live traffic','m4.distance':'Distance','m4.time':'Estimated time','m4.minutes':'{{count}} min','m4.hours':'{{hours}} h {{minutes}} min',
 'm4.save':'Save route','m4.saved':'Route saved','m4.name':'Route name','m4.namePlaceholder':'Where does this route take you?','m4.visibility':'Who can see this route?','m4.private':'Only me','m4.friends':'Friends','m4.public':'Everyone in the app','m4.privateHint':'Your full route stays private.','m4.shareHint':'Shared routes hide at least the first and last 200 m. Short routes may be hidden completely.','m4.sharePreview':'Preview shared route','m4.previewUnavailable':'Save and sync first to preview what others can see.','m4.remove':'Remove stop','m4.up':'Move earlier','m4.down':'Move later','m4.renameStop':'Stop name','m4.pinLimit':'You can add up to 12 stops.','m4.edit':'Edit route','m4.delete':'Delete route','m4.close':'Back to map','m4.cancel':'Cancel','m4.done':'Done',
 'm4.consentTitle':'Find places and road routes','m4.consentBody':'Ride Speed sends the search text and route pins you choose to Geoapify to find places and calculate roads. Your live location is not sent automatically.','m4.consentAccept':'Allow for route planning','m4.consentDecline':'Keep using map pins','m4.offline':'Your pins stay on this device. Connect to calculate roads or search places.','m4.locked':'Route editing is paused while moving. Stop before editing your route.','m4.toMap':'Return to map','m4.attribution':'Routing data','m4.unsaved':'Leave this draft?','m4.unsavedBody':'Your current draft stays on this device. You can return to it later.','m4.loadError':'The saved route could not be loaded.','m4.bicycle':'For this imported bicycle route, use recorded geometry. Motor-vehicle routing is unavailable.',
 'm4.error.auth':'Sign in to search places and calculate roads.','m4.error.invalid':'Check the route pins or search text.','m4.error.large':'This route is too large. Try fewer stops or a shorter route.','m4.error.noRoute':'No road route connects these pins. Move a pin and try again.','m4.error.quota':'The free routing allowance has been reached. Your draft stays saved on this device.','m4.error.throttled':'Wait a moment before trying again.','m4.error.provider':'Road routing is unavailable right now. Your pins are kept on this device.','m4.error.configuration':'Online road routing is not configured yet. You can still place pins.','m4.error.response':'The routing response could not be checked. Try again.','m4.error.account':'Your account changed. Open the route again.','m4.error.deleted':'Account deletion is pending. Route changes are paused.','m4.error.title':'Enter a route name between 1 and 80 characters.','m4.error.stops':'Choose 2–12 valid stops with names.','m4.error.notReady':'Calculate a road route or use a recorded ride before saving.','m4.error.storage':'The route draft could not be saved on this device. Retry before leaving.','m4.error.conflict':'This route changed on another device. Review the latest version before saving.','m4.error.unavailable':'This route is no longer available.','m4.retry':'Try again',
} as const;
export const m4Th:Record<keyof typeof m4En,string>={
 'm4.cachedRoad':'ตัวอย่างเส้นทางที่เก็บไว้ · คำนวณใหม่ก่อนบันทึก',
 'm4.providerCredit':'ข้อมูลจาก Geoapify',
 'm4.searchCoverage':'รุ่นทดลองฟรีค้นหาสถานที่ได้เฉพาะในประเทศไทย',
 'm4.error.distanceLimit':'รุ่นทดลองฟรีรองรับระยะระหว่างหมุดรวมไม่เกิน 200 กม. และเส้นทางตามถนนไม่เกิน 450 กม. ลองเลือกเส้นทางที่สั้นลง',
 'm4.hiddenGeometry':'เส้นทางสั้นเกินกว่าจะแสดงได้อย่างเป็นส่วนตัว จึงซ่อนตำแหน่งทั้งหมด','m4.sharedGeometry':'มุมมองที่แชร์ · ซ่อนช่วงต้นและท้ายด้านละ 200 ม.','m4.synced':'บันทึกในบัญชีแล้ว','m4.localSaved':'บันทึกบนอุปกรณ์แล้ว · รอซิงค์','m4.deleteConfirm':'ลบ “{{name}}” ออกจากเส้นทางที่บันทึกไว้ไหม',
 'm4.title':'วางแผนเส้นทาง','m4.search':'ค้นหาสถานที่','m4.searchHint':'พิมพ์อย่างน้อย 3 ตัวอักษร','m4.searchEmpty':'ไม่พบสถานที่ ลองค้นหาด้วยชื่ออื่น','m4.searching':'กำลังค้นหา…',
 'm4.start':'จุดเริ่มต้น','m4.via':'จุดแวะ {{number}}','m4.finish':'ปลายทาง','m4.tapStart':'แตะบนแผนที่เพื่อเลือกจุดเริ่มต้น','m4.tapFinish':'เลือกปลายทาง หรือค้นหาสถานที่','m4.tapNext':'แตะเพื่อเพิ่มจุดถัดไป ลากหมุดที่เลือกเพื่อปรับตำแหน่ง',
 'm4.stops':'จุดบนเส้นทาง','m4.stopCount':'{{count}} / 12 จุด','m4.undo':'ย้อนการแก้ไขหมุดล่าสุด','m4.reverse':'กลับทิศทาง','m4.roundTrip':'กลับจุดเริ่มต้น','m4.overview':'ดูทั้งเส้นทาง','m4.recenter':'ตำแหน่งของคุณ','m4.snap':'หาเส้นทางตามถนน','m4.calculating':'กำลังหาเส้นทางตามถนน…','m4.unsnapped':'มีเฉพาะหมุด · ยังไม่ได้คำนวณเส้นทางตามถนน','m4.road':'เส้นทางตามถนน','m4.recorded':'เส้นทางที่บันทึก','m4.freeFlow':'เวลาโดยประมาณ · ไม่รวมสภาพจราจร','m4.distance':'ระยะทาง','m4.time':'เวลาโดยประมาณ','m4.minutes':'{{count}} นาที','m4.hours':'{{hours}} ชม. {{minutes}} นาที',
 'm4.save':'บันทึกเส้นทาง','m4.saved':'บันทึกเส้นทางแล้ว','m4.name':'ชื่อเส้นทาง','m4.namePlaceholder':'ตั้งชื่อให้เส้นทางนี้','m4.visibility':'ใครเห็นเส้นทางนี้ได้บ้าง','m4.private':'เฉพาะฉัน','m4.friends':'เพื่อน','m4.public':'ทุกคนในแอป','m4.privateHint':'เส้นทางฉบับเต็มของคุณเป็นส่วนตัว','m4.shareHint':'เส้นทางที่แชร์จะซ่อนช่วงต้นและท้ายอย่างน้อยด้านละ 200 ม. หากเส้นทางสั้น อาจซ่อนทั้งหมด','m4.sharePreview':'ดูตัวอย่างก่อนแชร์','m4.previewUnavailable':'บันทึกและซิงค์ก่อน เพื่อดูเส้นทางที่คนอื่นเห็น','m4.remove':'ลบจุดนี้','m4.up':'เลื่อนมาข้างหน้า','m4.down':'เลื่อนไปข้างหลัง','m4.renameStop':'ชื่อจุด','m4.pinLimit':'เพิ่มได้สูงสุด 12 จุด','m4.edit':'แก้ไขเส้นทาง','m4.delete':'ลบเส้นทาง','m4.close':'กลับแผนที่','m4.cancel':'ยกเลิก','m4.done':'เสร็จแล้ว',
 'm4.consentTitle':'ค้นหาสถานที่และเส้นทางตามถนน','m4.consentBody':'Ride Speed จะส่งคำค้นหาและหมุดเส้นทางที่คุณเลือกให้ Geoapify เพื่อค้นหาสถานที่และคำนวณเส้นทาง โดยไม่ส่งตำแหน่งสดของคุณอัตโนมัติ','m4.consentAccept':'อนุญาตสำหรับวางแผนเส้นทาง','m4.consentDecline':'ใช้หมุดบนแผนที่ต่อ','m4.offline':'หมุดยังอยู่บนอุปกรณ์นี้ เชื่อมต่ออินเทอร์เน็ตเพื่อค้นหาสถานที่หรือคำนวณเส้นทาง','m4.locked':'แก้ไขเส้นทางได้เมื่อจอดแล้ว','m4.toMap':'กลับแผนที่','m4.attribution':'ข้อมูลเส้นทาง','m4.unsaved':'ออกจากเส้นทางฉบับร่างไหม','m4.unsavedBody':'ฉบับร่างนี้ยังอยู่บนอุปกรณ์ คุณกลับมาแก้ไขต่อได้','m4.loadError':'โหลดเส้นทางที่บันทึกไว้ไม่สำเร็จ','m4.bicycle':'เส้นทางจักรยานที่นำเข้านี้ใช้เส้นทางจากการบันทึกได้ แต่ยังคำนวณเส้นทางสำหรับรถไม่ได้',
 'm4.error.auth':'เข้าสู่ระบบเพื่อค้นหาสถานที่และคำนวณเส้นทางตามถนน','m4.error.invalid':'ตรวจสอบหมุดเส้นทางหรือคำค้นหา','m4.error.large':'เส้นทางนี้ใหญ่เกินไป ลองลดจุดแวะหรือเลือกเส้นทางที่สั้นลง','m4.error.noRoute':'ไม่พบถนนที่เชื่อมหมุดเหล่านี้ ลองขยับหมุดแล้วคำนวณใหม่','m4.error.quota':'ใช้โควตาคำนวณเส้นทางฟรีครบแล้ว ฉบับร่างยังอยู่บนอุปกรณ์นี้','m4.error.throttled':'รอสักครู่แล้วลองอีกครั้ง','m4.error.provider':'ยังคำนวณเส้นทางไม่ได้ในตอนนี้ หมุดของคุณยังอยู่บนอุปกรณ์','m4.error.configuration':'ยังไม่ได้ตั้งค่าคำนวณเส้นทางออนไลน์ คุณยังวางหมุดได้','m4.error.response':'ตรวจสอบผลเส้นทางไม่สำเร็จ ลองอีกครั้ง','m4.error.account':'บัญชีเปลี่ยนแล้ว กรุณาเปิดเส้นทางใหม่','m4.error.deleted':'บัญชีอยู่ระหว่างการลบ จึงยังแก้ไขเส้นทางไม่ได้','m4.error.title':'ตั้งชื่อเส้นทาง 1–80 ตัวอักษร','m4.error.stops':'เลือก 2–12 จุด พร้อมชื่อและพิกัดที่ถูกต้อง','m4.error.notReady':'คำนวณเส้นทางตามถนน หรือเลือกทริปที่บันทึกไว้ก่อนบันทึก','m4.error.storage':'บันทึกฉบับร่างบนอุปกรณ์ไม่สำเร็จ ลองอีกครั้งก่อนออก','m4.error.conflict':'เส้นทางนี้เปลี่ยนบนอุปกรณ์อื่น ตรวจสอบฉบับล่าสุดก่อนบันทึก','m4.error.unavailable':'เส้นทางนี้ไม่พร้อมใช้งานแล้ว','m4.retry':'ลองอีกครั้ง',
};
export type RouteErrorKey=keyof typeof m4En|'m4.error.sourceExpired'|'m4.error.localChanged'|'m4.draftExists'|'m4.sharePrivate';
export function routeErrorKey(error:unknown):RouteErrorKey {
 const raw=error!==null&&typeof error==='object'?error:null;
 const code=typeof error==='string'?error:raw&&'message' in raw?String(raw.message):'';
 const codes:Record<string,RouteErrorKey>={
  ROUTE_DISTANCE_LIMIT:'m4.error.distanceLimit',AUTH_REQUIRED:'m4.error.auth',ROUTE_SYNC_AUTH_REQUIRED:'m4.error.auth',
  INVALID_REQUEST:'m4.error.invalid',ROUTE_INVALID:'m4.error.invalid',ROUTE_LOCAL_INVALID:'m4.error.invalid',
  REQUEST_TOO_LARGE:'m4.error.large',ROUTE_TOO_LARGE:'m4.error.large',NO_ROUTE:'m4.error.noRoute',
  QUOTA_EXCEEDED:'m4.error.quota',THROTTLED:'m4.error.throttled',ROUTE_SYNC_RATE_LIMITED:'m4.error.throttled',
  PROVIDER_UNAVAILABLE:'m4.error.provider',ROUTE_SYNC_UNAVAILABLE:'m4.error.provider',SERVER_CONFIGURATION:'m4.error.configuration',
  ROUTE_PROVIDER_INVALID_RESPONSE:'m4.error.response',ROUTE_SYNC_INVALID_RESPONSE:'m4.error.response',ROUTE_INVALID_RESPONSE:'m4.error.response',
  ACCOUNT_CHANGED:'m4.error.account',ACCOUNT_DELETION_PENDING:'m4.error.deleted',ROUTE_MOVING_LOCKED:'m4.locked',
  ROUTE_INVALID_TITLE:'m4.error.title',ROUTE_INVALID_STOPS:'m4.error.stops',ROUTE_NOT_READY:'m4.error.notReady',
  LOCAL_READ_FAILED:'m4.error.storage',LOCAL_WRITE_FAILED:'m4.error.storage',
  ROUTE_REVISION_CONFLICT:'m4.error.conflict',ROUTE_OPERATION_CONFLICT:'m4.error.conflict',ROUTE_CONFLICT_CHANGED:'m4.error.conflict',ROUTE_OPERATION_CHANGED:'m4.error.conflict',
  ROUTE_UNAVAILABLE:'m4.error.unavailable',ROUTE_DELETED:'m4.error.unavailable',
  ROUTE_SOURCE_EXPIRED:'m4.error.sourceExpired',ROUTE_SOURCE_UNAVAILABLE:'m4.error.sourceExpired',ROUTE_SOURCE_MISMATCH:'m4.error.sourceExpired',
  ROUTE_LOCAL_CHANGED:'m4.error.localChanged',ROUTE_DRAFT_EXISTS:'m4.draftExists',ROUTE_SHARE_PRIVATE:'m4.sharePrivate',
 };
 return Object.hasOwn(codes,code)?codes[code]:'m4.error.provider';
}
