import type { Session } from '@supabase/supabase-js';
import { accountClient,isAccountCurrent,type AuthScope } from '../../state/AuthState';
import {sendRouteOperation,validateRouteOperation,validateRoutePage,validateRouteProjection,validateRouteSnapshot} from './syncModel';
import type {RouteCursor,RouteDeleteDraft,RouteSyncDraft} from './syncTypes';
export type {RouteDocumentV1,RouteDeleteDraft,RouteSyncDraft,RouteSnapshot,RoutePage,RouteProjection,RouteSyncAck,RouteCursor} from './syncTypes';
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
function current(scope:AuthScope,session:Session){if(!scope.userId||scope.userId!==session.user.id||!isAccountCurrent(scope))throw Error('ACCOUNT_CHANGED');}
function error(value:{code?:string;message?:string}){const codes=['ROUTE_INVALID','ROUTE_TOO_LARGE','ROUTE_OPERATION_CONFLICT','ROUTE_REVISION_CONFLICT','ROUTE_DELETED','ROUTE_SOURCE_UNAVAILABLE','ROUTE_SOURCE_MISMATCH','ROUTE_SOURCE_EXPIRED','ACCOUNT_DELETION_PENDING'];if(codes.includes(value.message??''))return Error(value.message);if(value.message==='Daily action limit reached')return Error('ROUTE_SYNC_RATE_LIMITED');if(value.code==='22P02'||value.code==='22P05')return Error('ROUTE_INVALID');if(value.code==='PGRST301'||value.code==='PGRST302'||value.message==='Authentication required')return Error('ROUTE_SYNC_AUTH_REQUIRED');return Error('ROUTE_SYNC_UNAVAILABLE');}
function transport(scope:AuthScope,session:Session){current(scope,session);const client=accountClient(scope,session);return async(name:string,args:Record<string,unknown>):Promise<unknown>=>{current(scope,session);const{data,error:failure}=await client.rpc(name,args);current(scope,session);if(failure)throw error(failure);return data;};}
export async function saveRoute(scope:AuthScope,session:Session,draft:RouteSyncDraft){const rpc=transport(scope,session);return sendRouteOperation(draft,'save',{send:d=>rpc('rs_save_route_v2',{p_operation:d.operationId,p_id:d.routeId,p_expected_revision:d.expectedRevision,p_document:(d as RouteSyncDraft).document}),status:op=>rpc('rs_get_route_operation',{p_operation:op})},()=>current(scope,session));}
export async function deleteRoute(scope:AuthScope,session:Session,draft:RouteDeleteDraft){const rpc=transport(scope,session);return sendRouteOperation(draft,'delete',{send:d=>rpc('rs_delete_route_v2',{p_operation:d.operationId,p_id:d.routeId,p_expected_revision:d.expectedRevision}),status:op=>rpc('rs_get_route_operation',{p_operation:op})},()=>current(scope,session));}
export async function getRouteOperation(scope:AuthScope,session:Session,operationId:string){validateRouteOperation(null,operationId);const rpc=transport(scope,session);return validateRouteOperation(await rpc('rs_get_route_operation',{p_operation:operationId}),operationId);}
export async function getRouteOwner(scope:AuthScope,session:Session,id:string){if(!uuid.test(id))throw Error('ROUTE_INVALID');const rpc=transport(scope,session);return validateRouteSnapshot(await rpc('rs_get_route_owner',{p_id:id}),scope.userId!);}
export async function listRoutesOwner(scope:AuthScope,session:Session,limit=30,cursor:RouteCursor|null=null){if(!Number.isInteger(limit)||limit<1||limit>50||cursor&&(!uuid.test(cursor.id)||!Number.isFinite(Date.parse(cursor.updated_at))))throw Error('ROUTE_INVALID');const rpc=transport(scope,session);return validateRoutePage(await rpc('rs_list_routes_owner',{p_limit:limit,p_before:cursor?.updated_at??null,p_before_id:cursor?.id??null}),scope.userId!);}
export async function getRouteProjection(scope:AuthScope,session:Session,id:string){if(!uuid.test(id))throw Error('ROUTE_INVALID');const rpc=transport(scope,session);return validateRouteProjection(await rpc('rs_get_route_projection',{p_id:id}));}
